
# mandira

**Hacivad** (semaî söyliyerek perdeye gelir).	\
	\
Semai Ferahnak	\
	\
Sana dil vireli, cana	\
Derunum yanmada hâlâ.	\
Kime ben eyleyem şekva?	\
Nakarat: Aman, naz itme ey zalim!	\
         Diğer gün olmada halim!	\
	\
Gelince bezme şermende. 	\
İdersin naz ile hande,	\
Bu haletler nedir sende?	\
	\
Eyzan.	\
	\
Olup ağyar ile hemdem 	\
Dökersin subesu perçem,	\
Nasıl sabr eyleyem bilmem!	\
	\
Eyzan.	\
	\
Hay Hak!	\
	\
(Perde gazelini okur.)	\
	\
Gafilan açsın gözün görsün ne çadır perdemiz!	\
Hikmet-i ustad-i pirden pür safadır perdemiz.	\
Hazret-i Sultan-i Orhan rahmetullah'tan beri 	\
Yadigâr-i şeyh-i Küşteri becadır perdemiz.	\
	\
Zahiri seyr ü temaşadır velakin batını 	\
Dide-i ariflere ibretnümadır perdemiz.	\
	\
Raks iden kim, ittiren kim, anı fark itmezlere 	\
Şöyle bir tâbiri güç başka hebadır perdemiz.	\
	\
Arabi hem farisî türki tekellümden diğer	\
Cüz’î cüz î her lisana aşinadır perdemiz.	\
	\
**Karagöz.** Ulan, bu herifin pattrdısından bıktım usandım! Gürültü ile saltanın yakasını yırttık! Vay, şalvar da yırtılmış! Hattâ geçende gürültüden mintanı da yırttıktı! Eve gideyim de dikeyim dedim, ipliği iğneye geçireyim derken karşımda duran kedinin burnuna geçirmez miyim, efendim? Kedi feryada başladı; doksan altı mahallenin kedisi haydi bizim kapının önüne biriktiler: haddin varsa çık dışarıya! Baktım, olacak şey değil! Mutbakta biraz ciğer var, şunu kedilere vereyim de gitsinler dedim, sokağa çıktım. Ne bakarsın: ne kadar kedi varsa toplanmış, etrafımı sarmazlar mı? Bizim salta bir tarafa, şalvar bir tarafa, kundura ayağımdan çıkmış, haberim yok. Kedinin birisinin bacağından yakaladım . . . (Birisinin bacağından tutar gibi yaparken Hacivad gelir, Karagöz Hacivadı bacağından yakalar.)	\
**H.** (bağırır). Aman. Karagöz! Ne yapıyorsun? Deli mi oldun?	\
**K.** Senin derdinden değil deli, hasta bile oldum.	\
**H.** Kuzum Karagöz, nedir senin bu hiddetin?	\
**K.** Ne olacak? Senin dırıltından, gürültünden hiç rahat yok! İşe sebebiyet veren sen!	\
**H.** Ben ise çoktanberi Karagözüm ile görüşmedik diye geldim, sen de beni dövmeğe kalktın!	\
**K.** Ben kalkmadım, sen beni geldin evden kaldırdın.	\
**H.** Canım bilâder, her şeyi bertaraf et de senin ile konuşalım!	\
**K.** Senin ile konuşacağımıza sabaha kadar dövüşelim!	\
**H** Karagöz, sen de boştasın, ben de boştayım. Bir iş ucu tutsak?	\
**K.** Tutalım anıma, yakalıyabilir miyiz?	\
**H.** Ne yapalım, Karagöz?	\
**K.** Ben sana iş buldum. Hacivad.	\
**H.** Nasıl iş. Karagöz? Ben yapabilir miyim?	\
**K.** Yaparsın. Neden yapamayacaksın?	\
**H.** Benim gücüm yeter mi? Bazı şeyde kuvvet ister.	\
**K.** Buna kuvvet istemez. Tam senin harcın. Açıktan hem karnın doyacak, hem para kazanacaksın. İki şey tedarik etmeli.	\
**H** Nedir o iki şey?	\
**K.** Bir gaz tenekesi, bir de maşa.	\
**H** Maşa ile gaz tenekesini ne yapacağım?	\
**K.**Köpek boku toplarsın.	\
**H.** Karagöz, münasebetsizlikten vazgeç!	\
**K.** Beğenmedin mi, Hacivad? Biraz dolaşırsın, teneke doldumu,doğru tabakhaneye! Sattığını satarsın, satmadığını eve götürür, çoluk çocuk, yersin.	\
**H.** Zaten bende kabahat! Senin gibi çingeneyi adam zannettim de sırrımı söyledim.	\
**K.** Beğenmedinse yapma!	\
**H.** Karagöz, bana münasib gördüğün san'atı sen yapsan a!	\
**K.** Benim sanatım var elimde.	\
**H.** Izgara, maşa yapmak mı?	\
**K.** Ne beğenmiyorsun ızgara, maşa yapmağı?	\
**H.** Beğenirim, san’at değil mi? Karagöz, biz ikimiz, birlikte büyük konaklara gideriz senin ile, beş on kuruş uyar.	\
**K.** Konaklarda ne yapacağız?	\
**H.** Şarkı söyleriz, mâni söyleriz, bilmece söyleriz,	\
**K.** Bilmece nedir?	\
**H.** Sana bir bilmece söyliyeyim de bil: Bir küçücük fıçıcık, içi dolu turşucuk, Bunu bilmeli.	\
**K.** Nasıl bilmeli? Bildim!	\
**H.** Nedir bakalım?	\
**K.** Fıçıcık.	\
**H.** Değil.	\
**K.** Turşucuk.	\
**H.** Değil, Karagöz! Sorrmuyorsun yenir mi. yenmez mi diye!	\
**K.** Yenir mi, yenmez mi?	\
**H.** Yenir.	\
**K.** Canlı mı, cansız mı?	\
**H.** Cansız.	\
**K.** Cansız kira beygiri.	\
**H.** Değil efendim, kira beygiri cansız mı?	\
**K.** Doyuncaya kadar arpa vermezler, onun için cansızdır.	\
**H.** Değil, bu söylediğim şey sarıca, suluca.	\
**K.** Sarıca, suluca? Çedik pabuç!	\
**H.** Çedik pabuç suluca olur mu?	\
**K.** Olur, neden olmaz? Yağmur yağar, ıslanır. Rengi de sarı değil mi? Sanca, suluca.	\
**H.** Benim söylediğim hastalara şifa	\
**K.** Hastalara şifa: aksülümen.	\
**H.** Aksülümen hastaya şifa mı?	\
**K.** Birdenbire götürür.	\
**H.** Karagöz, evde ve sair yerde yemek vakti gelince ortaya ne yayarlar?	\
**K.** Halı yayarlar.	\
**H.** Sofra yayarlar.	\
**K.** Evet, sofra yayarlar.	\
**H.** Sofranın üstüne dört ayaklı ne korlar?	\
**K.** Eşek korlar.	\
**H.** Değil, a gözüm, iskemle korlar.	\
**K.** Evet, iskele korlar.	\
**H.** İskemlenin üstüne ne korlar?	\
**K.** İskelenin üstünde babalar.	\
**H.** Karagöz, sini korlar.	\
**K.** Ne seni korlar, ne beni korlar.	\
**H.** Bakırdan mamul sini korlar.	\
**K.** Evet, sini korlar.	\
**H.** Sininin üstüne ne dizerler?	\
**K.** Adam düzerler.	\
**H.** Kaşık dizerler.	\
**K.** Evet, âşıkları dizerler.	\
**H.** Aşık mı? Ne münasebet?	\
**K.** Yemek yerlerken herkes eğlensin diye.	\
**H.** Sonra daha ne korlar?	\
**K.** Ne korlar?	\
**H.** Ekmek. Sonra orta yere ne korlar?	\
**H.** Orta yere korkuluk!	\
**H.** Münasebetsiz söz söyleme! Orta yere çorba kâsesini korlar.	\
**K.** Evet, çorba kâsesini korlar.	\
**H.** İçine ne sıkarlar?	\
**K.** Tabanca.	\
**H.** Değil!	\
**K.** Tüfenk.	\
**H.** Değil!	\
**K.** Top.	\
**H.** Değil!	\
**K.** Tuz.	\
**H.** Değil, a canım, tuzu ekerler.	\
**K.** Biber.	\
**H** Onu da ekerler. Limon sıkarlar. Benim de sana söylediğim: limon.	\
**K.** Ben de sana bir bilmece söyliyeyim, Hacivad.	\
**H.** Söyle bakalım!	\
**K.** Yer altında babam başı.	\
**H.** Lâhana?	\
**K.** (vurur). Sıçayım babanın külahına!	\
Sen gidersin. ben durur muyum? Ben de gideyim, evimde yan gelip Oturayım! (Gider.)	\
	\
(Şarkı ile Çelebi gelir.)	\
	\
**H.** Uğurlar olsun, beyim, efendim!	\
	\
**Çelebi.** Vay efendim, maşallah! Görüştüğümüze çok şükür, Hacivad Çelebi! Nasılsınız, eyi misiniz?	\
**H.** Dai bendinizim, efendim.	\
**K.** (pencereden bakarak). Ben de dayınızım, efendim.	\
**Ç.** Canım Hacivad Çelebi, sizi kaybettik. Nerelerdesiniz?	\
**H.** Vâkıa kusur ediyoruz efendim. Bendeniz, bu günlerde hiçbir yere çıkdığnn yok.	\
	\
**Karagöz** (gelir). Bey efendi, bu sıcak havada o kışlık paltoyu niye giymişsiniz? Terlemiyor musunuz? Bari yazlık bir palto yaptır!	\
**Ç.** Sen onu beğenmiyor musun? Fasonedir.	\
**K.** Ben renginden anladım fasulya olduğunu, sapsarı.	\
**H.** Karagöz, sen niçin etliye sütlüye karışıyorsun?	\
**K.** Benim etliye sütlüye karıştığım yok, sebzevattan başka.	\
**Ç.** Canım Hacivad, bu kimdir? Pek tuhaf bir zat!	\
**K.** O, sizlere ömür, vefat etti, beyefendi.	\
**Ç.** Kim vefat etti?	\
**K.** Osuruklu Perizat .	\
**H.** Karagöz, işine gitsen e! Senin işin yok mu?	\
**K.** Ulan, senin ne vazifen? Canım isterse giderim, canım istemezse gitmem. Sen benim kâhyam mısın?	\
**Ç.** Baba, senden pek hoşlandım.	\
**K.** Ben de senden hoşlandım. Oğlum, sormak ayıp değil ya! Niçin böyle kalınca palto giydiniz? Bana merak oldu.	\
**Ç.** Nahifülbünye olduğum için biraz kalınca giydim.	\
**K.** E? İçinde ceket yok ya!	\
**Ç.** Ağırlık veriyor da onun için giymedim.	\
**K.** Çok şey! Sanki o palto hafif mi?	\
**Ç.** E, ne yapalım? üşüyorum, efendim.	\
**K.** A beyim, o paltonuz da bütün leke olmuş.	\
**Ç.**Hayır efendim, onlar leke değil, zaten kendi rengidir. Ona „kar yağdı" tâbir ederler.	\
**K.** Adam, yelek de giymemişsiniz. Sokağa böyle apaçık nasıl çıktınız?	\
**Ç.** Canım, yelek giyince saat de taşımalı. Zaten ben ağır şeyden hazzetmem ki!	\
**K.** Pekgüzel. Haniya frenk gömleğiniz? Şimdi basma mintan giyilir mi ya?	\
**Ç.** Şimdi yeni moda oldu da ondan.	\
**K.** Peki, hani şemsiyeniz?	\
**Ç.** Hekim, güneşte gez diye tenbih etti de onun için kullanmıyorum.	\
**K.** Bari bir baston taşısaniz olmaz mı?	\
**Ç.** Baston kullanmasını zaten sevmem. Bendenize ağırlık verir.	\
**K.** Haydi öyle olsun. Ayağınızda potin da yırtılmış.	\
**Ç.** Mahsus yırttım efendim, nasır var da.. .	\
**K.** Bari kutunuzu verin de bir sigara olsun yapalım!	\
**Ç.** Zaten tütün içmem. Nasılsa alışmadım.	\
**K.** E, ben verirsem içer misin?	\
**Ç.** Ne ise, artık hatır için bir sigara yaparım.	\
**K.** Vay, tırıl’ beyim vay! Gustonuz yerinde amma cep delik!	\
**H.** Karagöz, deminden beri etliğin rezalet elverdi. Haydi işine git diyorum sana! (Karagöz gider.)	\
**Çelebi.** Hacivad Çelebi, kimdir bu zat?	\
**H.** Zatiâliniz pek rânâ bilirsiniz kim olduğunu.	\
**Ç.** Bendeniz tahattur edemiyorum.	\
**H.** Bu zata arsız, yüzsüz, budala Karagöz derler.	\
**K.** (pencereden başını uzatarak). Beni mi çağırdınız?	\
**H.** Seni çağıran yok!	\
**H.** Arsız dediniz de onun için. (Gider.)	\
**H.** Efendim, zatiâliniz ne âlemdesiniz biz görmiyeli?	\
**Ç.** Ne âlemde olacağız, Hacivad Çelebi? Meşguliyet âleminde.	\
**H.** Efendim, o malum. Allah: vücudünüze afiyet versin de .	\
**Ç.** Siz ne âlemdesiniz, Hacivad Çelebi?	\
**H.** Bizimkisi, efendim, ihtiyarlık. Malûmu âliniz, akşamdan afyonu yutar, uyurum. Bir yere çıkamam.	\
**Ç.** Aman, Hacivad Çelebi, sana tuhaf bir şey söyliyeyim!	\
**H.** Buyurun, efendim!	\
**Ç.** Bendenizde şimdi bir merak var.	\
**H.** Ne gibi efendim?	\
**Ç.** Her kim bana bir yalan söylerse ona beş yüz kuruş veririm.	\
**H.** Aman efendim, bu kolay bir şey! Yalan kıtlığına kıran girmedi ya1?	\
**Ç.**, Tecrübesi meydanda. Bakalım, söyleyin bir yalan.	\
**H.** Bendenizin başıma bir tarihte bir şey geldi.	\
**Ç.** Ne geldi?	\
**H.** Bir gün bendeniz fakirhanede otururken canım sıkıldı. Tenezzüh için mesiregâh bir mahalle gidip geştügüzar eylerken esnayı rahta yolum bir çeşme başına tesadüf eyledi. Orada biraz ârâm edip otururken gûşuma semadan acı bir kelb âvâzı geldi. Bendeniz dahi mütehayyir olup taaccüp eyledim. Kanadı olmıyan bir hayvanın semada pervaz edip uçması taaccübe şayan bir haldir.	\
**Ç.** Efendim, taaccüp olunacak bir şey değil. O gördüğünüz köpek yeni doğurmuştur. Yavruları da küçük. Çaylak da yuvasına nafaka getirmek için dolaşırken bir tanesini kapıp götürmüştür. Siz de o aralık tesadüf etmişsinizdir. Bu olur, olmaz bir şey değil.	\
**H.** Aman efendim! Bendeniz zatıâlinizden bahşiş alırım diye söyledim, lûtfünüze mazhar olamadım.	\
**Ç.** Al, Hacivad çelebi, şu beşibiryerdeyi!	\
**H.** Allah ömürler versin efendim! Bendenizin bir refikim varılır: Karagöz derler, efkarı fukaradandır. Ona da lûtfetseniz . . . Kendisi tuhaf bir zattır; yalan söylemeden yana hiç sıkıntı çekmez. Yalanı söyler, kubbesini de verir. Görüşseniz memnun olursunuz.	\
**Ç.** Görmek mümkünse görüşelim!	\
**H.** Mümkün efendim. Hakipayınız ile birlikte bizim fakirhaneye gideriz, ben de onu bulur, gelirim.	\
**Ç.** Buyurun gidelim!	\
**H** Buyurun efendim! (Giderler.) Bana baksan a hanım! Misafire kahve pişirin, ben şimdi gelirim.	\
	\
(Perdeye gelir ve Karagözün kapısını çalar.) Karagöz ! Karagöz!	\
	\
**K.** (içeriden). Ne var?	\
**H.** Sesin derinden geliyor, neredesin?	\
**K.** Tavan arasındaynn.	\
**H.** Tavan arasında ne yapıyorsun?	\
**K.** Çatıda bozukluk var. Onu tamir ediyorum.	\
**H.** Aşağıya gelsen e!	\
**K.** (gelir). Ne haber, Hacivad?	\
**H.** Bir mirasyedi bey geldi.	\
**K.** Bey geldi ise kır kozu!	\
**H.** Canım, benî dinle! Her kim ona bir yalan söylerse ona beş yüz kuruş veriyor.	\
**K.** Yalandan yana kasavet çekmem, hemen söylerim.	\
**H** Yalan söyleyeceksin amma, kubbesini de vermeli. Kubbesiz yalana para vermiyor.	\
**K.** Ben hem yalan söylerim, hem de kubbesini yaparım.	\
**H.** Karagöz, sana bir tuhaf hikâye nakledeceğim.	\
**K.** Şimdi hikâyenin sırası mı ya? Beyi buraya yolla da birkaç kuruş kapalım!	\
**H.** Benim söyliyeceğim hikâye yalana dair.	\
**K.** Söyle bakalım!	\
**H.** Karagöz, bendeniz geçen yaz tenezzüh için bir cuma günü Anadolu hisarına gitmeğe karar verdim. Bendehaneden kalkıp doğru Köprüye, Anadolu cihetine işliyen vapura rakiben Anadoluhisarına çıktım.	\
**K.** Anadollu Salim ağa ile mi acıktın?	\
**H.** İskeleden bir çifte sandala süvar olup Küçüksuya gittim. Orada biraz geştügüzar eyliyerek badehu yine sandala rakiben aheste aheste etrafü  eknafı seyrü temaşa ederek Göksudandoğru İçeriye, Tahtırevana’gittim.	\
**K.** Ulan, sen çocuk musun, tahtaravalliye biniyorsun?	\
**H.** Tahtaravalli değil. Tahtırevan, seyrin ismi. Orada gezip oradan içeriye Dörtkardeşlere gittim.	\
**K.** Dörtkardeşlere gideceğine beş kardeşlere git!	\
**H.** Seyrin ismi Dörtkardeşler. Orada Ali Bostanı derler bir bostan vardır. O bostana gittim. Gezerken bir de ne bakarsın Karagöz. .	\
**K.** Ulan, bakar babandır!	\
**H.** Turfanda, tarlanın ortasında, bir lahana var. taaccüp olunacak bir şey!	\
**K.** Lahanaya taaccüp olunur mu?	\
**H.** Lahana öyle cesim bir şey ki tarif edemem. Kırk tane yaprağı var, ve kırk yaprağında kırk tane leylek yuvası var. Leylekler ötmeğe başladığı vakit bir yapraktan öbür yaprağa ses gitmiyor.	\
**K.** Vay, yalancı köpoğlu! Ulan, bu ne kadar büyük lahana! Hacivad, bu bostana sığmaz.	\
**H.** Olmaz bir şey mi?	\
**K.** Hacivad, ben de senin gördüğün gibi bir şey gördüm.	\
**H.** Ne gördün, Karagöz?	\
**K.** Geçenlerde bir işim vardı. Samakola gittim, o işimi tesviye ettim. Gelirken bir şey gördüm: taaccübe şayan bir kazan. Gayetle büyük kırk tane kulpu var. Her kulpunda kırk tane kazancı ustası çalışıyor. Ellerinde çekiçler. Çekiçleri vurdukları vakit diğer kulpundan ses işidilmiyor, o derece büyük!	\
**H.** İşte bu yalan! Bu kadar büyük kazan olmaz. Asla görülmemiş bir şey!	\
**K.** A kerata! Senin söylediğin lahanaya böyle bir kazan olmalı ki içine sığsın. Yoksa başka türlü olmaz.	\
**H.** Aferin, Karagöz, sad aferin! Sen yalanı söyleyip kubbesini de vereceksin! Gideyim, beyefendiyi yollayım. (Gider.)	\
**K.** Yolla, gelsin! (Karagöz de gider.)	\
**Karagöz** (içeriden). Abla, bizim küp nerede?	\
**Karısı.** Nerede olacak? Aşağıda, avluda duruyor.	\
**K.** Ne kadar ağır, yerinden kalkmıyor!	\
**Ka.** Herif, küpü nereye götürüyorsun?	\
**K.** Nene lâzım senin? Nereye götürürsem götürürüm.	\
**Ka.** Sakın kırma!	\
**K.** Kırba değil, küp! (Arkasına alır perdeye gelir.)	\
**Hacivad** (içeriden). Efendim, size söylediğim zat Şeyh Küşteri meydanında teşrifinizi muntazır.	\
**Çelebi.** Ben şimdi gider onu bulurum. (Perdeye gelir.) Baksanıza efendim! Buralı mısınız?	\
**K.** Moralı değilim, buralıyım	\
**Ç.** Size bir şey soracağım.	\
**K.** Terbiyesizliğin lüzumu yok.	\
**Ç.** Bendenizi tekdir etmeğe ne hakkınız var? Menafi-i şahsiyenize dokunacak bir şey söylemedim!	\
**K.** İster münafık Şaziye söyle, ister bana!	\
**Ç.** Namusa intikal edecek bir şey söylemedim.	\
**K.** ..Mahmuzu ihtikan edecek yerde etmedim  diyor.	\
**Ç.** Fena bir şey söylemedim. Zatınıza birini soracağım.	\
**K.** Osuracağın varsa başka bir yerde osur, ayıptır. Hem de terbiyesizliğin büyüğüdür.	\
**Ç.** Estağfurullah efendim, bendeniz hiç bir vakitte terbiyesizliği kabul etmem! Namusumu bilir ve kendimi de bilirim.	\
**K.** Budala değil, herkes kendini bilir.	\
**Ç.** Size bir sualim var.	\
**K.** Soğanın varsa bakala sat!	\
**Ç.** Burada bir Çeşmi siyah var, bilirmisiniz?	\
**K.** Çeşmisiyah yok, Fedaî var.	\
**Ç.** Fedaî değil, Çeşmi siyah.	\
**K.** Çeşmede siyah yok, beyaz var.	\
**Ç.** Burada Aynı kare varmış.	\
**K.** Ayı ile fare vardı amma, ayı zinciri kopardı kaçtı.	\
**Ç.** Canım, ayı ile fare değil. Aynı kare.	\
**K.** Aynada kara yok, yalnız sırı dökülmüş.	\
**Ç.** Siz hiç lâkırdı anlamaz mısınız? Yoksa anlamak mı istemiyorsunuz?	\
**K.** Anlarım, niçin anlamam?	\
**Ç.** Demindenberi lâkırdılarıma aksi aksi cevap veriyorsunuz.	\
**K.** Bendeniz Cevadı bilmem.	\
**Ç.** Burada bir Karagöz varmış, biliyor musunuz?	\
**K.** Demindenberi söyliyeceğin bu mu idi? Vay gidi lâkırdı anlayan beyim vay! Buna türkçesi „Ambar delindi buğday döküldü" demeli.	\
**Ç.** Şimdi o zat nerededir, biliyor musunuz?	\
**K.** Kulunuzum.	\
**Ç.** Estağfurullah! Bendenizin merakım: bana her kim bir yalan söylerse ona beş yüz kuruş veririm. Siz de bir yalan söyleyin, size de beş yüz kuruş vereyim!	\
**K.** Bendeniz yalanı asla kabul etmem ve söyliyenden de hoşlanmam. Benim pederim vaktile Hayriye tüccarlarnıdandı. Sizin pederiniz bir gün bizim pedere gelir, der ki „Bu günlerde ziyadesile paraya ihtiyacım var, bana ödünç olarak bir küp altın verin!" Bizim peder de sizin pedere bir küp altın verir. Bir hafta sonra bizim peder ölür, sizin peder de vefat eder. Şimdi o babanın oğulları değil miyİz?,Varisi olduğumuz için şimdi bendeniz sizden, beyefendi oğlumuz, o parayı isterim.	\
**Ç.** Aferin, baba efendi sana! Yalan söylemeden yana aslâ sıkıntı çekmiyorsun! Ben bu kadar adamla görüştüm senin gibisini görmedim. Sahi desem küpü doldurmalı; yalan desem, beş yüzü, vermeli. Küpü doldurmaktansa beş yüzü verip kurtulmalı.	\
**K.** Ondan başka çaren yok, oğlum! Beş yüzü vermeli.	\
**Ç.**(verir). Al bakalım, baba!	\
**K.** Ver oğlum da verdi desinler!	\
**Ç.** Allaha 'smarladık! (Gider.)	\
**K.** Sefa geldin! Var mı yalana inanacak?	\
**Hacivad **(gelir). Karagöz, aşkolsun sana! Evden seni dinliyordum. Bîr yalan söyledin ki hiç kaçacak tarafı yok.	\
**K.** İstersen, sana da bir yalan söyleyim.	\
**H.** Bana yalan söylesen kaç para eder! Erbabına söyle de para kazan!	\
**K.** Nerede bulayım bu bey efendi gibi enayiyi?	\
**H.** Sefayı hatır ile paraları yeriz Karagöz. (Gider.)	\
**K.** Ben de şu âletimi alayım! (Küpü yüklenir, gider.)	\
Abla! Al şu küpü! Ulan, karı evde yok! Vay köpoğlu! Sandıklar da açık! Evi soymuş bizim karı, pahada ağır, yükte hafif ne varsa alıp götürmüş! Ben de kapının önüne çıkarım, kime rast gelirsem alır eve getiririm. (Perdeye gelir.) Şurada oturayım.	\
	\
(Şarkı ile Zenne gelir.)	\
	\
Şarkı Rast	\
	\
Gamdan azade heman dünyada bir meyhanedir,	\
Def-i gam itmek için âlet ise peymanedir;	\
Neş’e-yi zevk-i meyi tahkir iden divanedir.	\
Nakarat: Gam gelir, şadi gider, çün dil misafirhanedir.	\
         Def-i gam itmek için âlet ise peymanedir.	\
	\
Sun peyapey cam-ı meyden kim hayat-i tazedir;	\
Neş’e virmek badeye mahsus minnetsazedir;	\
Saki-yi meclis bizimçin tek heman bir tazedir.	\
	\
Ey zan.	\
	\
**Zenne.** Ah, kara talih, ah! Dünyada acaba benim gibi bedbaht adam var mıdır?	\
**K.** (başını Önüne eğer). Biçare kızcağız dertli!	\
**Z.** Yalınız başıma sokaklara düştüm. Nereye gideceğimi de bilmiyorum.	\
**K.** Nereye gideceksin? Bizim eve gidelim!	\
**Z.** A. üstüme eyilik sağlık! Burada bir şey var. Galiba atlama taşı olacak.	\
**K.** Sen de ard ayağın ile başını kaşı!	\
**Z.** A, kendi kendine söyliyor! Sen adam mısın?	\
**K.** Adam değilim, horozum.	\
**Z.** Kokoz mısın?	\
**K.** Kokoz değilim, horozum.	\
**Z.** Horoz isen, ötsen e!	\
**K.** Vakitsiz öten horozun başını keserler.	\
**Z.** Sen horoz de değilsin.	\
**K.** Değilim.	\
**Z.** Nesin?	\
**K.** Su terazisi.	\
**Z.** Senin suyun nereden gelir ?	\
**K.** Evvelâ yukardan gelir, sonra borulara taksim olur. Oradan da büyük musluğa gider, musluktan akar.	\
**Z.** Sen ne suyusun ?	\
**K.** Bedengirah suyu.	\
**Z.** Sair sulardan tatlı mıdır lezzeti?	\
**K.** Hepsinden eyidir. Vücuda nafi, bedene şifa verir.	\
**Z.** Sen su terazisi değilsin.	\
**K.** Değilim.	\
**Z.** Nesin?	\
**K.** Cin.	\
**Z.** Amanın dostlar! Ben cinden korkarım. Kuzum cin! Canım cin! Beni çarpma!	\
**K.** Ben seni parçmazsam sonra beni öteki cinler yolsuz eder.	\
**Z.** Kuzum cin! Canım cin. Ayağının altım öpeyim, beni çarpma!	\
**K.** Parçacağım, başka çare yok.	\
**Z.** Ne istersen veririm.	\
**K.** Doğru söyle, verir misin?	\
**Z.** Veririm dedim ya!	\
**K.** Ben vücudunun sadakasından1 isterim.	\
**Z.** Yüzümden mi istersin, gözümden mi?	\
**K.** Başka taraftan isterim.	\
**Z.** Sen cin de değilsin.	\
**K.** Değilim.	\
**Z.** Nesin sen?	\
**K.** Adamım, adam! (Doğrulur.)	\
**Z.** Ay. kör olmıyası!1 Adamsın! Seni görür görmez, içime sokacağım geldi.	\
**K.** Ben de senin gibi.	\
**Z.** Nasıl?	\
**K.** Ben de seni görür görmez sokacağım geldi.	\
**Z.** Demek ki beni beğendin, öyle mi?	\
**K.** O da söz mü ya? Beğendim.	\
**Z.** Beni alır mısın?	\
**K.** Sen vardıktan sonra ben de alırım.	\
**Z.** Ben de sana varırım.	\
**K.** Haydi eve gidelim!	\
**Z.** Buyurun gidelim! (Giderler.)	\
**K.** (içeriden). Senin hiç kimsen var mıdır?	\
**Z.** (içeriden). Sonrakinden başka kimsem yok.	\
	\
(Şarkı ile Çelebi gelir.)	\
	\
Şarkı Rast4	\
	\
Yine bir gülnihal aldı bu gönlümü, 	\
Sîmten, goncafem, bibedel ol güzel.	\
Ateş-i ruhları yaktı bu gönlümü.	\
	\
Nakarat: Pür-eda, pür-cefa, pek küçük, pek güzel!	\
	\
Görmedim kimsede böyle bir dilrüba, 	\
Böyle kaş. böyle göz, böyle el, böyle bel! 	\
Aşıkın bağrını üzmeğe göz süzer.	\
	\
Nakarat: Elaman, el’aman, her zaman, ol güzel!	\
	\
**Çelebi.** Hesapça bu ev olacak. Yerden bir taş alayım da atayım ! (Alır ve eve atar.)	\
**K.** (içeriden). Ulan, bu ne? Cam kırılacaktı. (Pencereden:) Kim o?	\
**Ç.** Baba, aşağıya gel!	\
**K.** (gelir). Ne istersin?	\
**Ç.** Baba, buralı mısın?	\
**K.** Morali değilim, buralıyım.	\
**Ç.** Burada birisi var, biliyor musun?	\
**K.** Kimmiş o?	\
**Ç.** Yedi dağın çiçeği, Hasırasıçtının kızı, Rabiş hanım.	\
**K.** Bu ne kader elkap! Ne yapacaksın onu?	\
**Ç.** O benim dostumdur.	\
**K.** Burada durun, ben şimdi gelirim. (Eve gelir.) Bana baksan a!	\
**Ç.** Ne var, ne istiyorsun?	\
**K.** Senin adın nedir?	\
**Z.** Neden sordun?	\
**K.** Bir insan kendi hareminin adını öğrenmek istemez mi?	\
**Z.** Yedi dağın çiçeği, Hasırasıçtınm kızı. Rabiş hanım derler.	\
**K.** Senin anan hasıra sıçtı mıydı?	\
**Z.** Vaktile öyle lâkap takmışlar.	\
**K.** Baban mı takmış anana, yoksa başkası mı takmış?	\
**Z.** Öyle demişler.	\
**K.** (perdeye gelir). Bana baksan a oğlum! Dediğiniz isimde var burada adam.	\
**Ç.** Sen ona git, de ki Üsküdardan Memiş gelmiş de!	\
**K.** (eve gelir). Abla!	\
**Z.** Ne var, herif?	\
**K.** Üsküdardan yemiş gelmiş.	\
**Z.** Al da gel!	\
**K.** (gelir). Ver de götüreyim!	\
**Ç.** Neyi götüreceksin?	\
**K.** Yemişi.	\
**Ç.** Baba, yemiş değil!	\
**K.** Yememiş mi?	\
**Ç.** Memiş, Memiş, Memiş!	\
**K.** (eve gelir). Yemiş yemiş de boş gelmiş.	\
**Z.** Anla da gel!	\
**K.** (gelir). (,Anla da gel!" dedi.	\
**Ç.**Sen ona çabuk git, de ki: (Çabuk:)	\
	\
,,Yaseminim saya düştü, sümbülündün sen benim,	\
İki kaşın aresinde bir gûlümsün sen benim.	\
El yanında düşmanımsın tenhalarda sen benimsin ben senin’’.’	\
**K.** Mendile doldur!	\
**Ç.** Hiç lâkırdı mendile dolar mı?	\
**K.** Tane tane söyle!	\
**Ç.** ,,Yaseminim suya düştü, sümbülümsün sen benim.’	\
**K.** (eve gelir). Abla!	\
**Z.** Ne var. herif?	\
**K.** ,,Yasef çıfıt suya düştü, sümüğümü ye sen benimI"	\
**Z.** Tuh. utanmaz herif! Anla da gel!	\
**K.** (gelir). Söyle bakalım!	\
**Ç.** „İki kaşın aresinde bir gülümsün sen benim."	\
**K.**(Gene gelir). Abla, iki kaşığın var mı?	\
**Z.** Ne yapacaksın?	\
**K.** ,,,iki kaşığın varsa, gel. götümü ye sen benim!'	\
**Z.** Vay terbiyesiz herif, vay!	\
**K.**(gelir). Söyledik,	\
**Ç** ..El yanında düşmanımsın, tenhalarda sen benimsin ben senin!" 	\
**K.** (eve gelir). Abla!	\
**Z.** Ne var. herif?	\
**K.** El yanında düşmanımsın. tenhalarda sen beni sik. ben seni!"	\
**Z.** Söyliyenden dinliyen ârif gerek!	\
	\
Yaseminim suya düştü, sümbülümsün sen benim.	\
İki kaşın ateşinde bir gülümsün sen benim,	\
El yanında düşmanımsın tenhalarda sen benimsin ben senin" mi dedi? 	\
**K.** Ulan, ne zaman geldi buraya?	\
	\
**Z.** Sen de ona git, de ki:	\
,,Karanfilsin kararın yok.	\
Gonca gülsün tımarın yok.	\
Ben seni çoktan severdim.	\
Senin benden haberin yok“ de!	\
**K.** Ben böyle dilenci vapuru gibi iki tarafa varıp gelecek miyim?	\
**Z.** Kuzum koca, söyle de gel!	\
**K.** Kaşıklık sepetine doldur	\
**Z.** Lâkırdı sepete dolar mı?	\
**K.** Tane tane söyle!	\
**Z.** ..Karanfilsin kararın yok."	\
**K.** (gelir). Bana baksana, oğlum!	\
**Ç.** Ne var, baba efendi?	\
**K.** Sen güneşte çok gezdin mi?	\
**Ç.** Neden sordun?	\
**K.** ..Kararmıştın haberin yok."	\
**Ç.** Anla da gel!	\
**K.** (içeriden). Söyledim.	\
**Z.** ..Gonca gülsün tımarın yok."	\
**K.** (gelir). ..Koca götsün, tımarın yok."	\
**Ç.** Haydi, eşek herif! Anla da gel!                          	\
**K.** (içeriden). Söyledim.	\
**Z.** ,,Ben seni çoktan severdim, senin benden haberin yok."	\
**K.** (gelir). „Ben seni çoktan sikerdim amma, senin benden haberin yok." 	\
**Ç.** Söyliyenden dinliyen ârif gerek,	\
**K.** Evet, Arifin dir kürek.	\
**Ç.**„ Karanfilsin kararın yok,	\
Gonca gülsün tımarın yok.	\
Ben seni çoktan severdim,	\
Senin benden haberin yok", öyle mi dedi?	\
**K.** Siz ne zaman birbirinizle konuştunuz? Ben nafile yere çulha mekiği gibi boşyere ikinize de varıp gelmeden anam ağladı!	\
**Ç.** Haydi çabuk, onu al getir! Mandıra sefasına gideceğiz.	\
**K.** Ben şimdi gelirim. (Eve gelir.) Abla!	\
**Z.** Ne var, herif?	\
**K.** , ,Ona söyle, ben onu alıp götüreceğim mandıra sefasına' diyor.	\
**Z.** Bir kere göreyim kendisini. (Zenne önde, arkada Karagöz perdeye gelirler.) Vay, maşallah, beyim! Efendim, sefa geldiniz!	\
**Ç.** Sefada daim olun !	\
**Z.** Ne haber bakalım?	\
**Ç.** Haberi: seni almağa geldim, mandıraya gideceğiz.	\
**K.** (arkadan). Para iste, para!	\
**Z.** Pek âlâ amma, burada benim çok kişiye borcum var. Bana bir, iki, üç lira vermeli1	\
**Ç.** Doğru söylüyorsunuz. amma, benim lira taşımadığımı bilmiyor musunuz?	\
**K.** (arkadan). Sorsan a, niçin taşımıyor?	\
**Z.** Lira niçin taşımıyorsunuz?	\
**Ç.** Sarılık illetine oğrarım diye.	\
**K.** Vay köpoğlu! Eyi mana verdi! Bari mecidiye iste!	\
**Z.** Mecidiye verin!	\
**Ç.** O da ağırlık veriyor, onun için taşımam.	\
**K.** Çeyrek iste!	\
**Z.** Çeyrek verin	\
**Ç.** O da çokluk bulunmaz.	\
**K.** İkilik kuruşluk iste!	\
**Z.** İkilik kuruşluk verin!	\
**Ç.** Onlar da parmakların arasından dökülüyor.	\
**K.** Metelik iste, onu da tutmaz bey!	\
**Z.** Metelik verin!	\
**Ç.** O da ellerimi kirletiyor.	\
**K.** Zaten bey tırıl olduğu anlaşıldı. Bir meteliğe kurşun atıyor1. Haydi sen eve git  (Zenne, gider.) Bana baksan a oğlum !	\
**Ç.** Buyurun efendim!	\
**K.** Lira taşımazsınız değil mi, sarılık olurum diye?	\
**Ç.** Evet efendim.	\
**K.** Mecidiye ağırlık verir?	\
**Ç.** O da ağırlık verir.	\
**K.** Çeyrek bulunmaz?	\
**Ç.** Çokluk çeyrek bulunmaz.	\
**K.** İkilik kuruşluk parmakların arasından düşer?	\
**Ç.** Evet efendim.	\
**K.** Metelik elinizi kirletir?	\
**Ç.** Malûm.	\
**K.** (vurur). Bedava karıyı alır götürürmüş, kerata puşt! (Eve gelir.) Bana baksan a!	\
**Z.** Ne var. kocacığım?	\
**K.** Bundan başka gelecek gidecek var mı?	\
**Z.** Hayır kocacığım, sonra gelecekten başka kimsem yok!	\
**K.** öyle ise, otur, yoksa ipi çökecektim.	\
	\
(Şarkı ile Hımhım gelir.)	\
	\
Şarkı Nihavend.	\
	\
Nar-i aşkınla senin, ey nevcivan, 	\
Döndü ateşzare cism-i natuvan. 	\
Hasret-i hâlinle hal oldu yaman.	\
	\
Nakarat: El’aman. ahu bakışlım, el’aman!	\
	\
Sine-i mecruhum, ey can paresi.	\
Gözgöz oldu hasretinle yaresi.	\
Lûtfuna kaldı bu zahmın çaresi.	\
	\
Eyzan.	\
	\
**Hımhım.** Gele gele geldim buracığa, daha gönlüm nereciğe? Yerden taş alayım, atayım! (Atar.)	\
**K.** (içeriden). Ulan, kafam yarılıyordu! (Pencereden:) Bu kim? Kalantor bir şeye benziyor.	\
**Hı.** Baba, aşağıya gel, aşağı!	\
**K.** Götüne maymun taşağı! Abla, bana bir parça pamuk ver!	\
**Z.** Ne yapacaksın?	\
**K.** Burnuma tıkayacağım. (Gelir.) Ne istersin?	\
**Hı.** Baba, buralı misin?	\
**K.** (Hımhım gibi konuşur). Buralıyım.	\
**Hı.** Sen de benim gibi hımhım mısm?	\
**K.** Hımhımım.	\
**Hı.** Anadan mı hımhımsın, babadan mı?	\
**H.** Hem anadan hımhımım, hem de babadan hımhımım.	\
**Hı.** Eğer benim ile eğleniyorsan, sen de benim gibi hımhım ol!	\
**K.** (aksırır). Siktir kerata! Ben hımhım değilim.	\
**Hı.** Kuzum baba, burada Hasırasıçtının kızı Rabiş varmış, biliyor musun?	\
**K.** Ne yapacaksın onu?	\
**Hı.** O benim dostum.	\
**K.** Karıdaki mide tanzifat arabası gibi! (Eve gelir.) Abla!	\
**Z.** Ne var yahu?	\
**K.** Bir hımhım geldi, tanıyor musun?	\
**Z.** Hımhımzade mi?	\
**H.** Bu da mı sade? Etli peynirli istemez mi?	\
**Z.** Saviver gitsin!	\
**K.** (gelir). Ben onu getirirsem, nerene korsun?	\
**Hı.** Koynuma korum.	\
**K.** Geliyor, hazır ol!	\
**Hı.** Hazırım, hazır.	\
**K.** (vurur. Hımhım gider). Vay köpoğlu! Baht vapuru gibi! (Eve gelir.) Başka bir gelen giden var mı ?	\
**Z.** Hayır, kocacığım, sonra gelecekten başka kimsem yok.	\
	\
(Şarkı ile Kekeme gelir.)	\
	\
Şarkı Nihavend	\
	\
Benim halim yaman haldir.	\
Hicabı areden kaldır!	\
Diler öldür, diler güldür! 	\
Nakarat: Hicabı areden kaldır!	\
Halimi ittim ifade, 	\
İltifat it bana sade	\
Bu gice bezm-isefade!	\
	\
Eyzan.	\
	\
**Kekeme.** Ge-ge-gele, ge-ge-gele, ge-geldik bu-buracığa, da-da-daha gö-gö-gönlüm nereciğe? Ye-ye-yerden bir ta-ta-taş alayım da at-at-atayım! (Alır atar.)	\
**K.** (içeriden). Az kaldı ayna kırılacaktı! (Pencereden): Bu da kim?	\
**Ke.** Bab-bab-baba, bıı-bu-buraya ge-ge-gel!	\
**K.** (gelir). Kimi istiyorsun?	\
**Ke.** Bab-bab-baba, bu-bu-buralı mısın ?	\
**K.** Buralıyım.	\
**Ke.** Bu-burada bi-bir Has-hasıra-sıç-sıç-sıçtının kık-kızı Rab-rabiş hanımı bib-bib-biliyor musun?	\
**K.** Sen dur azıcık burada! (Eve gelir.) Abla!	\
**Z.** Ne var, herif?	\
**K.** Bir kekeme geldi.	\
**Z.** Bildim, Kekemezade.	\
**K.** Bu da mı sade? Hiç kıymalı yok mu?	\
**Z.** Savıver!	\
**K.** (gelir). Sen onu ne yapacaksın?	\
**Ke.** 0 beb-benim dod-do-dostumdur. A-ahp gö-gö-götüreceğim.	\
**K.** Verirsem nere ye korsun ?	\
**Ke.** Kok-ko-koy-nun-numa.	\
**K.** Geliyor! (Vurur, Kekeme gider.) Vay Köpoğlu! Haline bakmıyor da .. (Evegelir.) Sen bana baksan a! Seninle nasıl edeceğiz?	\
**Z.** Neden, kocacığım?	\
**K.** Neden olacak? Zikzak postası gibi her tarafa uğruyorsun! Ne beyi, ne hımhımı, ne kekemesi kaldı!	\
**Z.** Sonra gelenden başka kimseni yoktur.	\
	\
(Şarkı ile Yahudi gelir.	\
	\
Ande vamos el de aki. .	\
	\
**Yahudi.** Yele yele yeldik buralara, daha yönlüm nerelere? Yerden bir taş alayım da atayim' (Alır atar.)	\
**K.**(içeriden). Vay kafam! Az kaldı kafam yarılıyordu! (Pencereden bakar.) Ulan! Bu eskici Yahudi de kim oluyor?	\
**Ya.** Yel hurda!	\
**H.** Ne istiyorsun, bezirgan?	\
**Ya.** Yaşamlarin hayrolsun!	\
**H.** Kuru götüne bir kazık girsin!	\
**Ya.** Burali misin?	\
**K.** Evet, buralıyım. Ne istersin?	\
**Ya.** Burda Yedi dağın çiçeği, Hasirasiçtinin kizi, Rabiş hanımı biliyor musun?	\
**K.** Sen onu ne yapacaksın?	\
**Ya.** Alacağım var onda.	\
**K.** (eve gelir). Abla! Bir yalıudi geldi, seni soruyor.	\
**Z.** Benim ona borcum vardı. Sav gitsin!	\
**K.**  (gelir). Bana bak, bezirgân! Geliyor, sıkı dur!	\
**Ya.** Varsın, yelsin!	\
**K.**  Geliyor. (Vurur, Yahudi gider.) Bu sefer gider, çıkışırım. (Eve gelir.) Bana baksan a!	\
**Z.** Ne var, kocacığım?	\
**K.** Senin ile nasıl edeceğiz? Gelenden gidenden ben bıktım.	\
**Z.** Sonrakinden başka gelenim gidenim yok.	\
**K.** Benim de bu lâkırdıdan karnım tok.	\
	\
(Şarkı ile Sarhoş gelir.)	\
	\
Şarkı Şehnaz	\
	\
Nice sevmeyeyim dostlar? Bîr acayib dili var,	\
Yanağında gül açılmış etrafında alı var.	\
Bugün bana cevr idersen yarın Hak divanı var!	\
   Nakarat: İçlim aşkın dolusunu, yâr bugün meclistedir!	\
	\
İki kaşın ateşinde bir beni var nur gibi, 	\
Karşusunda divan durdum eli bağlı kul gibi.	\
Ko çöksünler dare beni Hallaç-i Mansur gibi!	\
	\
Eyzan.	\
	\
**Sarhoş.** Hey gidi felek hey!	\
**K.** (içeriden). Hey gidi kürek hey! Tek ayak prangaya nasıl yakışırsın!	\
**S.** Dağ başından duman, insan başından hal eksik olmaz!	\
**K.** Senin de midende rakı eksik olmaz! Su yerine rakı içer köpoğlu.	\
**S.** Bizim Hasırasıçtınm kızı Rabişi Karagöz kapatmış ha!	\
**K.** (içeriden). Yine aşağıda zikri menhusum sirkat olundu!	\
**S.** Yerden bir taş alayım atayım! (Alır atar.)	\
**K.** (pencereden). Ulan, bu zorlu, ötekiler gibi değil! (İçeriden:) Abla!	\
**Z.** Ne var. herif?	\
**K.** Kapının önünde birisi var. Ben buna cevap veremem; sen git de sav!	\
**Z.** Olmaz, herif, sen git!	\
**K.** (gelir). Ne istersiniz?	\
**S.** Ne mi istiyorum ? Seni istiyorum!	\
**K.** Kulunuz geldim. Emrinize hazırım.	\
**S.** Sen bu mahalleli misin?	\
**K.** Evet, bu mahalleliyim.	\
**S.** Adın nedir?	\
**K.** Karagöz.	\
**S.** Vay, Karagöz! Filiz salıvermişsin!	\
**K.** Bendeniz yediveren asmasıyım, filiz salıvereceğim.	\
**S.** Sen Yedi dağın çiçeği, Hasırasıçtının kızı Rabişi almışsın, öyle mi?	\
**K.** öyle.	\
**S.** Haydi, sen ona git, de ki: ..Mandıradan Deli Tuzsuz gelmiş, seni alıp mandıraya götürecek."	\
**K.** Peki efendim, (Giderken Sarhoş çağırır)	\
**S.** Gel!	\
**K.** (Defa döner, gitmez). Buyurun!	\
**S.** Sen ona söyle: ..Bin dallı sevayi entarisini giysin de gelsin" dedi de!	\
**K.** ,,Bin dallı sevayi entarisini giysin de gelsin". (Giderken Sarhoş çağırır:) 	\
**S.** Gel!	\
**K.** Geliyorum! (Gelir.)	\
**S.** Canfes şalvarını giysin de gelsin!	\
**K.** ,.Canfes şalvarını giysin de gelsin!" (Giderken Sarhoş bağırır:)	\
**S.** Gel! Oyalı yemenisini başına bağlasın da gelsin!	\
**K.** ..Oyalı yemenisini başına bağlasın da gelsin!" (Giderken Sarhoş çağırır:)	\
**S.** Gel! Ayağına sarı pabucunu giysin de gelsin!	\
**K.** ,,Ayağına sarı pabucunu giysin de gelsin!" (Giderken Sarhoş çağırır:)	\
**S.** Gel! Samur kürkünü giysin de gelsin!	\
**K.** „Samur kürkünü giysin de gelsin!" (Giderken Sarhoş çağırır,)	\
**S.** Gel! Lâhuri şalını beline bağlasın da gelsin!	\
**K.** ..Lâhurî şalını bağlasın da gelsin!" (Giderken Sarhoş çağırır,)	\
**S.** Gel!	\
**K.** (artık gelmez, evine gider). Abla! Ben abdeshaneye saklanıyorum. Sen git de bu herifi sav, sakın eve alma!	\
**Z.** (perdeye gelir). Vay efendim, sefa geldiniz!	\
**S.** Sefada daim ol. iki gözüm!	\
**Z.** Nasılsınız? Eyisiniz inşallah!	\
**S.** Çok şükür! Sen de eyi misin?	\
**K.** (pencereden). Sen de ayı mısın, köpoğlu?	\
**Z.** Cariyeniz de eyiyim.	\
**K.** Vay, bizim kan herifin cariyesi imiş!	\
**S.** Haydi bakalım, seninle beraber mandıraya gideceğiz.	\
**Z.** Şimdi vakti değil.	\
**S.** Herkes yârini almış mandıraya götürüyor. Ben de seni götüreceğim.	\
**Z.** Öyle ise efendim, bizim fakirhaneye gideriz, biraz ârâm edersiniz. Size bir ekşili çorba da pişiririm, badehu gideriz.	\
**K.** Gördün mü bizim karının yediği boku! Herifi eve getiriyor!	\
**Z.** Buyurun gidelim!	\
**S.** Gidelim. (Eve gelirler,) Çok geç kalmıyalım!	\
**Z.** Ben şimdi size çorba pişiririm. Yedikten sonra gideriz.	\
**K.** Boğazınızda kalsın köpoğları!	\
**S.** Biz konuşurken kulağıma bir ses geliyor. Nereden geliyor o ses?	\
**Z.** Komşuda bir bunak herif var, bazen konuşur. Onun sesidir.	\
**S.** Ben arayacağım bu ses nereden geliyor.	\
**H.** Gördün mü? Şimdi Sarhoş ile derde gireceğiz.	\
**S.** Ulan, senin orada ne işin?	\
**K.** Kulunuz abdeshane mütevellisiyim.	\
**S.** Çık dışarı (Vurur) Çık dışarı!	\
**K.** (perdeye gelir). Vay köpoğlu herif! Kendi evimden beni kovdu!	\
**S.** (içeriden). Çorba pişti mi?	\
**Z.** Pişiyor.	\
**S.** Çabuk pişir! İçelim de gidelim!	\
**K.** Kendi evi gibi emrediyor be! Şimdi sana gösteririm. (İçeriye bağırır:) Bana baksana. Çelebi. Hımhım, Kekeme, Yahudi! Aşağıya gelin! (Hepisi gelirler.)	\
**Çelebi.** Ne var, baba efendi?	\
**K.** Ne olacak? Bir sarhoş geldi, bizim karıyı götürecek.	\
**Ç.** Ne demek? Biz adama karı mı veririz?	\
**K.** Sen ne dersin, Hımhım?	\
**Hımhım.** Sen korkma biz varken.	\
**K.** (Çelebiye.) Oğlum, şimdi onlar buraya gelirse sen ne yaparsın?	\
**Ç.** Benim baston şişlidir.	\
**K.** Benim sopa da kabagöt.	\
**Ç.** Şişi çeker çekmez sinesinde alının soluğu!	\
**K.** Sen ne yaparsın. Hımhım?	\
**Hımhım.** Hançerimi çeker çekmez barsaklarını yere dökerim!	\
**K.** Kekeme, sen ne yaparsın?	\
**Kekeme.** Beb-ben de çak-çakımi çek-çeker çekmez el-el-ma soyarım!	\
**K.** Sen de sersem davranırsan, ben de senin gözünü oyarım! Yahudi, sen ne yaparsın?	\
**Yahudi.** Papuçlarımı alır almaz Balatta alınm soluğu!	\
**K.** En cesaretli içerimizde sensin.	\
**S.** (içeriden). Haydi, nazeninim, gidelim! (önde Zenne, arkada Sarhoş gelirler.) Yürü sen e, nazlım!	\
**Z.** Nereye gideceğiz? Önümüzde kale duvarı var!	\
**S.** Bir tekme vur geç!	\
**K.** Bak, yengeç mi süzgeç mi, anlarsın 	\
**Z.** O senin bildiğin duvar değil. Bu, etten duvar,	\
**S.** Onun da kolayı var. Belimden kuburu çıkarırım parça parça ederim.	\
**K.** Orası doğru. Kuburu çıkarırsan ağzına beraber abdeshane taşar.	\
**S.** Haydi sen eve git! (Zenne gider.) Ey, ağalar!	\
**K.** Oltalar, dalyanlar!	\
**S.** Tutuşacak mıyız, vuruşacak mıyız?	\
**K.** Hem tutuşacağız, hem de vuruşacağız!(Arkadakilerine sorar:) Nasıl, hazır mısnıız?	\
**Hepisi.** Hazırız, hazır!	\
**Yahudi.** Ben kaçmağa hazırım.	\
**Sarhoş.** Haydi, bakalım! Birer birer mi geleceksiniz, yoksa hep birden mi ?	\
**K.** Hep birden. ..Ye kuzgun lâşe. ye devlet bâşe Haydi tutuşalım .(Hepsi birden Sarhoşa hücum ederler, kavga dövüş ederler. Hepsi giderler, yalınız -Karagöz kalır.) Vay, beyin saati düşmüş! ( Yerden alır.) Hımhımın bıçağı! (Yerden alır.) Kekemenin kuşağı düşmüş! (Yerden alır.) Ulan, Yahudinin gözlüğü! (Yerden alır.)	\
**Ç.** (gelir). Baba, benim saatimi gördün mü?	\
**K.** (vurur). Görmedim. (Çelebi gider.)	\
**Hımhım (gelir).** Baba, benim bıçağımı gördün mü?	\
**K.** (vurur). Görmedim. (Hımhım gider.)	\
**Kekeme (gelir).** Bab-baba, beb-benim kuk-kuşağımıgö-gü-gördün mü?	\
**K.** (vurur) Ne uşağını gördüm, ne de kuşağını. (Kekeme gider.)	\
**Yahudi (gelir).** Bana bak, benim yozluğumu yordun mu?	\
**K.** (vurur). Görmedim.	\
**Ya.** Fikarayim, yozluğumu ver!	\
**K.** (vurur). Görmedim, bezirgan. (Yahudi gider.)	\
	
(Oyun hitam bulur.)	
