
# ortaklar

**Hacivad ** (besteyi soyli yereli perdeye gelir).	\
\
Beste. Itrî. İsfahan	\
\
Gel. ey nesim-i saba, hatt-i yârden ne haber?	\
Gelir mi, kafile-i nıüşkbarden ne haber?	\
\
Şemim-i zülfüne amadedir meşam-i ümid, \
Ne güne cünbüşü var, ruzgârden ne haber?	\
\
Aman, serv-i nazım, işvebazım, dilnüvazım!	\
Canım, a canım, hatt-i yârden ne haber?	\
\
Hay Hak!	\
\
(Perde gazelini okur.)	\
\
Hikmet amiz-i makal-i arifandır perdemiz,	\
Nüktesenc-i ayn-i mir'at-i cihandır perdemiz.	\
\
Her kemalden bir varak remzin ifade itmede.	\
Anlar erbab-i hünerver, zemişandır perdemiz.	\

Suratı zevk u sefa, sirette genc-i marifet, \
Şem’a-i irfan ile baksan ayandır perdemiz.	\
\
Zat-i çeşm-i şevkete Rabbim keder göstırmesün, \
Ol velinimetime neş’ekeşandır perdemiz.	\
\
Ruz u şeb vird-i zebanımdır dua-yi devleti!	\
RaşIDA, vicdanımı arz-i beyandır perdemiz.	\
\
(Kavgadan sora:)	\
\
**Karagöz.** Efendim! Ru herifin elinden mahruk-u pürnar oluyorum! Çünkü köşe penceresini küşad-i bad pat ederek orada lengerendaz olup her subh u şam, ve belki her akşam, hiddet-i mağlûbanem galeyan-i iştidade başlamakla olmak hasebiyle bu babda firarı karara tebdil etmekten başka çarem kalmamıştır. Çünkü bu herifin elinden vücud-ü natüvanım istemedi ki surette külliyen mecruh olup yüreğim cevelân-i lerzan ediyor, ve bununla beraber sadika-yi mücadele eshabındanım. Maamafih o keratayı ruz u şeb darbettiğimden dolayı ahali-yi mahalle tarafından ıttırad-i ba’ide olunmuştur ve bu babda da mazlûmane mestur olacağım bedihidir.	\
**H.** (gelir).Vay Karagözüm, sen misin?	\
**K.**Sabah akşam benden dayak yer misin?	\
**H.**Dayak yemem, bir tabak helva olursa yerim.	\
**K.**Onu bulsam ben de yerim.	\
**H.** Geçen gün bendeniz fakirhanede otururken canım sıkıldı, evden çıktım.	\
**K.**Başka yere mi taşındınız?	\
**H.**Evde canım sıkıldı, gezmeye gittim.	\
**K.** Hiç evde oturmazsın, Hacivad!	\
**H.**O gün de hava mutedil idi.	\
**K.** Senin soyunu sopunu bilirim, hepsi gidi idi.	\
**H.**Doğru bendeniz Kalpakçılarbaşına®!	\
**K.**Benim de o günü işim vardı, gittim.	\
**H.** Nereye gittin?	\
**K.**Atlamataşına.	\
**H.**Bir de baktım ki, Karagöz, o duhter-i pakize ahterler orada.	\
**K.** Vay, onlar o günü orada mıydılar?	\
**H.** Kimler. Karagöz?	\
**K.**Fındıklıdaki aktarlar.	\
**H.** Aktarlar değil, a canım! Hanim efendiler.	\
**K.** Vay, hanımlar şimdi efendi mi oldu?	\
**H.** Değil a canım! Büyük familyadan olursa ,,hanım efendi' derler.	\
**K.** Meyhanede yat, evde ne derlerse desinler" fehvasınca, neme lâzım benim? Ne derlerse desinler, ister hanım ister efendi, — Ey, sora?	\
**H.**Bir aşağı, iki yukarı servi gibi hıram ederler.	\
**K.**Semerci Vasil ile mi giderler?	\
**H.**Canım, piyasa ediyorlar.	\
**K.** Piyaz mı satıyorlar?	\
**H.**Canım, geziyorlar. Bunlar gezerken bir de öteden beri bir araba sesi, bir de ne bakarsın, Karagöz?	\
**K.** Bakar sensin, köpoğlu!	\
**H.**Arabanın içinde iki tane duhteri hünerver.	\
**K.**Vay, onlar arabada mı ıdı ?	\
**H.** Kimler, Karagöz?	\
**K.** Turşucunun beslemesi Hünerver7.	\
**H.** Turşucunun beslemesi değil. Arabanın içinde iki tane hanım. Mezburelerin hüsn ü dilberlikleri zannedersin ki tulü eden afitab misâli etrafa şule vermekte. Birisi değirmi yüzlü, kar gibi beyaz, öbürü gayetle cilveli esmerce biraz, birisinin saçı sünbül, kaşı keman; diğerinin dili bülbül, gözü yaman; biri söyledikçe insan bayılır, öbürü söylerse hemen ayılır; birisine beste söyletüp dinlemeli, öbürüne ..Haydi canım” deyüp bade verdirmeli.	\
**K.**Vay köpoğlu köpek! Bu nekadar medih? Meddah olsa bu kadar medhedemez! — Ey, sonra, Hacivad?	\
**H.** Bendeniz bunları görür görmez aklim başımdan gitti, dedi dîvane oldum.	\
**K.**Eğer tarifin gibi ise, Hacivad, ben de görsem çingâne olurdum.	\
**H.**Eski zendostluğum hatırıma geldi. Bu dilnüvazlar bana nim nigâhla aşinalık ettiler; bendeniz de arabanın arkasına düştüm.	\
**K.**Bir yerin kırılmadı mı? Ben de geçen akşam sarhoşlukla analağıma düştüm. Sora nasılsa güç halile çıktım.	\
**H.** Biz işi pişirmeğe başladık; bir de ne bakarsın? Öteden beri bir ruyi siyalı ile kühensal iki kadın geliyor.	\
**K.** Vay. onlar da mı çarşıdaydı?	\
**H.**Kimler, Karagöz?	\
**K.**Revanici Haydarla Kör Visal?	\
**H.**Bizim Arap halayıkla koca kan, yani kayınvalide! Baktım ki durmak olmıyacak, çarşı ortasında rezalete kaftan giydireceğiz. Bir az zamparalık edelim dedim. ..Felek Hamzeye yâr olmadı". Biz oradan firare karar verdik puşt-u pa-zen.	\
**K.**Demek ki yeni çıkmış, evveli yoktu.	\
**H.**Ne yoktu?	\
**K.** Kuşlu pazen.	\
**H.**Kuşlu pazen değil; puşt u pa-zen, yani tabanı kaldırıp kaçtım. Eğer kaçmasam olmaz, sora evde rahatım selb olur.	\
**K.** Salepçiyi bulur mu?	\
**H.** Rahatım kaçar. Bendeniz arabanın arkasını takip ettim.	\
**K.**Taktuka ile süprüntü mü döktün?	\
**H.** Arabanın peşini bırakmadım; dilber gitti ben gittim.(Hacivad ile Karagöz sallanırlar.)Ben gittim dilber gitti, dilber gitti ben gittim. (Hacivad çabuk söyler.)Ben gittim dilber gitti, dilber gitti ben gittim, ben gittim dilber gitti.	\
**K.**Ulan kerata! Tramvay mı koşturuyorsun yoksa şömendifer mi? Nefes al be!	\
**H.**Karagözüm, bunlar araba ile Mahmudpaşa başından doğru etraf u eknafı temaşa ederek Cisr-i cedide indiler.	\
**K.** Terlikçi Refik ile kunturat mı ettiler?	\
**H.** Hayır! Köprü başında arabadan indiler, arabacının parasını verip köprüden geçtiler.	\
**K.** Hacivad, arkalarından git!	\
**H.** Bunlar doğru köprünün Boğaziçi tarafına işleyen vapurların yanaştığı mahalle geldiler. Orada bulunan vapur memurlarından birine Rumeli cihetine işleyen vapurun kaçta hareket edeceğini sual ettiler.	\
**K.** Hacivad, sakın arkalarını brakma ha! Yumurta kapıya geldi!	\
**H.**Bunların birisi benim yanıma geldi. Yalıları Boğaziçinde Rumelihısarında olduğunu ve kendileriyle birlikte gitmekliğim için reca ettiler.	\
**K.** Veca mı ettiler?	\
**H.** Birlikte gidelim  dediler.	\
**K.** Bin vapura, Hacivad, hiç durma, gitmene bak!	\
**H.** Halbuki o günde deniz gayet sert. Öyle lodos esiyor ki vapura binmek güç; dalgalar adam boyu gibi yükseliyor.	\
**K.** Bin vapura! Vapur batarsa yüzmek de bilmezsin, boğulursun, kerata, ben de senden kurtulurum.	\
**H.**Her ne kadar ibram ettilerse de bendeniz cesaret edip vapura binemedim. Sair vakit gelirim diye söz verdim, adreslerini de aldım.	\
**K.**Vay tabansız kerata vay! Kadınlar senden cesaretli!	\
**H.** Bunlar benimle vedalaşarak bilet mahallinden biletlerini alıp Rumeli vapuruna rakib oldular; saat onu çeyrek geçerek vapur köprüden hareket etti.	\
**K.** Ulan, ne haltetme ki vapura binmedin!	\
**H.** Bunlar vapurdan bana işaretle birbirimizi selâmlıyarak vapur Boğaziçi cihetine müteveccih oluncaya kadar yanıp yakıla tahrik-i çarh-i azimet eyledi.	\
**K.** Senin ne adam olduğunu anladı mı?,, korkak herifin birisi" demişlerdir.	\
**H.**Kuzum, Karagöz, sen hiç lâkırdı anlamaz mısın?	\
**K.**Niye anlamam? Pek âlâ anladım.	\
**H.**Vapur kalktı. Gözden nihan oluncaya kadar bendeniz arkalarından hayran u sergerdan iskelede kalakaldım.	\
**K.** Vay, tabansız köpoğlu vay!	\
**H.**Ah Karagözüm! O akşam bendeniz fakirhaneye geldim, geldim amma, ne yolda geldiğimi ben bilirim.	\
**K.**Elbette sen bileceksin, ben bilecek değilim ya! Ulan, ne haltetme ki vapura binmedin!	\
**H.** O gece sabaha kadar ağlayarak rahat yatamadım. Hâb-i rahatım selh oldu. Mecnun misali daima mahbubelerin fikr ü hayaliyle kendimi teselli ederdim. Bir an hayalleri gözümden gitmezdi.	\
**K.**Senİnkisi kırkından Sora saz çalmak değil, yetmişinden sora azmak! Hacivad, eline bir ayna al da suratına bak! A keçi sakallı kerata, sana yakışır mı zendostluk?	\
**H.** Meram-i andelib visâl-i güldür; gönüldür bu gönüldür bu gönüldür!" fehvasınca muhabbet bir belâdır ki giriftar olmıyan bilmez. Sen onu bilir misin?	\
**K.**Onu da bilirim yirmiyi de. Ben sana bir sopa atarım ki o zaman aklın başına gelir.	\
**H.** Derunumda olan aşk ateşinde o derece şiddet gördüm ki benimle beraber toprağa gömülmedikçe sönmez kıyas ederdim.	\
**K.** Ah benim mini mini oğlum! Vaz geç, evlâdım, vaz geç, Hacivad, süzgeç!	\
**H.** Baktım ki olacak iş değil. Bizim mahallede bir acuze-i mekkâre ve dahiye-i sahhare vardı ki iblise fenn-i telhisi talim ve tarik-i hileyi esasiyle tavzih ve tefhim ederdi.	\
**K.** Elini tut, destini puset, Hacivad! Derdine deva bulur.	\
**H.** Buna iltica edip yedini takbil eyledim.	\
**K.** Yedekçi Mukbil ile kavga mı eyledin?	\
**H.** Bir az yalvarıp para ile gönlünü aldım. Bu işi göreceğine söz verdi. Bendenizden hanımların semtini suâl eyledi. Boğaziçinde Rumelihisarında olduğunu söyledim.	\
**K.** Pişkince bir karı, mangal kapağı gibi kaltak!	\
**H.** Acuze teşmir-i sak vebu kaziyeyi kuvveden fiile çıkaracağına söz verip vad eyledi.	\
**K.**Ulan, Hacivad, sonu pot gelirse görürsün, kerata!	\
**H.** Bendeniz koca karının evinden kalkıp kendi haneme geldim. Ol taraftan gelen habere muntazır olarak, çehar çeşm ile intizarda kalarak müterakkip oldum.	\
**K.**Hacivad, niçin inkisarda kalıyorsun? Anan baban vaktiyle beddua mı ettiler?	\
**H.** Canım, yârin tarafından haber bekliyorum.	\
**K.** Yârin tarafından galiba sana sopa gelecek.	\
**H.** Derken. Karagözüm, akşam yakın oldu; bizim kapı dak dak çalındı!(Karagöze vurur.)	\
**K.**Köpoğlu, kapının tokmağı benim suratımda mı?	\
**H.** Dakk-ı bab.	\
**K.** Fındık kebab.	\
**H.** Bendeniz pencereden baktım, kapıyı çalan kim diye. Meğerse bizim gönderdiğimiz kocakarı değil miymiş?	\
**K.** Gözün aydın, Hacivad. kulakların da Manisa	\
**H.** Bendeniz sürurumdan şad u handan oldum.	\
**K.** Sürür ağayı şadırvanda mı buldun?	\
**H.** Sevincimden çıldırıyordum.	\
**K.** Çıldırırsan Toptaşına dayarlar seni.	\
**H.** Derhal inip kapıyı kocakarıya açtım.	\
**K.**Sevincinden etrafa para mı saçtın?	\
**H.** İstikbal eyleyip merdivenden yukarı çıkarıp bizim küçük odaya aldım. İstifsar-i hatırdan sora yârimden gelen hayır haberden sual eyledim.	\
**K.** Hayreddinden gelen soğancıyı belledin mi ?	\
**H.**Yârden gelen haberden sual eyledim. Bendenize ..beşaret olsun sîzlere " diye tebşir eyledi.	\
**K.**Vay, Hacivad, sevgilin beşaret mi olmuş?	\
**H.** Neden, Karagöz?	\
**K.**Neden olacak? ..Beşaret olsun sîzlere diye tebeşir verdi" diyorsun.	\
**H.** Hayır efendim! Müjde verdi.	\
**K.** Beşaret demek müjde, cenabet demek te fena haber mi?	\
**H.** Kocakarı nasılsa bunların hanelerini bir takrib ile bularak haneye duhul edip merasim-i hoşâmediyi icra ettikten sonra yalan torbasını	açıp tiynet-i asliyesinde merkûz olan habaseti izhar eyleyerek: »Efendim, bendenizin buraya gelmemin veçhi: ser-i zülfünüzün mübtelâsı, çeşm-i mahmurunuzun ibtilâsı, âşık-i efgendeniz olan merhamete şayan bir zatin tarafından vuslet ümidiyle geldim” der.	\
**K.** Vay, köpoğlu kocakarı! Bu ne kadar lâkırdı! Tamam bir senelik lâkırdıyı birden söylemiş.	\
**H.** Bunlar bu sözü acuzeden gûş edince kemâl-i sürür ile bülbül gibi güftare başlayıp: »Sürür ü ibtihacımız olan efendiye söyle: Malûm-u şerifleri olsun ki bu cariyeleri o gündenberi kemâl-i iştiyak ile dilsuz olup ruz u şeb fikr u hayaliyle ah u enin etmekteyiz. Egerçi hane-i biminnetimize lütfen teşrif buyurulursa bizleri dilşad ederler."	\
**K.**Hacivad, gittiğin vakit bu suratla gitme! Suratına maske tak da öyle git. olmaz mı?	\
**H.** Benim nem var? Tenasüb-ü âzada noksan mıyım, behey çingene?	\
**K.** Neren güzel? Ulan, eşkal herifin birisin.	\
**H.** Bendenize bu haber gelir gelmez, doğru, Karagöz, ben berbere tıraş oldum, nevaleyi düzdüm, ver elini Rumelhisarı!	\
**K.** Hisara gideceğine çöplüğe git, kerata!	\
**H.** Kendilerin tarifi üzere yalıyı buldum; kapıyı çaldım, kapıcı kapıyı açtı.	\
**K.** Hacivad dayak yemeden kaçtı!	\
**H.** Kemal-i ihtiram ile bendenizi tazim ü tekrim ile yukarı çıkardılar.	\
**K.** Seni o halde görmeli. Hacivad! Tesbih böceği gibi büzülmüşündür!	\
**H.**Aman. Karagözüm! Görüş ne güzel manzara! Köşkün içi döşenmiş, ortasında bînazîr fıskiye yapılmış, dört tarafından mermerden aslan ağızlarından ma'-İ leziz cereyan eder ve bahçede enva’-i reyahîn ve ezhâr! Bendeniz seyr u temaşa eylerken . . .	\
**K.** Rüyada mı bu, Hacivad, gördüğün şeyler, yoksa malihulya mı?	\
**H.** Aynen müşahede ettim.	\
**K.** Aynada mı seyrettin? Denizin şevki vurmuştur.	\
**H.**Birden, Karagöz, ne bakarsın!	\
**K.**  "Mahmur mahmur sen de bana yâr misin aman ", ulan, bu şarkıdır!	\
**H.** Çarşıda gördüğüm hanımlar geldiler, yanıma oturdular. Hoşâmedîden sora muhabbete koyulduk.	\
**K.** Muhabbet ederken duyuldunuz mu?	\
**H.** Duyulmak değil, a canım! Muhabbet esnasında meclis takımı kuruldu. \
**K.** Ahmed beye kurşuncu Sabire mi vuruldu!	\
**H.** Al kadehi, ver badeyi, iş u işret, zevk u sohbet!	\
**K.** Bu işin sonu nekbet, Hacivad.	\
**H.** Hanımlar başladılar şarkıya.	\
**K.** Hanımlar küfür mü ettiler Şevkiye?	\
**H.** Şarkıya.	\
**K.** Hay, keçi sakallı kerata!	\
**H.** Bendeniz aşka geldim, üç defa nare attım2. Karagöz!	\
**K.** Birisi de sana tokat ataydı!	\
**H.** Hanımlar şarkı söylerken bendeniz muttasıl bade nuşediyorum.	\
**K.** Bademle işret mi ediyorsun?	\
**H.** Bendeniz doldurup hanıma veriyorum, hanım doldurup bana veriyor.	\
**K.** Öyle ise, adeta değişik oluyor.	\
**H.**Vur patlasın, çal oynasın!	\
**K.** Hacivad de zevk duymasın !	\
**H.**Bu aralık bir cariye geldi: ,.yemek hazır' dedi. Hanımların ikisi birden ..buyurunuz efendim yemeğe" diyerek tazim ü tekrim ile yemek odasına girdik.	\
**K.**Hacivad, eyi kamını doyur, ne olur ne olmaz!	\
**H.**Yemek sofrası bahçeye nazır olan köşke alafranga bir surette kurulmuş idi. Zannedersem hazmı teshil için alafranga sofralarda meyveler bulundurmak âdet olduğundan sofrada billur kâsenin içinde dördü beşi bir kıyelik şeftaliler duruyordu.	\
**K.** Canım Hacivad, söyleme! Ağzım sulandı; o kadar methetme!	\
**H.** Amade ve ihzar etmiş oldukları at’ime-i nefise ve eşribe-i lezizeden tenavül buyurmaklığımı teklif ettiler.	\
**K.** Kuzum Hacivad, bir daha gidersen bir kaç tane koynuna ko da sora bana verirsin.	\
**H.** Sofrada bulunan at’imelerden ve eşribelerden ekl ü şürb edip badehu sofradan kalkarak elimizi yıkayıp köşkün üst katındaki sahile nazır olan küçük odaya çıktık.	\
**K.** Hacivad. hâlâ uykunuz gelmedi mi? Yatsanız a	\
**H.** Alâ mümessek kahveler gelüp nuş olunduktan sora hanımlar bendenize: Eğer istek bu vurulursa habigâha teşrif buyurmaklığımı teklif ettiler.	\
**K.** Kahveci Agâh ile bir yere mi gittiler?	\
**H.** Değil efendim. Yatak odasına gitmek için söylediler. Bendeniz de maalmemnuniye hanımların reyini kabule şayan gördüm, hanımlarla birlikte yatak odasına duhul eyledik.	\
**K.** Ben de fuhul eyledim.	\
**H.**Bir de, Karagözüm, baktım ki ne göreyim? Odanm ortasında bir karyola, altından musanna, bütün üstü işleme.	\
**K.** Benim işlediğim yok. sen işliyeceksin, köpoğlu 	\
**H.** Odanın mefruşatı sair odalar gibi değil, gayetle müzeyyen, ve karyolanın yanında üç ayaklı merdiven.	\
**K.** Hiç karyolanın yanında merdiven olur mu?	\
**H.** Karyola yüksek olursa merdiven olur, suhulet için.	\
**K.** Merdivenden yukarı çık!	\
**H.** Bir ayağı merdivene attım; öteki ayağımı basayım derken ayağım kayar kaymaz yüz üstü düşer düşmez ayağım kırılmasın mı?	\
**K.** Aman, Hacivad, gördün mü ettiğin haltı!	\
**H.** Bu kabahat mı? Kaza olacak. Bir de, Karagöz, o can acısiyle gözümü açtım baktım ki sabah olmuş.	\
**K.** Ey, bu söylediğin rüya mı?	\
**H.** Sen sahi diye mi dinliyorsun?	\
**K.** Ne bileyim ben? Sen rüya demedin! Beni iki saattir göz hapsine aldın kerata! (Vurur, II. gider.)	\
Ben de gideyim de evde karıcığımla görüşeyim ! (Gider.)	\
**K.** (içeriden).Abla! Aç kapıyı!	\
Karısı. Açtım, gel bakalım! Nerede kaldın, kocacığım?	\
**K.** Ah benim osuruklu karıcığım!	\
**K.k.** Ayol! O nasıl lâkırdı? Öyle senin ağzına yakışır mı?	\
**K.** Ben fena bir şey söylemedim, ,,osurukla karıcığım" dedim.	\
**K.k.** Hâlâ söyliyor; bak terbiyesize! Osuruklu da sensin sıçıklı da sensin. Sabaha kadar osuran sen,sabaha karşı donuna sıçan sen. terbiyesiz herif!	\
**K.** Ulan, kabahatimi yüzüme karşı söyliyorsun!	\
**K.** Söylerim ya! Sen beni kızdırıyorsun! Bana izin ver, ben teyzeme gideceğim.	\
**K.** Git, neme lâzım benim?	\
**K.k.** Yalnız „git!" olmaz, para da isterim.	\
**K.** Al bakalım!	\
**K.k.** Ayı herif! Kırk para! Ben bunu ne yapayım?	\
**K.** Al bakalım sana beş kuruş!	\
**K.k.** Bu da az.	\
**K.** Kesemdekinin hepsini sana vereyim!	\
**K.k.** Ben gidiyorum. Evi gör gözet!	\
**K.** Kaçmasın diye mi?	\
**K.k.** Ateş var. afet var; dikkat et bir yere ateş sıçramasın, sonra yangın olur; kapıyı gece sürmele, hırsız girer.	\
**K.** Ulan, ne kadar fenalık varsa söyliyor.	\
**K.k.** Ben gidiyorum; eyi dikkat et! Gece bahçe kapısını da kapa! (Evden çıkar, Hacivad tarafına doğru gider.)	\
**K.** Şimdi biz evde yalnız kaldık. Bir misafir gelse de eğlen sek \
(Şarkı ile bir Kocakarı ile bir Zenne gelir, Hacivad karşılar.)	\
\
Şarkı Hüzam.	\
\
Niçin nalendesin böyle .. .	\
**Hacivad.**Böyle aheste vü beste yine, ey kaşı hilâl,	\
Nereye, yosma fidanım, ne taraftan teşrif?	\
\
Bir bakışta o güzel tavruna hayran oldum, \
A benim serv-i revanim, ne bu reftar-i lâtif?	\
\
Bir gülistan-i nezaket diseler hakkında, 
İdemezler yine hakkiyle cemalin tarif.	\

**Zenn.** Şöyle bir bak hüsnüme, ruy-i nezaket-kârime!	\
Bir nigâhım sen gibi bin âşıkı hayran ider.	\

Yaktı yandırdı cemalim her gören üftadeyi.	\
Tiğ-i çeşmanım cihanı hâsir u viran ider.	\

**Kocakarı. A** o ne? Beyit sövüyorsun da bana yok mu? Beni beğenmedin galiba.	\
**H.** Estağfurullah efendim! Hanım kızımı çoktan beri görmedim, büyümüş maşallah. Onun için hoşuma gitti de beyit ile karşıladım.	\
**Koca.** Geçen sene kız ile beraber Göksuya gittik. Karşı tarafımızda bir çok erkekler oturuyordu. Bir tane bizim kıza söz atmaya başladı, diğer birisi de senin gibi bir beyit söyledi.	\
**Karagöz.** (pencereden) Mezarcı Mahmudun karısı mı bu aceba?	\
**Koca.** Bak. ne dedi, Hacivad?	\
**H.** Ne dedi, efendim?	\
**Koca.** ,,Karanfilim saksıda, götümü ye Göksuda" dedi.	\
**K.**(pencereden). Bundan âlâ beyit olamaz sana! Bokun lâyıkı osuruk.	\
**Koca.**Bu da kim? Maymuna bak! (Karagöze hitaben:) Ey, bana altın gösteriyor!	\
**K.**Sana altın gösteren yok; sana âlâ kazma kürek!19	\
**Koca.** ,,Sana âlâ gevrek" diyor. Dişim yok ki yiyeyim!	\
**K.** Sen istediğin kadar ilâlle. Ben ,,kazma kürek" diyorum, o ,.gevrek" diyor. Sağır işitmez uydururmuş.	\
**H.** Efendim, eyisiniz inşallah, büyük hanım?	\
**Koca.** Elhamdülillah, eyiyim. Sen nasılsın, Hacivad. bakayım?	
**H.** Duada kusurumuz yok efendim. Hanım kızım, sen de eyisin inşallah?	\
**Zenne.** Elinizi öpüyorum, Hacivad Çelebi.	\
**K.** (pencereden).Ah. ben de seni öpsem	\
**Z.**Beğendin mi beni?	\
**K.** (pencereden)...Beğendin mi" de söz mü? Beğendikten sora bayıldım bile.	\
**Koca.** (Karagöze hitaben). Ey inan olsun, varmam sana! Gözle bana işaret ediyor!	\
**K.** (pencereden).Ulan, sana kim işaret ediyor? Git işine!	\
**Koca.** Elbiselerimi asarım, sandıklara basarım, bana cevredersen senin yakana kusarım.	\
**K.** Ben de senin yüzüne kusanın.	\
**H.** Efendim, böyle ne taraftan teşrif buyuruluyor?	\
**Koca.**Ne taraftan olacak? Evden geliyoruz. Ah, Hacivad Çelebi, derdim büyük.	\
**H.** Ne gibi efendim?	\
**Koca.** Ne gibi olacak? Kız geldi yetişti, hâlâ bir kısmeti çıkmadı.	\
**H.** Daha, efendim, yaşı başı ne? Elbette çıkar kısmeti.	\
**Koca.** öyle amma, Hacivad, kız kısmının ard eteği ön eteğine düşmandır.	\
**K.** (pencereden).Seni de alan bin defa pişmandır.	\
**Koca.** A varmam dedim ya! Hâlâ gözüme bakıyor!	\
**K.** Senin gözüne bakan yok. kızının gözüne bakıyorum.	\
**H.** Onun da bir nasibi çıkar.	\
**Koca.** Ben ölmeden mürüvetini görsem! Ölürsem gözüm açık gider	\
**K.** Ben senin gözünü bağlarım, eyi dolap çevirirsin22!	\
**Zenne. **Canım, annemden ne istiyorsun?	\
**K.** Annenden bir şey istediğim yok, senden istiyorum.	\
**Z.**Seni görür görmez yüreğimden bir şey hop etti, merakım kalktı.	\
**K.** Ben de öyle: Seni görür görmez bir şey hop etti benim de kalktı.	\
**H.** Karagöz, zevzeklik ediyorsun!	\
**K.** Kuzum Hacivad, şunu bana uydur san a 	\
**H.** Senin evde karın yok mu, Karagöz?	\
**K.** Karım vardı, dondurma yaptım.	\
**H.** Canim, haremin yok mu?	\
**K.** O çoktan gitti.	\
**H.** Demek ki evde yalınızsın, öyle mi?	\
**K.** Yalınızım, Hacivad. Şunu uydur da iki çifte olalım'	\
**H.** Bak san a. büyük hanım	\
**Koca.**Buyurun, a canım!	\
**H.** Kerime hanıma ben birisini buldum. Buraya gelmeniz? uğurlu oldu.	\
**Koca. ** Nasıl adam bu, Hacivad Çelebi?	\
**H.** Pek güzel bir adamdır, bendeniz kefil olurum.	\
**Koca.** Kendisini göremez miyim?	\
**H.** Görürsünüz efendim. Karagöz, aşağıya gel!	\
**K.**(pencereden). öpeyim elini, büyük hamın!	\
**Koca.** Öpme, çok yaşama! Çomar ol, sabah akşam tımar ol!	\
**K.** Sen de eşekçilere himar ol!	\
**H.** Nasıl efendim? Münasip değil mi?	\
**Koca.** Pek âlâ efendim, varırım.	\
**K.** Hacivad, iş anlaşılsın: kocakarıyı mı alacağız yoksa kızım mı?	\
**H.** Kızını alacaksın.	\
**K.** Pek âlâ.	\
**H.** Şimdi mahalleliye haber göndeririz gelsin. Büyük hanım, siz bize teşrif buyurun!(Hepsi gider.)	\
\
(Şarkı ile Mahalleli gelir.)	\
\
Tıngır mıngır tezgâhımın sesi var...	\
**Hacivad.** (gelir).Vay efendim, sefa geldiniz!	\
**İmanı.** Sefada daim ol, Hacivad Çelebi!	\
**H.** Efendim, iki kişi var, birbirine yapışacak.	\
**K.** (perdeye gelir). Kâğıt mı yapışacak?	\
**İmam (Mahalleliye hitaben).** Tutkal çanağın yanında mı?	\
**Mahalleli.**Yanımda.	\
**H.** Efendim, iki kişi var, birbiriyle imtizaç edecek.	\
**İmam.** Ha, anladım: İki kişi birbiriyle guleşecek.	\
**K.** Çok güzel lâkırdı anlıyorlar!	\
**H.** Duaya başlayın!	\
**İmam.** Zevk u sefa için geldi ahali—!	\
**Hepsi birden.** Hay ha—yt	\
**İmam.** Hangisi kız, hangisi oğlan ki? Ne belli - '	\
**Hepsi birden.** Hay ha—y!	\
**İmam.**. Yavrucağım, bir anadan beş on pederli— !	\
**Hepsi birden.**Hay ha—y!	\
**İmam.**. Galiba damat şu olacak çifte semerli— !30	\
**Hepsi birden.** Hay ha— y!	\
**İmam.**. Çok kocaların başını yedi eski hünerli— P	\
**Hepsi birden.** Hay ha— y!	\
**İmam.** Eskiden bir karı aldı sekiz memeli— H	\
**Hepsi birden.** Hay ha—y!	\
**İmam.**. Damat beyin soyu sopu Sulukuleli— !s	\
**Hepsi birden.** Hay ha— y!\
**İmam.**.Zannım: güveyi bey gelin hanımı beğenmemiş, ziyade kederli- 	\
**Hepsi birden.**Hay ha—y!	\
**İmam.**. Gelin hanımın soyu kimi Kasımpaşalı, kimi Fenerli— !’	\
**H.** Buyurun da şerbet için!	\
**İmam.**.Başüstüne (Hepsi giderler.)	\
	\
(Defa Hacivad ile Karagöz gelir.)	\
	\
**Hacivad.** Ey Karagöz, mübarek olsun!	\
**K.** Eksik olma, Hacivad!	\
**H.** Şimdi git. evinde rahatına bak!	\
**K.** Evde kimse var mı?	\
**H.** Ben onları arka sokaktan gönderdim sizin eve.	\
**K.** Allaha ’smarladık sizi! Hacivad, duadan unutma bizi (Hacivad gider.)	\
**Koca karı.** Güle güle oturun, evlâdım!	\
**K.** Eksik olma, kayın valide hanım, öpeyim! (Zenneye:)Sefa geldiniz!	\
**Zenne.** Sefa bulduk efendim!	\
**K.**Keyfiniz eyi midir?	\
**Z.** Çok şükür. Sizin keyfiniz?	\
**K.** Çok şükür. Sizin keyfiniz?	\
**Z.** Çok şükür. Sizin keyfiniz?	\
**K.** Böyle sabaha kadar keyif mi soracağız? Büyük hanım, artık git öteki evine!	\
**Koca.A .** giderim evlâdım! (Koca karı sokağa çıkar, yine içeri girer.)	\
**K.** Valide gitti, değil mi?	\
**Z.** Gitti efendim.	\
**Koca.** Selâmünaleyküm!	\
**K.** Ey, bu nereden çıktı?	\
**Koca.** Daha yeni geldim, evlâdım.	\
**K.** Beş dakika olmadı sen gideli!	\
**Koca.** Kızım, sana Hürmüz hanımın selâmı. Kâmile hanımın da!	\
**Z.**Getiren gönderen sağ olsun!	\
**Koca.** Ey, çıldıracağım! Ne zaman gitti, ne zaman geldi ? Sen bana baksan a. Buraya gel! Sen artık git!	\
**Koca.** Giderim, evlâdım, niye gitmem? Ben istemem kimseye bar olmak. (Gider gibi kapıdan çıkar, yine gelir. Selâmünaleyküm!	\
**K.** Bana baksan a, hanım! Biz bununla nasıl edeceğiz?	\
**Koca.** Mahalledeki komşular hepsi sana selâm söyledi, kızım!	\
**K.** Sen azacık bana gel! (K. kocakarının arkasından dayanır.) Haydi bakalım evine!	\
**Koca. **Giderim, ayol!(Gider gibi yapar, arka arka yürür.)	\
**K.** (iter, evine geri geri gelir).Nasıl edeceğiz bununla?	\
**Koca.** Gidiyorum artık ben.(Gider. Karagöz gitti zanniyle eve gelir; koca karı defa yine eve gelir.)Selâmünaleyküm'	\
**K.** Ulan, ne zaman geldi bu karı?	\
**Koca.** ömrün günün kararsın! Kan kim? Hanım desen e.	\
**K.** Kuzum hanım, büyük hanım! Artık git, çok oldun, yatacağız!	\
**Koca.** Neme lâzım? Ben giderim amma, beni arkana almalı.	\
**K.** Haydi bakalım ! (K. arkasına alır.) Ulan, ne kadar da ağır!	\
**Koca.** Eksik olma, evlâdım! Çoktan beri de eşeğe bindiğim yoktu.	\
**K.** (arkasından atar, eve gelir).Usandım be I (Koca kan gider.)	\
**Karagözün eski karısı** (Karagözün kapısını çalar).Yahu, kapı aç!	\
**K.** Ulan! Bizim karı geldi, iş fena!(Perdeye gelir.)Ne var, ne geldin?	\
**K.k.** Tuhaf! Evim değil mi? Geldim!	\
**K.** Sana bir ay daha izin ‘ İstediğin gibi gez!	\
**İkinci karı. **(perdeye gelir).Herif, o ne? Niye gelmiyorsun?	\
**Birinci Z.** Bu kim, herif?	\
**K.** Teyzemin kızı.	\
**Birinci Z.** (vurur).Bu kim, herif?	\
**K.** Dayımın kız kardeşi	\
**Birinci Z.** (vurur). Bu kim, herif?	\
**K.** Amcamın süt hemşiresi.	\
**İkinci Z.** Hanım, siz ne istiyorsunuz?	\
**Birinci Z.** Sen ne istiyorsun?	\
**İkinci Z.** O benim kocam.	\
**Birinci Z.** Şimdi bayılacağım! (Vurur.) Herif, bu kim?	\
**K.**Bilmiyorum kim olduğunu.	\
**İkinci Z.**  (vurur).Bu tarafa gel bakayım! Bana anlat, bu kim?	\
**K.**Efendim, bu kayın anamın torununun torunu.	\
**Birinci Z.** (vurur).Bu tarafa gel bakayım ’ Bu karı kim, söyle bana !	\
**K.** Efendim, bu kadın büyük validemin anasının babasının kemiğine sıçayım!	\
**İkinci Z.** Buraya gel, herif! (Karar.) Bu karı kını?	\
**K.**Kızkardeşimiu ablasının teyzesinin hey teyzesinin de . . .!	\
**Birinci Z.** Hanım, sen kim oluyorsun bakayım?	\
**İkinci Z.** Ben onun karısıyım.	\
**Birinci Z.** Ey, bayılacağım şimdi! Ben onun kırk senelik karısıyım.	\
**İkinci Z.** Ben de karışıyım. Eskiye rağbet olsa Bitpazarına nur yağar.	Seni beğenmemiş, senin üstüne beni aldı	\
**Birinci Z.** Herif, bu karın mı senin?	\
**K.** O da karım, sen de karım! İkinizi de ben idare edecek değil miyim?	\
**Birinci Z.** Hain! Şimdi anladım!(İçeriye bağırır.)Enişte hu!	\
**Sarhoş.** (içeriden).Ne var, ne istiyorsun?	\
**Birinci Z.** Buraya gel!	\
**Sarhoş.**  (,,Bir güzelin sevdası var başımda”şarkısı ile gelir).	\
Ne var, ne istiyorsun bakayım?	\
**Birinci Z.** Şu herifi gördün mü ?	\
**Sarhoş.**Gördüm, ne olmuş?	\
**Birinci Z.** Benim bu herif kırk senelik kocanı.	\
**Sarhoş.**Evet, sora ne oldu?	\
**Birinci Z.** Ne olacak? Ben evde yokken bu hanımı da benim üstüme nikâh ile almış.	\
**K.** Efendim, ucuz buldum aldım.	\
**Sarhoş. ** (Zennelere:) Haydi siz ikiniz de gidin!(Gider.)Ey, gel, top sakallı herif! Ölümlerden ölüm beğen!	\
**K.** Efendim, bana ölüm; Yüzüme tükürürsün, bana birinci ölüm bu !\
**Sarhoş.** Öyle ise, ben de seni affettim, velinimet efendilere de bağışladım.	\
\
(Gider. K. ile H. gelirler, oyun hitam bulur.)	


