
# bahce


**Hacivad. **(şarkı söyliyerek perdeye gelir).	\
\
Nakş-i Hâce	\
\
Amed nesîm-i subhdem, tersem ki âzâreş küned.  \
Tahrik-i zülf-i anbereş ez hâb bîdâreş küned.	\
\
Cânân-i mâ, cânân-i mâ, rahmet bikün bercân-i mâ, \
An dem ki can ber leb resed hemrâh kün îmân-i mâ!	\
\
Hay Hak!	\
\
(Perde gazelini okur.)	\
\
Nakş-ı sun’un  remzider hüsnünde rü'yet perdesi, \
Hâce-i hükm-i ezeldendir hakikat perdesi.	\
\
Sireti surette mümkündür temaşa eylemek,\
Hail olmaz ayn-i irfana basiret perdesi.	\
\
Her neye im'an ile baksan olur iş aşikâr,\
Kılmış istilâ cihane hab-i gaflet perdesi.	\
\
Bu hayâl-i âlemi gözden geçirmektir hüner, \
Nice kara gözleri mahvitti suret perdesi!	\
\
Şem'i aşka’ yandırıp tasvir-i cismindir geçen.	\
Ademi amed-şüd itmekte azimet perdesi.	\
\
Hangi zılla İltica itsen fena bulmaz aceb?	\
Oynatan üstadı gör, kurmuş muhabbet perdesi.	\
\
Dergeh- i âl-i abâ’da müstakim ol, KEMTERİ!	\
Gösterir vahdet elin kalktıkça kesret perdesi.	\
\
(Taganniye başlar:) Yâr, bana bir eğlence! Yâr, bana bir eğlence!	\
Meded ey !	\
Lûtf eyle, Hüdayâ. bana cananımı gönder.	\
Can mülkü harab olmada, sultanımı gönder! Meded ey!	\
\
**Karagöz** (yukarıdan atlar, kavga ederlerken Hacivad gider, Karagöz bakar ki karşısındaki o da Karagöz).	\
**Birinci Karagöz,** Uan, bu kim?	\
**İkinci Karagöz.** Ulan, bu kim? .	\
**Birinci K.** Şimdi çıldırırım	\
**İkinci K.**Şimdi çıldırırım!	\
**Birinci K.**Sen kimsin?	\
**İkinci K.**Sen kimsin ?	\
**Birinci K.**Ben Karagözüm.	\
**İkinci K.**Ben Karagözüm.	\
**Birinci K.**Asıl Karagöz benim!	\
**İkinci K.**Asıl Karagöz benim!	\
**Birinci K.**Benim refikim de var.	\
**İkinci K.**Benim refikim de var.	\
**Birinci K.**Adına Hacivad derler,	\
**İkinci K.**Adına Hacivad derler.	\
**Birinci K.**Biz eskiden beri onunla beraber görüşür konuşuruz.	\
**İkinci K.**Biz eskiden beri onunla beraber görüşür konuşuruz.	\
**Birinci K.**Sen bu akşam nereden çıktın?	\
**İkinci K.**Sen bu akşam nereden çıktın?	\
**Birinci K.**Seninle derde gireceğiz.	\
**İkinci K.**Seninle derde gireceğiz.	\
**Birinci K.**Ben şimdi Hacivadı çağırırım.	\
**İkinci K.** Ben şimdi Hacivadı çağırırım.	\
**Birinci K.**Hacivad, aşağı gel!	\
**İkinci K.**Hacivad, aşağı gel!	\
**H.** (içeriden) Geliyorum, Karagöz! (Semai ile perdeye gelir.)	\
On kere dinledim mi sana: Sevme dokuz yâr!	\
Sekizde vefa yoktur ammâ yedi de zinhar!	\
Altı ile beş dört ile üç başe çıkılmaz, 
üçün ikisin terkidegör ta kala bir yâr!	\
\
Beni niye çağırdın, Karagöz?	\
**Birinci K.**Kuzum Hacivad, bu perdenin Karagözü ben miyim yoksa bu mu?	\
**İkinci K.**Kuzum Hacivad, bu perdenin Karagözü ben miyim yoksa bıı mu?	\
**H.**Efendim, o da Karagöz, sen de Karagöz.	\
**Birinci K.**Canım, anladık amma, asıl Karagöz hangimiz?	\
**İkinci K.**Canım, anladık amma, asıl Karagöz hangimiz?	\
**H.** Bu perdenin Karagözü sensin.	\
**Birinci K.**Gördün mü ulan, asıl Karagöz benim.	\
**İkinci K.**Haydi şuradan, budalâ sen de Asıl Karagöz benim!	\
**Birinci K.**Hacivad, nasıl edeceğiz, sabaha kadar döğüşecck miyiz?	\
**İkinci K.**Hacivad, nasıl edeceğiz, sabaha kadar döğüşecck miyiz?	\
**H.**Canım efendim, rica ederim, kavga etmeyin!	\
**Birinci K.**Bu lâkırdı anlamıyor!	\
**İkinci K.**Bu lâkırdı anlamıyor!	\
**Birinci K.**Anlaşıldı, buna dayaktan başka bir çâre yok.	\
**H.**Canım, hakkınıza razı olsanız a!	\
**Birinci K.** Ben hakkıma razıyım.	\
**İkinci K.**Ben hakkıma razıyım.	\
**Birinci K.** Haydi defol şuradan!(Vurur.) Defol diyorum! (Kavga ederler. Karagöz sonra gelen Karagözü kovar.) Ne belâ imiş bu be!	\
**H.**Karagöz, geçmiş olsun! Güç belâ kurtuldun!	\
**K.**Sen de kendine eş buldun! (Vurur.)	\
**H.**Eyiliğe kemlik!	\
**K.** Meşhur meseldir: ,,Her kime edersen eyilik, anda hazırdır kemlik.” (Vurur.)	\
**H.**Karagöz, seninle konuşmıyayım diyorum, bir türlü yapamıyorum.	\
**K.**Neden konuşmayacaksın benimle? Aramızdan kara kedi mi geçti?	\
**H.**Dayaktan başka bir şey bilmiyorsun; seninle iki çift sohbet etsek olmaz mı?	\
**K.** Niye olmaz? Pek âlâ olur, benim başıma gelenleri hiç sormiyorsun.	\
**H.**Hayır ola, Karagöz?	\
**K.**Bir Beyoğluna gittim, üç defa dayak yedim, dördüncü bir dayak daha yiyecektim, çabuk sıvıştım.	\
**H.**Aman bilâder, pek merak ettim! Rica ederim, başına gelen serencamı anlat!	\
**K.** Serence beyi anlatayım! Başkası söylese, insan inanmaz, Hacivad.	\
**H.**Çok merak ettim Karagöz.	\
**K.**Lâkırdımı kestirirsen, yumruğumu suratına yersin. Geçen gün evde otururken canım sıkıldı. Ne yapayım, nereye gideyim diye düşündüm. Nihayet aklıma sen geldin, hazır evde kimse yokken gideyim Hacivadla birlikte gezeriz dedim,	\
**H.** Eyi akıl etmişsin Karagöz!	\
**K.**Dayağı yiyeceksin, sesini çıkarma! Kalktım sizin eve doğru geldim. Kapıyı çalar çalmaz senin koca çomar pencereye koştu. ,,Kimdir o?" dedi. Ben de: ..Hacivad evde mi?“ dedim: ,,Ne yapacaksın" diye başladı âhiret suali sormaya. Ben de dedim ki: ,.Bir az gezelim diyecektim, aşağıya gönderir misiniz? der demez ..Hayır, hayır, o senin gibi terbiyesizlerle görüşmez, kim bilir alıp nereye götüreceksin. Adamcağız afyonunu yutup yatalı daha on altı saat oldu. Haydi rahatsız etme! inan olsun, başına bir kova su dökerim! Haydi çekil bakayım oradan!" demez mi? İşte o vakit hiddetim topuklarıma çıktı, küplere bindim.	\
**H.**Aman bilâder, hiddet etme, onlar saçı uzun aklı kısa cahildirler, her söyledikleri söze ehemmiyet verilmez.	\
**K.**Her ne hal ise, senin karın beni kovar kovmaz hemen eve geldim. Veresiye aldığım alangla pantolonumu giydim, redingotu da giydim, potinlerimi de ayağıma giydim. ışkırlağı başıma geçirdim, bastonumu da aldığım gibi sokağa fırladım.	\
**H.**Canım Karagöz, ne tarafa böyle?	\
**K.** Elinin körüne! Ulan, lâkırdı anlatırken sen ses çıkarma!	\
**H.** Ne darılıyorsun, bilâder. bir daha ağzımı açmam.	\
**K.** Ya açarsan?	\
**H.**Seni kör göreyim!	\
**K.** Yo. Hacivad, yemin etme!	\
**H.**Sonra, Karagöz?	\
**K.** Sonrası: Evden çıktım, doğru Sirkeciye. Saate bir nazar ettim, topa yarım saat var. Hemen bir ahçı dükkânına girdim, bir çorba söyledim getirin diye, on paralık da pide. Yemek önümde, boyuna teyemmüm ettim. Bop diye top patladı; çorba mideye ilk posta, ikinci posta bir	tas kebabı,onu da yedik. Hisabı sordum ahçıya: iki adet sim-mecidiye kuruşundan bir tek metelik eksik!\
**H.**Karagöz, ne ucuz!	\
**K.** Bir dakika lâf etmesen ağustos böceği gibi patlıyacaksın.\
**H.**Canım, sormıyayım mı?	\
**K.** Sorma da dinle!	\
**H.**Dinliyorum.	\
**K.**Hiç bir şey söyleme, sus! Şimdi dayak yiyeceksin!	\
**H.**Sustum, Karagöz.	\
**K.** Karnımı doyurduktan sonra iri bir fincan kahve üçüncü katan teşkil etti. Sonra yavaş yavaş kayıkların durduğu yere kadar geldim, dolmuşa atladım, doğru rıhtıma, meteliği bayıldıktan sora öteye beriye bakarak . . .	\
**H.** „Etraf u eknafı temaşa ederek..“	\
**K.**„Göz süzüp gerdan kırarak ...“ . Lâkırdı söylemesen patlıyacaksın! Sallana sallana yürümeğe başladım; ne kadar gittiğimin farkında değilim. Birisi bana: ,,Sakallı, na, gel!" diye çağırdı. Bir de etrafıma baktım: Ulan! Allı pullu yeşilli mavili kırmızılı üç otuzluk dört yirmilik madmazeller etrafımı almış!	\
**H.**Aman. Karagöz ! Sakın öyle yerlere girme!	\
**K.** Ulan, o kadar midesiz miyim ben?	\
**H.**Belki şeytana uyarsın.	\
**K.**Şeytana uyarsam, sana uyarım.	\
**H.**Ulan, ben şeytan mıyım?	\
**K.** Şeytandan da geri kalmazsın!— Ne işe, ben hiç aldırmadım. Derken ne oldu bilmem, „Uç, baba torik!" diye birisi bağırmaz mı? Haydi arkasından biri daha ,,Uç, baba leylek!" dedi. Böyle iltifatlarla biz köşeyi döndük, yavaş yavaş yokuşu tırmandık. Şaka maka derken saat bir buçuk ikiye gelmişti. Nasıl oldu bilmem, bir sokağa daldım, pencerelerden bir iki baş gözüküyor, bunlar da esnaftan amma, bir az kibar olmalı, sesleri çıkmıyor, adamı öyle ötekiler gibi çağırmıyorlar. Sokak biter bitmez Tepcbaşına geldiğimi anladım!	\
**H.**Karagöz, epeyce mesafe kat etmişsin.	\
**K.** Evet, epeyce kadayıf yedik. Ulan, vay canına yandığımın madamlar, mösyöler, madmazeller. efendiler, beyler, ağalar, züppeler, zenginler, züğürtler, kopuklar, külhanbeyleri! Vay efendim vay! Bütün millet orada! Bir az daha yukarı çıktım, bir kapının önüne birçok resimler koymuşlar; herkes geliyor oraya gelip bilet alıyor. Meğer orada sinematograf mıdır miriagotoraf mıdır nedir?	\
**H.**Sinematograf,	\
**K.** O oynıyormuş. Ben de gittim; ne olursa olsun, .şurasını da göreyim dedim. Bilet verilen yere sokuldum, çeyreği uzattım ,,Bir bilet ver!" dedim, herif yüzüme bakmadan ..Karşıdan aliniz!" dedi.	\
**H.** Demek ki, Karagöz, oyun biletini karşı taraftan mı veriyorlar?	\
**K.** Evet, öyle İmiş. Karşıda kahve dükkânı var.,.Oradan bilet alınır mı?" dedim, o da bana ""Karşıki kişeden al!" Hoppala! ,.Hangi şişeden alayım, orası sizin oyun mu? Sizin oyuna gireceğim!" dedim. „Evet, bizim" dedi. Ben de dümeni o tarafa kırdım, herif çeyreği aldı, elime bir bilet verdi, bileti verdiğim gibi beni karanlık bir yere tıktılar.	\
**H.** Sakın ahır olmasın, Karagöz?	\
**K.** Evet, ahırmış. Sizin peder orada arpa yiyor. Sırtın kaşınıyor galiba!	\
**H.**Niye kızıyorsun?	\
**K.**Niye kızmam? Girdiğim yeri ahıra benzettin!	\
**H.**Pek alâ, o karanlık yer neresi imiş?	\
**K.**Tiyatro imiş. İçeriye girdim, bir takım hayaller gördüm, sonra bir az daha aşağıya baktım: Ulan, koca bir ev tutuşmuş yanıyor, İtfaiye bile gelmiş de benim haberim yok.	\
**H.** Karagöz kaçaydın!	\
**K.** Niye kaçacaksın? Hemen ben ,,Yangın var!" diyerek başladım yangın yerine doğru koşmaya. Derken, efendim, bir yere çattım, başladım yuvarlanmaya, hem yuvarlanıyorum, hem de sille tokat her taraftan bize iniyor.	\
**H.** Sen de onlara vur, bilâder!	\
**K.** Nasıl vuracaksın ?	\
**H.** Niçin seni dövüyorlar?	\
**K.** Ben de farkında değilim. Benim de niyetimden geçiyor ,,Bir iki tokat vurayım!" demeye kalmadı, ortalık bir aydınlık oldu. 0 zaman farkına vardım ki ben yangın yerine doğru koşarken ahalinin üzerine yıkılmışım. Yumruk tokat derken bizi adamakıllı aşağıya kadar uçurmuşlar. Ben hâlâ dayak yiyorum, o patırtıda gözüme yangın olan taraf ilişti. Bir de ne görsem beğenirsin?	\
**H.** Ne gördün, Karagöz?	\
**K.** Bem beyaz bir perde.	\
**H.**Yangın basılmış mı?	\
**K.** Ben de farkında değilim basılmış mı basılmamış mı.	\
**H.**Tahminen yangın ne taraftaydı?	\
**K.**Marmara açıklarında.	\
**H.**Deli mi oldun, Karagöz? Hiç deniz tutuşur mu?	\
**K.** Lâkırdımı bitirmeden lâkırdı karıştırdın. Suratına bir tokat atarsam görürsün.	\
**H.**Pek âlâ, sonra ne oldu?	\
**K.**Ne olacak? İki kişi benim kolumdan tuttukları gibi kapı dışarı beni attılar, biz de soluğu burada aldık.	\
**H.**Aman Karagöz, geçmiş ola!	\
**K.**Geçirdik. Bir az edelim mola! ( Vurur, Hacivat! gider.)	\

(şarkı ile Çelebi gelir. Hacivad tarafına bahçe konur.)	\
\
Şarkı Hicazkar	\
\
Gel, seninle yarın, ey serv-i revân	\
Olalım mahfice Göksuya revân.	\
Dide-i ağyârden olup nihân	\
Nakarat: Olalım mahfice Göksuya revân.	\
Gonca gülsün, sen dahi, ey verd i nâz, 
Zevk it açılsın gözün gönlün biraz.	\
İki yıldır gitmedin, bari bu yaz.	\
\
Ey zan.	\
\
**Hacivad. ** (gelir). Vay beyim, uğurlar olsun!	\
**Çelebi.**Allaha emanet ol, Hacivad Çelebi!	\
**H.** Eyisiniz inşallah, efendim?	\
**Ç.** Teşekkür ederim, Hacivad Çelebi, siz de eyi misiniz?	\
**K.** (pencereden). Siz de ayı misiniz, Hacivad, yoksa kurt mu?	\
**H.**Duada efendime kuşunun yok.	\
**K.** (pencereden). Duvarda kusuru yok, temeli fâsid keretanın!	\
**Ç.** Buraya gelişimin sebebini bilir misin, Hacivad Çelebi?	\
**H.**Hayır ola, efendim?	\
**Ç.**Şu bizim Murgzar bağı yok mu?	\
**H.**Evet efendim, var.	\
**Ç.**O bahçeyi size teslim edeceğim, içerisinde köşkün eksiğine gediğine ve bahçenin tımarına nezaret edeceksiniz. Meşhur meseldir: "Bakarsan bağ olur, bakmazsan dağ olur."	\
**H.** Evet. Bendeniz de elimden geldiği kadar sây u gayret ederim, bahçıvan tutar, bahçeyi kirizme ettiririm; şükûfelere, sebzelere bakarlar sularlar, bağ budama zamanı ağaçları budarlar vesair eksiğine bakarlar.	\
**Ç.**Buyurun, gidelim de bahçeyi teslim edeyim!	\
**H.**Buyurun efendim! (Giderler.)	\
**Ç.** (içeriden). Bak. Hacivad Çelebi, bunlar salkım ağaçlarıdır kırmızı, sarı, beyaz, mor. türlüsü var.	\
**H.** Evet efendim.	\
**Ç.**Bunlar da karanfil saksılarıdır, bunların de envaı var.	\
**H.**Kulunuz elime çakıyı alır bunların budama zamanı kendim budarım, ve sair elimden gelen şeyleri de bahçıvana bırakmam kendim yaparım.	\
**Ç.**Bendeniz gidiyorum, Hacivad Çelebi. Şu iki yüz lirayı da alın !	\
**H.** Efendim, ard kapıdan teşrif buyurun!	\
**Ç.** Allaha ’smarladık.(Gider.)	\
**H.** Devlet ü ikballe!(Perdeye gelir.) Ey Karagöz, bak, ben bir bahçe sahibi oldum, hem de beş on kuruş bey efendiden aldım. Şen orada çatla patla!(Evine gelir.)	\
\
**Karagöz** (içeriden, makam ile:)	\
\
Gider oldum, göz yaşını dökerem dökerem.	\
Aman, karı senin hotozuna işerem, aman, aman ey, ey!	\
\
**Karısı.** (içeriden).Herif, ne oldun?	\
**K.** Ben de ne olduğumu bilmiyorum.	\
**K.k.** Deminden türkü söyliyordun, şimdi ağlıyorsun, hava değişti.	\
**K.**Hacivada bir çebellebi geldi.	\
**K.k.**Hacivad leblebi mi yedi?	\
**K.**Hayır, nohut yuttu. Ulan, nasıl lâkırdı anlarsın sen?	\
**K.k.**Ne bileyim? Senin lâkırdından bir şey anlaşılmıyor ki!	\
**K.**Hacivada bir bey geldi, bir bahçe teslim etti, iki yüz tane altın verdi.	\
**K.k.**Pek alâ, onun kısmeti ayağına gelmiş. Sen de tevekkül ol, senin de kısmetin ayağına gelir.	\
**K.**Benim kısmetim ayağıma gelinceye kadar gider Hacivaddan isterim.\
**K.k.**Sen bilirsin.	\
**K.** (perdeye gelir, bahçe kapısını çalar).Bana baksan a. çakçıvanci! (İçeriden köpek havlar:)'Au, ‘au, 'au!	\
**K.** Ulan, seni istemiyorum, babanı gönder! (Bahçe kapısını çalar.) Çakçıvanci!	\
**Köpek.** Au, au, au	\
**K.**Ulan, çakçıvanci!	\
**Köpek.** (gelir).'Au, au, 'au, au, 'au!	\
**K.** Ulan, oşt! (Köpek Karagözü ısırır, her tarafını, köpek bahçeye gider, Karagöz eve gelir.)	\
**Karısı.** A herif, ben mayısta yalvardım ,,Kocacığım, bana para ver de üç tane boynuz ensemden hacamat olayım" diye; bana vermedin, bak kendin ne güzel hacamat olmuşsun!	\
**K.** Sen hacamat olmak mı istiyorsun?	\
**K.k.** Evet.	\
**K.** Sen bana bir parça ekmek ver de ben sana hacamatçıyı getireyim!	\
**K.k.** Al bakalım, leğen hazırlayım mı?	\
**K.** Zırla zırlama, orasını bilmem.	\
(Karagöz perdeye gelir.) Ben şimdi kolayını bilirim.(Bahçenin kapısını çalar, köpek dışarı gelir.) Al bakalım!(Köpeğe ekmek verir, köpek yer.)	\
**Köpek. ** Nam nam ’au ’au ’au nam nam!	\
**K.** Köpoğlu, insan gibi lâkırdı edecek! Al bakalım, köpoğlu!	\
**K.**Nam nam nam au au ‘atı!	\
(Karagöz köpeği eve götürür, köpek hem karısını hem Karagözü ısırır).'Au ‘au “atı!	\
**K.** Aman, öldüm! Her tarafımı ısırdı köpoğlu!(Karısı da bağırır.)	\
**K.k.** Aman herif, bu nasıl şey? Her tarafım yara oldu, bütün dişledi!	\
**K.**Benim de her tarafımı şişledi!	\
**K.k.**Sen neredesin herif?	\
**K.** Ben korku ile küpe düştüm.	\
**K.k.**Ben de badyanın içine düştüm.	\
**K.** Çık oradan!	\
**K.k.** Herif, gel de çıkar, ben kendim çıkamam!	\
**K.** Ben nasıl çıkarayım? Nasılsa, kurtulduk!	\
**K.k.**Ben de güçle çıktım.	\
**K.** (perdeyegelir).Ey Hacı Cavcav, şimdi ne yapacaksın?(Bahçe kapısını çalar.)Ey, bahçıvancı, bahçıvancı!	\
**H.** (içeriden). Canım, kimdir o kapıyı çalan?	\
**K.** Bana şuradan on paralık tereotu ile yirmi paralık maydanoz kopar!	\
**H.**Burası sebze bahçesi değil, şükûfe bahçesi.	\
**K.** O küfeden de kopar on paralık!	\
**H.** Canım, kim bu kapının önündeki?(Dışarı gelir.) Ne o. Karagöz? Ne istiyorsun?	\
**K.** Ulan, benim iyiliğimi bilmezsin!	\
**H.** Hayır ola. Karagöz, ne oldu?	\
**K.** Ne olacak? Geçen akşam evde uykum kaçtı.	\
**H.** Olur ya! Bazen uykusu kaçar, bazen de insan Yemliha gibi yirmi dört saat uyur.	\
**K.**Evet, pençerenin önüne oturdum, cumbadan etrafı seyrediyorum. Karanlıkta iki üç kişi geldi bizim cumbanın altına.	\
**H.** Evet.	\
**K.**Usul usul konuşmaya başladılar.	\
**H.**Ne konuşuyorlardı, Karagöz?	\
**K.** İçlerinden birisi ötekilerine dedi ki ..Haberiniz var mı?" diye sordu. Onlar da ..Neden haberimiz olacak, bir şey mi olmuş?" dediler. „Hacivada bir bey gelmiş, iki yüz lira para vermiş, bir bahçe teslim etmiş" dedi. Sonra bunlar karar verdiler: ..Bir akşam bahçeye gireriz, Hacivadı öldürürüz, paraları da alırız" dediler.	\
**H.**Pek âlâ, şimdi senin maksadın ne?	\
**K.** Paraları bana verirsin ben saklarım.	\
**H.** Ben sana paraları verirsem onlar bahçeye gelmiyecekler mi beni öldürmeğe?	\
**K.** Gelecekler.	\
**H.** Madem ki gelecekler, beni öldürüp mundar kanıma girdikten sonra o paralar sende kalacağına o babayiğitlere helâl olsun. Ben sana böyle desise ile para vermem vermem; hem de seni bahçeye koymam koymam koymam! (Karagöze tekme ile vurur.)	\
**K.** Vay köpoğlu, yutmadı! Ben de, Hacı Cavcav,bu akşam bu bahçede sana rahat vermem vermem vermem (Gider.)	\
\
(Semai ile Acem gelir.)	\
\
Semai Uşşak'	\
\
Hayli dem zincir-i ziilf-i aşkının meltuniyem,\
Bir saçı leyla güneş-ruhsarinin Mecnuniyem.	\
\
Çektiğim hep derd-i dildendir benim, Arif, dahi 
Söylemem, bilsin bilenler, ben kimin nıeftuniyem.	\
\
Hayranın olam, kurbanın olam, sergerdanınam, \
Aman, biçarenem, ey yâr!	\
\
**Acem**(gazel okur)	\
\
Kanda varsa âşık-ı biçare cananın arar.	\
Derd ile biçar olan elbette dermanın arar.	\
\
Sanma rahmından sunar desti dil-i mecruhuma!	\
Ol keman-ebru ciğerde tir-i müjganın arar.	\
Verd-i gülzare dokunmakta sabanın kasdı var, 
Andelib-i binevanın zar-i pinhanın arar.	\
\
**Hacivad. ** (semai ile perdeye gelir).	\
On kere dimedim mi sana: Sevme dokuz yâr...	\
Hoş âmedi, sefa âmedî. İran gülü he he hey!	\
\
**Acem.**Hoş bulmuşanı, safâ bulmuşam, meydân bülbülü canım baba ha ha hay!	\
**K.** (İçeriden).Birisi „hoşafı kim içti" diyor, öteki de „ben içmedim" diyor.	\
**H.** Efendim, böyle ne taraftan âyende, ne tarafa revendesiniz?	\
**Ac.** Pas ki manim özümden sual edübdi?	\
**H.**Evet efendim.	\
**Ac.** Mân çokh yârlar dolaşmışam.	\
**H.** Ne tarafları dolaştınız, ne taraflarda gezdiniz?	\
**Ac.**Diyar-i Tahrân.	\
**K.**(pencereden).Diyar-i tarhâna.	\
**Ac.** Diyâr-i Horasân	\
**K.** Diyâr-ı kireçhane.	\
**Ac.** Diyâr-i Khoy.	\
**K.** Ma ma ma ma moy!	\
**Ac.** Diyar-i Tiflis.	\
**K.** Hacivad da müflis, ben de müflis.	\
**Ac.** Diyâr-i Kâşân.	\
**K.**Diyâr-i nişan.	\
**Ac.** Diyar-i Şiraz.	\
**K.** Diyar-i kiraz.	\
**Ac.** Diyâr-i İran.	\
**K.**Diyâr-i ayran.	\
**H.** Demek ki. efendim, zatı âliniz İranlısınız?	\
**Ac.** Bali. 	\
**H.**İranda ne isimle yâd olursunuz?	\
**Ac.** İranda Haca Sârfirâzın nökeri Baha Nukûd deyalla.	\
**K.** (pencereden).Hoş geldin, baba yoğurt, kova ile mi teşrif ettiniz yoksa torba ile mİ?	\
**H.** Karagöz, defol oradan!	\
**K.** Nene lâzım senin, ne tef olurum ne de dümbelek. Sen işe karışma, kelek oğlu kelek!	\
**Ac.** Pâs ki sizün ismivüzce ne diyella?	\
**H.** Akdenizin hartısı, Karadenizin martısı, lâkırdı kavvafı, insan sarrafı, Brusalı Hacı Evhad namiyle meşhur-u Afakım.	\
**Ac.** Pas ki Hacivad sansan? Pas kî Hacivad sânsan?	\
**K.** (pencereden). Hacivad da sersem, sen de sersem!	\
**H.** Yıkıl oradan. Karagöz! O senin tanıdığın adamlardan değil o, Iran gülüdür, İran gülü!	\
**K.** O İran gülü ise ben de istanbulun bülbülü.	\
**Ac.** Sen mannan mizahlanısan?	\
**K.** Ulan, seninle alay edersem ne olur?	\
**Ac.** Fârisî mîdânem.	\
**K.**Kaysı bir tane, iki tane, sana ne?	\
**Ac.** Ahu zitû âmûkht bâhângâm-ı davîdân	\
Râm kârdan u îstâdân u vâpâs nigâridân. \
Parvâna zimân, şam' zimân, gül zimân âmûkht \
Efrûkhtân u sûkhtân u câma darîdân.	\
**K.**Ahû zer-i muşmula şalgam kemiden,\ 
Ravi ki rivayet eder altun kemeriden.\ 
Pervane küned der kelebek suluca armut, \
Palto-i merâ ez ceket-i köhne deriden,	\
**H.** Karagöz, bunlar ne?	\
**K.**Bunlara âcizane eş'ar-i uydurmasyon-ı namütenahi tâbir ederler.	\
**H.**Efendim, sebeb-i teşrifiniz ziyaret kasdiyle mi yoksa ticaret maksadiyle mi?	\
**Ac.**Ticarât gasdinân gâlânin gılığı bela olurdi ha?	\
**H.**Demek ki efendim, ziyaret kasdiyle geldiniz?	\
**Ac.** İran'da mânim ağam olubdi, kendisi tarikha çokh mârağ edübdi. Bir gün belâ gena tarikh mütalaa edanda örmüş ki Rum’da bir murgzar bağı olubdi. Oni görmaği çokh mârağ etmiş, mâni çağınbdı. „Mânâ bakh, nökâr!" Mân dâ dedim ki: „Nâ var, ağa?" ..Rum'un mâsiragah mahallinda bir murgzar bağı olubdi, tez âsbinâ suvar olub Rum’a gedib o bağın bağıbanını bulun da biz dâ ardından şimdi püsarinan berabâr gâlübdi" deyâ mâni göndârdi.	\
**H.**İşte efendim, o bağın bağıbanı bendenizim.	\
**Ac.**Pas ki bağıban sânsan?	\
**H.**Kulunuz efendim.	\
**Ac.** Bağı bakhçâyi temaşa edândâ... 	\
**H.** Efendim, teslim edin ahçeyi, temaşa ettireyim bahçeyi!	\
**Ac.** Temaşa edayım bakhçâyi, teslim edârâm akhçâyi.	\
**H.**Buyurun efendim, gidelim!(Bahçeye girerler.)	\
**Ac.** Hacivad Çâlâbi, çokh yakhşidi bakhçavüz! Al. Hacivad Çâlâbi, sana min dane dinar!	\
**H.**Eksik olmayın efendim! Arka kapıdan gidin!	\
**Ac.**Kabablar kızaranda, badeler nuş olanda, İbrahim ağa çayırından ağamı alıb galanda. Allaha smarladıkh!	\
**H.** Safa geldiniz efendim! — Ey Karagöz, artık duyuldum. Bana gelen gelene İrandan Tahrandan bir acem geldi, yüz tane dinar verdi. Sen orada çatla patla palla!(Gider.)	\
**K.** (içeriden).Aman aman aman!	\
**Karısı.**Herif, yine ne oldu?	\
**K.** Ne olacak? Hacivada bir acem geldi.	\
**K.k.** Hacivad bir incir mi yedi ?	\
**K.** Hayır, bir küfe üzüm yuttu. Bizim karı da hiç lâkırdı anlamaz.	\
**K.k**Canım, ne oldu?	\
**K.** Hacivada bir acem gelmiş, yüz tane dünya altını vermiş.	\
**K.k.** Dünya altını olur mu?	\
**K.** Hacivad söyledi, ne bileyim ben?	\
**K.k.**Şimdi ne olacak?	\
**K.** Gidip Hacivaddan istiyeceğim.	\
**K.k.** Hiç verir mi?	\
**K.** Belki merhamete gelir de verir.	\
\
(Perdeye gelir, bahçe kapısını çalar.)	\
Bana baksan a. bahçıvancı!	\
**H.** (içeriden).Yine kimdir o kapının önündeki?(Gelir.)Yine ne var. Karagöz?	\
**K.**Aman Hacivad, ölüyorum.	\
**H.** Ne oldu Karagöz?	\
**K.** Ne olacak? Sarılık olmuşum.	\
**H.** Okutsun a!	\
**K.** Pabucubüyüğe mi?	\
**H.** Bir insan sarılık olursa okunduğu vakit geçer.	\
**K.** Bana başka ilâç salık verdiler.	\
**H.** Nasıl ilâç o?	\
**K.** Bin tane dünya altınını bir ipe dizip boynuma asmalı imişim.	\
**H.** Ey sonra?	\
**K.** Sonrası? Ol altınlar çangıl mangıl ettikçe illet baştan aşağıya doğru inermiş; çıngıl çıngıl ettikçe göbekten aşağıya inermiş, sora ayağından fırlar gidermiş.	\
**H.**Pek âlâ, o senin söylediğin altın var bende, hem de bin tane. Sana vereyim de yap, Sonra illet defolduktan sonra altınları geri iade edeceksin değil mi?	\
**K.** Öyle demediler.	\
**H.** Ya ne dediler?	\
**K.** Sonra altınları birer bozdurup ye“ dediler.	\
**H.** Karagöz, ben sana öyle desise ile para vermem vermem, hem de bahçeye koymam koymam!(Tekme vurur.) Giderim.(Gider.)	\
**K.** Vay kerata vay. ben de sana. Hacivad, eğer Karagöz isem, bu bahçede rahat vermem vermem vermem!(Gider.)	\
	\
(Şarkı ile Acemler gelirler, önde ağa, ortada nöker. arkada püser.) \
Şarkı	\
\
Pencerede şişem var,	\
Gül ile benefşem var.	\
Kız, seni alır kaçarım	\
Peşimize düşen var.	\
Bir su içtim destiden.	\
Gözlerimi mest iden
Elimden aldı rakip, 
Benim yâri eskiden.	\
**Ağa. ** Mana bakh. nöker!	\
**Nöker.** Ne var, ağa?	\
**Ağa. ** Bağbâna ünle diyiram.	\
**K.** (pencereden).Ulan, bahçeye Acemler gidiyor, ben de bunlara katılır giderim.	\
(içeriden:) Abla!	\
**Karısı.** Ne var, herif?	\
**K.** Bizim merkep nerede?	\
**K.k.** Aşağıki odada bez dokuyor.	\
**K.** Merkep çulha mı. bez dokuyacak?	\
**K.k.** Koynumdadeğil ya! Ahırda!	\
**K.** Bizim karı kinaye söyliyor, hakkı da var.Gel bakalım bizim arkadaş!\
**Merkep.** (anırır),İ a, i'a !	\
**K.** Şimdi şarkı söylemenin zamanı değil! Meşinden bir su kovası vardı, ne oldu?	\
**K.k.**Mutbaktadır,	\
**K.** Onu da başımıza giyelim!(Perdeye gelir.)Deh deh!
(Makam ile:) Tarator havanı, canım, saat yelkovanı!	\
**Ağa.** Nöker, bâğbâna ünle!	\
**N.** Aman ağa, siz ünlâyim!	\
**Ağa. ** Bâğbân baba! Bâğbân baba! Biya biya. ulan ha hâ hay!	\
**N.** Bâğbân baba! Bâğbân baba! Biya biya, ulan ha ha hay!	\
Pusar, san da ünle!	\
**Püser.** Bâğbân baba!	\
**K.**Canım, a canım! Ne kadar da nazik!	\
**Püser.** Bâğbân baba! Biya. biya, ulan bahâ hay!	\
**K.** Nöbet bizim. Bahçevan kerata! Bahçevan kerata! Pilav zerde aşure hey!	\
**H.** (gelir). Buyurun efendim, buyurun!(Gider,)	\
**K.**Acele etme kerata, geliyoruz.	\
**Ağa. ** Aşk-ı yaran, mubabbet-i canan! Ben de gittim Murgzar bağının aşkına, ya hey!	\
**Nö.** Ask-ı yaran muhabet-i canan! Ben de gittim Murgzar bağının aşkına, ya hey!	\
**Püser.**Aşk-ı yâran . . .	\
**K.** (püserin atının arkasına biner).Acele etme, beraber gideceğiz.	\
**Püser.**Yıkhıl gurumsaklı kişi, yıkhıl derâm! (Kovar.)	\
**K.** (merkebine biner).Yıkıldık.	\
**P.** Aşk-1 yâran, muhabbet-i canân, ben de gittim ağamın aşkına ya hey!	\
**K.** Nöbet bizim: Ekşili ayran, muhabbetli hayvan, filân filân! Ben de gittim acemlerin gümüş haşalarını çalmak aşkına! Haydi ulan, bahçe kapısı kapanacak! (Merkebin götüne eli ile vurur.) Haydi bakalım! Ne gezer? Yürümeye niyeti yok. Nasıl yürüsün, açlıktan anası ağlıyor! Deh deh! (Vurur, merkep ön ayaklarını kaldırır.) Haydi bakalım, demirlendin mi buraya? (Merkep ön ayağını indirir, ard ayağını kaldırır.) Çocuklar gibi sıralıyor! Kuzum merkep! Canım merkep, yürü! (Vurur, merkep gayet seri durduğu yerde yürür gibi hareket eder, bir karış ileri gitmen.) Ulan, eşek oğlu eşek! Demirlendin mi? Yürü! (Merkep yine başlar gayet seri yerinde hareket etmeye.) Sakalar suya yakın! Ulan, yangın tulumbası mısın, merkep misin, eşek oğlu? (Merkepten yine, bahçenin kapısına götürür, merkep yine yürümez, geri geri gelir.) Anlaşıldı, bizim kavlimiz vardır: altı ay bu beni taşır, altı ay da ben bunu taşırım, nöbet benim. (Merkebi omuzuna alır.) Ekşili ayran, muhabbetli hayvan! Ben de gittim acemlerin eşyalarını çalmak aşkına ya hey! (Bahçeye girer.)	\

**H.**Efendini, safa geldiniz!	\
**Ağa.** Safa bulmuşukh, Hacivad baba!	\
**H.** Efendim, kaç kişi geldiniz?	\
**Ağa.** Bir mân, bir nöker. bir de püsâr.	\
**H.** Efendim, aşağıda birisi var, gümüş haşaları karıştırıyor.	\
**Ağa.** O zât bizdân dâğildi.	\
**H.** Bendeniz anladım kim olduğunu.(Karagöze hitaben:) Bana baksan a, Acem baba, buraya gel!	\
**K.** Peski, eski, meski testi...’	\
**H.**Dışarı! (Karagöze vurur.) Dışarı!	\
**K.**Ne vuruyorsun, eski desti mesti? (Perdeye gelirler, Karagöz başını önüne eğer.)	\
**H.** Kaldır şahsını göreyim!	\
**K.** (başı önünde).Bak., aşağısını gör!	\
**H.**Kaldır, diyorum, başını!	\
**K.** Bugün yortusu var, kalkmaz.	\
**H.** Kaldır!	\
**K.** (başını kaldırır).Buyurun görün!	\
**H.** Vay, Karagöz!	\
**K.** Ne var?	\
**H.** Bu kılık kıyafet?	\
**K.** Sıçanlara ziyafet.	\
**H.** Aklın sıra bahçeye girip de bahçede oturacak mısın?	\
**K.** Oturacaktım.	\
**H.** Pek âlâ, niçin tek durmuyorsun?	\
**K.** Cibilliyet.	\
**H.** O başındaki he?	\
**K.** Su kovası.	\
**H.** Sözde Acem mi oldun? Acem kıyafetine değil, ne kıyafete girsen, ben seni bahçeye koymam koymam koymam!( Ayağı ile tekme vurur gider.)	\
**K.**Vay köpoğlu, beynimi delecekti! Ben de sana bu bahçede rahat vermem vermem vermem! (Giderken hatırına gelir:) Ulan, bizim merkebi verin! 	\
**H.** (içeriden). Atıverin merkebi, atıverin!	\
**K.** Ulan, atmayın! (Atarlar, merkep ölür, ayakları yukarıda, sırtı yerde.) Merkep ellerini açmış dua ediyor. Ulan, ben bunu ne yapayım? Şimdi eyi aklıma geldi! (Baş aşağı kor.)Kışın üstüne bir yorgan, tandır olur. Yemek yediğimiz vakit üstüne siniyi koy, iskemlelik eder. (Eline alır.) Ulan, dürbünlük de edecek! (Dürbün gibi bakar.) Bak, nereleri gözüküyor. seyir eyle gözüm! ,,Burası neresi?" dersen: Kâthane! Bak kayıklara, ne kadar kalabalık! Ben bunu eve götüreyim de pastırma yaparım, kışın yeriz.(Evine gelir.) Abla!	\
**Karısı.** Ne istersin, herif?	\
**K.**Al şu merkebi!	\
**K.k.** A herif, buna ne oldu?	\
**K.** Ne olacak? Öteki köye konakçı gitti.	\
**K.k. **Bu ölmüş!	\
**K.** Çoktan canı çıktı.	\
**Ağa.** (Hacivada hitaben:) Mana bakhsan a, Hacivad Çalabi!	\
**H.** Buyurun efendini!	\
**Ağa.**  Astana-i aliyâda zanân tâifâsindân çangilar olanda onları apar! derâm, tamâşâ edelim!	\
**H.** Peki efendim amma, onların çoğu erkek yanında oynamazlar; ara yere bir car gereriz o tarafta oynarlar, sizler de dinlersiniz.	\
**Ağa.**Bâli!	\
**H.**Ben şimdi gider, onların kolbaşılarına haber gönderirim.	\
\
( Şarkı ile Zenneler gelirler.)	\
\
Şarkı Hüseyni28	\
\
Gördüğüm gün rûyunu, ey mehlika.	\
Dil esir-i zülfün oldu bi-riya	\
Ah u zâr oldu işim subh u mesa.	\
\
Nakarat: Rahm idüp kulluğa, dilber, kıl seza!	\
Olsun her emrine can ü baş fedâ!	\
\
Hasretin kan ağladır her rûz u şeb,	\
Hep haram oldu bana şevk u tareb, \
Ah. nihayet bulmadı, çektim  ta’eb.	\
\
Eyzan.	\
\
**Karagöz.** (pencereden) Ulan, çakçeye kızlar geldi! (içeriden.) Abla’\
**Karısı.** Ne var, herif?	\
**K.** Beni yavşakla!	\
**K.k.** Ne demek yavşakla ?	\
**K.**Karılar gibi.	\
**K.k.**Ha anladım. Yaşmaklayım, öyle mı?	\
**K.** Bahçeye çengiler gidiyor, ben de onlar ile beraber bahçeye gideceğim.	\
**K.k.** Gel, önüme otur	\
**K.** Oturdum.	\
**K.k.**Başına bu hotozu giy!	\
**K.** Giydim,	\
**K.k.**Şunu aşır!	\
**K.** Aşırdım!	\
**K.k.**Yaşmağı koynuna niye koyuyorsun?	\
**K.** Aşır demedin mi?	\
**K.k.**İşi gücü hırsızlık!	\
**K.** Seninki de arsızlık.	\
**K.k.**Dur şöyle! Bakayım! Oklu. Şimdi bunu da yüzüne tut!	\
**K.** Ben boğuluyorum bunun altında!	\
**K.k.** Artık orasını bilmem. Feraceyi de giy!	\
**K.** Giydim.	\
**K.k.**Sesini incelt!	\
**K.** Bir törpü olmalı ki inceltelim!	\
**K.k.**Abû, canım, abû!	\
**K.**(kalın ses ile).Abû, canım, abû!	\
**K.k.** A herif, balık satar gibi oldu!	\
**K.** Ben yaparım, senin nene lâzım?	\
\
(Perdeye gelir.)Abû, canım, abû!	\
**Kolbaşı.**Kızlar, gele gele geldik buracığa, daha gönlümüz nereciğe?	\
**Oyuncubaşı.** Siz önde kösemen, biz arkada eli bağlı kuzu.	\
**K.** Hesapça ben de burada çoban köpeği.	\
**Oyuncubaşı.** Kızlar, o arkadaki karı kimdir?	\
**Acemi kız.** A efendim, odun yarıcının karısı Dütdürü Leylâ.	\
**K.** Ulan, ne tuhaf isim: Düdüklü Leylâ!	\
**Oyuncubaşı.** Kız, sana mahallede isim takmışlar.	\
**K.** Ne diye isim takmışlar?	\
**Oyuncubaşı.**..Kirli hanım" diye.	\
**K.** Yalnız bana takmamışlar, sana da takmışlar.	\
**Oyuncubaşı.** Ne isim takmışlar?	\
**K.** ,,Kurtlu kaşer" diye.	\
**Oyuncubaşı.** Sana taktıklarının asit var	\
**K.** Ne aslı var ne faslı.	\
**Oyuncubaşı.** Aslâ tırnaklarını kesmezsin, yüzünü yıkamazsın, ortalık süpürmezsin, kocana bakmazsın.	\
**K.** Canım sag olsun!	\
**Acemikız.** Yalnız can sağlığı para etmez.	\
**Kolbaşı.** Kızlar, bahçıvana seslenin!	\
**Oyuncubaşı.** Evvelâ siz seslenin, kolbaşı hanım!	\
\
Kolbaşı (makam ile).	\
\
Hey bahçıvanım, bahçıvan!	\
A benim canım, bahçıvan!	\
Bahçene kızlar geldi,	\
Aç kapıyı, bahçıvan!	\
Oyuncu başı hanım, sen de söyle!	\

**Oyuncu başı.** Baş üstüne efendim!(Makam ile:)
\
Bahçıvanım, bahçıvan! \
A benim canım, bahçıvan!	\
Bahçene bülbül geldi. \
Aç kapıyı, bahçıvan!	\
Acemi kız, sen de söyle!	\
\
**Acemi kız.** Baş üstüne efendim!	\
\
Bahçıvanım, bahçıvan \
A benim canım, bahçıvan \
Bahçene kızlar geldi, \
Aç kapıyı, bahçıvan!	\
\
**K.** Sıra bize geldi.(Makam ile:)	\
Çakçıvanci, çakçıvan!	\
Aç kapıyı, çakçıvan! 
Çakçene pırpızlar geldi. 
Aç kapıyı, çakçıvan!	\
\
Kırbam suya daldırdım, 
Dolu diye kaldırdım.\
Canım imanım, kardeş. 
Bileziğim aldırdım.	\
\
Lahna büber turşusu, 
Haniya bunun ekşisi?	\
\
**Kolbaşı.** Kızlar, o arkadaki rezalet eden karı kimdir ?	\
**Acemi kız.** Efendim, Dütdürü Leylâ.	\
**Hacivad. **(gelir). Buyurun efendim, buyurun!	\
**K.** Acele etme, kerata, geliyoruz.	\
**Kolbaşı.** Aşçının aşını yedik, başçının başını yedik; Hacivad, sana ne yaptık bizi bu kadar bekletiyorsun?	\
**H.** Efendim, kusura bakmayın, buyurun!	\
**K.** Şu Hacivad keratasına bir temiz dayak atın!	\
**Kolbaşı.** Aşk-ı yâran, muhabbet-i canan! Ben de gittim acemlerin bezirgânının aşkına ya hey!(Gider.)	\
**Oyuncubaşı.** Aşk-ı yâran, muhabbet-i canan! Ben de gittim kolbaşı hanımın aşkına ya hey!(Gider.)	\
**Acemi kız.** Aşk-ı yâran, muhab ...	\
**K.**Dur, beraber gidelim, muhabbeti! canan!	\
**Acemi kız.** Canım efendim, bırak beni!	\
**K.** Bırakayım amma, ben yalnız kalacağım.	\
**Acemi kız.** Aşk-ı yâran, muhabbet-i canan! Ben de gittim Oyuncubaşı hanımın aşkına ya hey!(Gider.)	\
**K.** Nöbet bizim: Ekşili ayran, içeride gürültü koparan filân filân! Ben de gittim çengilerin gümüş su tasını, mücevherlerini çalmak aşkına ya hey! (Gider.)	\
**H.**(içeriden).Vay efendim, sefa geldiniz!	\
**K.** Sefa bulduk. Hacivad Çelebi!	\
**H.** Safada dâim olun, efendim! Baksanız a efendim, siz kaç kışı geldiniz?	\
**Kol başı.** Bir ben, bir oyuncubaşı hanım, bir de acemi kız.	\
**H.** Aşağıda birisi var, sizin oyun elbiselerini karıştırıyor.	\
**Kol başı.** O bizden değil. Hacivad Çelebi!	\
**H.** Ben kim olduğunu anladım. Bana baksan a. koca başlı kadın	\
**K.** Abû canım, abû!	\
**H.** Sen bana gel bakayım! O esvapları niye karıştırıyorsun? Bütün sırmalarını sökmüşsün 	\
**K.** Kolbaşı hanım tenbih etti. ..biz sâde güzel çıkacağız" diye, ben de onu söktüm.	\
**H.** (vurur).Dışarı, dışarı diyorum sana, dışarı!(Vurur.)	\
**K.**Abû canını, abû! Hiç erkek kadına el kaldırır mı. abû? (Perdeye gelirler, başını Önüne eğer.)	\
**H.** Kaldır başını, şahsını - göreyim!	\
**K.** Bak, aşağısını gör!	\
**H.** Benim bu sese âşinalığım var. Karagöz !	\
**K.** Ha!(Bayım kaldırır.)	\
**H.** Karı kılığına değil, her ne kıyafete girsen. Karagöz, yine seni tanırım, bahçeye koymam koymanı koymam. (Tekme ile vurur.)	\
**K.** Vay, çifteli kerata, tekme de vuruyor! Hacivad, ben de Karagöz isem, ben de sana bu bahçede rahat vermem vermem vermem !(Gider.)	\
**Ağa.** Hacivad, çengiler raks idanla manim özüm zouk edanda. ..	\
**H.**Baş üstüne efendim! Bana baksan a, kolbaşı hanım!	\
**Kolbaşı.** Buyurun efendim!	\
**H.** Ağır ağır hazırlanın da çengiler oynasınlar!	\
**Kolbaşı.** Kızlar, haydi giyinin!	\
**Acemi kız. **Baş üstüne, efendim!	\
\
(Çengiler köçek havası* ile oynarlar. oyun biter.)	\
**Ağa.** Manii bakhsan a, Hacivad Çâlâbi !	\
**H.** Buyurun efendim!	\
**Ağa.** Mânim Haviyar hanında sarrafım olubdi, oni mâna apar, derâm.	\
**H.** Baş üstüne efendim!	\
\
(Şarkı9 ile Yahudi gelir.)	\
\
Ande vamoz el de aki .. .	\
\
**K.** Ulan, bahçeye sarraf gidiyor, ben de şunun peşine takılırım.(İçeriden) Abla!	\
**Karısı.** Ne var. herif?	\
**K.** Şu kahve çömleğini versen e!	\
**K.k.** Ne yapacaksın?	\
**K.** Sen ver bana!	\
**K.k.** Al bakalım!	\
**K.** Bir de mendil ver!	\
**K.k.** Al!	\
**K.** Başıma sar!	\
**K.k.** A herif, ne tuhaf oldun! Sen böyle nereye?	\
**K.** Çakçeye gidiyorum, korlarsa.(Perdeye gelir.)	\
**Yahudi.** Ey bakçivaniko!	\
**K. **(vurur Yahudi ye). Ey çakçivaniko!	\
**Y.** Ne vurursun oursuz olu ?	\
**K.** Sensin köpoğlu, uğursuzoğlu!	\
**Y.** Ey bakçivanîko!	\
**K.** (vurur). Ey çakçivaniko!	\
**Y.** Ne vurursun oursuz olu oursuzu ? Haydi arkamın tumani, onumun suyu	\
**K.** Vay köpoğlu, cinas söyliyor!	\
**Y.** Ey bakçivanîko!	\
**H.** (gelir).Buyurun bezirgan!(Gider.)	\
**K.**Geliyoruz kerata, acele etme!	\
**Y.** Aşk-ı yaran, muhabbetli hayvan, ben de gittim cumbuşleri salıvermeye.	\
**K.** Ekşi ayran, muhabbetli hayvan, ben de gittim Yahudinin para torbasını çalmak aşkına ya hey!(Gider.)	\
\
**H.** (içeriden). Bezirgan, siz kaç kişi geldiniz?	\
**Y.** Benden başka kimse yok.	\
**H.** Aşağıda para torbalarını birisi karıştırıyor.	\
**Y.** Ben yaliniz yeldim.	\
**H.** Ben kim olduğunu anladım. Buraya gel, bezirgân!	\
**K.** Ke kerez me keriz ?	\
**H.** (Karagöze vurur).Dışarı, dışarı diyorum sana!	\
\
( Perdeye gelirler.)	\
**K.**Vay köpoğlu! Yine yakalandık!	\
**H.** Kaldır şahsını!	\
**K.** Buyurun bakalım, ne istiyorsun?	\
**H.** Karagöz, Yahudi kılığına değil, ne kıyafete gizsen, seni tanırım, bahçeye koymam koymam koymam!(Tekme ile vurur.)	\
**K.** Vay kerata, çömlek kırıldı galibâ! Ben de sana rahat vermem vermem vermem!	\
\
(Eve gelir.) Abla!	\
**Karısı.** Ne var, herif?	\
**K.** Benim zurnam vardı, şunu bana versen e!	\
**K.k.**A herif, ben onu çocuğa sübek yaptım.	\
**K.** Ulan, ne bulsan çocuğun götüne mi sokarsın?	\
**K.k**Al bakalım!	\
**K.** Ulan, bu tuzlu bel	\
**K.k.**Yıka herif, yıka!	\
**K.**(üfler).Zır zır zır. dürüt dürüt, düdürü dürüt!	\
\
(Perdeye gelir, evvelâ bir taksim eder, sonra şarkı çalar.)\
Besle Nigâr*.	\
\
Gücenmezsen budur arz-i niyazım,\
Sabah oldu, uyan, ey mest-i nazım! 
Muhabbet iddim, uyku ne lâzım?\
Nakarat:Sabah oldu, uyan, ey mest-i nazım35	\
\
Visale meylini görsem de tutmam.	\
Geçen hatır nişanımdır, unutmam.	\
İki gözüm, seni mahmur uyutmam.	\
Eyzan.	\
\
Geceden eyledim hep bezmi tecdid. 
Şafakreng ol. aman, ey subh-i ümmid 
Kıyas itsün görenler doğdu hurşid.	\
Ey san.	\
\
Bu şeb bel bağlamam gayri sözüne.	\
Girer mi âşıkın uyku gözüne?	\
Oturdum subhe dek, bakdım yüzüne.	\
Eyzan.\
\
Acemler zevki Seviyorlar, bu vesile ile bahçeye girebilir miyiz?	\
**Ağa,**(bahçeden).Hacivad Çâlâbi!	\
**H.**Buyanın efendim!	\
**Ağa,** Gûşuma yanık yanık bir zurna sâdası gelir, çabukh apar! derâm.	\
**H.** Peki efendim, başüstüne! Şimdi bulur getiririm.	\
(Perdeye gelir.) Karagöz!	\
**K.** (zurnayı arka tarafımı saklar).Ne var?	\
**H.**Burada zurna çalanı gördün mü?	\
**K.**Hayır, görmedim.	\
**H.**Görürsen Karagöz, bana haber ver!(Gider.)	\
**K.**Peki şimdi ananı siktim senin, Hacivad!	\
(Zurna çalar, bir peşrev çalar, sonra yine bir şarkı çalar.)	\
**Ağa.**Hacivad Çâlâbi!	\
**H.**Buyurun efendim!	\
**Ağa.** Çabukh, nerede ise, bu zurna çalanı apar diyârâm, mın dana dinâr verirâm.	\
**H.** Peki, başüstüne! Şimdi bulurum.	\
**K.**Hacivad geliyor.(Zurnayı saklar.)	\
**H.**(gelir).Karagöz!	\
**K.**Ne var?	\
**H.**Zuma çalanı görmedin mi?	\
**K.** Ne zuma çalanı gördüm ne de kurna.	\
**H.**O elindeki nedir ?	\
**K.**Çubuk.	\
**H.**Göster bakayım!	\
**K.**(makam ile.)Na-na, na-na, na-na, na-na!	\
**H.**Karagöz, zurna!	\
**K.** Zuma babandır, köpoğlu!	\
**H.**Haydi gidelim!	\
**K.** Nereye?	\
**H.**Bahçeye.	\
**K.**Ona yüz surat ister be, bahçeye gitmeğe!	\
**H.**Neden?	\
**K.** Neden olacak? Bin defa kovulduk.	\
**H.**Haydi Karagöz, beş on kuruş uyar, sonra pişman olursun.	\
**K.**Vay köpoğlu herif! Bin tane dinar veriyor, bu bize ..beşon kuruş uyar” diyor.	\
**H.**Karagöz, kendi kendine ne konuşuyorsun?	\
**K.** Bana müteallik.	\
**H.**Haydi gidelim!	\
**K.** Sen benim yakamdan tut, ben gitmem derim, sen çek!	\
**H.** (tular).Haydi, Karagöz, gidelim!	\
**K.** Ben gitmem, Hacivad.	\
**H.**Haydi gidelim! diyorum.	\
**K.**Ben, inan olsun, gitmem.	\
**H.**Yemin ettin. (Bırakır gider.)	\
**K.**Vay köpoğlu, bıraktı! Ben yine çalarım zurnayı.(Çalar.)	\
**Ağa.** Hacivad Çaîabi! Zurna çalanı çabukh apar! diyaram.	\
**H.** Başüstüne efendim!	\
( Perdeye gelir.) Haydi Karagöz, gidelim!	\
(Bahçeye Karagöz ü götürür.)	\
**Zenneler** (hepsi bir ağızdan).A Karagöz, sefa geldin!	\
**K.** Sefa bulduk!	\
**Zenne.**Karagöz, sefa geldin!	\
**K.**Sefa bulduk!	\
**Diğer zenne.**Karagöz, sefa geldin ’	\
**K.** Sefa bulduk, siz ne yapıyorsunuz?	\
**Zenne.**Çakıyoruz. Sen de çakar mısın?	\
**K.** Hava bozulduğu vakit çakarım.	\
**Zenne.** Al anacığım, sana bir bade!	\
**K.** Ver bakalım, o güzel elin de!(İçer.)Hani meze?	\
**Birinci zenne.** Al Karagöz,, sana şeftali!	\
**K.** Eksik olma!	\
**İkinci zenne.** Benim elimden içmez misin?	\
**K.** içerim, anacığım!	\
**İkinci zenne.** Al bakalım!	\
**K.** Ver bakalım! (içer.)Hani meze?	\
**İkinci zenne.** Buyurun Karagöz, sana balık!	\
**K.** Ver bakalım, koca alık!	\
**Üçüncü zenne.** Karagöz, benden içmez misin?	\
**K.**İçerim, anacığım, ver bakalım!	\
**Üçüncü zenne.** Buyurun hem rakı, hem meze!	\
**K.** (içer).Ulan, bana bir şey oluyor!(Sarhoş olur.)Ulan, bana bir şeyler oluyor!	\
**Birinci zenne.** Karagöz, beni sever misin ?	\
**K.** Niye sevmem, severim.	\
**Birinci zenne.** Beni sevdiğini bileyim ki! Kendini şu havuzun içine at!	\
**K.** O boku yiyemem.	\
**İkinci zenne.** Karagöz, beni sever misin?	\
**K.** Severim.	\
**İkinci zenne.** Beni sevdiğini bileyim ki! Kendini şu ağacın üstünden yere at!	\
**K.** O boku da yiyemem.	\
**Üçüncü zenne.** Karagöz, beni sever inisin?	\
**K.**Severim.	\
**Üçüncü zenne.** Bahçe kapısının önüne git de bir nâra at!	\
**K.** Onu yaparım.	\
(Perdeye gelir.)Var mı benim bıyığıma pis diyen?	\
(Mahalle bekçisi gelir, elindeki sopa ile Karagözün kafasına vurur.)	\
**Bekçi.** Ulan, ikigadeh kekremsi hörpütüp de mahalle arasında dana gibü bağırıyorsun, ayu! Haydu gapuya!	\
**K.** Cuma gecesi yıldırım düşecek dediler; benim başıma düştü bekçi baba.\
**B.** Ni var?	\
**K.** Ben seni bir yağlı kapıya  götüreyim ki sen de gör!	\
**B.**Haydi varuver!(Bahçeye beraber giderler.)	\
**Zenneler **(hepsi birden).A Karagöz, bu ne? Bunu buraya niye getirdin?	\
Fare sığamadığı deliğe götüne kabak bağlarmış!	\
**K.**Ben onu getirmedim, o beni döve döve buraya getirdi.	\
**H.**Bekçi baba, sen al şu beş yüz kuruşu, deveyi gördün mü yeden olsun?\
**B.** Nime lâzım benim, ben melmekete kadar giderun,(Gider.)	\
**H.** Karagöz, haydi bakalım dışarı’ Sen buraya bok getireceksin.	\
**K.** (perdeye gelir).Ya öyle mi ? Ben de şimdi bir gürültü basayım da sen de gör!(Beş on kişi varmış gibi:)Alıverin şu taraftan, ya hey! Şu taraftan tutun! Kaçıyor!	\
\
(Bahçeyi kaldırırlar. Hacivad gelir, Karagöz sırt üstü yatar.)	\
**H.**Karagöz, ne oldun?	\
**K.**Aman Hacivad, öldüm bayıldım.	\
**H.**Sana ne oldu?	\
**K.** Ne olduysa bana oldu. Tekmil ahali üstümden geçti beni çiğnediler.	\
**H.**Alacağın vereceğin var mı?	\
**K.** Var zahir! Alacağım da var, vereceğim de var.	\
**H.**Alacağın ne kadar, vereceğin ne kadar?	\
**K.**Bu sene Yenikapıda karpuz yedimdi. kabukları orada kaldı; onları al, Hacivad!	\
**H.** Daha başka alacağın var mı?	\
**K.** Var. Galatada işkembe çorbası yedimdi, yumurta kırdırdım içine koymak için ; onların kabukları orada kaldı; onları al, Hacivad!	\
**H.** Peki, borcun ne kadar?	\
**K.** Bakkala bin beş yüz, kasaba beş yüz, zerzevatçıya altı yüz. ekmekçiye bin.	\
**H.** Karagöz, alacak vereceği ödemiyor. Kalk bakalım, ölmenin sırası değil!	\
(Mabadı malûm.)	\
