
# ferhad

Semai Tahir Puselik	\
\
O gülendam bir al şala bürünsün yürüsün, 
Ucu gönlüm gibi ardınca sürünsün yürüsün!	\
Alıp ağuşa bu çağında meyan-i nazın	\
Saran ol serv-kadi, VÂSIF, öğünsün yürüsün	\
Gel gel gel, serv-i nazım, gel gel gel, çaresazım!	\
O gül endam bir al şala bürünsün yürüsün 	\
\
Hay Hak!	\

( Perde gazelini okur.)	\
\
Bihamdillâh kuruldu perdemiz bu âli divane,\
Sefalansın temaşa eyledikçe zat-ı şahane!	\
Huzurunda benim bu şem'-i bahtım şulelendikçe \
Felekte minnet itmem pertev-i hurşid-i rahşane.	\
Bir az sohbet iderdim bu gice çeşm-i siyahımla \
Veliyyünnimetim aff eyleyip bakmazsa noksane.	\
Makadirdân-ı arif padişah-ı pür maarif kim 
Hayalinden geçen lûtf ü inayet ehl-i-irfane.	\
İrade beklerim, zira ki mabeyn-i hümayunun \
Kapısı eşiğini öpmeğe geldim edibane.	\
Zehi sultan-ı zişan sahib-i lûtf ü adalet kim \
Dua-yı devlet-i şahanesi farzoldu insane!	\
Sefada daim olsun daima sıhhatle, ey Hüsni,\
Vücudile şeref verdikçe taht-ı Al-i Osmane.	\

\
Huzıır-u haziran / cemiyet-i-irfan / vakt-i sefa-yı yâran! Lâindir, dinsizdir, münafıktır, biedeptir şeytan! / Şeytana lânet / Rahmanın birliğine hamd-i bigayet!	\
Ol cenab-ı rabbülenam şevketlû, kudretlû, kemal-i mehabetlü Padişahımız Efendimiz Hazretlerini ilâ yöümilkıyam erikepira-yı ihtişam buyursun!	\
\
Dergehinden kesmesin payın nesim-i-afiyet \
Gonce-i bahtı açılsın hemişe gül gibi!	\
\
Efendim! Demem ödemek değil!	\
Bu bendenize, bu hakir duacınıza eli yüzü yunmuş, elfazı düzgün, sözü sohbeti tatlı bir fasihüllisan yâr-i vefaşiar olsa, geliverse şu meydan-ı pür sefaya, arabî bilse, farisi bilse, bir az fenn-i şiir ü musikîye aşina olsa, o söylese bendeniz dinlesem, bendeniz söylesem o dinlese, oturan zevkperveran-ı kiram da sefayab olsa! Diyelim: Bu gece işimizi Mevlâm rasgetire\
\
Yâr, bana bir eğlence, aman, bana bir eğlence!	\
Yâr, bana bir eğlence!	\
Kanda varsa âşık-ı biçare, cananın arar.\
Dert ile bimar olan elbette dermanın arar.	\

(Karagöz gelir, kavga ederler, Hacivad gider.)	\
**Karagöz.** Seni gidi utanıp arlanmaz, hadd ü hududunu bilmez herif seni! A kerata! Kapımın önüne her akşam gelirsin, bir kerecik demezsin ki Karagöz ne yapıyor? Evinde rahat oturuyor mu, yoksa boş keseden akça mı sayıyor? Yalnız bir gürültüden ibaret. Evde hesabım var, hesap görürken kerata gürültüyü bastı, bir sıfır eksik attım, açığım çıktı, az daha açıkta boğuluyordum.	\
**H.** Vay, nur-u didem Karagöz!	\
**K.** Beyaz çiğdem, Hacivad!	\
**H.** Derdin nedir diye sormazsın.	\
**K.** Sen de hiç bir akşam evinde oturmazsın.	\
**H.** Ne yapayım, gözüm mini? Seni görmesem yapamam, elimde değil,\
**K.**Ayağında mı köstek?	\
**H.**Teessüf ederim, Karagöz, dünyaya boş gelip boş gideceksin.	\
**K.** Vay Hacivad, sen dolu geldin de dolu mu gideceksin?	\
**H.**Değil efendim, benim yirmi parmağımda yirmi hünerim var.	\
**K.**Benim de yirmi fenerim var.	\
**H.**Ben o sayede geçinirim,	\
**K.**Ben de senin gibi, Hacivad, ben de geçiririm.	\
**H.**Öyle ise. efendim, musikişinas mışmız?	\
**K.**Evet, mum sıkmaya pek aşinayım.	\
**H.**Anlayamadın Karagöz, yani usulbend misin?	\
**K.**Musibet sensin, ağzını topla!	\
**H.** Canım, sen gezinmek bilmez misin ?	\
**K.** Niye bilmem ulan, sen biraz öteye var! (Gezinir.)	\
**H.** Öyle değil, elini kulağına koy da ağzınla gezin!	\
**K.** Onu öyle söylesen e! (Karagöz elini kulağına kor, yerde ağzı ile yüzü koyun gezer.) Tu! Allah mustahakını versin! Bütün ağzıma toprak doldu!	\
**H.** Öyle değil, üşekâ-yı ümmet!	\
**K.** Eşekçi Mehmet sensin.	\
**H.**Hay budala hay! Beni dinle bakayım!(Hacivad taganni ile)  Hey, hey meded ey!	\
**K.**Hacivad, böyle mi olacak?	\
**H.**Evet efendim, böyle olacak, bakayım sen dûm-tek bilir misin?	\
**K.**Ne dedin?	\
**H.**Dümtek. yani arapça Leyli.	\
**K.**Arabacı evli de seyis bekâr mı, Hacivad?	\
**H.** Değil efendim. Arapça Leyli bir kaç kısımdır: Mısrî var, İskenderuni! var, Halebi var, Bağdadî var, Trablusşamî var.	\
**K.** Hacivadın anasının arm var, Mısır buğdayı üsküdarda var, İstanbulda var, her yerde var,	\
**H.**Değil birader. Yürük Beste, Aksak Semaî bilir misin?	\
**K.** Ha! Sağır saka, topal bekçiyi bilirim, onlar bizim mahallededir.	\
**H.**Değil efendim. Yani muradım: Türk Aksağı”, Nevzemin.	\
**K.**Ahbabımdır, Hacivad.	\
**H.** Kim?	\
**K.** Galata’daki kürkçü Emin.	\
**H.** Efendim, şöyle bir Nimdeyir yapıver bakayım!	\
**K.** Nargileyi mi devireyim? Aferin Hacivad! Kahveciden bana dayak yedireceksin!	\
**H.** Haydi Karagöz, başla gezinmeğe!	\
**K.**(ağziyle taksim eder.) Hey, hey!	\
**H.**Aman Karagöz, dik!	\
**K.** Hacivad, bir yerim mi söküldü ?	\
**H.**Değil efendim. Perde dik!	\
**K.** Benî sana yorgancı kalfası diye kim söyledi?	\
**H.**Biraz daha peşçe!	\
**K.** Hey, hey!	\
**H.**Biraz daha peşçe!	\
**K.** Biraz daha pekmezce, Hey, hey!	\
**H.**Aman Karagöz, azıcık daha pes!	\
**K.**(Gayet yavaş:) Hey, hey!	\
**H.**Azıcık daha pes!	\
**K.** Hey, hey!	\
**H.**Azıcık daha!	\
**K.** (Gayet yavaş:) Hey, hey!	\
**H.**Azıcık daha pes!	\
**K.** Hı, Hı!	\
**H.** Azıcık daha!	\
**K.**(zorlar. osurur), Put, pırt!  (Tokadı atar, H. gider.) Vay köpoğlu! Makamın bana geriden sedasını çıkarttı.	\
**H.**  (gelir).Aman Karagöz, başla!	\
**K.**Şimdi sinsilenden başlıyacağım.(Karagöz Rast yolundan okur.) Hey, hey, meded ey!	\
**H.**  Aman bilâder, beste Rast geldi.	\
**K.** Ben de biliyorum, beste rasgeleliğini. Yoksa, bana kalırsa, hiç birşeyden haberim yok. (Makam ile taganni eder.) Hey, hey!	\
**H.**Aman bilâder. bu pek soğuk Neva oldu.	\
**K.** Mangalda biraz ısıtıver	\
**H.**  Bilâder, Nihavend bilir misin?	\
**K.** Naneci Ahmedi bilmem.	\
**H.** Hele biraz pesten gezin bakayım!	\
**K.** (söyler).Yâr, yâr meded yâr!	\
**H.** İşte bu Rahatülervah oldu.	\
**K.** Şimdi alt taralı da .sıkıntıyı ruh olacak.	\
**H.**İsfahan kullanır mısın ?	\
**K.** Hayır, merakım Şiraz içmektir.	\
**H.** Bestelerden Hisar-Puselîk?	\
**K.** Ulan Hacivad. Hisarda kim oldu küfelik?	\
/**K.**(gülerek:)Ha ha ha ha! Ne tohafsın, Karagöz! Bir parça tiz gezin de Evicarâyı bul!	\
**K.** Evin içini gezeyim de hararı bulayım mı?	\
**H.** Çargâh kolunda bir beste var, Ferahnak; bilir misin onu?	\
**K.** Allah cümlemizin hanesini ferahnak eylesin, amin!	\
**H.**Gezin bakayım bir az!	\
**K.**Hey, hey meded ey!	\
**H.** Şimdi, bilâder, Neva-yı Tatardan Kara Batağa gireceksin.	\
**K.** Talar Hüseyin Ağadan dayak mı yiyeceksin? Bana ne, ulan?	\
**H.** Bilâder, Saba kolundan Beste-Nigâr.	\
**K.** Sabahleyin mide bozar pestil ile enginar.	\
**H.** Bir de şey vardır, bestelerden: Hüzam ile karışık Neveser.	\
**K.**Dülgerde mi, Hacivad, destere, keser?	\
**H.** Değil bilâder, hele biraz gezin bakayım!	\
**K.**Hey, hey, meded ey !	\
**H.**İşte, bilâder, Hüseyni-Aşiran Nühüft oluyor.	\
**K.** Ne oluyor, ne oluyor? Hüseyin ağa aşırılıp lüp mü oluyor?	\
**H.** Dur bakayım, bestelerden bir şey daha vardır, yani Çifte-Düyek , Devr-i Revan.	\
**K.** Sofulardaki Deli Süleyman kim?	\
**H.**Anlıyamadım bilâder, Zincir, Devr-i Kebir.	\
**K.** Zeyrekteki Sümüklü Bekir kim?	\
**H.**Baksan a bilâder. Segah  yolunda bir makam var.	\
**K.** Samatya yolunda hamam mı var? Ha, ona Büyükağa derler.	\
**H.** Değil bilâder. sen kazı koz anlıyorsun. Şimdi lâtifeyi bırak da bir az tiz gezinerek Çargâh’tan Neva'ya atla.	\
**K.** Çergede gezineyim de tavaya mı atlayım? Kızarmak için galiba, değilmi? Hay bunak herif, hay	\
**H.**Aman Karagöz, gezin!	\
**K.**Meded ey, hey hey, meded ey’	\
**H.**  Aman bilâder, Saba oluyor!	\
**K.** Şafak attı mi, Hacivad?	\
**H.**Neden?	\
**K.** Sabah oluyor dedin de . . .	\
**H.** Münasebetsizlik etme, Karagöz! Birazda tizden söyle bakayam!	\
**K.** Hey', hey, meded ey, aman, aman!	\
**H.**İşte Muhayyer-Sünbüle, Acem Kürdi.	\
**K.** Ulan, simitçinin tablasını kim devirdi?	\
**H.**Değil a canım, Saba’dan başlayıp tiz Segâlha vararak Neva-yı Kürdi’yi bulup Makam-l Araban’a inivermeli.	\
**K.** Onu yapamam, Hacivad.	\
**H.**Neden?	\
**K.** Sabahleyin kalkmalı, tezgâhçılara varmalı, bekçi Kürdü tutup arabaya atmak, bu benim elimden gelmez.	\
**H.**Değil a canım!  Bestelerden bir şey vardır, bakayım: Tarz-ı Cedid ile Şevkaver.	\
**K.** Tarakçı Reşit ile kunduracı Yaver kim, ulan?	\
**H.**Efendim, Dilkeş Haveran.	\
**K.** Onu tanırım.	\
**H.**Kimi tanırsın?	\
**K.** Eşekçi Yaver ağayı.	\
**H.**Bilâder, Suzinâk’tan bir şarkı vardır, onu meşkedelim ! Evvelâ ben söyliyeyim de sen dinle:	\
\
“Firakın, sevdiğim, kâritti cane, \
Kül oldum nar-i aşka yane yane, \
Budur senden niyazım âşıkane,\
Kül oldum nar-i aşka yane yane.	\
Haydi Karagöz, söyle bakalım!	\
\
**K.**Dayak atmaya ararım bahane,	\
Kızardı kel kafam acıyor yane yane,
Dayak atmaya ararım bahane,	\
Kızardı kel kafam acıyor yane yane.	\
\
(Hacivada tokat atar. H. gider.)Vay köpoğlu!	\
**H.** (gelir).Aman bilâder, Müstear ile Mahurkaldı.	\
**K.** (vurur. Hacivad gider).Hâlâ ,,Mustafada marul kaldı" diyor.	\
Ulan, sen gidersin de beni pamuk ipliği ile mi bağlıyorlar? Ben de giderim îdgâha, dolaba, dilber seyrine. Bakalım ayine-i devran ne suret gösterir! (Gider.)	\
\
(Şarkı ile Hacivad tarafına köşk, Karagöz tarafına dağ konur.)	\
\
Esirin oldum ey zülfü kemendim.	\
\
(Şarkı biler, Karagöz dağdan aşağıya düşer.)	\
**K.**Ulan Hacivad! Buraya bu molozu yığmışsın! Köşkü kendi tarafına yapmış, bizim tarafa süprüntüleri dökmüş!(Hacivadın kapısına gider. Hacivadı çağırır.)Ulan Hacivad, aşağıya gel!	\
**H.**Ne var, Karagöz? Beni niye çağırdın?	\
**K.**A Hacivad, kendi tarafına köşkü yapmışsın, benim tarafıma molozu yığmışsın!	\
**H.**Karagöz, benim tarafımdakine Kasr-ı Şirin derler, senin tarafındakim de Kûh-u Ferhad derler.	\
**K.**Öyle ise, Hacivad, sen git te bir kalıp sabun ile iki kova su getir.	\
**H.**Ne yapacaksın?	\
**K.**O paslı şirden ile küflü berbadı yıkayalım!'	\
**H.**Karagöz, ben bunların minevveli ilâ âhirini anlatırım amma, vakit geçer.	\
**K.**Aman Hacivad, anlat!	\
**H.**Kulak ver de dinle!	\
**K.**Dinliyorum.	\
**H.**Amasya şehrinde Harun namında birbezirgân varmış. Mal-i Karun 'a malik, malının hesabını bilmez, böyle bir bezirgan amma, misli cihana gelmemiş. Mumaileyhin emlâk ve akarı hakîkaten tasvir olunmaz bir raddede ise de, ne çare, ki dâr-ı dünyada bir semere-i ömr ü fuadı, yani evlâdı olmadığı için bu zatın, kubbe-i âlem başına bir dâr-ı mihen olarak, gözüne bir şey görünmez idi.	\
**K.** Kendisi gidi mi?	\
**H.**Dinle, Karagöz!	\
**K.** Söyle, Hacivad!	\
**H.**Mürur-u zaman ile bütün ticaret ile iştigalden kat‘-ı rişte-i alâka ederek gönlünü eğlendirmek ve müteselli olmak efkâr-ı batılasîyle sayd u şikâra merak eder.	\
**K.**Seyyit bey ile Kâthaneye mi gider?	\
**K.** Bir çok zaman da bu yolda tazyi'-i evkat eder ise de, nihayet bundan da lezzetyab olamıyarak, Mecnun misali, ne yolda vakit geçireceğinden âciz kalır.	\
**K.** Bir gece sizde misafir mi kalır?	\
**H.** Bir gün devlethanelerinde otururken nüdema-yı esrarından birini huzuruna celbederek der ki ..Ey benim nedim-i hassım, halim neye müncer olacak? Benim gibi mal iradı hadd ü hesaba gelmez adama cenab-ı Hakk-ı müstean bir evlât ihsan edip te derağuş etmeğe muvaffak etmez ise, hadden efzun mal neye yarar" diyip bir ah-ı sert çekerek çâk-i geriban olur.	\
**K.** Kaybettiği ceketin yakasını bulur mu?	\
**H.**Ve daha buna mümasil bir takım tefevvühat-ı teessüf-iştimalden sonra.. Bari, benim esbimi ve mayelzem-i seferi hazır et, bir kaç tane de tevabi‘-i kârgüzar alalım da bir parça gezelim" der.	\
**K.**Vay. efendi kahvecilik edecek; tevabiyi ne yapacak?	\
**H.**Nedim-i merkum aklığı emri bitamamiha icra ile yola çıkarlar.	\
**K.** Vay, demek ki bezirgan yoldan çıkıyor?	\
**H.** Şehirden bir kaç saat ilerledikten, ve biraz dolaştıktan sonra yolları bir çeşme başına tesadüf eder.	\
**K.** Bezirgân tarassut mu eder?	\
**H.** Hem biraz istirahat etmek, hem de beygirleri sulamak üzere, hayvanlardan inip çeşmeye muttasil bir ağaç sayesine nüzul ederler.	\
**K.** Hepsi bırakıp giderler mi?	\
**H.**Dinle! Nagâh vera-yı şecerden nuranî simali bir pir-i fâni zuhur ediip: ""Safa geldin, ya tacir Harun!" der demez Harun ayağa kalkıp pirin ayaklarına kapanarak: ""Mademki sen benim Harun olduğumu bildin, kalbimdeki olan muzmarımı da bilirsin" diye rica ve istirhama başlar başlamaz. . .	\
**K.** Hacivad, Ortaoyunu mu oynıyorlar?	\
**H.**Pir: ..Estağfurullah, seni muztarip eden bir evlâdın olmadığı içindir. Mademki buna haris ve arzukeşsin, şu nüshayı al. akşam konağa avdetinde bir bardak su içine bu nüshayı at ve üzerine bir şey kapa, açık durmasın.	\
**K.** Açık durmasın elbette, İçine bir şey düşer.	\
**H.**Yirmi dört saat nüsha suda dursun; sonra yansını sen iç ve yansım zevce-i menkûhana içir, muradın hâsıl olur" der ve derakap gözden nihan olur.	\
**K.** Gözlükçü Avram’ı bulur mu?	\
**H.**Efendi şad u hurrem olarak hanelerine avdet ederek tıpkı pirin târifi mucibince nüshayı bardağa koyarak suyun yarısını kendi ve yarısını zevcesi içer, biinayetillah o geceden itibaren haremi hamile kalır.	\
**K.** Haremi Haremde kalır?	\
**H.**Dinle, Karagöz!	\
**K.**Söyle, Hacivad!	\
**H.** Sözü uzatmıyahm: Dokuz ay, dokuz gün, dokuz saat, dokuz dakika, dokuz saniye diyince afet-i devran, Zeliha-yı sani bir duhter-i pakize rahm-i maderden nüzul ile dâr-ı fâniye teşrif eder.	\
**K.**Tımarhaneye teşrif mi ediyor? Bezirgan mı? Demek ki çıldırmış!	\
**H.** Ol saat pederine müjdeciler gider, tepşir ederler, kurbanlar kesilir, fıkaraya in'am u ihsan olunur.	\
**K.**Çocuk dünyaya gelir gelmez her şey bulunur.	\
**H.**Çocuğun ismini Şirin tesmiye ederler. Talim ü terbiyesine nezaret etmek üzere süt analar, cariye ve köleler ve bir ayrı daire-i fahire tertip olunur.	\
**K.**Büyük bir daire alınır diyorsun; çocuk mu çalacak o daireyi?	\
**H.**Değil a canım! Şirin kızcağızını bir aylık, iki aylık, üç. dört, derken dokuz, aylık, derken bir yaşınagelir; iki yaş, üç yaş, dört yaş. derken yedi yaşına gelir.	\
**K.** Bir kuru, iki kuru, üç kuru, dört kuru . ..	\
**H.**Karagöz, bu kurular ne olacak?	\
**K.** Bu kadar yaşın yanında hiç kuru istemez mi?	\
**H.**Şirin hanımı mektebe başlatırlar, hocaya verirler. Biraz zaman okuduktan sonra mektepten alıp nağış ustası tutup nağiş öğrenir ve sair marifetler öğrenir. Günlerden bir gün Şirin hanım otururken ,,Kızlar!" deyip el çırpıp kırk tane cariye gelip edebi icra edip zeminbusî eyledikten sonra el bağlayıp karşısında dururlar. Şirin hanım bin naz ile emredip: ..Kızlar, şu benim gergefimi getirin!" der demez cariyeler yer ile beraber temenna ederek her biri bir odaya giderler, arusek gergefi alıp getirirler. Nansuk tülbendi çekip üç yaldızlı lehek kılaptanı türlü elvan ipekler ile bu benim arkamdaki köşkün resmini işler. Akşam olur, Şirin hanimin pederi gelir gelmez: »Ey benim velinimetim pederim! Eğer ben senin kızın isem bu köşkün resminde senden bir köşk isterim" der demez pederi de: »Başüstüne, benim bir tanecik kerimem!" diyerek sözünü kabul etti. Sabah oldu, güneş kule-i Kaftan baş gösterip âlem nur ile münevver oldu. Neccar gelip temeller atılıp kurbanlar kesildi. Köşk bitmede olsun, kalıyor içinin bir nakşı.	\
**K.**Bu nakış ne oluyor?	\
**H.**İçinin nakşı, yani boyası.	\
**K.**Boyaya nakış mı derler?	\
**H.**Evet, bilâder. O zamanda nakkaşların piri Behzadoğlu Ferhad.	\
**K.** Şöyle bakalım, Berbadöğlu berbat!	\
**H.**Çavucak, bu işin ehli Ferhadı getirtirler. köşkün pazarlığım ederler, boyalar ezilip Ferhad başlar köşkü nakşetmeğe.	\
**K.** Vay. Ferhad ta nağiş mı işliyor?	\
**H.** Birinci kat yaseminler, ikinci kat karanfiller, üçüncü kat ıtrışahîler, dördüncü kat güller, beşinci kat sümbüller, altıncı kat menekşeler, yedinci kat: Şebboy çiçeğinin gölgesini sağdan vereceğine soldan vermiş.	\
**K.**Ehl-i merak çavucak sağdan soldan veriyor.	\
**H.**Ehl-i merak çavucak iskeleyi ayağının akına koyup kırk kalem peşte-mal belinde, mücevherli fırça elinde, altın boya çanağı yerde, perçemi bir omuzdan bir omuza dökülmüş, pembezar gömleğin kollarını sıvayıp elini şakağına koyup „Ya dost meded!" dediği zaman Amasya dağlan çıngır çıngır ötüyor.	\
**K.**Demek ki Amasyanın dağları horoz olmuş!	\
**H.**Ferhad köşkü nakşetmekte olsun. Şirin hanıma müjdeciler gider, köşk bitti diye. ,.Buyurun temaşa edin!" derler. Şirin-i pürcefa, çarşafa bürünüp kırk tane cariye yanında, kimi sağında, kimi solunda, köşkün kapısına kadar fernayiş şal döşenmiş, tıpış tıpış yürüyerek iki tarafına göz süzerek, etrafı eknafı seyr ü temaşa ederek, köşkün kapısına gelip sağ ayağını atar atmaz kurbanlar kesilir.	\
**K.**Hacivad, ben de isterim kurban payı.	\
**H.**Birinci kata çıkıp: maşallah peh peh, ikinci kata çıkıp: maşallah peh peh, üçüncü kata çıkıp: maşallah peh peh, dördüncü kata çıkıp: maşallah pe peh, beşinci kata çıkıp yine: maşallah peh peh. altıncı kata çıkıp: maşallah peh peh . . .	\
**K.**Hacivad, bu katlara hep maşallah peh peh nakşetmişler!	\
**H.** Efendim, ,.maşallah peh peh" demek „maşallah eyi" demek. Yedinci kata çıkıp gûşuna yanık bir seda gelir.	\
**K.**İs kokulu. Öyle mi?	\
**H.**Bu ses nereden geliyor diye merak eder, bir de bakar ki ne baksın? Ferhadı görür görmez düşüp can evinden vuruldu. Ferhad bu gürültü nedir diye bir de baktı ki ne bakarsın .. .	\
**K.**Baktığım yok, ulan!	\
**H.**Maşuku olan Şirin hanım yerlere serilmiş yatıyor.	\
**K.**Halı yerine sermişler.	\
**H.**Karagöz, Şirin deyip te geçiverme!Gövelâ göz, çekme burun, hokka ağız, çene zenehdan, bir karış gerdan, sim pazular . . .	\
**K.**Çifte cazular..	\
**H.**Pembe göğüs, endam aynası gibi karın, turunç gibi memeler, ayva göbek .. .	\
**K.**Çok methettin köpoğlu köpek!	\
**H.**Ferhad-ı biçare de iskeleden kendini aşağıya atıp o da bin can ile vurulur.	\
**K.**Hacivad, bu iki vurulmuştan bir ölen yok mu?	\
**H.**Karagöz, bunlar birbirlerine âşık olmuşlar.	\
**K.**Kaşık mı olmuşlar?	\
**H.**Değil a canım, gönül alıp gönül vermişler.	\
**K.**Kaça alıp kaça vermişler?	\
**H.**Birbirlerine alâka etmişler.	\
**K.**Birbirlerile kavga mı etmişler?	\
**H.**Senin anlıyacağın kantar Bursada kestane tartar! Ben gidiyorum.	\
Şimdi bunlar buraya gelip görüşse gerektir.(Gider.)	\
**K.**Siktir kerata! Köşkü kendi tarafına yapmış, molozu bizim tarafa yığmış, bana masal söylüyor.(Gider.)	\
\
(Ferhad şarkı ile aşağıya gdir.)	\
\
Şarkı Mahur	\
\
Sabah oldu, tan yerleri atıyor,	\
Destur almış cümle kuşlar ötüyor,	\
Sarılmışlar iki hasret yatıyor.	\
Nakarat:Şakı, bülbül, var uyandır yârimi!	\
Ben kıyamam, sen uyandır yârimi!	\
\
Sabah olsun ben şu yerden gideyim,	\
Garib bülbül gibi feryad edeyim, 
Sen dururken ya ben kime gideyim?	\
\
Eyzan.	\

Çıkabilsem yüce dağın başına, 
Güneş vurmuş hateminin taşına, 
Henüz girmiş on üç on dört yaşına.	\
\
Ey zan.	\

**Ferhad.** (0f çeker.)	\
\
Bir haber ver, ey saba, serv-i revanım kandadır?	\
Canımın âramı yok, âram-l canım kandadır? 
Neyledin nettin, felek, hurşid-i âlemtabımı? 
Ol ruh-u ferhunde mah-ı mihribanım kandadır?	\
\
(Of çeker.)	\
Yine terk-i vatan kılıp diyar-i gurbete düştüm,\
Cüda düştüm tabibimden, firak-ı hasrete düştüm, \
Kandadır ol yüzü mahım, erişti göklere ahım,\
Meded senden, ey Allahım, ne türlü afete düştüm!	\
\
(Şirin gelir.)	\
\
Cemalin arz idip uşşaka, sultanım, safa geldin! \
Şeref bahşa iden hurşid-i rahşanım, safa geldin!\
Yapıldı kasr-i dil, kâşane-i hâtır, kudumunla, 
Saadetlû benim ey mihr-i tabanım, safa geldin!	\
\
Bihamdillah gönül ol mah gördü, dideler ruşenl \
Peyam ister iken, didarı gördü, dideler ruşen!	\
Tekellüm mahfiye mahsus idi ruhsar-ı dünyada, \
Ayan ol devlet-i bidarı gördü, dideler ruşen!	\
\
**Şirin.**
Ben cariyesin arzulayup gelen efendim, \
Açılmış gonca güller şenindir.	\
Çok şükrolsun Hûdaya! Gelip kavuştuk!	\
Servi gibi ince beller senindir.	\
Ben Şirin kuluna itme cefa!	\
Sürelim seninle zevk u safa!	\
Sanma, Ferhadını, beni bivefa \
Şekerlenmiş tatlı diller şenindir.	\
\
**F.**
Bir yanım çayır çimen, bir yanım derya deniz,\
Hâk-i paya yüz sürüp bir buse ister bendeniz.	\
\
**Ş.** Sen gibi efendime canım feda itsem gerek.	\
Nevcivanım var iken ya ben kimi sevsem gerek?	\
Ta kıyamet haşrolunca gönlümü virdim sana,\
Sen dururken busemi ben kimlere virsem gerek?	\
\
Al efendim! Buse de senin. Şirin de senin!	\
**F.** (Şirini öper).Ah efendim, Şirinim!	\
**Karagös. **(içeriden).Şirdendi baba, bumban kokutuyorsun!	\
**Ş.**Ruyumu eline alıp durmaz sunarsın	\
Ey âşık-ı biçare buldukça bunarsın?	\
**F.**Busenden dil gani olmak vuslatın şeydasıdır,\
Mazur tut, Şirinim! Dünya tamah dünyasıdır.	\
**Ş.** Cariyenize müsaade buyurun da gideyim. Ferhadım	\
**F.**Ne söylüyorsun, Şirinim? Bir insan tendeki canına nasıl izin verir?	\
**Ş.**Peder maderimden izinsiz geldim, sonra adûlar duyar, pederime söyler, bunda görüşürken sonra görüşemeyiz. Cariyeniz gidiyorum.	\
\
Nafe-yi müşk-ü Huten turrene olmaz hembu,\
Sümbül-ü cennet eğer olsa gıda-yı ahu.	\
Heves-i zülfün ile azm-i reh-i Çin ettim,	\
Seni şimden gerü, ey gözleri ahu, yahu!	\
(Gider.)	\
\
**F.**Ya men hu! Of!	\
Gittin amma yalnız koydun hasret-i canan bile, 
İstemezem sensiz olan sohbet-i yâran bile.	\
Devr-î meclis bana girdabı belâdır sensizin,\
Şimden sonra istemezem sâğar-ı gerdan bile.	\
Kimseler görmüş değildir can bedenden gittiğin,\
Îşte ben gördüm gözümle kendi canımdır giden.	\
\
Ya aşk-ı Şirin!	\
\
(Kendisini attan aşağıya atar, yüzü koyun yere düşer.	\
Hacivad gelir, Karagöz de Ferhadın atına biner.)	\
**Hacivad.** Ne bindin o ata?	\
**K.** Ne vazifen, a kerata? Burası at pazarı mı yoksa oğlan pazarı mı? Bu at ne duruyor burada, bu oğlan ne yatıyor yerde?	\
**H.**Karagöz, ben bunların hikâyesini sana anlatmadım mı? Evvelâ ol şehbaz-ı bülend.aşk u muhabbette yekta olan yiğidin adına Ferhad-ı mümtaz derler. Aşk ateşine sabr u kararı kalmayıp Şirinin payinde payendaz olduğunun aslı budur. Karagöz.	\
**K.**O köy buraya yakın mıdır?	\
**H.**Nasıl köy?	\
**K.** ..Aslıbudur" köyü!	\
**H.**Ben öyle şey bilmem.	\
**K.**Neme lâzım benim arayı marayı, atı satalım da harçlık himara bakalım.(Karagöz atı evine götürür, yine gelir.)Hacivad, soyalım!	\
**H.**Ben sana adam soydurmam,	\
**K.** Senin boğazım sıkarım, sen de yatarsın boylu boyuna.	\
**H.**Haydi diyelim ki soyalım: bana nesini vereceksin?	\
**K.** Evvelâ o başındaki taç benim, çepken benim, ok yay benim, şalvar benim, gömlek benim, içdonu benim, kuşak benim, tütün kesesi benim .. .	\
**H.**Hani bana?	\
**K.**Kunduranın bir teki benim, bir teki senin benim.	\
**H.**Senin benim ne oluyor?	\
**K.** Şimdi sana veririm, köşe başında arkandan gelir, sana gücüm yeter, elinden alırım.	\
**H.**Haydi şuradan, defol!	\
**K.**Ben sana lâtife söyledim, Hacivad. Sen şu delikanlıyı kaldır!(Gider.)	\
**H.**Kalk yiğidim, şehbazım!	\
**F.** (kalkar).Yahu, sen kimsin?	\
**H.**Hacivad pederin, evlâdım!	\
**F.**Of!	\
Söylesem derd-i derunum kimse takdir eylemez.	\
Gördüğüm rüyaları hiç kimse tâbir eylemez.	\
Gençlikte bir belâya uğradım, ah eylerem.\ 
Taşa tesir eyler amma yâre tesir eylemez.	\
\
**H.**Evlâdım, yazık değil mi senin gençliğine- Dağlar taşlar eteğinde kurtlar kuşlar gıdası olacaksın. Vazgeç evlâdım, vazgeç! Seni doğuran ana bir daha doğurmaz. senin gibi yiğit kırk yılda meydana gelir. Bir kız için bu kadar ah u enin etmede mâna yoktur.	\
**F.**0f	\
Geçmen ol sevdadan oldukça bana ömr-ü tavil,\
Üstuhân-ı kellem içre dutsa akrepler vatan.	\
Ne söyliyorsun, Hacivad Çelebi?	\
\
**H.** Aşk ehline dünyada dilâra mı bulunmaz?	\
Mecnun isen, ey dil, sana Leylâ mı bulunmaz?	\
Gûş it nefesim, eyleme feryad çimende,	\
Ey bülbül-ü şeyda. gül-ü râna mı bulunmaz?	\
Benim ciğerköşem Ferhadım, yazık sana! insan kıyafetinden çıkmışsın. Bilmez misin Leylâ ile Mecnunu, Aşık Garibi, Kerem ile Asliyi ? Bunların hangisi bermutat olmuşlar? Hepsi namurat gitmişler.	\
**F.**Can gibi bir hibede! canana virdim gönlümü,\
Misli yok bir afet-i devrana virdini gönlümü.	\
Sen ne diyorsun Hacivad Çelebi?	\
**H.** Bak evlâdım, elimi sallasam ellisi, başımı sallasam başı tellisi. Sana ben bir kız bulayım ki misli cihana gelmemiş.	\
**K.** (içeriden).Kuzum Hacivad! Bana da bir oğlan bul!	\
**F.** Of!	\
Halk ı âlemde safalar, bende gam eksik değil,\
Gözlerimden daima hiç kanlı nem eksik değil.	\
**H.**Evlâdım, arlık buna bir diyeceğim kalmadı. Kendin bilirsin.	\
**F.**Aman Hacivad Çelebi! Sana bir ricam var; getir elini öpeyim!	\
**H.** Estağfurullah! Nedir ricanız?	\
**F.**Şu benim hakk-ı sâlihim olan Şirinin evine git de bana bir cevab-ı şâfi getir! Kuzum Hacivad baba, ayağının altım öpeyim!	\
**H.** Aman evlâdım, benim bağrını yufkadır, böyle şeye dayanamam.	\
**K. **(içeriden).Benimki de yoğurtlu tatarböreğidir.	\
**H.**Peki evlâdım, gideyim.	\
\
(Gider. Şirinin evine gelir, kapıyı çalar.)	\
**Şirin **(içeriden).Hanım nine, aşağıda bir sivri külâhlı adam var.	\
**K.**Ecinnidir, keratayı kovun!	\
**Şirinin anası.** A kızım, Hacivad Çelebi gelmiş, kapıyı açın!(Kapıyı açarlar.) Buyurun, Hacivad Çelebi! Ayağınıza soğuk su mu dökelim yoksa sıcak su mu?	\
**K.**Sicak su dökün de ıstakoz gibi haşlansın!	\
**H.**Aman efendim, ""Kulda kusur çok olur, affeder efendisi" fehvasınca... Akşamdan dükkânı kapayıp bir lokma taam ettikten sonra hâb-ı rahata varırım.	\
**Ana.** Kızım, Hacivada bir nargile doldurun, bir de sade kahve, biraz da tatlı getirin.	\
**K.** Yesin ziflensin !	\
**H.**Aman efendim, ne zahmet!	\
**Ana..** Sen benim evime kırk yılda bir kere geldin.	\
**H.**Şirin hanımın keyfi eyi midir?	\
**K.**Elinizi öperler.	\
**H.**El öpeni çok olsun, kullar halayıklar öpsün elini!	\
**Ana..** Bu günlerde, Hacivad Çelebi, çok canım sıkılıyor.	\
**H.**Ne gibi, efendim?	\
**Ana.** Ne gibi olacak? Şirin hanımın kısmeti çıkıp ta bir kocaya veremedik.	\
**H.** Efendim, onun adı Şirin, talihi de şirindir, elbette çıkar kısmeti.	\
**K.** Gönder Hacivad bana meddah İsmeti	\
**Ana.** Öyle. Hacivad. amma, kız kısmı yirmi yaşını geçerse biraz ağırlaşır?	\
**K.**Tuz ekin de kokmasın .	\
**H.**Efendim, sizin Şirin hanıma bendeniz bir delikanlı buldum, ikisi de biribirinin dengi.	\
**K.** Hacivad ta oğlan pezevengi.	\
**Ana..** Canıma minnet, Hacivad Çelebi. Damadımız olacak delikanlının ismi nedir?	\
**H.** Efendim, Ferhad.	\
**K.** Söyle berbadoğlu berbat!	\
**Ana..** Ayol, nasıl Ferhad? O Amasyalı Ferhad olmasın!	\
**H.** Evet Efendim, odur.	\
**Ana..** Aferin Hacivad! Benim kızımı öyle dağda bayırda gezen çapkına mı lâyık gördün?	\
**H.** Efendim, Ferhadın ağzı mı eğri, yoksa burnu mu çarpık, kolu mu çolak, ayağı mı topal?	\
**Ana..** Pek âlâ delikanlı! Gökte yıldızlar bana yakın, o uzak.	\
**H.**Eyvah, keşki söylemiyeydim!	\
**Ana..** Bak, Hacivad. öyle bir takım adama kız vereceğime boynuna bir taş bağlar denize atardım daha eyi. Eğer bunun için gddinse buyurun dışarı!	\
**K.** Hacivadın itibarı ziyade! Kapı dışarı zamkinos!	\
**H.**Yazıklar olsun, efendim, iz’anına irfanına!	\
**Ana..** Ben de senin iz’anına irfanına veremedim. Hacivad!	\
**K.** Ben de sizin ikinizin de irfanına veremedim!	\
**H.** (perdeye gelir).Vazgeç, evlâdını, bunlar lâkırdı anlayan adamlar değildirler.	\
**F.** Of!	\
Gel nesîm-i bad-ı sabâ, hatır-ı yârden ne haber?	\
Gelir mi o kafile acep? Müjde-i yârden ne haber?	\
Şem’-i hüsnün ruyuna amade kılsam nola ben,	\
Ne yaman cünbüşu var! Rüzgârdım ne haber?	\
\
Kuzum Hacivad, benim edna hatırım için bir daha Şirinin evine gidin!	\
**H.** Peki evlâdım, hatırın için gideyim. (Gider.)	\
**K.** Bu sefer dayağı yer gelirsin!	\
\
**H.** (içeriden).Baksanız a, efendim!	\
**Ana..** Kızım, aç kapıyı! Hacivad geldi.(İçeriye alırlar.) Buyurun Hacivad, sana bir şey söyliyeceğim: Sizin teklifinizi kabul ederim amma, benim de size bir teklifim var.	\
**H.** Nedir, efendim?	\
**Ana..**Bak Hacivad, bizim Amasya şehrinde suyun fıkdanı var. Şu karşıki Elma Dağını delip şehre suyu getirmeli, kızı sineye sarmalı.	\
**H.**Aman efendim, bu güç maslahat. Hazret-İ Süleyman zamanında bu kadar dev, peri gelmiş, o dağın bir parçasını koparamamışlar. Nerede kaldı ki Ferhad dağı delsin, suyu getirsin?	\
**Ana..** Aşkla her bir şey olur, Hacivad. Eğer âşık-ı sadık ise dağı deler.	\
**H.**Bendeniz bir kere kendisine söylerim.(Perdeye gelir.)Evlâdım, vazgeç bu sevdadan; sana pek yazık olacak!	\
**Ferhad.** Hacivad Çelebi, ne söylediler ise söyle, sakın çekinme!	\
**H.**Şu karşıkı Elma Dağını delmeli, şehre; suyu getirmeli, ondan sonra Şirin Hanımı sineye sarmalı.	\
**F.**Hacivad, müjde desen e!	\
**H.**Efendim, ölmenize mi?	\
**F.**Of!	\
Kuh u çerhi hâke yeksan eylemek bir şey midir?	\
Tişe-i ahımla viran eylemek bir şey midir?	\
Gözlerimin yaşını nehr edip icra eylesem,	\
Şehr-i maksud içre rizan eylemek bir şey midir?	\
Aman Hacivad Çelebi! Öküz öldü, gayret dayıya kaldı. Senin bildiğin yerde bir ahenger var mıdır?	\
**H.**Efendini, benîm refikim vardır, demirden anlar. Haydi bizim eve gidelim de hem sana bir kaşık çorba pişirsinler, ben de o adamı alıp geleyim.(Ferhadı Hacivad evine götürür.)Siz burada bir kahve için, ben şimdi gelirim.	\
\
(Ferdeye gelir. Karagözü çağırır.)Karagöz, aşağıya gel!	\
**K.**(gelir).Ne var bakahm?	\
**H.**Karagöz, evde demirin var mı?	\
**K.** Var.	\
**H.**Ne kadar var?	\
**K.**Biraz var.	\
**H.**Beş on okka var mıdır?	\
**K.**Ziyade.	\
**H.**Elli okka?	\
**K.**Ziyade.	\
**H.**Yüz, iki yüz. bin okka var mı?	\
**K.**Evde bir kapı tokmağı vardı, bizim oğlan onu da leblebiciye satmış.	\
**H.**Demek ki hiç yok.	\
**K.**Yok.	\
**H.** Şimdi yüz batman dimişkî, yüz batman çelik, yüz batman nalpare, bunları kaynatıp özünden bir yanı sivri, bir yanı keskin külünk isterim.	\
**K.** Samakola gider, demir alır yaparım.	\
**H.** Gel bilâder, senin ile Ferhada gidelim, pazarlığı et, akçeni al, başla yapmağa!(ikisi de gider.)	\
işte efendim, külüngü yapacak adam kudur.	\
**F.** Hoş geldin, baba!	\
**K.** Hoş bulduk, oğlum!	\
**F.**Baba, al şu beş yüz kuruşu, külünk bitsin, kemerimde beş yüz, kuruş daha var, onu da veririm.	\
**K.**Onu da ver. oğlum, ne olur ne olmaz.	\
**F.**Baba, külünk ne zaman biter?	\
**K.**Kıyamete bir saat kala biter.	\
**F.** Behey baba, doğru söyle!	\
**K.**Bak evlâdım, cuma günü dükkân açmam, cumartesi günü hiç bir işe bakmam, pazar günü işim çoktur, pazartesi günü ocak yakmam, salı günü kömür almam, çarşamba günü keyfim olmaz, perşembe günü dükkâna gitmem, alacaklı çoktur, yakamdan tutmasınlar diye.	\
**F.**Ne vakit gidersin ?	\
**K.**Haftadan gayri başka bir gün olursa giderim.	\
**F.** Haydi babacığım, sen külüngü yap da senin gönlünü hoş ederim.	\
**K.**Peki oğlum.	\
(Gider kendi evine.)Abla, şu benim merkep nerede?	\
**Karısı.**Mutlakta dolma dolduruyor.	\
**K.**Acayip, eşek dolma doldurur mu? Aşağıda yok.	\
**K.K.**Yukarıki büyük odada çevre işliyor.	\
**K.**Aferin, eşek nağış da öğrenmiş' Ha, gel bakalım buraya!	\
**Eşek.**İ-a, i-a, i-a ...	\
**K.**Haydi gidelim, türkünün sırası değil.	\
\
(Şarkı ile Karagöz merkebin üstünde perdeye gelir.)	\
Şarkı Hüseyn i Zemzeme	\
\
Ben bu teferrüçte baş kalfa oldum.	\
Yolunu öğrendim erkânın bildim,	\
Fundanın kıymetin ben şimdi buldum.	\
Nakarat: Süpürgeler, püsürgeler, eyi meydan süpürgeler	\
Funda dedikleri bir yanar dağdır.
Firavun'dan kalma bir eski kârdır, 
Şu garip çingene çok ustakârdır.	\
\
Ey zan.	\
\
(Yılan gelir.)	\
**Yılan.**Zır, zır, zır. zır, zır.	\
**K.** Ulan, bu ne be? Kış! Yaz?(Yılan gider.) Bu nekadar büyük'	\
**Y.**(gelir)Karagöz!	\
**K.** Vay, adımı da biliyor! Ne var?	\
**Y.** Sen nereye gidiyorsun?	\
**K.** Samakol’a.	\
**Y.** Samakol'da ne yapacaksın?	\
**K.**Demir alacağım,	\
**Y.** Demiri ne yapacaksın?	\
**K.**Külünk yapacağını.	\
**Y.** Külüngü ne yapacaksın?	\
**K.**Senin kafanı yaracağım.	\
**Y.**(hücum eder).Zırı, zın ....	\
**K.** Ulan, kış!	\
**Y.** Karagöz!	\
**K.**Ne var?	\
**Y.** Eşek benim kardeşim.	\
**K.** Eşek senin kardeşin mi? Nasıl oluyor? O anırıyor, sen zırlıyorsun.	\
**Y.** Anamız bir, babamız ayrı.	\
**K.** Ananızın da kemiğine sıçayım, babanızın da!	\
**Y.**(hücum eder).Zır, zır, zır!	\
**K.** Defol şuradan!	\
**Y.** Eşekte benim alacağım var.	\
**K.** Ne yapayım, alacağın varsa? Ne parası bu?	\
**Y.** Ben Samakol'da bakkalken benden tarator yedi.	\
**K.**Ulan, bak eşşoğluna, izzet-i nefsi de var! Ben açlıktan ölüyorum, o tarator yemiş! Tarator yiyeceğine götümü yesin	\
**Y.** Ben paramı isterim.	\
**K.**Yoksa parası?	\
**Y.**Tuttururum.	\
**K.**Yok! Anlamaz mısın? Yok!	\
**Y.** Sen başını öte tarafa çevir, eşeğe bir şey söyliyeceğim.	\
**K.**Söyliyeceğin varsa söyle!	\
**Y.** Senden utanıyorum.	\
**K.** Sende utanacak yüz, surat var ya Gel, söyle(Karagöz başını çevirir arka tarafına, yılan merkebin başını alır gider. Karagöz şarkıya başlar.)	\
Funda dedikleri bir yanar dağdır,\
Firavun'dan kalma bir eski kârdır.\
Şu garip çingene çok ustakârdır.	\
Süpürgeler, püsürgeler, eyi meydan süpürgeler!	\

(Karagöz bakar ki eşeğin başı yok.)	\
Ulan Zırıl, eşeğin baş tarafını getir de sana külbastılık göt tarafından vereyim! Amma deminden eşek bir sallandı; ben ise işiyor zannettim, meğer ise can çekişiyormuş!	\
(Eşeği eline alır, bir kaç şeye benzetir.)	\
Alâ koltuk, üstüne otur' Kışın altına mangal koy, âlâ tandır olur, üstüne de bir yorgan. Ulan, bu dürbünlük de eder!(Eline alır bakar.) Ulan, her tarafı görüyor, bakar mısın bir kere tünelden geçenleri! Ben bunû eve götürürüm de pastırmasını yaparım.(Eve gelir.) Abla, al şu eşeği!	\
**Karısı.**A herif, buna ne oldu? Başı nerede?	\
**K.** Öteki köye konakçı gönderdik. Ben tavan arasına çıkıyorum; bir az uyuyacağım. Ferhad gelir beni sorarsa ..evde yok" de!	\
**K.k.**Peki, kocacığım.	\
**Ferhad. ** (içeriden) Hacivad Çelebi, Karagöz gelmedi,haydi şuna bakalım!	\
**H.**Peki Efendim, haydi gidelim!(Gelirler. Karagözün kapısını çalarlar.)Bana baksan a, Karagözün karısı!	\
**K.k.** Kimdir o?	\
**H.**Karagöz evde yok mu?	\
**K.k.**Herif, ne diyeyim?	\
**K.** (tavan arasından) ,Evde yoktur" de!	\
**K.k.**Hacivad Çelebi, evde amma „evde yoktur de" diyor.	\
**K.** Dedenin de bok çatıma olsun senin de! Dur, geliyorum, Hacivad!	\
\
(Karagöz kapıyı açar.)	\
**Ferhad.**Külünk bitti mi?	\
**K.**Bir kere baksan a, civan ölüsü gibi eşeğim avluda yatıyor.	\
**F.**Şimdi ne yapacağız?	\
**K.**Şurada bir kazma var, işine gelirse vereyim.	\
**F.**Baba, kazma dağ deler mİ?	\
**K.**Peynir tulumunu parça parça etti amma, dağı deler mi bilmem.	\
**F.** Baba, benim işim âsân olursa bununla da olur. Ver bakalım!	\
**K.**Bu esbaplarla dağ yarılır mı? Bu esbapları buraya bırak!	\
**F.**Al baba, sakla!	\
**K.**Benim aşağıda bir eski dizlik var, sana vereyim.	\
**F.**Eksik olma, baba, beni duadan unutma!	\
**K.**Sağ salim gelirsin, oğlum, muradına erersin.	\
\
(Ferhad çıplak, elinde kazma ile perdeye gelir, şarkı ile.)	\
Şarkı Beste İsfahan	\
\
Ya Rab! Kime feryad ideyim yârin elinden!	\
Ya ben nice kan ağlayım ağyarın elinden!	\
Eylerse nola haline bülbül gibi feryad,\
Kurtaramadım, gonca, seni hârin elinden.	\
Nakarat:Dideler giryan. ciğerini biryan, halim yaman, senin elinden.	\
Of\
Bülbül- asa bir gül- handân ola, ya Rab. bana\
Ma’-i maksudum gelüp rızân ola, ya Rab, bana!	\
Kuvvet ü kudret senindir, ben neye kadir olam \
Lûtf u ihsan kıl. işim âsân ola, ya Rab, bana!	\
Of!	\
Ey cenabül kibriya 1 Bazuma kuvvet isterem, \
Lûtf u ihsanınla senden hem inayet isterem.	\
Gam değil bu aşk ile rencide itsem kendimi,\
Erişip maksuduma encam rahat isterem.	\
\
(Şarkı ile dağı delmeğe başlar.)	\
Şarkı Gülizar	\
Bir güzelin sevdası var başımda.	\
Gündüz hayalimde, gece düşümde.	\
Mecnun gibi hiç aklım yok başımda.	\
Nakarat: Onun için dolaşırım şu dağı,\
Susadıkça vir ağzıma dudağı!	\
\
Gördünüz mü Ferhad ile Şirini?	\
Onlar da şevmişler biri birini,	\
Amasya şehrinde gördüm yerini.	\
Ey zan.	\
\
(Farhad dağı deler.)	\
**K.** (Pencereden bakar, Ferhad bir kazmayı da Karagöze vurur.)Ulan, beynimi delecekti köpoğlu! Bütün her tarafı su bastı. Kırk senedir mahbup-dostluk ederim, bir kaldırım taşını sökemem, bir kız için bütün dağı parça parça etti!	\
**Şirinin anası **(içeriden).Ne var. Karagöz?	\
**K.** Senin Berbat bütün ortalığı suya garketti.	\
**Ana.** Kuzum Karagöz, doğru söyle, Ferhad dağı deldi mi?	\
**K.**Deldi, bir kazma da bana rasgeldi.	\
**Ana.**Haydi Karagöz, git, senin Bok Anana söyle: ,, Şirinin validesi sana bir şey söylemiş onun vaktidir’ de!	\
**K.**(içeriden).Bana baksana. Bok ana!	\
**Bok Ana.** Nedir ayağul?	\
**K.**Şirinin anası sana bir şey söylemiş.	\
**Bok Ana.** Evet, yevlâdım.	\
**K.**Onun vakti gelmiş.	\
**Bok Ana.**Feryad dağı dyeldi mİ?	\
**K.** Deldi. Senin beynini İnle delecek.	\
**Bok Ana.**Alıverin şu benim yılandan fotozumu, yılandan âsamı, lokma çanağını!	\
**K.**Böyle acele nereye gidiyorsun?	\
**Bok Ana.**iki hasreti birbirinden ayıracağım.	\
**K.** Allah da seni tatlı canından ayırsın!	\
**Bok Ana.**(perdeye gelir),Zırı zırı zırı!	\
**Ferhad.** Valide, in misin yoksa cin inisin?	\
**Bok Ana.**Ne inim ne cinim, senin gibi benıyâdemim, yevladinı.	\
**F.**Nereden gelip nereye gidiyorsun?	\
**Bok Ana.**Ayaklarım kırılaydı da gitmiyeydim! Amasya şehri mi derler, yoksa Mamasya şehri mi. dükkânlar kapanmış, her kes yas matem tutuyorlar, karalar giymişler.	\
**F.** Banu, Amasya şehrinde bir ölen filân mı var?	\
**Bok Ana.**. Ananın babanın .....	\
**K.**Canına sıçayım!	\
**Bok Ana.**Ananın babanın bir tanecik kızı yölmuş.	\
**F.** O kızın ismi ne imiş?	\
**Bok Ana.**  Şirden midir, yoksa bumbar mıdır?	\
**F.**Sakın Şirin olmasın!	\
**Bok Ana.**Şirden yevlâdım, Şirden.	\
**K.** Şimdi senin şirdenine bumbarına sıçacak!	\
**F.**Onun bir âşık-ı efgendesi var mı imiş acaba?	\
**Bok Ana.**Bir tuhaf adlı yavuklusu varmış; Feryad mıdır, Berbad mıdır?	\
**F.** Sakın valide, Ferhad olmasın!	\
**Bok Ana.** Feryad, Feryad.	\
**K.** Sen şimdi kazmayı yediğin ile feryadın asümanı tutacak.	\
**F.**Doğru söyle, valide, benim Şirinim öldü mü?	\
**Bok Ana.**Benim gibi cennetlik hatun yalan mı söyler?	\
**K.** Ulan, seni cehennem bile kabul etmez.	\
**F.**Ey muradım aksine devreyleyen çerh-i felek!	\
Şimdi gönlüm namurad olmak diler, nitsem gerek?	\
Şimdi Şirinim öldü mü?	\
**Bok Ana.**Yöldü, ayağul, yoldu.	\
**F.**Dün gece şehrin içinde karalar gördün mü hiç?	\
Sinede taze açılmış yaralar gördün mü hiç?	\
Ben de senin bu dünyadan namını nişanını kaldırayım da bir bağrı yanık âşıkın bağrını yakma!(Külünk ile kocakarıyı öldürür.)	\
**Bok Ana.**Aman yevlâdım, vurma!(Ferhad vurur.)Ö' ö’l(Götünden canı çıkar.)	\
**K.**Bizim Bok Anarun cimi götünden cicos!	\
**F.**Of!	\
Derdimi vasfeylesem, billahi, sığmaz deftere, \
Yâzsalardı şu cihanda kûh u çerh-i çembere!	\
Şimdi bu aşk ile ölmek bana olmuştur hayat,	\
Ey deriğa, kaldı hasret şimdi ruz-u mahşere.	\
Atam külüngümü, verem serimi. Ezrail almak dilerdi canımı; ya Rab, bana mahşerde kavuştur cananımı! ’ Yaaşk-ı-Şirin!(Külüngü atar, acele ile Şirin gelir.)Vay. efendim, sen sağ mıydın?	\
**Şirin.** Düşmanların Ölsün, Ferhadım! Arusek gergefimin başında bir dal çevre işliyorken uyuya kalmışım, rüyamda bir aksakallı pir gelip ,,Ne duruyorsun, Ferhad kendini helak ediyor" der demez buraya nasıl geldiğimi bilmiyorum.	\
**F.**Doğdu çüm vuslat hilâli, geldi canım, müjdeler!	\
Bedrolup karşımda durdu mihribanım, müjdeler!	\
Ferhada gam değil ömrüm dahi olsa tamam,	\
Bukadar: gördüm seni ruh-i revanim, müjdeler!	\
İlâhi ya Rab, biz nasıl hasretimize kavuştuk ise deryada karada olanları da hasretine kavuştur! Haydi Şirinim, gidelim adûlar arasından! (Ferhad ile Şirin gider.)	\
**Karagöz ** (gelir).Ben de şu cenabete kavuşayım.(Kocakarıya bir tokat vurur.)	\
**H.** (gelir).Karagöz, bu ne yatıyor burada?	\
**K.**Evde tahtabiti çok da burada yatıyor serin serin.	\
**H.**Bilâder, bunun üstü başı bütün kan!	\
**K.**Sülük tutunmuş.	\
**H.** Hayır, bu mortoyu çekmiş.	\
**K.**Evet, Büyükçekmeceyi geçmiş.	\
**H.**öylesi değil, gebermiş.	\
**K.** Sikime, geberdi ise !	\
**H.**Haydi bunu götür de bir yere göm!	\
**K.**Ben bunu mezara gömsem nekadar ölü varsa ayağa kalkar.	\
**H.**Denize at!	\
**K.**Denize atsam nekadar balık varsa bunun şerrinden karaya uğrar.	\
**H.**Ne yapacaksın ?	\
**K.** Düşünüyorum. Kenefe atsam? O da olmaz.	\
**H.**Nereye atacaksın?	\
**K.** Bostan kuyusuna atarım.gider,( Hacivad da gider.)	\
**Karagözün karısı. **(içeriden) Herif, buna ne oldu?	\
**K.** Mortosunu çekti.	\
**K.K.**Yoğurtçu çeşmesinde kahve mi içti?	\
**K.** Hayır, Modada bir tek rakı içti. Öldü, öldü!	\
**K.K.** Herif, bunun altın çıkını olacak. Can acısiyle düşürmüş ise, bir kere bak!	\
**K.** (perdeye gelir, Hacivadı yakalar götürürken:)Eve kadar götürmeli.	\
**H.**Karagöz, ne yapıyorsun?	\
**K.** Çok şükür, eyiyim; sen ne yapıyorsun ? Ben seni para kesesi zannettim.	\
**H.**Benim para kesesine benzer yerim var mı?	\
**K.** Ufak tefek orta yerde dolaşma!(Vurur.)	\
(Alt tarafı malum.)	\
