
# orman

**Hacivad.** (semai söyliyerek perdeye gelir).	\
İki dilber ata biner, uydu gönül, bile gider, \
Birbirine nisbet eder: Sen mi güzel, ben mi güzel?	\
\
Biri der ki: Gel varalım, varalım yolda duralım.	\
Gelen yolcuya soralım: Sen mi güzel, ben mi güzel?	\
\
Birisinin kaşı kara, birisinin gözü elâ,\
ikisi de cana sefa, o da güzel, bu da güzel.	\
\
Hay Hak!	\
\
(Perde gazelini okur.)	\
Kurulsa meclise güller gibi handan olur perde, \
Yanarsa şem'-i veçhi manzar-ı huban olur perde.	\
On iki bend ile dört kûşe resm-i Küşteridir bu 
Derunu aşk ile pür suledir rahşan olur perde.	\
\
Zehi ibretnüma eğlencedir edna ve âlâya	\
Şu âlemde hemişe mecma'-i irfan olur perde.	\
\

Verasın fehm iden hisse alır tasvir-i pakinden	\
Bu MuKBİL binevaya bâ'is-i ihsan olur perde.	\
\
**Karagöz.** (yerde yatar).Amanın ser-i bi-muyum, kafatasım, beyintencerem, çürük pencerem! Gırtlaşmaktan kalayı sıyırıldı! Amanın dostlar, yetişin! Birdenbire vehleten lerzan olacağım. Vera-yı bî-gümanım sengalûde-i temastan inhidam oldu. Bizim Hacivad da belasını buldu.	\
**Hacivad.** (gelir). Vay, benim gözümün nuru Karagözüm!	\
**K.**Vay, ömrümün süruru Hacivadım!	\
**H.**Gel, benim gönlümün eğlencesi!	\
**K.**Senin yanına gelmem, çarşı işkembesi!	\
**H.**Ah Karagöz, seni ne kadar severim bilsen	\
**K.** Ben de öyle, Hacivad.	\
**H.**Demek ki, Karagöz, sen de beni seversin?	\
**K.** "Seversin" de söz mü?	\
**H.**Bakayım, beni ne kadar seversin?	\
**K.**Sen beni ne kadar seversin?	\
**H.** Ben seni sevdiğimden sana beyit bile yaptım.	\
**K.** Oku bakalım, Hacivad, yaptığın beyti!	\
**H.** (Der hakkı Karagöz ez zeban-ı Hacivad:)	\
\
Kaddi uzundur Karagöz.	\
Çekme burundur Karagöz,	\
Şanı oyundur Karagöz.	\
Nakarat: İşvenümundur Karagöz,	\
Bukalemundur Karagöz.	\
\
Kalpağının rengine bak!	\
Sıkma potur, mavi şayak	\
Meclise bastıkça ayak:	\
\
Ey zan.	\
Veçhi güzel, güler yüzü,	\
Tuti misalidir sözü,\
Kaşı keman, kara gözü.	\
Ey zan.	\
\
Yerse kebab ü kirdeyi	\
Dahi pilâvla zerdeyi. 
Neşelendirir perdeyi.	\
Eyzan.	\
\
Alsa eline bardağı,	\
Nuşeder ab-ı ırmağı,	\
Haci Evhadın yardağı,\

Ey zan.	\
\
**H.**Nasıl Karagöz, beğendin mi?	\
**K.**Aferim, Hacivad! Sen de beni dinle!	\
**H.**Söyle bakalım!	\
**K.** (Cenah ez zeban-ı Karagöz).	\
\
Servi misali kametim,	\
Gamdan emin ü rahatım, \
İşte budur mahiyetim.	\
Nakarat: Perdekeşan-i şöhretim, \
Karagözüm, bir âfetim.	\
Perdeyi hoş kilizlerim\
Hacivadı marizlerim	\
Sonra evime vızlarım	\
Eyzan.	\
\
Hacivada baş cğmezem.	\
Yanıma gelse koymazam.\
Dest ü avuçta durmazam.	\
\
Eyzan.	\
\
Kalpağımız, çatal matal. \
Hiç yetişir mi bana kal ? \
Her kim eder ise sual:	\
Eyzan.	\
\
Menkibeler uçururum.	\
Bazı veca' geçiririm, 
Gizli hapis kaçırırım.	\
Eyzan.	\
\
**K.**Nasıl, Hacı Cavcav?	\
**H.**Aferin, Karagöz, sen kapalı kutu imişsin!	\
**K.** Ne zannettin, a çürük'	\
**H.** Daha başka bu yokla şiirlerin var mıdır?	\
**K.**Varlık olmasın, bana meşhur şuaradan Katakoftici Karagöz derler.	\
**H.**Karagöz.demek kı evde boş vakit geçirmiyorsun. Divan mütalâa buyuruyorsunuz. bazı edebiyata dair şeyler okuyorsunuz değil mi?	\
**K.**Varlık olmasın, vaktimi beş geçirmem.	\
**H.**Sana, bir beyit okuyayım. Karşılığım senden isterim, yani naziresini.\
**K.**Oku bakalım!	\
**H.**Çakı çakmak çakılırsa gü-gü-güneş tutulur,	\
Senin gibi bir güzel ka-ka-kande bulunur?	\
\
**K.**(Hacivada vurur).Siktir kerata! Bunu kim söyliyecek be? Neme lâzım, varayım, gideyim evime, rahat rahat oturayım.(Gider).	\
Abla! Aç kapıyı	\
**Karısı.** (içeriden).A herif, yine eli boş mu geldin?	\
**K.** (içerden). Çeşmeden doldurdum da geldim.	\
**Ka.** Ben öyle münasebetsiz lâkırdıdan hoşlanmam.	\
**K.**Ben de mektebe başlanmam.	\
**Ka.**Zevzekliği bırak da bir iş ucu tut!	\
**K.** Tutacağım amma, bir türlü yakalıyamıyorum.	\
**Ka.**Bak, herif, hatırıma ne geldi.	\
**K.**Ne geldi hatırına?	\
**Ka.**Bizim kapının önünden gelen geçen eksik olmaz. Orada kahvecilik etsen olmaz mı?	\
**K.** Pek âlâ olur, karı, eyi hatırına geldi. Ben de yapanın.	\
**Ka.**Hazır evde kahve takımı var, eskiden kalma.	\
**K.** Yaptım gitti. Sen bana, bir eski fesim vardı, onu veriver Eski urubalarım vardır, onları da ver!	\
**Ka.**Al bakalım, giyiver!	\
**K.** Nasıl, abla, yaraştı mı?	\
**Ka.**Güzele ne olsa yaraşmaz?	\
\
(Perdeye kahve acağt konur. Karagöz de perdeye gelir).	\
**K.** Etli, peynirli kahveci verelim! Şekerli, sade, kıymalı, ıspanaklı kahve verelim!	\
\
(Şarkı ile Zenne gelir,. Hacivadın kızıdır.)	\
Şarkı Hicaz*	\
\
Kendine niçün emsal ararsın?	\
İsmin gibi pek nazik edasın;	\
Gerçi bir az da sen bi vefasın.	\
Nakarat: ismin gibi pek nazikedasın.	\
\
Kim sevmez âya sen gibi yâri!	\
Biçarene gel, lûtfeyle bari!	\
Kizb û riyadan iridir âri.	\
Eyzan.\
\
**Zenne.** Yüreğimde ne kadar çarpıntı var! Vücudumun her tarafını vakit vakit bir ra'şe kaplıyor. Kalbimin içinde güzel güzel emeller uçuşuyor; fakat içim içime sığmıyor,	\
**K.** Bu kim? Kendi kendine söyleniyor. Deli mi nedir?	\
**Z.**Canım muttasıl dolaşmak istiyor. Dolaşıyorum.	\
**K.** Çok dolaşırsan kör düğüm olursun.	\
**Z.** Yüreğimdeki hiss-i ruhani beni bilâihtiyar tefekküre sevkediyor. Biraz düşünüyorum, düşünürken bir zamanlar hayal-i vuslatiyle gönlümü eğlendirdiğim o gözlü yektanın ağuş-u zevciyetine muvaffak olacak mıyım ? Beyim hâlâ gelmedi, nerede acaba? Kuş, yuvasında eşini bekler gibi gözlerim yolda kaldı.	\
**K.** Beyefendi de bir gece bizde kaldı	\
**Z.** Dakikalar saat, saatler gün kadar uzuyor, işte pederim geliyor	\
**Hacivat.** Vay, hanım kızım, burada mısın? Seni evde aradım, bulamadım.	\
**Z.**Hava almak için çıktım, babacığım.	\
**K.**Havan alacaksan eli bende.	\
**H.** A. benim mahsul-ü ömrüm! Artık düşünecek ne kaldı? Cemiyetiniz için iktiza eden levazımatın kâffesi tedarik ve istihzar olundu.	\
**K.** "Göksudan aldığımız testi bulundu" diyor. Demek ki kaybolmuş.	\
**Z.** Eksik olmayınız, babacığım! Sizin sayenizde .	\
**K.** Babanın kemiğine sıçayım!	\
**H.**Senin şerefine, hanım kızım (Ağlıyarah)Lâkın, nazlı kızım, şimdi validen de sağ olaydı de senin mürüvvetini göreydi, kim bilir ne kadar mesrur olacaktı, değil mi?	\
**Z.**  Evet babacığım. Allah sana uzun ömürler versin, beni seninle mes'ut etsin!	\
**H.** Ah, o sertin dua eden ağzını sevsinler. Kızım, sen daha gençsin, yani bir taze fidansın. Feleğin henüz bad-ı hazan-ı sahtını görmedin; dünyanın ne olduğunu öğrenmedin!	\
**Z.** Evet efendim	\
**H.**Şimdi senin validen olmadığı için küllü-l-vücuh idarene ben nigâhban olmağa borçluyum.	\
**K.** Borçlu isen ver parasım!	\
**H.**Anın için sana nasihat kılıklı bir kaç sözüm var, Can kulağı ile dinlemelisin, yavrum!	\
**Z.**Dinliyorum efendim.	\
**H.**Bu âlemde beni beşerin tarz-i maişeti bir renk üzre değildir, muhteliftir. Kimi adam kendini fevkalâde surette idareye muvaffak olur, kimi hevaperestâne yaşar, kimi bir zülf-ü perişana gönlünü bağlar	\
**K.** Hacivad da süpürge bağlar	\
**H.** "Kimini sevdi Huda, kimini sevdada kodu.	\
Gülü arayış edup bülbülü gavgada kodu"	\
beytinin mefhumunca, kimi cihanın saadetlerinden, meserretlerinden nasibedar, kimisi de feleğin sitem ü ekdarına duçar olur.	\
**K.** Kızım, Hacivad senin derdine deva bulur.	\
**H.**işte bunlar hep cenab-ı vacibü-l-vücudün insana ihsan ettiği akl ü zekânın suver-i istimalinin derecesine göre husulpezir olur.	\
**K.** Hacivad da rezil olur,	\
**Z.**Mahz-ı hakikat söylüyorsun, babacığını.	\
**H.**İşte kızım, bu dakikadan itibaren aklım başına al!	\
**K.** Aklı götünde mi? Başında değil mi?	\
**H.** Mudebbirâne davranıp ta kendini kullanırsan mes'ut olur, rahat yaşarsın. Çünkü insana dünyada ana baba baki değildir. Bir zamanlar kucağında yattığın sevgili valideciğin şimdi kara toprak içinde yatıyor. Benim de bir ayağım çukurda ...	\
**K.** İki ayağın birden girer çukura!	\
**H.** Yarın, öbür gün, ben de çıkar giderim.	\
**K.** Uğurlar ola!	\
**Z.**Allaha emanet, babacığım 	\
**H.**İşte işbu sözlerimi piş-i teemmüle al da mes'udiyetini ikmal edecek olan zevcin olarak zatın isticlâb-ı hüsn-ü teveccühüne sarf-i mahasal-ı ikdam ve muhafaza-ı hüsn-ü muaşerete ihtimam et!	\
**Z.**Başüstüne, efendi pederim! Nasihatlerim ömrüm oldukça kendime düstur u amel ittihaz edeceğim.	\
**H.**Ben gidiyorum, kızını.	\
**Z.** Güle güle babacığını 	\
\
( Şarkı ile Çelebi gelir.)	\

Şarkı Beyati	\
\
Sebep ne? Bakmıyor yârim yüzüme,	\
Görünmüyor cihan şimdi gözüme,	\
Bu günlerde benim bakma sözüme 	\
Nakarat:Görünmüyor cihan şimdi gözüme.	\
\
Arayanlar beni gayrı yorulsun!	\
Sevenler her zaman gönlünde bulsun!	\
Bu bal oldu bana, eyvahlar Olsun!	\
Eyzan.	\
\
**Zenne.** Seni hakikatsiz seni! Azıcık daha gelmeseydin, inan olsun, bir daha yüzüne bile bakmıyacaktım,	\
**Çelebi.** Efendim, söz verir de hiç gelmez miyim?	\
**Z.** Yapmadığın şey değil ya!	\
**K.** Hacivadın damadı bey efendi!	\
**Ç. **Estağfurullah, hilafı hiç bir vakit kabul etmemi	\
**K.**  Ben de kalafat kabul etmem, tekmil omurgalarımı değiştirmeli.	\
**Ç.** Güzelim, pederin elinden guçhal ile yakamı kurtarabildim.	\
**Z.** Ben böyle yalanlara inanmam.	\
**Ç.** A benim enis-i ruhum, sana yalan söylemeğe ne mecburiyetim var?	\
**Z.** Pek âlâ var. Kim bilir nerelerde Sefa ediyordun.	\
**Ç.** Emin ol ki ...	\
**K.** Emin olma. Mehemmed ol 	\
**Ç.**Bu cihanda senden başka sevdiğim, senden başka emelim, senden başka düşüncem yoktur.	\
**K.** Bellini de bu lâkırdıya karnım toktur.	\
**Z. ** İnanayım mı bari?	\
**Ç.**Ben hakikat-i keyfiyeti arzedeyim de sen istersen inan, istersen inanma!	\
**Z.**İnanmasam, senin muhabbetinden emin olmasam, buralaragelir miyim? Buraya beni senin muhabbetin sürükledi; yoksa buralarını gece rüyamda görsem korkarak uyanırım.	\
**K.** Ben senin bir gece rüyana gireyim de sen de gör!	\
**Z.** Beyim, arzu buyurularsa, şu karşıdaki ormanın manazır-ı lâtifesini temaşa edelim. kuş cıvıltılarını dinliyelim!	\
**Ç.** Nur-u didem! \
\
,,Olanlar hisseyab-ı intibah âsâr-ı kudretten	\
Alırlar hisse-i ibret temaşa-yı tabiattan"	\
\
beyt-i güzini azamet-i ilâhiyeyi görmek için âsâr-i intibahâver-i tabiatın temaşasına sevkediyor. Lâkin mahasal-i âmâlım! Nur u mübinden manidar olan gözlerinin lâtif süzülüşündeki meharet-ı ziya .. ’ane bana kudret-i fâtıra-ı samadaniyeyi daha celi bir surette göstermez mi? Etrafı temaşaya ne hacet?	\
**Z.** Beni buraya getiren hep senin bu sözlerin değil mi ?	\
**K.** ".."Beni çift Sürmeğe alıştıran babamın öküzleri değil mi?" diyor! Babanın öküzleri varsa beyin de eşekleri var.	\
**Ç.** Meleğim,’artık vakt-ı müfarakat hulul etti Bana müsaade ediniz!	\
**Z.** Ah, beni bırakma! Ben senden nasıl ayrılırım!	\
**K.** Su döker ayırırım.	\
**Ç.** Güzelim, inşallah bir başka müsaadeli vakitte yine burada görüşürüz.	\
**K.** Orası güççe! Ben gördüm mü, görmedim mi?	\
**Z.** Elveda, beyim, elveda!(Ağlıyarak gider.)	\
**K.**Ulan, burası pazartesi pazarı  mi. yoksa çarşamba pazarı mı? Tuhaf be! Dağ başım ıssız buldular muhabbete koyuldular Bir daha yağma yok! Geçmiş ola!	\
\
(Şarkı ile Tiryaki gelir.)	\
Fesleyen ektim ...	\
\
**Tiryaki.** Bahar eyyamı erişti, yetiştik gül gibi yaze,	\
Sıcağı ref etmek için  yakışır deste yelpaze.	\
**K.**Bizim ihtiyar pek kepaze!	\
**T.** Bana baksan a, kahveci baba!	\
**K.** Ne istersin, sakalı kaba?	\
**T.**Oğlum, bana bir mümessek kahve pişir!	\
**K.**Başüstüne!	\
**T.**Nasıl pişireceksin, biliyor musun?	\
**K.** Nasıl istersen, öyle pişiririm.	\
**T.**Bir cezvenin içinde hem sade, hem şekerli kahve pişireceksin.	\
**K.**Defol şuradan, budalâ mısın nesin? Ulan, bir cezvenin içinde hem şekerli hem sade kahve pişer mi?	\
**T.**Pişirirsen, sana bir kahve parası yerine on tane kahve parası veririm.	\
**K.**Pişiremem! Sen şekerli mı istiyorsun, yoksa sade mi?	\
**T.**Sade olsun.	\
**K.**Peki, pişireyim.	\
**T.**Pini pini parmakların ile menuşeyi al da alâ küllü men tuteş getir!	\
**K.**Tepelerim, ihtiyar, seni! Ben bu lâkırdıdan ne anlarım?	\
**T.**Canım efendim, o güzel parmaklarınla maşayı al da bana külsüz bir ateş getir!	\
**K.**Evvelki söylediğin nerede, bu nerede? Arasında koskoca dağ var.	\
**T.**Aman, kahveci, pişir!	\
**K.**Pişireyim!(0 aralık Zeybekler ormandan gözükürler.)	\
**T.**Çabuk olsan a, çanım!	\
**K.**Pişiriyorum.(K. hırsızları görür.)Eyvah! Donuma kaçırdım, paçalarımdan akıyor!	\
**T.**Fatma kız damdan mı bakıyor?	\
**K.**Damdan mı, şamdan mı anlarsın!	\
**Birinci Zeybek.** Davranmayın	\
**K.**Kıpırdamam bile.	\
**T.**Aman, bittim!	\
**K.**Ben de sirkeyim.	\
**Birinci Zeybek.** Ulan, tutun!(Karagözle Tiryakiyi tutarlar.)	\
**K.**Kuzum efendim, beni ne yapacaksınız?	\
**İkinci Zeybek.** Soyacağız.	\
**K.** Ben zaten soyulmuşum.	\
**Birinci Zeybek.** İhtiyarı götürün de benzetin!("Tiryakiyi götürürler.)	\
**K.** Eyvahlar olsun! Beni benzetirlerse işim boktur.	\
**İkinci Zey.** Çabuk sökül. ulan!	\
**K.** Benim hiç bir tarafım dikiş tutmaz. Her tarafım sökük. Sökülmeye hacet yok.	\
**Birinci Zeybek.** Kemerde ne varsa çıkar, yoksa şimdi kafanı keserim!	\
**K.** Efendim, kemerde bir şeyler yok, İsterseniz bakın!	\
**İkinci Zey.** Pek âlâ, kemerinde bir şey yoksa, çekmeceden getir!	\
**K.**Hangi çekmeceden?	\
**Birinci Zeybek.** Ya büyük çekmeceden gelir, ya küçük çekmeceden!	\
**K.**  Postam değil. Ne Küçükçekmeceye  uğrarım ne  Büyükçekmeceye.	\
**İkinci Zey.** Biz seni uğratacağız.	\
**K.** Kapı dışarı mı?	\
**Birinci Zey.**Şimdi ihtiyarın gittiği köye göndereceğim.	\
**K.** Fıkarayım efendim, çoluk çocuk sahibiyim, efendim, bana acıyın efendim!	\
**Birinci Zey.**Mademki fıkarasın, seni fıkarılıktan kurtarayım'	\
**K.** Eksik olma, efendim!	\
**Birinci Zey.**Uzat kafanı	\
**K.** Ne olacak ?	\
**Birinci Zey.**Kafanı keseceğiz be!	\
**K.** Efendim, kabak çıkar, kesmeyin!	\
**Birinci Zey.** İster kabak çıksın, ister patlıcan, o bizim bileceğimiz şey.	\
Kesiver şunu 	\
**İkinci Zey.**Başüştüne, efendim.(Karagöze:)Haydi gidelim!	\
**K.** Nereye gidiyoruz?	\
**Birinci Zey.** Şu herifi hendeğe götür!	\
**K.** Pendiğe gidemem. Maltepede otururum.	\
**İkinci Zey.** Tepede oturacaksın. Haydi gel gidelim !	\
**K.** Efendim, sizde hiç merhamet şefkat yok mudur?	\
**Birinci Zey.** O Şevket dediğin kim oluyor?	\
**K.** Herifler mermerden heykel.	\
**İkinci Zey.**Bekliye bekliye ayaklanma kara su indi. Haydi gidiyoruz, haydi 	\
**K.** Beni öldürüp elinize ne geçecek?	\
**Birinci Zey.** Bu kadar yalvarıyorsun. Haydi seni içimize alalım  içimize girer misin?	\
**K.** Zıvanalı mısınız? İçinize nasıl girerim?	\
**İkinci Zey.**Biz zorla sokarız. Sen girecek misin içimize?	\
**K.** Girerim.	\
**Birinci Zey.** Senin için sırlı mıdır, yoksa sırsız mı?	\
**K.** Sırlıyım, efendim. Göksu testisi gibi.	\
**Birinci Zey.** Seni aldık içimize. Şimdi buraya bir yolcu geldi mi, bize haber vereceksin.	\
**K.** Nasıl, efendim?	\
**Birinci Zey.**Parola: Sana bir düdük veririm, yolcu geldiği vakit çalarsın düdüğü.	\
**K.** Düdüğüm öterse eyi.	\
**Birinci Zey.**Al bakalım şu düdüğü!	\
**K.** Ver bakalım düdüğü! (Alır.)	\
**Birinci Zey.** Biz gidiyoruz; dersini belledin mi?	\
**K.** Belledik.	\
**İkinci Zey.**Allaha’smarladık (Giderler.)	\
**K.** Sefa geldiniz! Ulan, güç belâ kurtulduk!	\
\
(Şarkı ile Türk gelir.)	\
Şarkı Uşşak
\
Yine gördüm boyu uzun serv-i bulendum, dimne tek,\
Afatı gördüğüm bir gez daşa çaldum nacağu!\
Kezbanumun gaşı gara, pek beyaz du bacağu.\
Nakarat:Afatı gördüğüm bir gez daşa çaldum nacağu.\
Boşboğazsın, a teres, nuzlaya garsun boğazın\
Dilerun hem dalasan guyruk örü gıçcuğazın.	\
Issudan gizdi cehendem gibü. emmi, köyümüz!	\
Zırıgırak dutdu sararduk solagalduk bu yazın.	\
Vanlu ayvaz gibü dutmaz gerüsü, zırzır öter\
Yaz günü kim yise baklayla fasulya piyazın.	\
Gırçıl olmuş sakalın gel de bîcük aynaya bak!\
Yakışır galpağunu gaffana geysen papazın.	\
Goğlayup âyana, Himmet, bizi dövdürdü gadu, 
Bellerün anasını bir gun olur ol gamazın!	\
\
**Türk.**Dahdurocuk durucuk, geldi gondu bir serçecük. Civucük civucük! Halime haldaş, yoluma yoldaş; bir baba dostu olsa da izucuk mezeleşşek	\
**K.** Baba, hoş geldin!	\
**T.**Sikdü get sen de! Neden boş geliyon? Elümde nacak, sırtumda aba!	\
**K.**Vay, ayı dayı, vay! Behey canım!	\
**T.**Canın çıkhsun!	\
 **K.**Behey ciğerim 	\
**T.**Ciğerünü gopekler yisün 1	\
**K.**Behey gözüm!	\
**T.**Gozun cıkhsunl	\
**K.**Behey ayı!	\
**T.**Mehraba dayu I	\
**K.**Söyle bakalım, ayı oğlu ayı, nereden gelip nereye gidiyorsun?	\
**T.**Istanguldan geliyon.	\
**K.**Nereye gidiyorsun?	\
**T.**Gastamonuya.	\
**K.**İstanbulda ne iş yapardın?	\
**T.**Bekcülük, mahallede zopa gagucu	\
**K.**Mahalleden para aldığın vakit aylık mı alırdın, yoksa yıllık mı?	\
**T.**Aylukh alurdum yıllukh da alurdum. Ekserü yıllukh alurdum. Tamam bir sene yıllar başlangıcımdan başlardum.	\
**K.** Yıllar başlangıcı nedir?	\
**T.**Cühül herüf! Ni ayunu biliyon, ni de gününü!	\
**K.** Haydi aylan say bakalım biliyorsan!	\
**T.**Yıllar başlangucı, itiş dalaş ayu, böyüh nasuf, guçüh nasuf, böyüh aralukh, guçüh aralukh, irceb, mum ayu, emegol ayu, emegol bezegu, iki bezek gısugu. davar bezegu.	\
**K.** Vay. ayı. vay! Ne tuhaf ay isimleri.Bunları kim anlar?	\
**T.**Tamam bir sene.	\
**K.** Çok para kazandın mı? Kemerin dolu mu?	\
**T.** Senin nene gerek? İster dolu, ister boş.	\
**K.** Darılma! Benim sorduğum; memlekete giden adamın kemeri dolu olmalı,	\
**T.**  Benim kemerümde yüz tene lire var.	\
**K.**Zeybeklerin kulağı çınlasın ( Hırsızlar dinlerler.)	\
**T.**Bizüm  Kezban gıza on tene beşibiryerde boynuna daksun deyi hazurladum.	\
**K.** İyi saatte olsunlar! Daha başka öte beri aldın mı?	\
**T.**Hongudu\	\
**K.** Hongudu ne dernek? Aldım demek mi?	\
**K.** Ahmede edük aldum, Mehmede düdük aldum; bi dazlangaç, bi hazlangaç.	\
**K.**Onları anlıyamadım. Neyse .. .(Düdüğü çalar.)	\
***Zeybekler.** (hepisi birden).Davranma!( Türkü tutarlar.)	\
**T.**Ulan, nireye gidiyoruz?	\
**K.**Ayağın yere basmadan memlekete.(Götürürler.)Ayı dayı şifayı buldu.	\
\
(Şarkı ile Ermem gelir.)	\
Yine bir gülnihal..."	\
**Ermeni.** Ne güzel manzara! Aşıkım galebe etti; şu manzaraya karşı bir beyit söyliyeyim!	\
**K.** Sen manzarayı sonra görürsün, dehşetli manzara!	\
**Er.**Beni bir İnci Dudu aşıkan itti, ne derim?	\
Geçe gündüz gılınm elde tutar da gezerim.	\
Şirinin, canına rahmet koyayım  Fehrad için	\
Sinesin çakeçak etti, ona bende he derim.	\
Aşıkını başıma koysam yüreğim çörçoröter,	\
Şıpdeyı aygır eşekler gibi fehrad ederim.	\
Beni bir hırsa komuş ki bana maytab ediyor, \
Dibimi yırtmış edersem ele geçmez: ne derim?	\
Marşupayla içerim cermak çuru şarvoş olmam.	\
Muhabbet derd ü belâdır, buna yanmış ederim.	\
Yüz eşek zırlasa fehradıma karşı duramaz	\
Gecenin kuşu gibi çorlıyarak âh ederim.	\
\
**K.**Sen şimdi ah da edeceksin, vah da amma, çaresi yok.	\
**Er.** Aşkamlarınız hayr olsun!	\
**K.** Senin de diken gibi olsun!	\
**Er.**Siz kahveci misiniz?	\
**K.**Evet, kahveciyim.	\
**Er.**Bana baksan a, dostum, güzel bir kahve pişir, içeyim!	\
**K.** Şekerli mi, sade mi?	\
**Er.**Kahve olsun da nasıl olursa olsun.	\
**K.**Sizin şiire merakınız var.	\
**Er.**Ne söylersin, ahbar? Bayılırım taryihe şiriye!	\
**K.** Sen de benim götümü ye! „Şiri ye“ diyor! Şiir yenir mi?	\
**Er.**Benim bir ahbabım vardı: Artin Ağa. Çocuğuna bir taryih yaptılar.çok parlaktır, ahbar. kıyak şeydir.	\
**K.**Ne yolda tarih?	\
**Er.**‘Hyların eşbehi, kumpanya mudiri Artin:	\
Urpat şapat; Mega Asvas, mek oğulcuk! derdi.	\
Gâb gafilden dak deyince bu çocuk dünyaya	\
Şıp deyi Artin Ağa işte muryada® erdi.	\
Çıktı taryih dibinden, zo, ne dersin ahbarım?	\
Butsu Meryem Dudu Artinine bızdık verdi,	\
Tam taryihdir; doğrusu: olmaz şey!	\
**K.** On dakika sonra da tarihte görülmemiş bir şey göreceksin. Nereden gelip nereye gidiyorsun?	\
**Er.**İstanbuldan geloorum, Sıvaza gideceğim.	\
**K.** istanbulda ne iş yapardın?	\
**Er.**Cenabınız neden sordunuz?	\
**K.** Sormak-ayıp mı?	\
**Er.** Bendeniz sarrafım.	\
**K.** Çok para kazandınız mı?	\
**Er.**Allah bin bin bereket versin! Bin liradan ziyade kazandım.(Hırsızlar dinlerler.)	\
**K.**Kulağınız çınlasın ! Kuyumculuğunuz da var mıdır?	\
**Er.** Bir taryihte o sanatı da yaptım. Kıyak şeyler yapardım.	\
**K.** Benim de kuyuculuğum vardır.(Düdüğü falar, Ermeniyi tutarlar.)\
**Er.**Zo, bunlar kimdir ?	\
**K.**Efendini, bunlar gece kuşu.	\
**Er.**Zeyrekyokuşu mu?	\
**K.** Bak, yokuş mu, iniş mi, anlarsın,	\
**Birinci Zey.** Haydi, alın götürün!	\
**Er.**Zo efendim, nereye gideniniz?	\
**K.**Ahrete.	\
**Er.**Sen de kıyak köpoğluyimişsin!	\
**K.**Ağzını topla!	\
**Birinci Zey.** Söyletmeyin (Hepisi gider.)	\
\
(Şarkı ile Ak Arap gelir.)	\
Befta hindi...’	\
\
**Arap.**Merhaba, gahveji baba!	\
**K.** Merhaba, hacı baba!	\
**A.** Siz bir gahua bişirir?	\
**K.**Evet, kahve pişirir; hazan arkadaşlarım adam şişirir.	\
**A.** Kım şişirdi, ganim?	\
**K.** Aşçı başı pişirdi.	\
**A.**  Demak, hurda şok adam var?	\
**K.** Şimdiki halde kimse yok amma, icabına göre .. ,	\
**A.**  Demak, bazan kımsa yok. hazan şok galabalık?	\
**K.**Evet, alabalık.	\
**A.**  Siz hurda şok oturdu mi?	\
**K.** Evet, Osurdum.	\
**A.**  Agayib! O nasil lâgirdi mi bu?	\
**K.** Nereden gelip nereye gidiyorsun, hacı baba ?	\
**A.** Ben şok yer dolaşli, gazdı.	\
**K.**Ticaretle mi gezdin ?	\
**A.**  Bazan tigaret. bazan ziyaret.	\
**K.** Çok para kazandın mı?	\
**A.** Şok bara gazandi.	\
**K.**Kaç yüz lira kazandın?	\
**A.** Ne yuz lira? Bin lira, iki bin lira.	\
**K.** Kulağınız çınlasın! (Hırsızlar dinler.) Şimdi nereye gidecek ?	\
**A.** Şimdi ben İstanbulda gidejek.	\
**K.** Bırakırlarsa.	\
**A.** Nişin birakmiyajak?	\
**K.**(düdüğü çalınca hırsızlar gelip Ak Arabi tutarlar.)Hacı baba demirledi \
**Zey.** Davranma!	\
**A.** Agayib! Nişin böyle oldi?	\
**K.**Havasından.	\
**Birinci Zey.** Mm. götürün, söyletmeyin!	\
**A.** Gânim. ben nerde gidejek?	\
**K.** İlk posta ile ahrete. Baksan a, efendi! Bize hiç bir şey yok mu?	\
**Birinci Zey.** Sonra görüşürüz.(Gider.)	\
**K.**Biz bedavadan vurup enseye pala çalıyoruz, bize bir şey yok	\
(Şarkı ile Yahudi gelir.)	\
\
Ande vamoz2	\
\
**Yahudi.**Maşalâ, maşalâ! Daha kiş yelmeden ayi çikti karşıma!	\
**K.** Şimdi sen ayıyı da görürsün, maymunu da!	\
**Y.** Sen maymunculuk da mi yaparsin?	\
**K.**Beş dakika sonra taşaklarımı kaparsın! Nereden gelip nereye gidiyorsun, bezirgan?	\
**Y.** Ben çok yerler dolaştım, çok yerler yezdim.	\
**K.**Ne tarafları gezdin bakalım?	\
**Y.** İstanbul bir, Burs-iki. Tokat bir, Sıvas iki, Edirne bir, ya Kalas-iki.	\
Ayağında çorap yok, neye-mesin sİki?	\
**K.**Tepelerim, Yahudi, seni! Cinas söyleme, köpoğlu!	\
**Y.** Kimi tepelersin?	\
**K.**Seni tepelerim!	\
**Y.** Bu surattan mı?	\
**K.** Hayır. Maraza için evde ayrı bir suratım var, onu takar gelirim.	\
**Y.** Vay, Mamzar oğlu mamzari be! Bana bir kahve pişir!	\
**K.** Şekerli mi. sade mi?	\
**Y.** E, nasıl olursa olsun.	\
**K.**Nasıl İstiyorsun?	\
**Y.** Yansı sade, yansı peynirli.	\
**K.**Bir sopa atacağım sana! Ulan, bu börek mi, yoksa boğaca mı? "Yarısı sade, yansı peynirli" diyor.	\
**Y.** Sade pişir, tepeşir Beşir\
**K.**Haydi ,.pişir" iyi, o „tepeşir Beşir" ne olacak?	\
**Y.** Kahveci, çabuk pişir!	\
**K.**Pişiriyorum.	\
**Y.** Ne kadar yuzel bir aşka yeldim, sana bir şarkı soy leyim, dinle!	\
**K.**Sen şarkıyı, maniyi beş dakka sonra söylüyeceksin.	\
**Y.**(makamla).Altun tasta yul kuruttum, ah ninem!(Mükerrer.)	\
Yar osurdu, sen yuttun, ah, ninem!(Mükerrer.)	\
**K.**Bezirgan, güfteyi anlamadım.	\
**Y.** (makamsın).Altun tasta yul kuruttum.	\
Yari sinemde uyuttum.	\
**K.**Demin söylediğin güfte karışık ism-i fail.	\
**Y.** Kahve pişti mi? (Hırsızlar Yahudiyi tutarlar.)	\
**Zey.** Davranma, ulan!	\
**Y.** Kipirdamam bile. Memed ağa Karauyuz, bunlar kim?	\
**K.**Kırmızı frengi. Doğrusunu istersen, kahvenin böcekleri.	\
**Zey.** Haydi, götürün!	\
**Y.** Nereye yidioruz?	\
**K.** Son posta ile ahrete!(Giderler.)	\
Ey Karagöz! Bu kadar adamın kanına girdin! Vicdanım razı değil. Ben de şerik-i cinayet sayılırım. Yaptım amma, can korkusundan. Ben şimdi gider, bunları ele veririm.(Gider.) Bana baksan a, Tuzsuz Ağa!	\

**Sarhoş.** (içeriden).Ne istiyorsun, Karagöz?	\
**K.**Arkadaşlarına haber ver, bir yere götüreceğim sizi.	\
**S.** Hayır ola, bir şey mi var?	\
**K.**Ariz ü amik konuşmağa vaktim yok. Parola: Ben düdüğü çalar çalmaz siz gelir o yanımdaki adamları tutarsınız. Sonra esası size anlatının.	\
**S.** Olur, Karagöz, Bana baksanız a: Dili Tuzsuz, Bekri Veli. Sakallı Deli, Hımhım Ali, Hovarda Çakır, Kırmızı suratlı Bakır, Burunsuz Mehmed, Çopur Haşan, Cimgöz Mustafa! Hepiniz geliniz!	\
**Helisi.** Geliyoruz, arkadaşlar!	\
**K.** Anladınız ya parolayı? Ben düdük çalar çalmaz gelin, yoksa iş fenaya varır.	\
**Deli Tuzsuz.** Anladık, canım. Sonra dişe dokunacak bir şey var mı?	\
**K.**Hem dişe dokunacak var, beni kuşa!(Perdeye gelir.)Ey keratalar! Beni kendinize bend edip benim vasıtamla epeyce iş gördünüz, canlar yaktiniz. Şimdi siz de bulursunuz. Bana baksana a. Uzun Efe!	\
**Zeybekler.**(hepisi gelir).Ne istiyorsun, Karagöz?	\
**K.** Bir şey istediğim yok. Yalnız şunu soracağım: O adamları öldürdünüz mü, yoksa hayatta mı?	\
**Z.** Senin vazifen değil o, bizim bileceğimiz şey.	\
**K.** Benim de bileceğim şey bu!(Düdüğü çalar, Matizlerin hepisi gelir, kuşatırlar.)	\
**Z.**Ya Karagöz, ettin mi bize edeceğini?	\
**K.** Siz edeceğinizi ettiniz, benim de size edeceğim bu.	\
**Deli Tuzsuz.** Teslim olun! Sonra iş fenaya varır.	\
**Birinci Zey.** Olduk, hem de cezamızı bulduk.	\
**Sarhoş** Veriniz silahlarınızı!	\
**Zey.** Alınız!(Silahlarını alırlar hepisim götürürler.)	\
(Karagöz de gider, kendi elbiselerini giyer. Hacivad ile perdeye gelirler, oyun biter.)	\
