
# buyukevlenme

 **Hacivad.**(semaiyi söyliyerek perdeye gelir).	\
Dil mest olur huşyar iken . . .	\
\
Hay Hak’	\
( Perde gazelini okur.)	\
\
Sureta bir çargûşe bezdir amma perdemiz.	\
Gösterir ahval-i âlemden temaşa perdemiz.	\
\
Gerçi kil u kal ile memlû safa meddahıdır, \
Akl-i dana hallider sırr-ı muamma perdemiz.	\
\
Nağmesaz oldukça mutrib Karagöz raks eylesün 	\
Nezd-i şahide safalar ide icra perdemiz.	\
\
Hak Şehinşah-i cihanın ömrünü müzdad ide,	\
Zevk u şevk-i şevkete her dem müheyya perdemiz.	\
\
Fevkımızdan sayesin dür itmesün Mevlâ anın!	\
Rağbetiyle, Raşîda5, bulmakta mâna perdemiz.	\

(Kavgadan sora:)	\
\
**Karagöz.**.Aman, öldüm bayıldım! Hacivadın elinden yandım! Deminden evde yatıyordum, Hacivadın gürültüsünden uyandım. Amanın aseldirlerim yani baldırlarınım! Her suph u şam, ve belki her akşam, bu herifin elinden hâba varmayıp sabaha kadar köpek gibi hırhır hırlarım. Darbe-i tekmeviyenin tesirinden eşek gibi zırlarım. Amanın omuz-başlarım! Cereyan-i tokattan tüysüz kalan hilal kaşlarım! Hacivad, şimdi senin sinsilenden başlarım! Vücud-u darbe-alûdum ahçı kevgiri gibi delik deşik oldu. Amanın sağ cenahım Adeta temayülen meyl-i inhidam etmiş de haberim yok.	\
**Hacivad** (gelir) Ah. Karagöz, ah. Böyle her akşam pencereden aşağıya atlarsın!	\
**K.** Sen de, Hacivad, lâkırdı etmesen bok gibi patlarsın	\
**H.** Efendim, bendeniz bu sabah hatır-ı şerifinizi nüvazişlere garketmek istedim!	\
**K.**O ne demek, Hacivad?	\
**H.**Ne demek olacak? Hatırım sormak istedim.	\
**K.** Canım, şunu her zamanki gibi sorsan a!	\
**H.** Çeşm-i siyahım, zaman incelmek istiyor.	\
**K.** "Siyah çeşme" ne demek?	\
**H.** Şüûn-ü âlemden pek bibehresin.	\
**K.** O ne demek, Hacivad?	\
**H.** Yani demek isterim ki bir şeyden çaktığın yok.	\
**K.** Akşamlan benimle beraber değilsin ki bileceksin!	\
**H.**Akşamları ne olmuş, Karagöz'	\
**K.** Ne olacak? Ben her akşam çakarım.	\
**H.**. Demek ki bade nuşedersin, öyle mi?	\
**K.**Evet, badem ile işret ederim; benim mezem o dur.	\
**H.** Demek, her akşam meykede meykede gezersin?	\
**K.** Evet, akşamları peykede gezer sabhları da gezer.	\
**H.** Peykede ne gezer?	\
**K.** Bit! Ne gezecek? Hattâ geçen akşam mahalle kahvesinde otururken ensemde bir tane buldum.	\
**H.** İşretlerden ne işret kullanırsın?	\
**K.** Onu sen git te meyhaneci Apostola sor, aceba çakmadığım bir şey kalmış mı?	\
**H.**Demek ki. Karagöz, sen çok hovardalık etmişsin!	\
**K.** Ettim zahir! Hovardalık yüzünden sata sata hiç bir şeyim kalmadı.	\
**H.**Neler sattın, Karagöz?	\
**K.** Neler olacak? Babamdan kalan hanlar, dükkânlar, apartmanlar, yalılar, köşkler, konaklar . ..	\
**H.**Karagöz, rüyanda mi gördün? Babandan kalma yalıya bayılırım.	\
**K.**Yalıda bayılırsan ben de seni sovuk su banyosu yapsın dîye pencereden fırlatırım.	\
**H.** Ah, zevzek ah. Yalınız nerede idi bakayım?	\
**K.** Boğaziçinde idi, Kavakta.	\
**H.** Kavağın hangi tarafında idi?	\
**K.** Orta dalda oturuyordum.	\
**H.** Yalı duruyor mu?	\
**K.** Sattım, Hacivad; şimdi kazıklarda oturuyorum.	\
**H.** O ne demek o?	\
**K.** Yanı bir yerime bir şey batmasın diye kumda oynuyorum.	\
**H.**Karagöz, sen bu yalanlan nereden öğrendin?	\
**K.** Söylediklerim yalan mı?	\
**H.**Yalan ya! Sen kimin oğlusun? Maşacı Zobuoğlunun oğlusun, ondan mevrus kalsa kalsa sana bir kırık mangalla bir sacayağı, iki eski maşa, bundan ibaret,	\
**K.** İşte, ben de onları sattım.	\
**H.**Onlar kaç para eder?	\
**K.**Ne ederse etsin, sattım.	\
**H.**Ya yalı lâfı ediyordun!	\
**K.**Yalan değil. Boğaziçinde.	\
**H.**Nasıl Boğaziçinde?	\
**K.**Nasıl olacak? Akşam yediğim yağlı yemek boğazımın içinde, eğer yalansa beni yarım okka baklava ile zehirle!	\
**H.**Canım, o nasıl zehirlenme?	\
**K.** Yeni çıkma zehir.	\
**H.**Bu zehiri ne zaman öğrendin?	\
**K.** Ramazanda.	\
**H.**Demek senin lüpçülüğün de var desen e!	\
**K.** Ne dedin Hacivad? Senin kadar olmayımI	\
**H.** Bu lâfı brak’	\
**K.** İşine gelmedi mi? İşim gelmezse öyle olur, seni dalkavuk seni!	\
**H.**Ekseri evden çıkmıyorsun, Karagöz.	\
**K.**Ne yaparsın? Parasızlık. Bu gün kandan para koparayım diye uğraşta koparamadım.	\
**H.** Karın parayı nereden bulur?	\
**K.** Orasını sorma, bizim keseden.	\
**H.**Sen karına para koklatmazsın ki.\
**K.**O yolunu bulur, ben uyurken kesemden alır.	\
**H.**Sen bir şey söylemez misin?	\
**K.** Söylesem de para etmez ki! ..Yavuz hırsız ev sahibini basar" derler, meşhur meseldir.	\
**H.**Ayı yolunu buluyor.	\
**K.**Ah, Hacivad,  Başıma gelenleri bilsen! Cebimde beş para yok; kahveye çıkıp da bir kahve bile içemiyorum.	\
**H.** Haydi gidelim, ben kahve parasım veririm.	\
**K.** Yalınız kahve parası olsa eyi.	\
**H.**Kahveciye borcun mu var ?	\
**K.**Borç değil, fincan parası, geçen gün bir fincan kırdım.	\
**H.**Birisinin kafasına mı attın ne yaptın?	\
**K.** Yok canım, anlatayım. Geçen gün kahvede oturuyordum, canım sıkıldı; bir az şöyle dolaşayım dedim. O aralık bir gürültü koptu. Ne var diye birine sordum. Yangın var dediler. Ben de yangını görmek için bizim mahalle camisinin minaresine çıktım. Bir de aşağıya baktım ki ne göreyim?	\
**H.**Ne gördün, Karagöz?	\
**K.** Tımarhanede ne kadar deli varsa koyuvermişler.	\
**H.**Sora?	\
**K.** Sorası: Arkamdan bir tanesi de minareye çıkmış.	\
**H.**Karagöz, sen minarenin kapısını kapamadın mı?	\
**K.**Orasının farkında değilim kapadım mı kapamadım mı.	\
**H.**Kaç, Karagöz, kaç!	\
**K.** Havaya mı kaçacağım? Aşağıya inenim ki! Herif mutlak „Ben seni boğazlarım'' demesin mi?	\
**H.**Aman, Karagöz, ne yapacaksın?	\
**K.** Yapacağı yok. "Aman, baba, sen bir eyi adama benziyorsun, gel seni şuradan aşağıya atayım" dedi. Aman, oğlum, şöyle olur böyle olur diye biz tükenmeze girdik.	\
**H.**Tükenmez şerbeti ini?	\
**K.**Hayır, ecel şerbeti.	\
**H.**Karagöz, aşağıya in!	\
**K.**Bak, inebilirsen inmemezlik etme! Herif kuşağımdan tuttu.	\
**H.**Herif uşak mı tuttu?	\
**K.**Hayır, hizmetkâr aldı. Budalâ mısın nesin bilmem. Herif beni bacağımdan tutar tutmaz bizi minareden aşağıya attı.	\
**H.**Eyvah eyvah eyvah !	\
**K.**Ördek nağmesini bırak! Ben de korku ile Aman! diye bir bağırmışım,
**H.**Bir yerine bir şey oldu mu?	\
**K.**Bir şangırtıdır koptu. Bir de gözümü açtım, kahvenin ortasında fincan kırıkları, meğerse iskemlenin üstünde uykuya dalmışım.	\
**H.** Demek, söylediğin rüyamış?	\
**K.** Evet, rüya. Sen sahi mi zannettin?	\
**H.**Ne bileyim, sahi zannettim. Sen rüya demedin ki!	\
**K.**Bun sana derdimi anlatacaktım, sen bana kahve fincanını sordun.	\
**H.**Anlat bakalım derdini!	\
**K.** Ah, Hacivad, ah! Hâlâ paralara içerim yanıyor!	\
**H.**Üzerine bir bardak sovuk su iç de söndürsün!	\
**K.** Zaten seninle konuşmağa gelmez ki, sivri sakallı herif!	\
**H.**Kızma. Karagözüm, kızma!	\
**K.** Kızdığım yok amma, hiddetim galeyana geldi.	\
**H.**Canım, eyi ya! Paralara ne oldu?	\
**K.** Bu cuma mirasyedinin birisinden iki lira kadar para aldım.	\
**H.**Ne yapacaktın o parayı?	\
**K.** Yiyecektim.	\
**H.**Hiç bakma, yut!	\
**K.** Ben de öyle yapacaktım anma, lezzeti kaçar dediler.	\
**H.**Nasıl yaptın?	\
**K.** Ekmekle yedim.	\
**H.**O paralar şimdi boğazına gitti ha!	\
**K.**Gitti.	\
**H.**Öyle ise, bir hafta pehrizdesîn,	\
**K.**Hay budala herif hay! O liranın birisi karının kesesinde, birisini de harcettim.	\
**H.**Ne bileyim, sen ,.Hepsini yedim" dedin!	\
**K.** Ben parayı buldum ya! Oğlana dedim ki: Hadi Fenerbahçesine gidelim amma, öyle birahaneye girmek yok. Bizim oğlan zaten böyle şeylere hazır.	\
**H.**Elbette ya! O senden açıkgöz.	\
**K.** Kira ile aldığım elbiselerle epeyce süslendik, levanta süründük, yine o eski âyakkablanınızı giydik.	\
**H.**Oldu mu ya? Potinlerinizi giymeliydiniz.	\
**K.** Göklerimizde gözlük , ceplerimizde yüzlük, şimdi moda bu, yüzsüzlük ; olduk birer zübbet! Haydi babam, vapura, oradan birinci mevki bilet aldık.	\
**H.** Vapurda yer buldunuz mu?	\
**K.** Bulduk. Güzel bir kana peye oturduk, Kadıköyüne gidinceye kadar vapurda bir güzel uyku uyudum.	\
**H.** Etrafını görmedin demek.	\
**K.**KadıkÖyüne çıktık, oradan bir araba, doğru Fenerbahçesine.	\
**H.** Seni arabada iken görmeli idi, Karagöz!	\
**K.**Tam bahçeye gireceğimiz zaman kapıdaki adam birer kuruş vereceksiniz diye dikildi. Ben:  ” Canım, dilenciye para vermek adetim değildir” dedim. O ”Beyim, buraya parasız girilmez" dedi. Ne ise. birer kuruş da oraya toka ettik  bahçeye girdik: Birde baktım kı içerisi kadın dolu.	\
**H.**Sende, Karagöz, bir tane yakala!	\
**K.**Onlar elde avuçta durmazlar ki!	\
**H.**Sen de elde avuçta duranı İnil!	\
**K.** Baktım, herkes bir kadının peşinde. Ben de nasıl gelirse gelsin bir tane de ben bulayım dedim.	\
**H.**Karagöz, kadınlara takılma, sora dayak yersin!	\
**K.** Neden dayak yerim?* Herkes nasıl yaparsa bende herkesin yaptığım yapacağım.	\
**H.** Ne dedin bakayım?	\
**K.** U-h, yallah! dedim.	\
**H.**Bu bîr az kabaca düşmüş.	\
**K.** Sora inceltiriz, ziyan yok,	\
**H.**Sora daha ne söyledin?	\
**K.** ”Güzelim, gel yanıma, şeker alayım sana” dedim.	\
**H.**Ne tuhaf söz söylemişsin. 	\
**K.** Sen de dursun a! Karının hoşuna gitti galiba, çarşafını yerden kaldırdı. Bizim oğlana bu işaretin ne demek olduğunu sordum.  "Bizi çağırıyor" dedi.	\
**H.**Kadın güzel mi idi?	\
**K.**Doğrusu suratını görmedim, her ne kadar olsa, kadın değil mi? Haydi babam, biz düştük peşine.	\
**H.**Karagöz, bayılırım senin işine.	\
**K.**Aman efendim, aman! Bizim oğlan neler söylemiyor! Karıya söyledikçe onun koltuklan kabarıyor. Ne ise, koluna girdik, orada akşama kadar turp yaptık.	\
**H.**Yok, şalgam yaptınız.Ayol, ona ..turp" demezler, tur derler.	\
**K.** ister ,,otur“ desinler ister ,,oturma" desinler!	\
**H.** Bir şey söylediğin zaman mânasını bil de öyle söyle!	\
**K.** Pe ki, olur. Bir de saate baktım, on. Akşam olmuş, bahçedeki kadınlar erkekler ikişer olmuşlar, hepsi çift, hiç tek yok. Biz de bir tane bulduk ya! Bize yeter dedik, nereye gideceğimizi sordum. ,,Köprüye" dedi.	\
**H.**Demek, o taraflı değil.	\
**K.** Hayır, Bir arabaya bindik, iskeleye gidinceye kadar kadını epeyce sıkıştırdım amma, hâlâ yüzünü açmıyor. O kadar rica ettim, " peçeni kaldır" diye, yüzünü göstermedi. İskelede ona da bîr bilet aldık, doğru köprüye. Yine sordum nereye gideceğimizi. Kadın bizim mahalleyi tarif etmesin mi? Biz bir arabaya bindik, doğru bizim mahalleye.	\
**H.** Bizim karı duyar diye korkmadın mı?	\
**K.** Bir defa göz kızmış. Her ne hal ise, bizim mahalleye geldik. Arabadan indik, evini sordum, bizim evi tarif etti, boynundan anahtarı çıkardı kapıyı açtı; içeri girer girmez peçesini açtı. Bir de bakayım ki bizim karı değil mi? Eyvah  dedim, baltayı taşa vurduk, sıfırı tükettik! Karı açtı ağzını, yumdu gözünü: "Evde nurtopu gibi karın varken senin dışarda gözün" diye bar bar bağırdı. Arabada parayı cebimden çalmışmış, onu da yiyecekmişim, daha bir çok lâkırdılar,	\
**H.** Senin sesin çıkmıyor mu?	\
**K.** Nasıl sesim çıkar? Kabahatliyim! Bizim oğlana bir temiz dayak attı. Ben de anladım: Bize de nöbet gelecek dedim. Sora da bize başlamasın mı vurmaya? Bir temiz dayak da bize attı. Hacivad, bundan eyi Fener eğlencesi olur mu?	\
**H.**Afiyet olsun, Karagöz.	\
**K.** Çenen tutulsun, Hacivad! (Vuru gider.)	\
Sen gidersin de ben durur mıyım? Ben de gideyim idgâha dolaba dilber seyrine. Bakalım, ayine-i devran ne suret gösterir!	\
(Eve gelir, kapıyı çalar.)	\
\
**Karagözün karısı** (içeriden).Kim o	\
**K.**Aç, ben geldim.	\
**K.k.**Aç geldinse ne yapalım? Zaten evde de bir şey yok. Sen de aç, biz de aç, çoluk çocuk hep aç.	\
**K.**Ulan, sana: kapıyı aç! diyorum.	\
**K.k** Ben şimdi kalkamam.	\
**K.** Kapıyı bana kim açacak?	\
**K.k**Komşunun kedisi.	\
**K.** Ne âlâ .Kediler de iş görüyor! Kapıyı aç, karı, zevzekliğin lüzumu yok.	\
**K.k** Ben yerimden kalkamam.	\
**K.**Sora pişman olursun, karı!	\
**K.k** Ömrün günün kararsın.Benim adım yok mu?	\
**K.** Senin ne dadın var ne dayan. Aç kapıyı!	\
**K.k**Benim adım yok öyle. ,,Hanım" diyemiyor da ,,kan”!	\
**K.** Ulan, sen bana ,,herif" diyorsun ya! Ben hiç bir gün ağzından ..efendi" dediğini işitmedim ,,Herif" aşağı, ,,herif" yukarı!	\
**K.k**(gülerek).Ha ha hay, güleyim bari! Senin efendilik nene? Okuman yok. yazman yok!	\
**K.** O senden sorulmaz. Bir adam evinin hem efendisidir hem de beyidir.	\
**K.k** Sana beylik de uzak efendilik del	\
**K.** Aç kapıyı, şimdi kıracağım!	\
**K.k**Kır da bak ne görürsün!	\
**K.** Kırdığım vakit ne lâzım gelir? ( Tekme ile K. kapıyı kırar içeri girer,)\
**K.k** A sahiden kırdı!	\
**K.** Ulan, bugün ne olacaksa olacak.	\
**K.k** A herif, öyle hindi gibi ne kabarıyorsun?	\
**K.**Kabarırım zahir! Sen kim oluyorsun Bana niye kapıyı açmıyorsun ? Bu kimin evi, senin mi benim mi?	\
**K.k** İster senin olsun ister benim, gönlümün tahtapoşu! Keyfimin kâhyası değilsin ya!	\
**K.**Düzgün kuklası kaltak!	\
**K.k**Haydi şuradan, miskin avanak!	\
**K.**Tencerenin dibinde kara kalmamış kaşlarına çekmeden, mıymıntı karı!	\
**K.k**Karı kadar başına taş düşsün!	\
**K.**Senin başına düşsün!	\
**K.k**Herif, artık senin kahrını çeke çeke çekemez oldum,	\
**K.** Ben de zaten kendime eş buldum,	\
**K.k**Ehem ehem.güleyim bari. Senin başına aceba benden başka kim kusar?	\
**K.**Senin başına da benden başka kim işer?	\
**K.k**Beni aldığın vakit ayın ondördü gibi idim; senin kahrından kargaya döndüm.	\
**K.**Ben de seni aldığım vakit aslan gibi idim : ben de senin kahrını çekmeden şimdi kedi gibi oldum.	\
**K.k**Ne olacak böyle? Her akşam evde kavga, gürültü, patırdı! Komşular bile senin elinden bıktı usandı.	\
**K.**Komşular bana karışmaz; herkes kendi evine karışır.	\
**K.k**Herkes kendi evine karışır amma, böyle her akşam bizim gürültümüzü patırdımızı kimse dinlemez.	\
**K.** Sen karışma! Komşular ne söyliycceklerse bana söylesinler, benim onlara lâfım var.	\
**K.k**Bir değil, iki değil, üç değil her akşam bu eve getirmiş yok, götürmüş yok. eve bir şey almazsın.	\
**K.** Neden almıyorum? Gözüne dizine dursun, nankör karı amma, para ile almıyorum da çalıyorum, yine eve zahire getiriyorum ya	\
**K.k**Ha ha ha hay. Aman, bari bir az güleyim! Hiç de güleceğim yoktu!	Gülmeden çatlamazsam çok şeyi	\
**K.** Çatlıyacağına patla, köpoğlu!	\
**K.k**Sen patla! Musibete bak, uyuz herif!	\
**K.**Sen patlarsan ben de senden kurtulurum. Baksan a! Saçın basmacı faturası gibi on türlü renge girmiş. İhtiyar olmuşsun, tazesine bakalım!\
**K.k**Vay gidi genç ağa vay.Tuzlayım ila kokmıyasın!	\
**K.**Ben lakerda fıçısı mıyım, beni tuzlıyorsun?	\
**K.k**Baksan a! Efendi evlenecekmiş, biz artık ihtiyar olduk, saçımız ağardı.	\
**K.**Yalan mı söylüyorum?	\
**K.k**Derd ü mihnetle ağardı mu-yi ser.	\
**K.** Bana selâm mı söyledi Kör Visal?	\
**K.k**Karagöz, yazık sana verilen emeklere!	\
**K.** Yazık sana da verilen yemeklere.	\
**K.k**Yazıklar olsun. Karagöz, sana! Yedirdiğim içirdiğini insanın başına kakıyorsun.	\
**K.**Yalan mı söylüyorum? Bir oturuşta bir okka ekmek yersin. Bir okka ekmeği bir hafta idare etmeli. Müsrifsin, israf haram.	\
**K.k**..Eğer derd-i derunum söylesem hep	\
Figan eyler kalem, ağlar mürekkep"	\
fehvasınca senin kahrını çekeceğime keşki çekmiyeydim! Ne talihsız başım varmış!	\
**K.**Benim de öyle. Seni aldığım için ne talihsiz başım varmış!	\
**K.k**Herif, ben şimdensora senin ile oturmam.	\
**K.** öyle ise, uğurlar ola! Ben de senden bıktım usandım! Bir parça edeyim mola!	\
**K.k**Ben de gidiyorum.	\
**K.**Kapılar küşade! — Ulan, sahiden gitti karı!	\
(Perdeye gelir).Ulan, karı gitti, biz kaldık bekâr! Ben şimdi evde yalınız ne yapabilirim! Evliliğe alışmışım.	\
\
(Hacivad semaîyi söyhyerek perdeye gelir).	\
On kere dimedim mi sana . . .-	\
**Hacivad.**Karagöz, böyle vakitsiz sokakta ne işin var?	\
**K.**Alı Hacivad, başıma gelenleri sorma!	\
**H.**Hayır ola. bilâder!	\
**K.**Hayrı mayrı kalmadı , bizim kan evden gitti.	\
**H.**Misafirliğe mi gitti?	\
**K.**Hayır, misafirliğe değil	\
**H.**Ya nereye gitti?	\
**K.**Büsbütün gitti	\
**H.**Ne o? ipin ucunu kopardınız?	\
**K.** Öyle oldu.	\
**H.**Sen şimdi nasıl edeceksin yalınız başına evde?	\
**K.**Ben de şaşırdım kaldım ne yapacağımı.	\
**H.**Gel, seni evlendirelim !	\
**K.** Bana münasip bir şey olursa ben de rahat olurum.	\
**H.**Bizim arka sokakta Ekemekcizadelerin kızı var, onu sana uydurayım.	\
**K.** Bana uyduracağına babana uydur!	\
**H.** Canım, öyle değil! Lâkırdıyı ters anlama! O kızı sana alıvereyim olmaz mı?	\
**K.** Olur.	\
**H.**Ben şimdi gider kızın validesi ile görüşürüm.	\
**K.**Hacivad, al da gel!	\
**H.**Mahallebiciden mahallebi mi alıyoruz? Dur bakalım, söz kesilsin!	\
**K.**Kesildikten sora mı alacağız?	\
**H.**Elbette! Bakalım ne diyecekler. Ben gidiyorum.(Gider.)	\
**K.**Hacivad eski baba dostudur!	\
**H.** (içeriden).Açın kapıyı efendim!	\
**Kaynana.** (içeriden),A kızlar, bakın, kim gelmiş?	\
**Zenne.**Efendim, Hacivad Çelebi gedmiş,	\
**Kaynana.** A buyurun, Hacivad Çelebi! Ayağınıza sıcak su mu dökelim yoksa sovuk su mu?	\
**H.**Efendim, ziyarette kusur ediyorsam da duada kusurum yoktur.	\
**K.**Köpoğlu ..duvarda kusurum yok ” diyor.	\
**Ka.** İnşallah eyisiniz?	\
**H.**Teşekkür ederim, efendim. Sizler de eyi misiniz?	\
**K.** Teşekkür ederim efendim, siz de ayı mısınız diyor!	\
**Ka.**Eyiyiz, Hacivad Çelebi.	\
**H.**Hanim kızım ne yapıyor? Eyi midir?	\
**Ka.** Eyilerdir. Sizin hanımınız da eyi midir?	\
**H.**Eyilerdir efendim. Nasıl efendim, kızının bir kısmeti çıkmadı mı?	\
**Ka.** Şimdiki halde hiç kısmetlisi çıkmadı.	\
**H.**Bendeniz ona bir koca buldum.	\
**Ka.**Nasıl, Hacivad Çelebi, bize göre münasip mi?	\
**H.**Efendim, gayet zengin; kızınıza hiç bir şeye sıkıntı çektirmez; bir eli yağda bir eli balda.	\
**K.**Amma uçurdu köpoğlu!	\
**H.** Akdenizde gemileri, Karadenizde çektirmeleri, bağlar bahçeler, gayet zengin!	\
**Ka.**,,Kısmet ise, gelir Hindden Yemenden, kısmet değilse, ne gelir elden?" fehvasınca kısmet ise ne diyelim?	\
**H.**Size göre pek münasip!	\
**Ka.**Hacivad Çelebi, güvey çelebi ârif mıdır zarif midir?	\
**H.**Gideyim de sorayım.(Perdeye gelir.)Karagöz!	\
**K.**Ne var?	\
**H.**Gittim, kaynana hanımla konuştum, razı oluyorlar. Sual ettiler: "Güvey çelebi ârif midir zarif midir?" diyorlar.	\
**K.**Sen de kayana hanıma söyle: Hem arifim hem zarifim.	\
**H.**Peki efendim. (Gider)Baksanız a efendim! Kendilerine sordum,,, Hem arifim hem zarifim" dediler.	\
**Ka.**Onun ârif zarif olduğunu bileyim ki, bir peynir şekerini kırk defa ısırıp kırk birincide bir arusek peştahtanın üstüne komalı.	\
**H.** Başüstüne, gider söylerim.( Perdeye gelir.)Karagöz!	\
**K.**Ne var?	\
**H.** Bak, kaynanan hanım nediyor! ,,0nun ârif zarif olduğunu bileyim ki, bir peynir şekerini kırk defa isirıp kırk birincide anisek peştahtanın üstüne bırakmalı" diyor.	\
**K.**Ondan yana esef etmesin; bir okka şekeri birden yerim.	\
**H.**Demek, yapacaksın?	\
**K.**Elbette.	\
**H.**Ben şimdi gider söylerimi.(Gider.)„Yaparım" diyor.	\
**Ka.**Pek âlâ, damat beyin tüccar olduğunu anladık, kendisinin elişi kendi elinde. Başka bir sanatı yok mudur?	\
**H.**Gider sorarım.(Perdeye gelir.)Karagöz, kaynana hanım diyor ki; "Damad beyin tüccar olduğunu anladık, kendisinin elişi kendi elinde. Başka bir sanatı yok mudur?" diyor.	\
**K.**Beni o kadar sorup sual ediyorlar! Kendilerinin elinde ne sanatı var? Sen onlardan sual et! Benim bir başım yastığa gelirse ne yapacaklar?	\
**H.**Peki, gider anlarım.(Gider içeriden:)Baksanız a efendim !	\
**Ka.** Buyurun Hacivad Çelebi!	\
**H.**Bak, damat bey ne diyor!	\
**Ka.**Ne diyor?	\
**H.**,.Onlar ince elekten kalbırdan eliyorlar, benim sanatımı soruyorlar. Sen onlara sor, onların sanatı nedir? Aceba benim başım yastığa gelirse ne yapacaklar?" diyor.	\
**Ka.**Öyle ise, damat bey hem ârifmiş hem zarifmiş. Sen de ona git söyle: „Benim sanatım Sultan Mehmedde küp dibi bekleyici, baldız hanım da çapak silici,gelin hanım da hamamlardan bohça kaldırıcı". Sen de git güvey çelebiye söyle!	\
**H.**Peki efendim!(Perdeye gelir.)Karagöz bak, kaynana hamın ne diyor!	\
**K.**Ne diyor?	\
**H.**Kaynana hanımın sanatı Sultan Mehmedde küp dibi bekleyici, baldız hanımın da çapak silici, gelin hanımın sanatı da bireh bireh bireh!	\
**K.**Bireh birehçi mi?	\
**H.**Değil efendim, hamamlardan bohça kaldırıcı.	\
**K.**Demek biz soya sopa düşmedik, analağmına düşmüşüz. Hanım uykudan uyandı, sildi çapağın, ..tencere yuvarlandı buldu kapağın"! Benim de elimden gelen elişi: camilerden pabuç çalıcı.	\
**H.**Gideyim söyleyim!(Gider.)Damat beyin sanatı da camilerden pabuç çalıcı.	\
**Ka.**Pek âlâ, sanatın kötüsü olmaz. Damat bey arkasına ne giyor?	\
**H.**Efendini, ne giyecek? Her şey giyer: bazan palto, bazan ceket.bazan pardösü,	\
**Ka.**Bari, hüsne malik bir şey mi?	\
**H.**Evet efendim.	\
**Ka.** Damat bey kara kaşlı, top başlı, sürme gözlü, güzel sözlü, ablak yüzlü, al yanaklı, kirez dudaklı, kara gözlü, kara bıyıklı, top sakallı, orta boylu, güzel huylu olmalı.	\
**H.**Gider söylerim, efendim.(Gider.) 'Damat bey kara kaşlı, top başlı, sürme gözlü, güzel sözlü, ablak yüzlü, al yanaklı, kirez dudaklı, kara gözlü, kara bıyıklı,top sakallı,orta boylu, güzel huylu olmalı’ diyorlar.	\
**K.**Evvelâ tokmak gibi baş, sülük gibi kaş. pirohi gibi kulaklarım, kazma dişlerim, gelin hanıma gece gündüz işlerim, kaynana hanımı da bazan kızarsam şişlerim. Ulan. bunlar esir pazarından köle mi alıyorlar yoksa cariye mi? Erkeğin güzeline çirkinine bakılmaz.	\
**H.**Gider söylerim.(İçeriden:)Baksanıza efendim! Damat bey bak ne diyor :..Erkeğin güzeline çirkinine bakılmaz; huyu güzel olmalı diyor.	\
**Ka.**Pek doğru söylüyor. Şimdi düğün için olacak masarif. Çok bir şey istemez. Eli doyurmuş hiç kimse yoktur-.	\
**H.**Doğru söylüyorsunuz.	\
**Ka.**Şimdi evvelâ bir çorba, sora bir et yemeği, sora pilav zerde. Çorba için un kırk çuval olsa elverir.	\
**H.**Doğru efendim.	\
**Ka.** Koyun: beşyüz tane kıvırcık, üçyüz tane Karaman, ikiyüz tane Dağlıç, yüzelli tane de Malıç.	\
**H.**Evet efendim.	\
**Ka.**Pilâv, zerde için pirinç: yüz gazevi Mısır pirinci, ikiyüz gazevi de Dimyat pirinci.	\
**H.**Pekâlâ.	\
**Ka.**Zerde için şeker: beşyüz. okka, elvermezse yüz kıye bal; zerde için zafrandan yüz kıye.	\
**H.** Gider söylerim.(Perdeye gelir.)Karagöz., bak kaynana hanım ne diyor	\
**K.**Nediyor?	\
**H.** 'Bu alemde eli doyurmuş yoktur' diyor.	\
**K.** Pek doğru.	\
**H.** 'Evvelâ çorba, sora bir et. pilâv zerde' diyor.	\
**K.**Peki.	\
**H.**Kaba yemek, ince yemek değil. Çorba için kırk çuval un.	\
**K.**Fırın mı açıyoruz?	\
**H.**Koyun: beşyüz tane kıvırcık, üçyüz tane Karaman, ikiyüz tane Dağlıç, yüz elli tane Malıç.	\
**K.**Mandıra mı açıyoruz?	\
**H.**Pilâv zerde için pirinç; yüz gazevi Mısır pirinci, ikiyüz gazevi de Dimyat pirinci,	\
**K.** Bunlar imaretlere mi taksim olacak?	\
**H.**Zerde için şeker: yüz okka; eğer elvermezse yüz okka da bal.	\
**K.** Bal için kasavet çekmem, arılar müdürü benim ahbabımdır. Ben ona rica ederim, ne kadar arı varsa gelsin kaynananın ağzına sıçsın .	\
**H.**Zerde için yüz okka da zafran.	\
**K.**Akdenizle Karadeniz! sarıya mı boyayacağız? Daha başka istedikleri var mı anlayım!	\
**H.** (içeriden)."Peki" dediler. Daha başka bir şey var mı eksik gedik	\
**Ka.** Paça için iki bin ayak; kaymak: yüz lenger de kaymak.	\
**H.** (gelir).Karagöz, paça için iki bin ayak.	\
**K.** Bizim kaynana hanıma bir muhkem dayak! Çıldırmış kaltak!	\
**H.**Yüz lenger de kaymak.	\
**K.** Onun için de sıkıntı çekmesinler, gece gündüz kayarım.	\
**H.**Gideyim söyleyeyim. (Gider.)Baksanız a efendim, onlar da olacak.	\
**Ka.**Bak. Hacivad Çelebi, bir kere biz kendimiz damat beyi görelim.	\
**H.**Demek ki efendim, bendenize emniyetiniz yok?	\
**Ka.**Hayır, Hacivad Çelebi, onun için değil! Öyle arzu ediyorlar.	\
**H.** Pek âlâ efendim. Şeyh Küşteri Meydanında görebilirsiniz. Bendeniz gider kendisine malûmat vereyim.(Perdeye gelir.)Karagöz seni gelip görecekler; sakın ha, bir koz kırma!	\
**K.** Koz kırmam. üstüne giderim. Ulan, benim nemi görecekler?	\
**H.**Ben gidiyorum, şimdi gelecekler.(Gider.)	\
(Şarkı ile Zenneler geliyor.)	\
\
Şarkı Saba.	\
\
Nigâh-ı mestine canlar dayanmaz.	\
Uyanmaz uykudan canan, uyanmaz.	\
Bu naz u işveden aslâ usanmaz.	\
Nakarat:Sabah olduğuna gûya inanmaz.	\
Uyanmaz uykudan canan, uyanmaz.	\
Sabah geysuların itmiş perişan.	\
Gül olmuş zir-i sünbülden nümayan, \
Güneş veçhine olmuşken zerefşan.	\
Eyzan.	\
\
**Kaynana.**Kızlar, gele gele geldik buracığa, daha gönlümüz nereciğe?	\
**Zenneler.**Siz önde kösemen, biz arkada eli bağlı kuzu.	\
**K.**Pek büyük kaynana hanımın hotozu.	\
**İkinci Zenne.** Aceba damat beyin kahvesi hangisi?	\
**Üçüncü Zenne.**Hacivad Çelebi "Şeyh Küşteri Meydanında" dedi.	\
**Birinci Zenne.**Acaba şu duran olmasın?	\
**2.inci Z.**Bir kere sorarız.	\
**3.inci Z.**Baksanız a, efendim!	\
**K.**Buyurun, ne istiyorsunuz?	\
**1.inci Z.**Burada bir Karagöz Bey varmış, onu bilir misiniz?	\
**K.**Onu ne yapacaksınız?	\
**2.inci Z.**Kızımız var da ona vereceğiz.	\
**K.**Ona vereceksiniz amma, o eyi adam değildir.	\
**3.inci Z.**Eyi olmasın, biz de pek eyi adam değiliz.	\
**1.inci Z.**Peki, bunun fenalığı nedir?	\
**K.**Hırsızdır.	\
**2.inci Z.**Hırsızsa fena değil ya. Çalar çalar bize getirir.	\
**K.** Alâ. Yüzsüzdür namussuzdur.	\
**3.inci Z.**Biz de aşüfteyiz, ne ziyanı var?	\
**K.**Biz suya düşmemişiz, Balatın lâğımına düşmüşüz!	\
**1.inci Z.**Daha başka nesi var?	\
**K.** Başka illeti de vardır.	\
**2.inci Z.**Ne illeti var?	\
**K.** Efendim, illeti illet-İ müzmine-i zemim.	\
**3.inci Z.**Onun ziyanı yok: onu kibar illeti derler,	\
**K.**Ne olsa, bunların makbulü!	\
**2.inci Z.**Peki, daha nesi var?	\
**K.**Soyu sopu uygunsuz.	\
**2.inci Z.** Soyundan sopundan bize ne?	\
**K.**Her gece Beyoğlunda gezer.	\
**3.inci Z.**Biz de her sokakta gezeriz.	\
**K.**Âlâ. Yankesicidir.	\
**1.inci Z.**Fenamı? Pekâlâ san’at!	\
**K.** Hamamlardan çıkmaz.	\
**2.inci Z.**Temiz temiz yıkanır.	\
**K.** Mahbup-dosttur.	\
**3.inci Z.**Biz de zendost.3	\
**K.** Haftada bir geceye eve gelir ya gelmez.	\
**1.inci Z.**Biz de ayda bir kere evde kalırız ya kalmayız,\
**K.** Ne olsa makbul! Daha bir soracağınız var mı?	\
**2.inci Z.**Hayır, bir soracağımız yok. Haydi, kızlar, gidelim!	\
**3.inci Z.**Haydi gidelim ala ala hey! (Gider.)	\
**K.**Doğrusu ya: Hacivadın bulduğu kız çok eyi,	\
**H.** (gelir).Nasıl, Karagöz, bir pot kırmadın ya!	\
**K.**Onlar beni tanımadılar, bana sordular, ben de zemmettim; bir insan kendini metheder mi?	\
**H.**Doğru. Karagöz. Bir kere de onlarla görüşeyim!(Gider.) Nasıl buldunuz efendim, damat beyi?	\
**Kaynana (içeriden).** Aferin, Hacivad Çelebi! Ayol, benim kızımın başını ateşe mi yakacaksın?	\
**H.**Neden efendim?	\
**Ka.**Neden olacak? Her külli kusur güvey çelebide mevcut.	\
**H.**Efendim, siz kendisine <. . >'’ Bana diyor ki ,,Hiç bir insan kendini metheder mi?” diyor, „ben de zemmettim” diyor.	\
**Ka.**Öyle ise, ârifmiş. Düğün tedariki görülsün, düğüne bugünden itibaren mübaşeret edelim!	\
**H.**Başüstüne efendim. Ben de şimdi haber veririm.(Perdeye gelir.)Bana baksan a, Karagöz; kendilerini gördüm konuştum. Sizin söylediğiniz şeyler hoşlarına gitti. ”Bir insan kendim methetmez diyor", dedim.”Bugünden itibaren düğüne başlansın!” diyor.	\
**K.** ”Kocakarılar teknede hamur yoğurur, gör ki analar ne doğurur!" Şimdi ne kadar çeyiz takımı varsa göndereceğim.(Giderler)	\
\
(Şarkı ile Karagözün tekmil çeyiz takımı gelin evine gider.)	\
\
Şarkı Hicaz.	\
\
Niçin a sevdiğim, niçin ...	\
(1inçi: Karagözün çiçek takımları, 2.inci: sahan ve yemek lakımları, 3.incii: sair şeyler, 4üncü: koyunları, 5inci: keçileri. 6ıncı: develeri, 7 inci: inekleri, 8inci: domuzları, 9uncu: eşekleri. 10uncu: atları, 11inci: maymunları, 12inci: ayıları, 13üncü: Karagözün akrabaları, 14üncü: gelin arabaları. Giderler, gelini alırlar. Karagözün evine getirirlerken Hacivadla Karagöz gelirler, gelini arabadan çıkarırlar. H. gider.)	\
**K.**Ulan, bu nasıl gelin böyle?	\
**H.** (içeriden).'Kadınını, bana bîr şivecik!' de!	\
**K.** Kadınım, bana bir şivecik ’	\
**Gelin.** Okumu attım havaya,	\
Geldi düştü tavaya.\
Tef çalın kızlar tef çalın vay! — Anne, benim çişim var!	\
**K.**Hacivad, ne buyurursun buna? Çişi varmış!	\
**H.**Yanlış anladın. ..Benim kocaya varacak vaktim değil, anne . benim işim var" diyor.	\
**K.**Çişim — işim: eyi uydurdu köpoğlu.	\
**H.**Söyle: 'Kadınım, bana bir şivecık' daha!	\
**K.**Kadınım. bana bir şivecik	\
**Gelin.** Balığı koydum tavaya. Uçtu gitti havaya.	\
Tef çalın kızlar, tef çalın, vay! Tef çalın, kızlar, tef çalın vay! — Anne, benim kakam var.	\
**K.** Hacivad, buna ne buyurursun? ..Anne, benim kakam var" diyor.	\
**H.**Değil efendim! ..Benim kocaya varacak vaktim değil, benim tasam var" diyor.	\
**K.** Tasam—kakam: Eyi uydurdu.	\
**H.**Canım. Karagöz, yüz görümlüğünü ver de yüzünü aç!	\
**K.**Al şu yüzüğü, parmağına tak, kaldır nikahını!(Açar, görür görmez kaçar.)Ulan, bu ne surat? Suratına maske takmış gibi!	\
**Gelin.** bAman gocacığım, gözlerim kararıyor, goğlum bulanıyor, garnım gümbür gümbür ediyor.	\
**K.**Hacivad. aşağıya gel!	\
**H.** (gelir).Hayır ola, Karagöz.!	\
**K.** Bak, ne diyor, işit!	\
**Gelin.**Aman gocacığım, ağzım sulanıyor, goğlum bulanıyor, gamım gümbür gümbür ediyor.	\
**H.**Karagöz, bu gebe.	\
**K.** Kimden?	\
**H.**Kimden olacak? Senden!	\
**K.**Utan, ben şimdi duvağım yeni açtım	\
**H.** Yo, Karagöz! Elin kızına iftira etme! Tamam sen bunu alalı dokuz ay on gün oluyor.	\
**K.**Demek ki aylar beş dakka?	\
**H.**Şimdi hesap edelim.	\
**K.**Hesap edelim.	\
**H.**Altımızdaki ay: bir, üstümüzdeki ay: iki, arkamızdaki ay: üç. önümüzdeki ay: dört, gelecek ay: beş, çıkacak ay: altı, çıkmış ay: yedi, yine çıkacak ay: sekiz, çıkan ay: dokuz. Şimdi bugün de tamam ayın onu: tamam dokuz ay on gün oluyor sen bu kızı alalı.	\
**K.**Kızı deme, kadın ninemi de!	\
**H.**Karagöz, sen şimdi gidersin arka sokakta üç numaralı hanede ebe hanım vardır, al da gel!	\
**K.** Peki, gideyim!(Gider.)	\
\
( Şarkı ile Karagöz Ebe han tın gelirler.)	\
Şarkı	\
\
Ey çulha kızı, çulha kızı, 
Gördünüz mü bendenizi? 
Gücendirdün ben de sizi.	\
Nakarat:Gördünüz mü bendenizi?	\
\
**H.**Karagöz, bunu nerede buldun?	\
**K.**Şurada süprüntülükte eşiniyormuş, ben de aldım,	\
**H.**Buna adla sanla Sağırsığır Ebe derler, lâkırdı anlamaz.	\
**Gelin.** Aman, kocacığım, ölüyorum!	\
**H.**.Karagöz, ebeyi önüne doğru getir!	\
**K.**Ebe kadın, ileri arş! (Kulağına bağırır:) Ebe kadın! Bir kadın var, doğuracak.	\
**Ebe (makam ile).** Kaç avret var boğulacak?(Mükerrer).	\
**K.** (kulağına bağırır).Bir kadın hamlini vaz' edecek!	\
**Ebe (makam ile).** Hangi kürsüde va‘z edecek?	\
**H.**Karagöz, ileri sür şunu!	\
**K.**(ebeyi gelinin yanına getirir).Haydi bakalım, ebe hanım!	\
**Ebe.** Ha kızım, gayret et!	\
**Gelin.** Aman ebecüğüm. ölüyorum!(Çocuk doğar.)	\
**Ebe.** Al bakalım. Karagöz, oğlunu!	\
**H.**Haydi, siz içeri gidin!	\
**Gelin.** Kocacığım, kime görüneyim?	\
**K.** Soy da sop da, bana görünme de kime görünürsen görün!	\
(Hepsi giderler, Karagöz ile cocuk kalır.)	\
**Çocuk.** Baba!	\
**K.**Vay köpoğlu! Lâkırdı ediyor! Ulan, ne var?	\
**Çocuk.** Baba, beni dandini!	\
**K (kucağına alır).** Dandini dandini hopla, oğlum, hopla!	\
**Ç.** Baba!	\
**K.** Ne var?	\
**Ç.** O senin başındaki ?	\
**K.**Işkırlak.	\
**Ç.**  Onun altındaki?	\
**K.** Kafam.	\
**Ç.** Altındaki?	\
**K.** Kaşım, gözüm, burnum.	\
**Ç.** Alt yanındaki?	\
**K.** Ağzım.	\
**Ç.** Baba, ağzına sıçayım!	\
**K.** Ben de senin suratına sıçayım!	\
**Ç.** Baba, senin karnında ne var?	\
**K.**İşkembe bumbar.	\
**Ç.** İşkembenin içinde ne var?	\
**K.** Bok var.	\
**Ç.**  Sen o boku ne zaman yedin ?	\
**K.**  Anneni aldığım vakit yedim.	\
**Ç.** Baba, sana bir şey söyliyeceğim.	\
**K.** Nedir söyliyeceğin ?	\
**Ç.** Baba, bana bir göt versen e	\
**K.** Sen de bana versen e!	\
**Ç.** Hacivad amca, Hacivad amca!	\
**H.**Ne var, oğlum?	\
**Ç.**  Babam benden göt istedi.	\
**K.**  Ulan, ilk önce benden istedi.	\
**H.** Gel oğlum, ben seni dadılarla dayalarla büyütürüm!	\
**K.**  Ulan, bu kadar çeyizlerim boşuna gitti!	\
(Alt tarafı malûm.)	\
