
# karagozunagaligi


**Hacivad.** (semaiyi söyliyerek perdeye gelir).	\
\
Semai Besle İsfahan	\

O nühüfte gamzelerden bunu kim reca iderdi?	\
Bu nigâh-i aşina’î neden iktiza iderdi?	\
Gice gördüm encümende bün-ü nahl-i narevende	\
Ki rakib ile çemende çelebim safa iderdi.	\
\
Hay Hak!	\
\
(Perde gazelini ahur.)	\
\
Çeşm-i insafa beyaz-i perde hikmet gösterir, \
Mebde’-i icad-i âlemden İşaret gösterir.	\
Pertev-i şems-i hakikatten uyandı şem'ası,	\
Sireti ibretnümadır gerçi suret gösterir.	\
Bu hayal-i cümbüşü seyr eyle zir-i perdeden,\
Ademe bir özge şevk ile meserret gösterir.	\
Hak Şehinşah-i cihanın şevket ü dâratını\
Eylesün payende! Sultanım adalet gösterir.	\
RAŞIDA, durdukça dünya sağ ola Şah-i cihan!\
Sayesinde her kişi halince rahat gösterir.	\
Huzur-u erbab-ı safada . . ,	\
\
(Taganniye başlar).Yâr, bana bir eğlence! Yâr. bana bir eğlence!	\
Eğer an türk-i Şirâzi bedest âred dil-i mârâ,	\
Behâl-î hindüveş bahşem Senıarkand u Buhârârâ!	\
(Karagöz pencereden bakar çekilir, Hacivad yine taganniye başlar.)	\
**Karagöz.**  (pencereden bakar).Kerata, acele etme! Geliyorum aşağıya!	\
**H.**  (yine başlar).Yâr, bana bir eğlence! Yâr, bana bir eğlence!	\
**K.**  (pencereden bakar).Ben sana şimdi aşağıya gelirsem eğlenceyi meylenceyi gösteririm!\
(H. yine taganniye başlar, Karagöz pencereden atlarken ayağı çamaşır ipine dolaşır, başlar sallanmaya.)Tü! Allah müstahakkını versin!	\
**H.** Acayip! Karagöz galiba kapan kurmuş, ayı gibi bir sansar tutulmuş!	\
**K.** Ayı senin baban!	\
**H.** Ne oldun. Karagöz?	\
**K.**  Ne olacak, elinin körü! Görmüyor musun? Sana lâf anlatmak için çabuk aşağı geleceğim diyerek acele ile ayağım çamaşır ipine dolaştı.	\
**H.** Elbette bir ettiğin var ki ayağına dolaştı.	\
**K.**  Kerata, benden intikam mı alıyorsun?	\
**H.**  Ne olacak şimdi?	\
**K.**  Ne olacak? Manav dükkânında asılan hevenk üzümü gibi asıldım kaldım.	\
**H.** "Yâr bana bir eğlence!"	\
**K.**  Eğleniyor musun. Hacivad?	\
**H.** Münasebet?	\
**K.**  Ulan, münasebeti filân var mı? İşte karşında baş aşağı sallanıp dururken "bana bir eğlence" demenin mânası var mı? Ah, Hacivad, ah! Senin bu gürültün patırdın başıma bu belâyı getirdi. Sanki birisi Hacivadın boğazını sıkıyormuş gibi!	\
**H.**  "Yâr, bana bir eğlence! Yâr. bana bir eğlence!"	\
**K.** Hacivad, münasebetsizliğin sırası değil ; şimdi eğlenceyi bırak ta beni kurtar!	\
**H.** Kel aktar mı?	\
**K.**  Hayır, çolak muhtar! Kuzum, Hacivad, beni kurtar!	\
**H.** Aman efendim, ben seni nasıl tahlis edebilirim?	\
**K.** Gördün mü ettiği haltı? "Ben seni nasıl tahlis edebilirim" diyor! Ben bir kurtulsam sana yapacağımı bilirim. İş kurtulmada.\
**H.** Ne dedin?	\
**K.**  Sora anlarsın ne dediğimi,	\
**H.** Adım mı atlıyacaksın?	\
**K.** Bir kurtulsam köşe kapmaca oynayacağım. Canım Hacivad, şakayı bırak da şuradan beni kurtar!	\
**H.** Canım, ben nasıl kurturayım? Sen yüksektesin, ben alçakta. Sen evdekilere seslen, onlar İpin ucunu koyuversinler!	\
**K.** Ulan, bunak herif! Bizim evde kiler var mı?	\
**H.** Canım, sizin evde taife-i nisadan kimse yok mu?	\
**K.** Bizim evde davulcu esnafından kimse yok.	\
**H.** Camın, sizin odabaşıyok mu?	\
**K.**  Hacivad. ben handa oturmuyorum, kendi evimde oturuyorum.	\
**H.** Anlamadın, bîlâder. Sizân evde kaşık düşmanı  yok mu?	\
**K.**  Bereket versin, Hacivad. bizim komşunun tekir kedisine! Evde hiç bir tane bırakmadı.	\
**H.** Neyi bırakmadı?	\
**K.**  Kaşık düşmanlarını.	\
**H.** Kaşık düşmanı dediğin kim oluyor?	\
**K.**  Kim olacak? Fareler,	\
**H.** Değil efendim. Sizin evde bacı yok mu?	\
**K.** Ulan, budala herif! Bir karıya ne kadar isim taktın!	\
**H.**  Ona seslen de ipi koyuversin!	\
**K.**  Eyi hatırıma getirdin. — Abla!	\
**Karısı.** (içeriden)Ne var. herif?	\
**K.**  Kuzum ablacığım. acele İle çıkarken çamaşır ipi ayağıma dolaştı asıldım.	\
**K.k.**  (içeriden).Çamaşırcının kızı ile basıldın mı?	\
**K.** Al lâkırdı anlıyanın birini daha!	\
**K.k.** Memnun oldum, pek âlâ olmuş! Belândır, çek! Hem bana seslenme, ben çocuğun uyku ilâcını yedirdim!(Makam ile:)	\
Uyusun da oğlum ninni.	\
Büyüsün de oğlum ninni!	\
**K.** Uydurduk! Kuzum Hacivad. Sen bari lâkırdı anla! Nasıl edeceğiz?	\
**H.** "Yâr. bana bir eğlence! Yâr, bana bîr eğlence!"	\
**K.** Şimdi başlıyacağım senin eğlencene! Üzme beni!	\
**H.** Canım, Karagöz, ne kadar telâş ediyorsun!	\
**K.** Telâşı var mı? Baş aşağı durmadan ciğerlerim ağzıma geliyor! Ah, bir aşağıya insem!	\
**H.** Zaten ben orasını biliyorum ; sen kurtulursan, beni bir temiz döversin.	\
**K.** Tövbeler tövbesi! Yalınız tekme vururum.	\
**H.** Ne dedin?	\
**K.** "Teknede hamur yoğururum" dedim.	\
**H.** Karagöz, inanayım mı?	\
**K.** İster inan, ister inanma!	\
**H.** Pek inanamıyorum, bilâder.	\
**K.** Eşek sudan gelinceye kadar döveceğim.	\
**H.** Eşekle Silihtara mı gideceksin?	\
**K.** Bak, Silihtara mı gideceğim yoksa Kâthaneye mi gideceğim anlarsın.	\
**H.** Ben eve gidiyorum. Karagöz.	\
**K.** Ne? Aman, Hacivad! Rica ederim, benim çareme bak!	\
**H.** Dur bakayım! (İpi çözer. K, H.ın arkasına biner.)insene aşağy!	\
**K.** Bir az şöylece durayım.	\
**H.** Aman, Karagöz, omuzum çöktü, in aşağı!	\
**K.** (H.ın omuzunda» iner.).Güç belâ kurtulduk!	\
**H.** Karagöz, geçmiş olsun!	\
**K.** Allah müstahakkım versin!(Vurur.)	\
**H.** Eyiliğe kemlik!	\
**K.** Meşhur meseldir: "Her kime edersen eyilik, onda hazırdır kemlik."	\
(Vurur, H. gider.)	\
Sen gidersin de ben durur mıyım? Bende gideyim idgâha dolaba dilber seyrine! Bakalım aine-i devran ne suret gösterir!(Gider.)	\
(Semaiile Acem geliyor.)	\
Semaî Uşşak2	\
\
Haylı dem zincir i zülf-i aşkının meftuniyem . . .	\
(Semaî bittikten sora Acem gazel söyler:)	\
Kanda varsa âşık-ı biçare cananın arar.	\
(Acem gazeli bitirir, Hacivad semaî ile gelir.)	\
Semaî Uşşak.\
\
Hoş geldi bana meykedenin ab u havası!	\
Vallahi güzel yerde yapılmış yıkılası!	\
Meddah olalı çeşm-i gazâlânına BAKİ,\
Öğrendi gazel tarzını Rum'un şu arası.	\
(Semai biter. H. Acemle aşinalık eder.)	\
\
**H.** Vay efendim, hoş âmedî, safa âmedi!	\
**Acem.** Hoş bulmuşam, safa bulmuşum, canım baba ha ha ha hay!	\
**K.** (pencereden bakar),,Hoşaf bulmuşum" diyor. Ben de bulsam hoşafı, içerim.	\
**H.** Efendim, böyle ne taraftan âyende. ne tarafa leventlesiniz?	\
**Ac.** Man İrandan® gâlirâm.	\
**H.** Efendim, sebeb-i teşrifiniz ziyaret kasdiyle mi yoksa ticaret maksadiyle mi ?	\
**Ac.** Ela manâ bakh,canım baba! Ticarat gasdile gâlânin gıllığı gıyafâti bela olirdi ha?	\
**H.** Demek kî efendim, ziyaret kasdiyle? geldiniz?	\
**Ac.** Bâli! Mân ki çokh mâlmâkâttar gaştügüzar edanda, . .	\
**H.** Ne tarafları gezdiniz?	\
**Ac.**Diyar-i Horasan.	\
**K.**(pencereden).Diyar-i kireçhane!	\
**Ac.** Diyar-i Khoy.	\
**K.** (pencereden).Ma ma ma ma moyt	\
**Ac.**Diyar-i Tahran.	\
**K.**  (pencerdeden).Diyar-i tarhana!	\
**Ac.** Diyar-i Tiflis.	\
**K.** Hacivad müflis, ben de müflis.!	\
**Ac.** Diyar-i İran.	\
**K.** Diyar-i ayran!	\
**Ac.** Diyar-i Hâmadan.	\
**K.** Diyar-i mum mikrazı şamdan!	\
**H.**Efendim, maskat-ı resiniz Iran mıdır?	\
**Ac.** Bali.	\
**H.**İranda ne isimle yâd olun ursunuz?	\
**Ac.** İranda Haca Sârfirâzın oğli Baba Nukûd deyellâ.	\
**K.**  (pencereden).Hoş geldin. Baba Yoğurt! Kova ile mi teşrif buyurdunuz yoksa torba ile mi?	\
**H.**Defol, Karagöz, oradan!	\
**Ac.**Ela siz dâ mânâ ismüvüzû bağışlasız?	\
**H.** Fenn-i lûbiyatın yektası, meydan şeyhinin merd-i dânâsi, bezm-i irfanın şem-i safası, Bursah Hacı Evhad mimiyle meşhur-u âfakım.	\
**Ac.** Pas ki Hacivad sânsan? Pâs ki Hacivad sânsan?	\
**K.**  (pencereden). Hacivad da sersem, sen de sersem!	\
**Ac.** Yıkhıl deram, galtaban, yıkhıl! derâm.	\
**K.** Neme lâzım benim?	\
**Ac.** Har nâ gadar ziyaret için gâldimsâ dâ, mânim babanım ortağı ölândâ mânim pâdârimin vâfatından sönra galan malların paraların vermiyub nakd yerinâ mânâ mal verdi; haliynân biz dâ mâcbur oldukh o malları satmağa.	\
**H.** Pek doğru söyliyorsunuz. Ne mal getirdinizdi?	\
**Ac.** Min dâva incü.	\
**H.** Evet efendim.	\
**Ac.** Min dâva zümürrüt.	\
**H.** Pek âlâ.	\
**Ac.** Min dâva almas, min dâva yagut, min dâva marcan gâtirdim.\
**H.** Bunların paralarını ne yaptınız?	\
**Ac.** Gızgulâsinin tapasi gadar bir şimşirakh taşiynân değişmişam.	\
**H.** Pek âlâ.	\
**Ac.** Bâlki yââsima galâbâ eylârâm fikriynân Oropanın, Amerikanın, Afrikanın, Asyanın çokh yârlârin gaştügüzar eliyarak tâhfif-i gamma çalışmış isâm dâ, na çara, muvaffakh olammamışam. En nihayât eşitmişâm ki Dar Aliyâ'dâ gıyakh  mâddahlar vardı. Bâlki olar mânim hüznümü izalayâ muvaffakh olur deyârâk Dâr-i Hilafât-i Alîyâyi ziyarât gasdiynân gâlmişâm.	\
**K.** " Ziyan ettim de geldim" diyor. Neden ziyan etmiş?	\
**H.** Yıkıl oradan, Karagöz! O senin tanıdığın adamlardan değil, o İran gülüdür. İran gülü.	\
**K.**  Dikeni burnuna batsın, kerata!	\
**Ac.** Sân mânimnân mezahlanısan ?	\
**K.**  Ulan, seninle alay edersem ne olur?	\
**Ac.**Fârisî mîdânam.	\
**K.**  Kayısı bir tane . İki tane değil, çok!	\
**Ac.** Man ân mûrâm ki dar pâyâm bimâlând,	\
Nâ zânbûrâm ki az nîşâm binâlând.	\
Kucâ mân şukr-i in nîmat guzârâm,	\
Ki zûr-i mârdum-âzâri nâdârâm!	\
**K.**  Hiyâristân u şalgamrâ nihâdend.	\
Meğerçi batlıcan bâşed kemerbend.	\
Zehi turşu u pançar u hiyarım,	\
Fasulya, bakla bustani nedârem.	\
**Ac.** Bir daha söyleyam!	\
**K.**  Söyle bakalım!	\
**Ac.** Khâstâ-i işgâm ki fâryâd-i hâzârâm mîkuşâd,	\
Şâm'-i bâzm-i toubâ âm, bâd-i bâhârâm mîkuşâd.6	\
Mân hâlâk-i dârd-İşgâm sâbr mîgûyâd tabîb,	\
In câhâlât zûdtâr âz hacr-i yaram mikuşâd.	\
**K.**  Hasta-i aşure'em hasret-i hiyârem miküşed.	\
Bakla dârem ki hemîşe enginârem mîküşed 
Taze yaprak dolması ez patlıcan olsun nasib, 
Pek geniş, tepsi börek olsa doyarem, miküşed.	\
**H.** Karagöz, bunlar ne?	\
**K.** Bunlara acizane eş'ar-i uydurmasyon-ı namütenahi tâbir ederler.	\
**Ac.** İştâ, Hacivad Çâlâbi, imdi man sândan çokh rica elârâm ki mâni khoş sözleriynân eğlândirâcakh bir adam bulasan. Ağar o mânim galb-ı ğâmnâkimi fârahnâk edanda mân ana pul verâm, dinar verâm.	\
**H.** Pek âlâ efendim. Demin burada mülâtefe ettiğiniz Karagöz namında bir refikim vardır. Kendisi tuhaflardandır, hattâ, efendim, rivayete nazaran Fatihteki kömürcü develerini bile güldürmüş.	\
**K.**  (içeriden).Vay, mübalâğacı kerata vay!	\
**H.** Buyurun bendehaneye! Bir az istirahat buyurunuz! Bendeniz de kendisini bulayım.	\
(Acem ile Hacivad birlikte Hacivadın evine giderler.	\
Defa Hacivad perdeye gelir. Karagözün kapısını çalar.).Karagöz!	\
**K.** (içeriden).Ne var?	\
**H.** Aşağı gel!	\
**K.** (gelir).Buyurun bakalım!	\
**H.** Demin görüştüğün acemi tanır mısın ?	\
**K.** Hayır, tanımam.	\
**H.** Karagöz, o gayetle zengin İran bezirgânlarından.	\
**K.**  Demek, o herif Yahudi ha?	\
**H.** Bezirgân diye gayet zengin olanlara derler.	\
**K.** Ya?	\
**H.** İşte, Karagözüm, o acemin pederi Irandan Tahrana gelirken vefat etmiş.	\
**K.** Pazardan tarhana getirirken Vefaya mı gitmiş?	\
**H.** Bak habise! Yani esna-yı rahta füc’eten mürd olmuş.	\
**K.**  Ayvansarayda bekçi Kürdü mü bulmuş?	\
**H.** Bak şu münasebetsize! Yani yolda pederi ölmüş.	\
**K.** Ulan, deminden beri böyle söylesen e! E, sora?	\
**H.** Sora, bilâder, Tahrana gitmiş, orada oturamamış.	\
**K.** Buraya mı gelmiş oturmak için?	\
**H.** Nihayet, belki hüznümü izaleye muvaffak olurum diyerek İstanbula gelmiş.	\
**K.** Hasan ağa ile fıstıklı lokum yiyerek Îstanbula mı gelmiş?	\
**H.** Eğlenirim diye Îstanbula gelmiş.	\
**K.** E,sora?	\
**H.** Sorası, Karagözüm, eğer şimdi bu acemin kalb-i gamnâkıni ferahnâk edecek olursan, sana bir çok dinar verecek.	\
**K.** Nasıl, nasıl? Eğer acemin karnabaharını kebab edersem bana enginar mı verecek?	\
**H.** Canım, eğlendirecek olursan sana bir çok lira verecek.	\
**K.** Lira mı verecek? Aman, ayağını öpeyim! Acemi buraya yolla!	\
**H.** Ben şimdi gider yollarım.(Gider. İçeriden:)Baksanız a, efendim, size söylediğim adam Şeyh Küşteri meydanında teşrifinize muntazır.	\
**Ac.** (içeriden).Mân şimdi gedâr bularam.(Perdeye gelir.)	\
**Karagös.** Vay efendim! Akşamı şerifler hayırlar olsun! . . .(Acem cenah vermez.)Efendim, evet! . . . Teşrifi teşerrüfünüzden müteşerrif oldum! . . . Kulunuz bu gibi şeyleri iltizampezir buyururum . .(K. Hacivada gider:)Hacivad, bu herif dilsiz, lâkırdı etmiyor.	\
**H.**  (içeriden).Sen ona patı çak-!	\
**K.**  (perdeye gelir).Vay efendim!(Aceme vurur.)	\
**Ac.** Pas kİ biyö Pas ki biyö!	\
**K.**  (içen gelir).Hacivad, bu herifin evden çıkarken karnını doyurmak yok mu ?	\
**H.**  Neden?	\
**K.**  Neden olacak? Herif vurur vurmaz "Pestil pilaf. pestil pilaf" diye bağırmaya başladı.	\
**H.** Hay Allah müstahakkını versin? Canım, git, de ki "Hacivadın tarif et tiği adam benim" de!	\
**K.** (gelir).Baksanız a, efendim! Hacivadın tarife defterleri varmış, verin!\
**Ac.** Pas ki man mugayyid miyâm, mugayyid miyâm?	\
**K.** Ben mümeyyiz miyim?(İçeriden:)Hacivad, dedim ki "Hacivadın tarife defterleri varmış" dedim; "pes kı men mugayyid miyem. pes ki men mugayyid miyem" dedi.	\
**H.** Canım, öyle değil! ""Hacivad Çelebinin tarif ettiği Karagöz benim de"	\
**K.** (perdeye gelir).Baksan a, acem baba! Hacivad Çelebinin tahin yediği çanağı verin!	\
**Ac.**Pas ki man tahin yemânâm! Pas kı mân tahin yemânâm!	\
**K.**  Tahin yemezsen ziftin kökünü ye!(İçeriden.)Yine anlatamadık, Hacivad!	\
**H.** Kalın kafalı adamsın ! ..Hacivadın tarif ettiği adam benim" !	\
**K.**Sen isen, gitsen e!	\
**H.**Benim dediğim gibi söyle!	\
**K.**Peki.(Gelir.)Hacivad Çelebinin teravihe gittiği feneri verin!	\
**Ac.** Pas ki mim taravihâ getmanâm! Pas ki man târaviha getmanâm!	\
**K.**  (içeriden).Hacivad, ”ben teravihe gitmenem” diyor.	\
**H.**  (içeriden).Sen ne dedin?	\
**K.** (içeriden).”Hacivad Çelebinin teravihe gittiği feneri verin" dedim.	\
**H.** Vay, kalın kafalı herif vay! Haydi git, de ki ”Hacivadın gönderdiği sade Karagöz benim" de!	\
**K.** Piki.(Perdeye gelir.)Hacivadın gönderdiği sade Karagöz benim. Etli peynirli isterseniz fırından daha çıkmamış,	\
**Ac.** Pas ki mân sadâ dâ istâmâm, kıymalı da istâmâm, peynirli da istâmâm.	\
**K.**  (içeriden).Hacivad, o ne sade istiyor ne de peynirli istiyor, ne de kıymalı.	\
**H.**  (içeriden).Sen ne dedin ona?	\
**K.** (içeriden)."Sade Karagöz benim" dedim.	\
**H.** Haydi git de ki "Hacivad Çelebi bendenizi tarafı âlinize sevk etti" de!	\
**K.** (perdeye gelir).Hacivad Çelebi bendeniz ile Tarabyada zevk etti.	\
**Ac.** Pas ki siz Tarabyada zouk ettinizse mana na? Pas ki siz Tarabyada zouk ettinizse mânâ nâ?	\
**K.** (içeriden).Hacivad, biz buna bir türlü lâkırdı anlatamıyacağız.	\
**H.** Yalınız de ki, sen ona: "Bendeniz Karagöz kulunuzum" de, başka bir şey söyleme!	\
**K.** (perdeye gelir).Efendim, Karagöz kulunuzum.	\
**Ac.** Garagöz sânsan ?	\
**K.**  Karagöz sersem değil, akıllıdır.	\
**Ac.** Ah Garagöz!	\
**K.**  Efendim.	\
**Ac.** Yakhdı mâni khub sözlerin, o gara gözlerin.	\
**K.**  Hacivad Acem fikri değiştiriyor galiba!	\
**Ac.** Mânâ bakh, Garagöz! Sân tıbki mânim bir dâvam vardı, ana benzisân; eğil ki binam üstüne!	\
**K.**  Acem baba, kendine gel!	\
**Ac.** Tuhaf bir zatâ benzisân, Garagöz!	\
**K.**  Oldukça tuhaflardanım.	\
**Ac.** Ela bizim İranda bir takhım mâddah kimâsnâlâr hayvan takhlidi yapallardı; sân dâ yapısan?	\
**K.**  Oldukça yaparım.	\
**Ac.** E, na takhlidi yapıan ?	\
**K.** Min gayri haddin ördek gibi öterim.	\
**Ac.** Öt kı görem!	\
**K.**  Vak vak vak vak!	\
**Ac.** Ha ha ha! Tuhaf zatsan, Garagöz! Daha nâ takhlidlâri yapısan?	\
**K.**  Efendim, acizane keçi gibi bağırırım.	\
**Ac.**Bağır ki görem!	\
**K.**  Mâ mâ mâ bâ bâ!	\
**Ac.** Ha ha ha! Mânâ bakh! Keçi gibi bağrışan amma, goyunca da bağrışan?	\
**K.** Onu sizin mahdum bey daha eyi bağırırmış.	\
**Ac.** Eşâkhçâ bağrışan, Garagöz?	\
**K.** Büyük pederin hakkını yemem, zira o daha eyi bağırır diyorlar.	\
**Ac.** Ha ha ha! Bisyâr mâmnun olmuşam, Garagöz, gıyakh zatsan. Al şu min dinarı! İnşallah bir daha galanda daha çokh verirâm!	\
**K.** Eksik olmayınız efendim! Enayiliğinize doymayınız efendim! Yine buyurun! İnşallah ben sizi güldürmekten hiç geri durmam! (Acem gider.)Oğurlar ola! Ben de eve gideyim.	\
\
(K. evine gelir, kapıyı çalar, karısı kapıyı açar.)	\
**Karagözün karısı.** Herif, nerede kaldın?	\
**K.** Ağzını topla, kan! Herif kim?	\
**K.k.** A üstüme ey ilik sağlık! Herif değil de nesin? Karı mısın?	\
**K.** Sora pişman olacaksın, karı!	\
**K.k.** Bu akşam avurt ediyorsun; avurdun kime?	\
**K.** Bak şu paralara!	\
**K.k.** Ah kocacığım da kocacığım! Benim top sakallı kocacığım !	\
**K.** Demin herif idik, şimdi top sakallı kocacığın ha! Hey gidi para hey’\
**K.k.** Efendim, emret, kocacığım! Ne istersin?	\
**K.**  Vay köpoğlu karıcığım, anam babam paracığım! Benim bir takım şık elbiselerim vardı, nerede onlar? Getir hana!	\
**K.k.** Baş üstüne, kocacığım!	\
**K.**  Karı ne kadar inceliyor, şimdi kopacak	\
**K.k.** Bohçasiyle beraber getirdim.	\
**K.** Beni giydirsen e! Emrediyorum!	\
**K.k.** Bâş üstüne, efendim!	\
**K.** Frenk gömleğim nerede?	\
**K.k.** Hazır efendim!	\
**K.**  Hani kerevetim?	\
**K.k.** Gıravat burada, buyurun!	\
**K.** Kerevetimi bağla!	\
**K.k.** Bağladım efendim.	\
**K.** Bizim karı şimdi kopacak, o derece inceliyor. Pantolonumu giydir!	\
**K.k.** Giyiniz efendim!	\
**K.** Hani yeleğim?	\
**K.k.** Burada yelek, kocacığım!	\
**K.**  Hani ceket?	\
**K.k.** Burada, giyin efendim!	\
**K.** Eldivenlerim yok mu?	\
**K.k.** Eldivenleriniz yok. Yenisini alırsınız.	\
**K.**  Fotinlerimi lostra et!	\
**K.k.** Boya yok efendim.	\
**K.**  Tencere karesiyle boya!	\
**K.k.** Aman efendim! Hiç tencere karesiyle boyanır mı? Emrederseniz, yirmi kutu boya gelir.	\
**K.** Sen eskiden rastık çekerdin, hiç yok mu?	\
**K.k.** Rastıkla fotin boyanır mı?	\
**K.** Ben sokakta boyacı bulurum.	\
**K.k.** Kocacığım, sen giyindin kuşandın; benim üstüme başıma yapmıyacakımsın?	\
**K.** Bayram gelsin de istediğinden âlâsını üstüne başına yaparım.	\
**K.k.** Sen böyle nereye gidiyorsun, kocacığım?	\
**K.** Sen kapının önüne bir sandalye koy!	\
**K.k.** Baş(perdeye sandalye konur)üstüne!	\
**K.** Bu akşam ağa oklum, Karagözlükten çıktım. Abla, bana baksan a!	\
**K.k.** Buyurun ağacığım!	\
**K.** Sakın boşboğazlık edip de komşulara söyleme "kocam ağa oldu" diye!	\
**K.k.** Neme lâzım benim?	\
(Karagöz şarkı ile perdeye gelir.)	\
Şarkı Uşşak.	\
\
Bir elinde şişe, canım, bir elinde ma meze.	\
Neden lâyık olduk amma bu sitem söze?	\
Eğer teşrif edersen, buyurun bize!	\
Nakarat: Üzme beni, gel. a canını, üzme beni, gel!	\
\
**Karagöz.** .Lâ teşbih ve lâ temsil, bu akşam perdenin ağası oldum, sahte mirasyedi. Şimdi bir az ağalık meşkedelim!	\
**Karagözün karısı (içeriden).** Bana baksan a, Hürmüz hanım hu!	\
**Hürmüz hanım (içeriden).**Ne var, kardeşim?	\
**K.k.** Duydun mu?	\
**H.**  Hayır ola!	\
**K.k.** Bizim herif bu akşam ağa oklu.	\
**H.**  Yakışır ya! Deveye kazazlık! — Dürdane hanım hu	\
**Dürdane (içeriden).** Ne var, kardeşim?	\
**H.**  Duydun mu?	\
**D.**Hayır ola!	\
**H.** Karagöz bu akşam ağa olmuş,	\
**D.**Yakışır ya! Kel başa şimşir tarak! — Nazlı hanım hu!	\
**Nazlı hanım (içeriden).** Ne istiyorsun, kardeşim?	\
**D.**Duydun mu?	\
**K.**  Hayır ola!	\
**D.**Karagöz bu akşam ağa olmuş.	\
**N.** Vay musibet vay!	\
**Karagöz.** .Bana baksan a. abla!	\
**K.k.**  (içeriden).Nedir, kocacığım ?	\
**K.** Kimseye bir şey söyleme diye tenbîh ettim.	\
**K.k.**  (içeriden).Ben kimseye bîr şey söylemedim, yalınız Hürmüz hanıma söyledim. Hürmüz hanım da Dürdane hanıma söyledi, Dürdane hanım da Nazlı hanıma söyledi.	\
**K.** Öyle yapacağınıza Sabah gazetesine bir ilân vereydin! Vay boşboğaz köpoğlu vay! — Şimdi bir simafir gelirse ne yapacağız? Vay efendim! Buyursunlar! Şöyle ikbal buyurun! Kulunuz bu gibi şeyleri incimad ederim; pek kızarsam da bırakır giderim. Efendim, vakti şerifleriniz şerif olsun! Gazete mustakla buyuruyor musunuz? Kulunuz geçen gün Direklerarasında çaycıda oturuyordum. Bir de ne göreyim? Tekmil alacaklılarımı etrafımda görmeyim mi? Bakkal kulunuz, kasap kulunuz,, zerzevatçı kulunuz. Vay efendim, buyursunlar şu tarafa! Tenavül buyurun! Zatı âlimi çoktan beri gördüğünüz yoktur efendim. Ne âlemdesiniz? Bendenize sorarsanız daima süpürge yapmakla meşgulüm. Geçenlerdeki vukuatı duydunuz mu? Bendenizin malûm-u âlim oldu. Bir sivri sinek yerden bir karıncayı almış yuvasına götürürken karınca yere düşerken bir ihtiyar zatın başına düşer düşmez beyni patlamış. Böyle şeyler olağandır efendim!	\
(Hacivad gelir.)Vay, Hacivad geldi!	\
**H.** Görür müsün? Ehl-i zevkın biri kapının önüne iskemle atarak etrafı temaşa ediyor! Galiba müstecir olmalı; yoksa konağı yeni iştira etmiş. Her ne ise mademki komşu olmuş, gideyim de arz-ı ihlâs deyim ... Efendim! Vakti şerifler hayır olsun! inşallah keyf-i âliniz eyidir! Galiba bu semte yeni nakil buyuruldu?	\
**K.** Haydi, defol, biedep! Artık vermeden derun-u kisemi biderun olarak tahliye ettiniz! Veremem, efendim!	\
**H.** Aman efendim,merhamet buyurun! Bendeniz güruh-u se'eleden değilimi\
**K.**Hâlâ kirli köseleden değilim diyor! işine git! Şimdi hiddetim rutubet-i hava ile incîmad edecektir ha!	\
**H.** Efendim, vakıa bendenizi tanımazsınız, lâkin züll-i sual için gelmedim. \
**K.**. Ey hâlâ söylüyor! Ulan, zil çalmak için gelmedin de burada ne işin var?\
**H.** İnayet buyurun! Bendeniz kâşane-i âlinize mücavirim, hele bu mahallenin kudemasındanım.	\
**K.** Ulan, seni kim davet etti de kâtçı Veli ağaya misafir olmuyorsun?	\
**H.** öyle değil efendim! Yani size pek yakın komşuyum.— Lâkin benim bu sese aşinalığım var ... Dur bakalım! Vay. Karagöz, bu ne hal?	\
**K.**  Vay, kerata tanıdı! Halimin nesi var? Sorma, Hacivad, ağa oldum,ağa!	\
**H.** Karagöz Ağa, hakikaten pek memnun oldum, lâkin böyle olmaz. Evvelâ bir daire tanzim etmeli, her ne hal ise, şimdi bana hizmet yok mu? Yani beni bir işte kullanmıyacak mısın?	\
**K.**  Ulan, haydi, seni ayvaz yaptım,	\
**H.** Aman efendim, bendeniz alîlül-vücudum, ayvazlık yapamam.	\
**K.** Orası da var ya! Lâkin ne hizmet bulmalı? Haydi reis yamağı ol!	\
**H.** Ciğerparem, kulunuz beygir ilminden anlamam; hem beni böyle hidemat-i süfliyeye lâyık görür müsün?	\
**K.** Amma uzattın ha! Baba, seni ne yapmalı?	\
**H.** Bak. Karagöz, sana hepsinden evvel bir kâhja-yı umur lâzım; bu iş için de benden eyi adam bulamazsın.	\
**K.**  Haydi, seni kâhya yaptım, Lâkin bana karışma! Ayda bana ne vereceksin bakayım?	\
**H.** Canım, lâtifeyi bırak ! Bu kıyafetle olmaz, gideyim ben de elbisemi değiştireyim de geleyim.	\
**K.** Haydi bakalım! Çabuk ol, zira konak için mübayaat-i bilüzum var.	\
**H.** Sen merak etme! Şimdi gelirini.(Gider, yine gelir.)	\
**K.** Vay anasını. . .! Son moda bir bey geliyor! Buna nasıl meram anlatmalı? Efendim, buyursunlar! Kudumunuzla tekaddüm buyurmuş oldunuz!	\
**H.** Karagöz, halimi beğendin mi?	\
**K.** Vay Hacı Cavcav! Allah bilir, tanıyamadım! Ulan, sen adeta deste kaçgını bir bey olmuşsun!	\
**H.** Elbette saye-i velinimette her kesin bir kat elbisesi bulunur.	\
**K.**  Ulan, aferim! Boğazı kendinden kâhya; lâkin bilmiş ol ki bire beş yazmamalı!	\
**H.** Canım, şimdi bunları bırak da konak için lâzım olan şeylere bakalım. Evvelievvel bir hizmetkâr lâzım.(Hacivad gider.)	\
**K.** Çabuk gönder, Hacivad!	\
(Şarkı ile Çelebi gelir.)	\
\
Şarkı Hicaz.	\
Aşkınla sine dağlaram,	\
Gülgune yare bağlaram,\
Bunca zemandır ağlaram.	\
Nakarat:Eşk-i terim silmez misin?	\
Mecburinem, bilmez misin?	\
Geldikçe sen, ey gülnihal.\
Ben ağlaram bülbül misal.	\
Alıp eline destimal	\
Eşk-i terim silmez misin?	\
Mecburinem, bilmez misin?	\
**Çelebi.**Hacivadin tarif ettiği herif bu olmalı. Dur, bir az eğleneyim! Efendim, affedersiniz, zatı âlinizden bir şey İstifsar edeceğim.	\
**K.** Bir şey mi istimal edeceksin? Bana ne?	\
**Ç.**  Arzedemedim efendim. Bir zat-ı âli kadri arıyorum.	\
**K.** Mademki Kadri beyi arıyorsun, mahalle kahvesinden sor!	\
**Ç.** Anlatamadım, efendim. Bir şey sormak isterim.	\
**K.**  Boşuna yormak mı istersin? Ağırca yük vermeli.	\
**Ç.** Hayır efendim! Buralarda bir Karagöz bey efendi varmış, onu görmek isterim.	\
**K.** (kendi kendine).Ha, oğlan beni anyor ...!O Karagöz bey efendiyi ne yapacaksın?	\
**Ç.** Efendim, saika-i kaderim; bendeniz şayan-i merhamet bir haldeyim, Temin-i maişet için hiç bir şeye malik olmadığımdan ırz u namusumla etbaılık ederim.	\
**K.** Çünkü ve mademki ihtiyaç denilen şey istikbal-i münfail oluyor, sözlerinizden bir şey anlıyamadığımdan çar u naçar yine affinize intikal ederim.	\
**Ç.** Efendim, af buyurun! Gerçi pespaye isem de deniyü t-tabı değilim.	\
**K.** Nasıl? Pisboğaz iseniz de değirmende tabip değilmisiniz? O halde fırında tımarcı olunuz!	\
**Ç.** Sözlerim galiba size garip geliyor. Her ne ise, sorduğum beyi tanıyor musunuz?	\
**K.** Karagöz beyi mi ?	\
**Ç.** Evet efendim.	\
**K.** Sen onu niçin arıyorsun sanki?	\
**Ç.** O zatın hizmetinde istihdam olmak için bendenizi Hacivad Çelebi izam etti.	\
**K.** O zatın himmetiyle ihtilâm olmak için Hacivad Çelebiye ikram mı etti?	\
**Ç.** Öyle değil efendim. Karagöz beyin umur u hususuna nazaret etmek üzere geldim.	\
**K.**  Karagözün evinde rezalet etmek üzere mi geldin?	\
**Ç.** Siz hakikaten kölenizle istihza ediyorsunuz. Bunlara ne lüzum var? Beyi tanıyorsanız lütfen tarif buyurun!	\
**K.** Demek, seni Hacivad gönderdi, öyle mi? öyle ise, o Karagöz bey benim.	\
**Ç.** Aman, efendim, eğer bilmiyerek bir kabahat ettimse af buyurun!	\
**K.**  Estak fırıldak! Evvelce nerede idin, oğlum? Kaç efendi kullandı seni? Kaç kapıya hizmet ettin?	\
**H.** Evvelce Abida Beyin bunağındaydım; oradan çıktını, bir kaç konağa daha hizmet ettim, şimdi de efendimin hizmetinde bulunacağım.	\
**K.**  Sen ne hizmet yapabilirsin bakayım?	\
**Ç.** Elimden geldiği kadar hüsnü hizmetten geri durmam. Sabahleyin haremden teşrif buyuruldu mu, evvelâ sigaranızı yaka2, kahvenizi pişirip elinize veririm.	\
**K.**  Ya ben Harem’den kalkıp da sora Üsküdar’a uğramadan doğru köprüye gelirsem sigarayı ben senin eline mi vereceğim? Baba, ben şirketin bir numaralı vapuru mıyım?	\
**Ç.** Estağfurullah! Kahveyi içtikten sora meselâ bakılacak bazı mektuplar olur, onlar görüldükten sora bendeniz de katlar çantaya korum.	\
**K.**  Koymak tarafı hep senin; hizaya gelip bana kısmet olmıyacak mı?\
**Ç.** İnayet buyurun.Sora arabayı emir buyurdunuz mu, hemen seise gider haber veririm. O aralık zatıâliniz gitmek için tekrar içeri girdiniz mi, köleniz de tuvaletimi ikmal ederim, araba da kapıya gelir, bendeniz de ya sandığa çıkar yahut hemen kılavuza atlarım.	\
**K.**  Bunlar yangın olduğu vakit olur; ne olacak?	\
**Ç.** Anlıyamadım efendim.	\
**K.**  Baba, bunda anlamıyacak ne var? 'Sandığa girer kılavuza atlarım’ diyorsun. Benim bildiğim kılavuz kapı sandıklarında olur.	\
**Ç.** Arzedemedim. Benim dediğim arabanın sandığı.	\
**K.** Arabanın sandığı ha! Ben yangın zannettim. Ey. sora?	\
**Ç.** Sorası: Ticaretgâhınıza teşrif buyurdunuz mu, bazı elden olacak şeyleri tesviye ederim; sair emirleriniz de harfiyen icra olunur. Bilfarz sizi görmek isteyen olursa icabına göre cevap veririm. Akşam konağa avdette aynı böyle. Elhâsıl, istirahatınıza taallûk edecek her ne olursa ifada kusur etmem.	\
**K.**  Öyle ise, iş oldu bitti.	\
**Ç.** Emir buyurularsa yatağımı, sandığımı alayım geleyim,	\
**K.** Vay, senin sandığın da var ha!	\
**Ç.** Tabii değil mi efendim? Benim gibi garibüd-diyar bikesin nesi olur? Bir karyola, dört şilte, sekiz yastık, beş altı kat çamaşır, bundan ibaret bir şey.	\
**K.**  Ya kısmet. Dört şilte, sekiz yastık, karyola filân a! Oğlum, sen uşaklık edeceğine Yorgancılarda bir dükkân açsan a! Zavallı ben pöstekide yatmadan ense kemiklerim bibirine geçti!	\
**Ç.** Estağfurullah! Tekdir buyurulur. Öyle ya: biçaregânı her kes tahkir eder. Beis yok, beyim!	\
**K.** Ey, şimdi ayda ne vereceğiz?	\
**Ç.** Mürüvvete endaze olmaz ya! Ne münasip görürseniz bendeniz kail olurum.	\
**K.**  Yo! Kavilsiz giren haksız çıkar.	\
**Ç.** Evvelki kapımda elbise efendime ait olmak üzere şehri iki buçuk altın alırdım.	\
**K.** İste, iste, korkma!	\
**Ç.** Efendim, üç altın verin.	\
**K.**  İste, canım, iste!	\
**Ç.** Dört verin, beş verin!	\
**K.**  iste, sıkılma!	\
**Ç.** Altı verin, yedi verin!	\
**K.**  Canımı sıkıyorsun amma! İste!	\
**Ç.** Sekiz verin, dokuz verin!	\
**K.** İste!	\
**Ç.** Bin verin!	\
**K.** Eini-vereceğim amma, hizmetin nasıl? Haydi oğlum, yatağını al da gel!	\
**Ç.** Baş üstüne!(Çelebi gider, Hacivad gelir.)	\
**Hacivad.**.Nasıl. Karagöz Bey? Uşağı beğendinz mi?	\
**K.**  Pek âlâ beğendim. Şimdi gidip yatağını getirecek.	\
**H.** Daha başka ne istersiniz?	\
**K.** Ahçı isterim.	\
**H.**Ben şimdi gider sana bir ahçı gönderirm. (Gider).	\
\
(Şarkı ile Türk gelir.)	\
Yine gördüm boyu uzun scrv-i bulendum, dime tek,...	\
\
**K.**  Hoş geldin, aşçıbaşı!	\
**Türk.** Hoş gördük efandüm	\
**K.**  Yemeklerden ne yemeği bilirsin bakayım?	\
**T.** Harcı bol olursa ben size yağlı bezi bile yuttururum.	\
**K.** Ondan yana merak etme. Tatlılardan ne tatlısı bilirsin?	\
**T.**Baston yir müsün ?	\
**K.**  Baston yiyemem, şemsiye yerim.	\
**T.** Sizin bilduğunuz gibi değül; fıranculadan olur. Dilber dudağı yir müsün?	\
**K.**  Bayılırım dilber dudağına, kendisine bayılırım.	\
**T.**Efandüm, bunlar undan olur. Kaşkülü fukara?	\
**K.**  Ben fıkara istemem, zengin isterim.	\
**T.**Efandüm, bu da sütlen olur. Hanım parmağı, hanım göbeği?	\
**K.**  Onlarda mı tatlı? İsimleri güzel.	\
**T.**Evet efandüm. Tuzlulardan kadın budu, mafiş.	\
**K.**  Kadın buduna bayılırım. Mafiş de mi yemek? Ne tuhaf isimler!	\
**T.**Efandüm, bana ayluk mu vireceksünüz yoksa yıllık mu?	\
**K.**  Nasıl istersen.	\
**T.**Aylık verirseniz, arabîden mi hesab goreceğüz yoksa rumîden mı?	\
**K.**  Nasıl istersen.	\
**T.**Ben size ayları sayayum!	\
**K.**  Say bakalım'	\
**T.**Yıllar başlangucu, itiş dalaş ayu. böyüh nasuf. goçuh nasuf, böyüh aralukh, guçüh aralukh, irceb, mum ayu, emegol ayu, emegol bezegu, iki bezek gısugu, davar bezegu.	\
**K.** Ayda kaç kuruş istiyorsun?	\
**T.**Beşyüz gunış.	\
**K.** Beşyüz kuruş çok. Üstüne başına yapanın, ayda sana üçyüz kuruş.	\
**T.**Pekiefândüm!	\
**K.** Yatağını al da gel!(Türk gider, Hacivad gelir.)	\
**Hacivad.** Nasıl, Karagöz Bey? Ahçıyı beğendiniz mi?	\
**K.** Pek âlâ beğendim.	\
**H.** Daha başka ne istersiniz2?	\
**K.**  Cariye isterim.	\
**H.** Ben şimdi gider esir pazarında bir cariye bulur zatı âlinize gönderirim.(Gider.)	\
\
(Şarkı ile Zenne gelir.)	\
Şarkı Suzinâk.	\
\
Hayalin didede ateşler bıraktı,canıma.	\
Gelmez oldun, ey mâhru, sen de benim yanıma, 
Hâsılı: kâr itti gamzen bu dil-i suzanıma.	\
Nakarat:Veçhi var yansam yakılsam aşk ile cananıma\
Saklaram esrar-i aşkı sinede canım gibi.	\
\
Nola ben ağlayıp âh eylesem leyl ü nehar, \
Hasretinle daima itmekteyim âh ile zar,\
Dinlese bir dem neva-yı nalemi bülbül, yanar.	\
Eyzan.	\
\
**Zenne.** Canım efem, Hacivad Çelebi "Şeyh Küşteri meydanına git" dedi. Aceba burada ne tarafta o bey?	\
**K.**  Bu da kim? Galiba bunu da Hacivad gönderdi. Dur bakalım!	\
**Z.** Baksanız a, efem! Burada bir Karagöz bey varmış, biliyor musunuz?	\
**K.** Neden sordunuz?	\
**Z.** Hacivad Çelebi cariyenizi gönderdi,	\
**K.** Siz cariye misiniz?	\
**Z.** Evet efem.	\
**K.** O Karagöz Bey benim.	\
**Z.** Aman efem, cariyeniz bilemedim, affedersiniz.	\
**K.** Affetsem bir daha yaparsınız. Kızım, senin ismin nedir?	\
**Z.** Cemalifer.	\
**K.** Camlı fener mi?	\
**Z.** Cariyenizi ne hizmette kullanacaksınız?	\
**K.** Kızım, aşağı hizmeti, yukarı hizmeti, orta kata da sen bakacaksın.	\
**Z.** Canım efem, elimden geldiği kadar hizmetimde kusur etmem.	\
**K.** Kızım, sen nesin?	\
**Z.** Salgım salgım incüyim, güzellerin genciyim;	\
Aslımı sorarsanız, ben çerkesin piçiyim.	\
**K.** Ben de orospu çocuğuyum! Kızım, sen eski kapından niye çıktın?	\
**Z.** Ah efem! Orasını sormayınız! Bizim bir küçük bey vardı.	\
**K.** Kaç yaşında?	\
**Z.** efem. yedi, sekiz, on, on bir, on iki, on üç, on dört.	\
**K.** Bu çocuk değil, koskoca adam.	\
**Z.** Bir gün, efem, hasta olmuş küçük bey. ..Aman, Cemalifer, yatağımı yap" dedi. Cariyeniz de yatağını yaptım. Bir de baktım ki bey efendi yatakta tiril tiril titriyor, sovuk almış. Üstüne bir yorgan örttüm. "Aman Cemalifer, üşüyorum; bir yorgan daha ört" dedi.	\
**K.** Kızım, yorganla ısınmaz o. Göğüs sobası!	\
**Z.** Baktım efem, ne yapayım? Bey efendiye acıdım, "Ne yapayım? İlâç mı kaynatayım?" dedim. ,,Aman Cemalifer, koynuma gir" dedi.	\
**K.** işte, ben sana evvel söyledim: Göğüs sobası, göğüs sobası.	\
**Z.** Efendinin koynuna girdim, cariycnize sikim sikim sarıldı.	\
**K.**  Sen de ona sarıl! Sen de ona sarıl!	\
**Z.** Baktım ki bey efendi ziyade titriyor.	\
**K.**O illet saridir, sana da geçmedi mi?	\
**Z.**„Aman efendim, bırak beni" dedim. Bir de o aralık baktım ki, efem, bir yılan çıkmış başladı katımsı dokunmaya.	\
**K.**  O kör yılandır, sokmaz.	\
**Z.** Aman, bey efendi, yılan çıktı diye haykırır haykırmaz kapı açıldı. Bir de baktım ki bizim kalfa ,,Seni hınzır kız” dedi ,,seni! Burada ne işin var?" diye kolumdan tuttu kapı dışan attı.	\
**K.** Yılan seni sokmadı mı?	\
**Z.** Hayır efem! Ondan sora cariyenizi sattılar.	\
**K.**  Şimdi kısmet olursa ben alacağım seni. — Cemalifer!	\
**Z.** Efem!	\
**K.** Sen diz ovmasını bilir misin?	\
**Z.** Bilirim efem.	\
**K.** Gel. şu dizlerimi ov! ( Cemalifer dizlerini ovar.)Kızım, azıcık daha yukarı!(Kız omuzunu ovuyor.)Azıcık aşağı, kızım!(Kız Karagözün dizlerini ovmaya başlar.)Sen lâkırdı anlamaz mısın?	\
**Z.** Canım efendim, ne emrettiniz de yapmadım ?	\
**K.**  Cemalifer!	\
**Z.** Efem!	\
**K.**  Cemalifer!	\
**Z.** A canim	\
**K.** Camlı fener!	\
**Z.** Efem!	\
**K.**  Efendim dikenin dilini seveyim.	\
(Zenne gider, Hacivad gelir.)	\
**K.** Cemalifer, camlı fener!	\
**Hacivad.**.Karagöz, sen coşmuşsun; ne oldu sana?	\
**K.** Aman, Haçı Cavcav. kâhyalık vazifesini eyi ifa ediyorsun! Gönderdiğin kız çok kıyak.	\
**K.** Beğendiniz mi, efendim, cariyeyi?	\
**H.** Beğendim, Hacivad.	\
**H.** Efendim, daha başka ne istersiniz?	\
**K.**  Köçek isterim.	\
**H.** Baş üstüne!	\
(Curcunabazlar, sora köçekler oynar gider.)	\
\
(Gazelile kötürüm dilenci Ak Arap geliyor.)	\
Befta hindi . . \
**Arab.**Esselâme aleikum!	\
**K.** Hacı baba, kim getirdi lokum?	\
**Ar.** Ulak, lokum değil, selâme 'aleikum!	\
**K.** Ve aleyküm selâm, Hacı baba! Sen kimsin?	\
**Ar.** Ena miskin.	\
**K.**  Ben de senin ananı sikeyim.’	\
**Ar.** Nişun, ganım, böyle fena lâkırdı söyler?	\
**K.** Ben de fena bir şey söylemedim; sen söyledin, ben de söyledim.	\
**Ar.**Ganim, ben sâ'il!	\
**K.** Sair ol, sen ol, hepimiz aç gözlü.	\
**Ar.** Emma efendim, ben şok fukara! Bana fulûs uar!	\
**K.** Kim uyuz? Sensin uyuz!	\
**Ar.** Ganim, uyuz değil, bana fara uâr, fara!	\
**K.** Al, Hacı baba, sana bir kuruş!	\
**Ar.** Banim elim da yok, ayâgım da yok. at 'ağzımda!	\
**K.**  Al, Hacı baba! (Ağzına kor.)	\
**Ar.** Bân sana şok du'a yapajak, Sen 'amin dâ!	\
**K.**  Peki, Hacı baba!	\
**Ar.** Yâ Karagöz eföndı, şok yaşamayâsın sen!	\
**K.**  Amin, Hacı baba, amin!	\
**Ar.** Yâ Karagöz eföndı, merdimenden duşâsın!	\
**K.**  Amin, Hacı baba, amin!	\
**Ar.** Farşa farşa’ olasın	\
**K.** Amin, Hacı baba!	\
**Ar.** Başın dururken ayâgına taş dokunmâsın!	\
**K.** Amin, Hacı baba!	\
**Ar.** Ya Karagöz eföndı. benim ağzımda iki kavrulmuş lâti lokum şekeri olsun!	\
**K.** Amin! Bana bir şey yok mu, Hacı baba?	\
**Ar.**Ya Karagöz eföndı, senin ağzında iki kaurulmuş . . .	\
**K.** Amin!	\
**Ar.** . .. iki kaurulmuş katır boku olsun!	\
**K.** Hacı baba!	\
**Ar.** Na'am?	\
**K.** Lağam sensin! Ağzını topla!	\
**Ar.** Ganim, ne istersin?	\
**K.** Sana verdiğim kuruşu versen e! Başka para vereceğim.	\
**Ar.** Ben fara yutti.	\
**Ar.** Seni sıçırtıncaya kadar çabalarım.	\
**Ar.** Ya ğanım! Benim elim da yok ayâgını da yok; benim gibi fukaradan ne istersin?	\
**K.** Ben zorla alırım parayı!	\
**Ar.** Ya ganim, kimse yok mu orda? Adam oldurajaklar burda!(Arap kaçar gider.)	\
(Şarkı ile Bebe Ruhi gelir.)	\
\
Vardım Halaba,	\
Girdim dolaba.	\
Paraları verdim	\
Rakı şaraba.	\
Ya lel ya lel ya lel	\
Ya lel ya lel ya lel \
Ya tel ya lel.	\
\
**Bebe Ruhi.** Selâmım aleyküm ve aleyküm selâm! Eyi misin? Benim keyfim eyi, seninki de eyi mi? Ben söyliyeyim sen dinle; ben dinliyeyim sen söyle!\
**K.** Nefes al be! Daha ağzımı açmadım!\
**B.R.** Baba, sana kaplanmaya geldim,	\
**K.** Ulan, yorgan çarşafı mısın, kaplanacaksın ?	\
**B.R.** Baba, hiç olmazsam, hiç olmazsam sana şatır olamaz mıyım?	\
**K.** Bana şatır olacağına bostana git, dolaba katır ol!	\
**B.R.** Baba, seis olayım	\
**K.**  Ulan, ziyade beygir osuracak olursa fışkıya karışırsın.	\
**B.R.** Babacığım, ayvaz olayım!	\
**K.**  0 hiç olmaz; tablanın altında ezilirsin.	\
**B.R.** Sana ahçı olayım!	\
**K.**  O hiç olmaz; kazanın içine düştüğünnen İstakoz gibi haşlanırsın.	\
**B.R.** Baba, şimdi sana yapışacağım!	\
**K.**  Tutkal çanağı yanında mı?	\
**B.R.** Yapışacağım.(B.R. Karagözün üstüne doğru gider Karagöz sandalyeden kalkar, B.R. sandalyeyi alır havaya kalkar.)Baba, atayım mı?	\
**K.** (yukarıya bakar).Ulan, atına, atma!(Bebe Ruhi gider.) 
\
(Hacivad gelir, Karagöz eve gider, elbisesini değiştirir, defa perdeye gelir.) \
**H.** Eyi misin, Karagöz? Geçmiş ola!	\
**K.**  Müteveffa kargalar gözünü oya!(Vurur.)	\
**H.** Karagöz, elin ayağın kırılsın!	\
**K.** Kenetletir yine vururum!(Vurur.)	\
**H.** Yiyecek ekmek bulma!	\
**K.** Devlet millet sayesinde has firancola yer yine vururum. (Vurur)\
(Mabadı malûm.)	\
