
# canbaz

**Hacivad.** (semaiyi söyliyerek perdeye gelir).	\
Ey kaşı keman, tir-i müjgân canıma geçti, \
Peykânlanrının her biri bir yanıma geçti.	\
Pus itmeği ruhsarını sarkıntılık ittim, \
Zülf-ü siyahın halkası gerdanıma geçti.	\
\
Hay Hak!	\
\
(Perde gazelini okur.)	\
\
Gel, ey zahid, kenar-ı bezm-i irfandan makal anla,\
Hakikattir sözü ariflerin, guş it, me'âl anla!	\
Görünen perdedir amma, verasın bilmede maksud \
Cihana itimad itme, heman zıll u hayal anla!	\
Mecaza haml idenler ehl-i zahirdir bu esrarı. \
Sen ibretle nazar kıl, fâni dünyadan misal anla!	\
Tehi sanma bunu! Şeyh Küşterinin yadigâridir, \
Ne gûna gösterir, bak, âlemi, sahib-kemal, anla!	\
Nasihattir kelamı sadıkın, avare zann itme.	\
Tefekkür eyle manayi lâtife hasbıhal anla.	\
\
(Kavgadan sora:)	\
\
**Karagöz.**.Seni gidi utanıp arlanmaz, etrafı tekerlek, ortası sivri, kenarı değirmi, mangal kapağı kıyafetli kerata! Ne aldın ne veremiyorsun? A bunak herif! Her akşam gelir kapımın önüne: Dır dır dır(Hacivad gelir kaçar)dır. zır zır zır(H. gelir yine kaçar)zır, mır mır mır(H. gelir kaçar)mır! Mart kedisi kıyafetli kerata! Hiç utanıp arlanman yok mu?	\
**Hacivad.** (gelir).Yok.	\
**K.**Al bu yumruğu burnuna sok!(Vurur, H. gider.)	\
**H.** (gelir).Benim böyle lâkırdıya karnım tok.	\
**K.**(vurur).Durma karşımda, bok oğlu bok!	\
**H.**Karagözüm. Karagözüm, karlı dağım, sünbüllü bağım, sen misin?	\
**K.** (vurur).Sabah akşam benden dayağını yer misin?	\
**H.**Yazık, Karagöz, sana, yazık! Şu dünyaya eşek geldin eşek gideceksin!	\
**K.** A kerata, sen eşek geldin de sürücü beygiri mi gideceksin?(Vurur.) 	\
**H.**Ah, Karagöz, kabahat sende değil, senin peder ü maderinde ki hin-i sabavetinde seni terbiye etmemişler; onun için böyle cahil kaldın!	\
**K.** Demek terbiye etmedikleri için, cahil kaldım, öyle mi?	\
**H.**Evet. Bunda calib-i tereddüd hiç bir nokta yoktur.	\
**K.** Binaen aleyh bu babda sizin de sarfiyata hakkınız yoktur.	\
**H.**Karagöz, bu ne demek?	\
**K.** Ne dernek olacak? Varidatın adem-i duhulünden fiil-i mazi zuhur eder demek isterim.	\
**H.**Böyle malâyani sözlerden hoşlanmam.	\
**K.**Evet, ben de manav Yaniden hoşlanmam.	\
**H.**İstifadeli söz söylemeli!	\
**K.**İstifan ağa ile hesap mı görmeli?	\
**H.**Söylediğin sözlerin mânasını tayin eder gibi söylüyorsun.	\
**K.** Evet, tahkir eder gibi söylüyorum.	\
**H.**Karagöz, artık can sıkıyorsun. Söyliyeceğim sözleri kemal-i itina ile dinle!	\
**K.**Peki.	\
**H.**Geçen gün bir büyük yerde senin ismin geçti.	\
**K.** Geçerken Büyükdereden simitçi İsmail mi geçti?	\
**H.**Canım, öyle değil! Geçen gün bir zat-1 alikadirle seni konuştuk. Bana dedi ki A Hacivad Çelebi, o Karagöz dedikleri ulûm ü fünundan bibehre terbiyesiz herifle kat’i ülfet et! Zira senin onunla düşüp kalkmaklığına kimse razı olmaz, hattâ yavaş yavaş biz de seninle kat’i münasebet edeceğiz" kılıklı serzenişte bulundular.	\
**K.**Terzi Reşit de mi bulundu?	\
**H.**Yani, sitem ettiler, başıma kaktılar.	\
**K.**Şimdi ne demek istiyorsun?	\
**H.**Demek istiyeceğim: sana hayırhahane bir ihtarım var.	\
**K.** Yarın akşam iftarın im var?	\
**H.**Sana bir kaç sözüm var.	\
**K.** Söyle!	\
**H.**Bak, Karagöz, şimdiye kadar bir baltaya sap olamadın.	\
**K.**Beni sana meşe odunu diye kim söyledi?	\
**H.**Yani bir işle meşgul değilsin, elinden bir iş gelmez.	\
**K.**Âlâsı gelir!	\
**H.**Bakayım ne iş yapabilirsin?	\
**K.** Hırsızlık.	\
**H.**Tü! Allah müstahakkını versin! O iş mi? Düşmanım dahi o yola sülük etmesin! Hiç bir san atin yok mu?	\
**K.**Var.	\
**H.**Nedir?	\
**K.**Âlâ ısgara maşa yaparın.	\
**H.**Demek okuman yazman yok, öyle mi?	\
**K.**Kim söylemiş yok diye?	\
**H.**Aman, Karagöz, yazı bilir misin?	\
**K.**Yazı da bilirim ilk bahan da kışı da.	\
**H.**Ben sana yazı kışı sonnıyorum. Hüsnühattın var mı?	\
**K.**Hüsnüye çattığım yok.	\
**H.** Yazın güzel mi?	\
**K.** Oldukça.	\
**H.**Canım, Karagöz, çok okudun mu? Kitabetin var mı?	\
**K.** İstediğinden âlâ.	\
**H.**Karagöz, edebiyata aşina mısın?	\
**K.** Et payını aşıramam, sora aşçıdan dayak yerim.	\
**H.**Şiir tanzim eder misin?	\
**K.**Mükemmelini.	\
**H.**Asar-i münteşiren var rai?	\
**K.**Amasyada eniştem yok. amcam var.	\
**H.**Ne kadar gazelin var?	\
**K.**Altı tane kadar gazevim var.	\
**H.**Gazevi değil, gazel! Hiç aruz gördün mü?	\
**K.** Gördüm.	\
**H.**Aman bilâder, çok gördün mü?	\
**K.** Yedi sekiz tane kadar gördüm.	\
**H.**Gördüğün nedir?	\
**K.** Horoz.	\
**H.**Horoz değil! Aksam-i şiiri gösteren bir fen vardır, ona aruz derler.	\
**K.** Sana horoz, bana da tavuk derler! (H. gider.) Kerata nereden bulur da çıkarır? Yok. sana horoz derler bana da tavuk, söylediği şey abuk sabuk!	\
Sen gidersin de ben durur mıyım? Ben de gideyim idgâha dolaba, dilber seyrine! Bakalım ayine-i devran ne suret gösterir!(Gider.)	\
(Şarkı ile Zenne Çelebi gelirler.)	\
\
Şarkı Rast	\
Zümre-i huban içinde pek beğendim ben seni,	\
Cismime can ittihaz ittim, efendim, ben seni,	\
Ruha teşbih eyledim, ey serbülendim, ben seni.	\
Nakarat: Cismime can ittihaz ittim, efendim, ben seni.	\
Arızındır gülsitan-i hüsnünün verd-i teri,\
Kametindir saye-i bâğ-i melâhat ar’ari.	\
Cevher-i kân-i letafettir vücudun, ey peri!	\
Ey zan.	\
\
**Zenne.**Vay, maşallah, beyim efendim, oğurlar olsun!	\
**Çelebi.**Allaha emanet ol. ciğerparem!	\
**Z.**Böyle ne tarafa teşrifiniz?	\
**Ç.** Efendim, el hizmetkârlığı acayip bir şey. Saat altıya kadar efendi karşısında eli bağlı divan duruyorum. şimdi efendi hareme istirahat etmeye gittiler; ben de efendinin ahbaplarından birinin konağına gidiyorum, orada kapı yoldaşı ağalarla tavla iskambil oynıyacağım, vakit geçirmek için.	\
**Z.**Canını efendim, ben sizleri gökte ararken yerde buldum. Tenezzülen bizim fakirhaneye gideriz muhabbet ederiz.	\
**Ç.**Hayır efendim! Bendeniz sizin anladığınız delikanlılardan, değilim.	\
**K.** (içeriden).Sizin anladığınız delikanlılardan değildir, kansız tayıncılardandır.	\
**Z.**Ben sizi bu gece koyuvermem.	\
**Z.** Bendeniz gidemem efendim. Bu yaşa geldim, zamparalık nedir bilmem, harama uçkur çözmedim.	\
**K.** (içeriden).Çök deliğinden uydur.	\
**Z.**Efendim, ben size öğretirim. Bir gecenin içinde sizi usta yaparım.	\
**Ç.**Ben bu sanatı öğrenirsem para kazanır mıyım?	\
**Z.**Bu sanatı öğrendiğinle her nereye giderseniz gecede üç, beşyüz kuruş para verirsiniz.	\
**Ç.** Ben öyle bir sanat öğrenmeliyim ki başka bir yere gidersem para kazanmalıyım.	\
**K.** (içeriden).Ben sana bir tayıncılık sanatını öğreteyim, nereye gitsen günde bir lira kazanırsın.	\
**Z.**Haydi efendim, buyurun, gidelim!	\
**Ç.** Ben başımdan korkarım.	\
**K.** (içeriden).Başından korkacağına götünden kork, puşt!	\
**Z.**Rica ediyorum, gidelim efendim!	\
**Ç.** Bendeniz gidemem.	\
**K.** Amma nazlandı köpoğlu! Kentlini dirhem dirhem satıyor ; ben kendimi batmanla satıyorum amma hiç kimse almıyor!	\
**Z.**Kuzum efendim, pederimin bir samur kürkü var, bu gece bizim fakirhaneye tenezzül buyurularsa haddim olmıyarak kürkü size veririm.	\
**Ç.** Gidemem efendim.	\
**Z.**Cariyeniz size kul köle olsun; pederimin bîr altın saati var, onu size takdim ederim.	\
**Ç.**Bendenizin üzerime düşmeyin!	\
**K.**(pencereden).Üstüne düşerlerse sen orada yamyassı olursun.	\
**Z.**Gidelim efendim, ne arzu buyurularsa fakirhanede hepsi mevcut.	\
**K.**(içeriden).Namevcut,	\
**Ç.** Ne kadar üstüme düşüyorsunuz!	\
**Z.**Pederimin bahçede incir ağacının dibinde gömülü kavanozun içinde yüz tane lirası var, onu da size veririm.	\
**Ç.** Kuzum, sizin pederiniz kim? Ben tanır mıyım?	\
**Z.**Cariyeniz Hacivadm kızı değil miyim?	\
**K.**(içenden).Hacivat:, kulağın çınlasın! Kavanoz yerini yadırgıyacak.\
**Ç.** Öyle ise, bendeniz devlethaneye yarım saate kadar gelirim.	\
**Z.**Başüstüne efendim!	\
**Ç.**Şimdilik Allaha'smarladık!(Gider.)	\
**Z.**Safa geldiniz!(Gider.)	\
**Karagöz.** (perdeye gelir).Hacı Cavcav! Kulağın çınlasın!	\
\
(Şarkı ile uzun sakallı, sivri külâhlı, elinde değnek, pir-i fâni büyücü gelir.)	\
\
Şarkı Rast	\
Yine bir gülnihal aldı bu gönlümü.	\
\
**Büyücü.** Hak dostum hak! Yat. yat. yat!	\
**K.**Bana mı söylüyor? Yatayım bari!( Yatar arka üstü.)	\
**H.** (elindeki değneği sallar).Kalk, kalk, kalk!	\
**K.**(ölü gibi kendinden geçer, hareketsiz doğru kalkar),Ulan, aklıım başımda amma, ölmüş gibi vücudumda hareket yok,	\
**B.**Yat; yat, yat!	\
**K.** (yatar).Ulan, ne tuhaf!	\
**B.**Kalk, kalk, kalk!	\
**K.** (doğru kalkar, hareket eder).Aman efendim, size bir ricam var!	\
**B.**Ne gibi rica?	\
**K.** Bana nefesinizden verseniz de ben de beş on para kazansam!
Fıkarayım!	\
**B.**Fıkara mısın ?	\
**K.** Evet efendim, efkarı fıkaradan ve güruh-u kıptiyandanım.	\
**B.**Ağzını aç!	\
**K.** Efendim, ağzımı açarsam,aç kalırım; gözümü açsam daha eyi değil mi?\
**B.**Ben ne dersem sen onu yap'	\
**K.** Baş üstüne! (Ağzını açar.)	\
**B.**Tü (Karagözün ağzına tükürür)Yut. yut!	\
**K.**Güç! Yutulacak şey değil, koca balgam!(Yutar.)	\
**B.**Şimdi ne istersen yapabilirsin. Sakın ha zinhar, fena bir şey için, intikam almak için bir şey yapma!	\
**K.**Yapmam efendim.	\
**B.**Sora pişman olursun,	\
**K.** Fenalık için yapmam efendim.	\
**B.**Sakın korkma! Gözüne türlü türlü şeyler görünür.	\
**K.**Şayet korkarsam . . .	\
**B.**Helak olursun ; duasını da öğreteyim.	\
**K.** Öğretin efendim!	\
**B.**Hop budur hop bu, ayakkabın ğugu, vakka espali sagalti panguli guk, meçinde meçinde boğça!	\
**K.**Ulan, ne zor şey!	\
**B.** Söyle bakalım!	\
**K.** Hop budur hop bu, ayakkabın gugu, vakka espali sagalti panguli guk. meçinde meçinde boğça!	\
**B.**Sakın dersini unutma! Ben gidiyorum.(Gider.)	\
**K.**Şunu tecrübe edelim. Hop budur hop bu. ayakkabın gugu, vakka espali sagalti panguli guk, meçinde meçinde boğça!(Makam ile büyük cin gelir.)	\
**Çin.** Ji ji ji ji (Makam ile zırlar, ayağiyle Karagözü havaya kaldırır.) \
**K.**Ulan, gidiyor muyuz?	\
(Yere bırakır gider. Karagöz evine gider.)	\
\
**Karagöz.**. Abla!	\
**Karısı (içeriden).**Ne var, herif?	\
**K.**Bizim büyük su küpü nerede?	\
**K.k**.Nerede olacak? Aşağıda.	\
**K.** Ulan, ne kadar ağır bu be!	\
**K.k**.Herif, küpü nereye götürüyorsun?	\
**K.** Onu senden sormazlar, (Perdeye küpü kor.)	\
**Hacİvad (gelir).** Karagöz, ne yapıyorsun ?	\
**K.** Şükür, Allaha emanet ol! Sen ne yapıyorsun?	\
**H.**Ben sana keyfini sormıyorum. Burada ne yapıyorsun?	\
**K.**Hocalık yapıyorum.	\
**H.**Nasıl hocalık?	\
**K.** Bakıcılık.	\
**H.**Demek ki insanın bir kaybı olsa sana baktırsa bileceksin, öyle mi?	\
**K.** Öğle değil, ikindi.	\
**H.**Benim evimde ne var ne yok bilir misin?	\
**K.** Bilirim.	\
**H.**Bil bakalım.	\
**K.**Hop budur hop bu, ayakkabın ğugu, vakka espali sagalti panguli gak, meçinde meçinde böğça!(Cin gelir, küpten bir kafa çıkar.)	\
**H.**Aman, Karagöz, korkuyorum!	\
**K.**Sus, sesini çıkarma.(Küpten bir kol çıkar, sora bir ayak çıkar, bir el çıkar.)	\
**H.**Aman. Karagöz, bunlar ne?	\
**K.**Ulan sus! Sesini çıkarma!(Küpten yılan çıkar, diğer şeyler de çıkar.)	\
**H.**Karagöz, küpten türlü türlü şeyler çıkıyor!	\
**K.**Sus. sesini çıkarma!(Yere bakar.)Hacivadnı evinde ne var, söyleyin! (Birisi Karagöze lâkırdı söylemiş gibi.)Başüştüne! Onu buraya getirin! (Küpten Hacivadın kürkü çıkar.)	\
**H.**Aman, Karagöz, benim kürk o.	\
**K.** Sen sus!( Yeri dinler.)Başüst üne. bura ya getirin!(Küpten Hacivadın saati çıkar.)	\
**H.**Karagöz, benim altın saat!	\
**K.** Sen sus!(Yeri dinler,) Başüstüne Haydi getirin!(Küpten Hacivadm altın kavanozu çıkar.)	\
**H.**Karagöz, benim evdeki gömülü olan altın kavanozu nereye gidiyor?	\
**K.**Sen sus!	\
**H.** Aman Karagöz, bunlar nedir böyle?	\

**K.** Benim bakıcılığım sayesinde bunları sana gösterdim.	\
**H.** Aman Karagöz, sen çok keskin hocaymışsın!	\
**K.**Ne zannettin, a çürük?	\
**H.**Kuzum Karagöz, her şey biliyorsun, benim öleceğimi de bil.	\
**K.** (Hacivada tokadı atar. H. gider).Kerata, senin, öleceğini nasıl bilirim?	\
(Küpü alır evine gider.)Abla	\
**Karısı** (içeriden).Ne var, herif?	\
**K.**Bizim merkep nerede ?	\
**K.k**.Nerede olacak? Ahırda.	\
**K.** Sen onu bana ver!	\
**K.k**.Tuhaf söylüyorsun.Bu bardak mı yoksa testi mi. "bana ver" diyorsun? Kendin git ahırdan alsan a!	\
**K.**Gel bakalım, benim kardeşim gibi merkebim!	\
**K.k**.Herif, sen böyle merkeple nereye gidiyorsun ?	\
**K.** Gurbete.	\
**K.k**.Benden izin almadan?	\
**K.**Ben çocuk mıyım senden izin alacağım?	\
**K.k**.Bir insan uzak bir mahalle gidecek olursa hareminden ruhsat almadan gitmez. Sen ise kendiliğinden iş görüyorsun.	\
**K.**Bu da doğru söz.	\
**K.k**.Gidip gelmemek var, gelip bulmamak var.	\
**K.**Gelip bulmamak eyi, amma gidip gelmemek fena.	\
**K.k**.Bir iş için mi gidiyorsun ?	\
**K.**Gittiğim yerden mal alacağım, gelip burada satacağım.	\
**K.k**.Güle güle git kocacığım, güle güle gel, artık eksik helâl et!	\
**K.**Ulan, ölüyor muyuz köpoğlu, helâl olsun?	\
**K.k**.Bana gelirken hediye getir, kocacığım !	\
**K.** Gelirken sana bir eşek nalı getiririm.	\
**K.k**.Ben eşek nalını ne yapayım?	\
**K.** Başına takarsın, nazar değmez.	\
**K.k**.Bana gelirken bir dizi inci getir!	\
**K.**İncir getirmeye hacet yok, burada da var incir.	\
**K.**.A üstüme eyilik sağlık! İncir değil, inci! Deli olmuş bu herif!	\
**K.** Getiririm.	\
\
(Merkebe biner perdeye gelir, karşısına üç tane Zenne gelir.)\
\
Şarkı Hicazkâr	\
Ey melek-haslet şehinşah-i vahid, \
Eylesün Hak zatını gamdan ba'id! \
Olsun ikbalin gibi ömrün mezid!	\
Nakarat; Her şebin kadr ola, her ruzun saki!	\
Menba’-i lûtf ü inayetsin, şeha, \
Yoktur ihsanına hadd ü intiha.	\
Ferr  ü şevketle safa sür daima!	\
\
Eyzan.	\
**Karagöz.**.Bunlar kim be?	\
**1.Zenne**Ah. kızlar, yol bilmemek ne kadar fena şey!	\
**2.Zenne**Pek doğru söylüyorsunuz.	\
**3.Zenne**Elbette birisine tesadüf eder ona sorarız.	\
**K.** Bizim merkep durduğu yerde mıhlandı.	\
**1.Zenne**A kız, baksan a! Karşımızda bir eşekti adam var!	\
**2.Zenne**Ne kadar tuhaf adam!	\
**3.Zenne**Başına da kırmızı renkte külah giymiş.	\
**1.Zenne**Kız. o adama da benzemiyor.	\
**2.Zenne**Sakın maymun olmasın!	\
**K.** De hey meret1!	\
**3.Zenne**A kız. maymun da değil.	\
**1.Zenne**Ya nedir o?	\
**2.Zenne**Ecelacayip bir şey!	\
**K.**Acayip, bunlar hiç insan görmemiş mi? Şunlara göstereyim kendimi!	\
**3.Zenne**Kızlar, ben size bir şey söyliyeyim mi? Bu cin olmalı.	\
**1.Zenne**Bana baksan a, merkepti!	\
**K.**Ne var, merkepsiz?	\
**1.Zenne**Sen nesin?	\
**K.** Yaban adamı.	\
**2.Zenne**Nereden gelip nereye gidiyorsun?	\
**K.** Yuvamdan geliyorum.	\
**1.Zenne**Senin yuvan buraya yakın mı ?	\
**K.** Yakın.	\
**1.Zenne**Ne aramaya çıktın?	\
**K.** Yavrularıma nafaka aramaya.	\
**1.Zenne**Sen ne yer ne içersin?	\
**K.**İnsan eti yerim.	\
**1.Zenne**.Aman, sakın bizi yeme.	\
**K.**Sizi yemeyim de açlıktan öleyim, öyle mi ? Hazir ayagıma gelmiş rızkım.	\
**2.Zenne**Kuzum baba, canım baba, bizi yeme!	\
**K.**Bir haftadır kursağıma insan eti girmedi, çocuklarım dersen, açlıktan ölecekler.	\
**3.Zenne**Sana para verelim, sen o para ile çocuklarına nafaka al, bize dokunma!	\
**K.** Haydi diyelim ki ben sizden parayı aldım. 0 para ile insan eti alamam: mutlaka sizi yiyeceğim,	\
**1.Zenne** Canım kuzum, sana yalvarıyorum, bizi yeme!	\
**K.** Haydi ikiniz dursun, birinizi yiyeyim!	\
**2.Zenne**Canını efendim, biz üç kardaşiz, birbirimizden ayrılamayız.	\
**K.** Ben sizi ayırırım.	\
**3.Zenne**Öyle ise, sizde asla merhamet şefkat yok.	\
**1.Zenne**Bir insan ebnayı cinsini yer mi, paralar mı?	\
**K.** Ey kuzum, öyle insan var ki kalbinde asla merhamet yok, ebnayı cinsîni hem yer hem paralar.	\
**3.Zenne**Demek siz de o cinstensiniz?	\
**K.** Evet.	\
**3.Zenne**Öyle ise yamyamsınız.	\
**K.**Yamyamım.	\
**1.Zenne**Bari, bizi yiyeceksen üçümüzü birden ye de kurtulalım!	\
**K.** Birinizi yiyeceğim.	\
**2.Zenne**Birimizi yersen üçün ikisi geride kalır.	\
**K.**Siz beni bilemediniz.	\
**1.Zenne**Hayır, bilemedik. Siz kimsiniz?	\
**K.** Ben gulyabani.	\
**1.Zenne**Gulyabani nedir?	\
**K.**Tenha ve yaban yerlerde insana türlü türlü şekille görünür.	\
**2.Zenne**Şimdi senin meramın nedir?	\
**K.** Ben şimdi sizin bir tanenizi kapıp kûhu Kafa götüreceğim.	\
**Zenneler (hepsi birden)** Aman, aman, bırak götürme!	\
**K.** öyle ise. ikinizi götüreyim.	\
**3.Zenne**Kuzum, bizi bırak!	\
**K.** Haydi, üçünüzü birden götüreyim!	\
**1.Zenne** Adam sen de. Sen sözünde ısrar ediyorsun, ne yapacaksan yap! \
**K.** Ben size lâtife ediyorum. Ben de sizin gibi insanım, ne inim ne cin.	\
**2.Zenne**Siz böyle ne tarafa gidiyorsunuz?	\
**K.** Gurbete. Siz nereye gidiyorsunuz?	\
**3.Zenne**Gözümüzün gördüğü yere.	\
**K.** Gözünüz beni görüyor; öyle ise, bana geliyorsunuz.	\
**1.Zenne** Kuzum efendim, size kim derler?	\
**K.**Evvelâ siz bana isminizi söyleyiniz.\
**1.Zenne**Benim adım Suluca Yayla Çayın.	\
**2.Zenne**Benim adım da Dillice Çeşme.	\
**3.Zenne**Benim adım da Gari Bit Ahırı.	\
**K.** Benim adım da Kulaksız Kuyruksuz Tay. Evvelâ Suluca Yayla Çayırında bizim tayı otlatalım, sora Dillice Çeşmede sulayalım, sora da Gari Bit Ahırına çekelim, olmaz mı?	\
**1.Zenne** Rafta kurabiye var amma, sana göre yok. Haydi kız, gidelim!	\
(HepİSİ birden giderler.)	\
**K.** Vay fındıkçı - köpoğlu!(Merkebe hitaben:)Haydi, biz de gidelim! Kısmetimiz yokmuş, ne yapalım, biz de kısmetimizi başka yerden ararız. Deh!(Gider.)	\
(Şarkı ile Çelebi gelir. Hacivad karşılar.)	\
\
Şarkt Hicazkâr	\
\
Eyle vaslınla, efendim, behredar, \
iltifatınla hem eyle kâmkâr.\
Ben sana üftadeyem, bu aşikâr!\
Nakarat: Sen gibi hiç görmedim bir şivekâr.	\

Her kesin âlemde vardır dilberi,	\
Şensin ol dilberlerin çüm serveri, \
Dilrübasın, hoş-edasm, ey peri!	\
Uyzan	\
Hatıra geldikçe, ey nazik-eda, \
Ayş ü işret zevk u sohbet daima.	\
Alemi döndüm dolaştım biriya,	\
Eyzan.	\
\
**Hacivad.**.Vay efendim, maşallah, iki gözüm, nuru aynım ! Safa geldiniz! \
**Çelebi.** Safada daim ol. Hacivad Çelebi!	\
**K.** (pencereden).Vefada dayım ol, Zeyrekte de amcam ol!	\
**H.**Efendim, böyle ne taraftan teşrif?	\
**Ç.**Zatı âlinizi arzuladım, sîze geliyorum.	\
**H.**Buyurun, ihya buyurdunuz!	\
**Ç.**Buraya gelişimin sebebi: Sizden burayı Şeyh Küşteri meydanını tutmaya geldim, buraya menzil kurup canbazlık edeceğiz.	\
**H.**Pek âlâ efendim; bendenizin refikim de var. sizinle birlikte bulunsa bir kaç kuruş da o alsa?	\
**Ç.**Elinden canbazlık gelir mi, Hacivad Çelebi?	\
**H.**Efendim, canbazlık yapamaz, palyaço, komiklik yapar.	\
**Ç.**Pek âlâ, o da bizlen beraber bulunsun. Para için konuşalım mı?	\
**H.** Efendim, hasılat çıksın, o vakit görüşürüz.	\
**Ç.**Pek âlâ, Hacivad Çelebi, o da olur. Allaha 'smarladık.	\
**H.**Sefa geldiniz, efendim ! (Çelebi gider, Hacivad ela gider.)	\
(Şarkı ile canbazlarm menzil ipi kurulur.)\
Esirin oldum, ey zülfü kemendim . . .	\
\
**Karagöz.** (yukarıdan allar, ipe takılır).Ulan, bu domuz kapanı mı? (Usulle ipten iner.)Ulan, Hacivad, aşağıya gel!	\
**H.** (gelir).Ne var, Karagöz? Ne istiyorsun?	\
**K.**Hacivad, bu ip nedir? Burada çamaşır sereceksin?	\
**H.**Değil, a canım! Bu canbazların menzil ipi.	\
**K.** Bu ne olacak böyle?	\
**H.**Şimdi burada ipin üstünde oynıyacaklar.	\
**K.**Beni de şunlara dahil etsen e!	\
**H.**Sen ne yapabilirsin, Karagöz?	\
**K.** Onlar ne yaparsa ben de yaparım.	\
**H.**Onlar ipte oynar.	\
**K.** Ben de Eyyüpte oynarım.	\
**H.**Onlar halatta oynar.	\
**K.** Ben de Balatta oynarım.	\
**H.**Canbazlıkta türlü türlü oyun var; sen her oyunu bilir inisin?	\
**K.** Bilirim, hattâ değişik oyunu ben de bilirim.	\
**H.** Sen yerde mî oynarsın . , .	\
**K.** Yoksa gökte mi?	\
**H.** Yerde mi oynarsın yoksa ipte mi?	\
**K.** İpte de oynanın yerde de oynarım.	\
**H.**Pek âlâ, cimnastik?	\
**K.** Lâstiği niye bilmem? Kışın her kes ayağına giyer.	\
**H.**Öylesi değil, kuvvet oyunu.	\
**K.** Ben Kadri beyin koyununu bilirim.	\
**H.**Kadri beyin koyununu değil, kuvvet oyunu.	\
**K.**Bilirim.	\
**H.**Flikflik?	\
**K.** Filikayı da bilirim sandalı da.	\
**H.**Trabezede oynar mısın?	\
**K.** Tirabazanda oynamam, baba götüme batar.	\
**H.**Turnike’ oynar mısın?	\
**K.**Öyle tekeden mekeden anlamam.	\
**H.**Pek âlâ. Arkalıç?	\
**K.**Ulan, ben hamal mıyım? Arkalıcı ne bileyim?	\
**H.**Ecel beşiği?	\
**K.**Ecel beşiğini de sevmem salıncağını da.	\
**H.**Demek, sen bu oyunları bilmiyorsun.	\
**K.**Öğreniriz, Hacivad,	\
**H.**Ben senin tarafından canbaz, başı ile görüşlüm konuştum; benim hatırım için seni kullanacaklar.	\
**K.**Seni kullansınlar, köpoğlu!	\
**H.**Sen şimdi git, bir palyaço elbisesi bul. giy de gel!	\
**K.**Benim evde varılır esvabım.	\
**H.**Giy de gel	\
**K.** Peki, giyer gelirim.(Giderler.)	\
(Çalgı vas çalarlar, cdnbaz İpe çıkar, oynar; Karagöz de yerde tuhaflık eder. Canhaz ipten iner gider; başka canbaz gelir, o da ipte oynar gider. Çocuk. gelir, o da ipte oynar gider. Sora canbaz başı Karagöz ile beraber kayıkla ipe çıkarlar, canbazbaşı ayırılık gazelini söyler, kayık iki parça olur, canbazbaşı gider, K. yalnız kalır, ipi sallar, K. düşer ölür.) \
**H.** (gelir).Bakar mısın bir kere? Benim bunca senelik arkadaşım olan Karagöz ölmüş, eyvah eyvah! Bari gideyim de soyuna sopuna haber vereyim!(Gider.)Bana baksanız, Ayıbokunun oğlu!	\
**Çingene (içeriden ).** Ne var, Hacivad Çelebi?	\
**H.** Sizin Karagöz menzil ipinden düştü öldü; gelin şunu kaldırın!	\
**Çingeneler.** Geliyoruz, Hacivad Çelebi!(Bir kaç kişi gelirler.) Ulan, senin mis gibi sanatın dururken nene lâzım senin, ayol, can can can galabazlık!(Karagöze vururlar, Karagözü alır götürürler.)	\
\
(Şarkı ile Karagözün ölüsünü kaldırırlar.)	\
Şarkı Çeribaşınm gelini. . .	\
\
(Karagöz orta yere gelir gelmez, tabuttan başını kaldırır atlar hepsi kaçarlar. Karagözün karşısına Hacivad gelir, oyun biter.)	\
