
# karagozun sairlerle imtihani

 **Hacivad.** (semaî söyliyerek perdeye gelir).	\
\
Semaî Yegâh.	\
\
Benim afet-i cihanım!	\
Yoluna feda bu canım, \
Dili dost, kalbi düşmanım!	\
Nakarat:Aman, itme bu edayı!	\
Beyim, itme bu cefayı!	\
Alsan elimi eline. \
Mailem tatlı diline, \
Sarılsam ince beline!	\
Eyzan.	\
\
Gel benim servi bülendim,	\
Boyu boyuma menendim. \
Kerem eyle, gel efendim!	\
Eyzan.	\
\
Kulunam senin, ezelden, \
Mailem can u gönülden, \
Severem, ne gelir elden ?	\
Eyzan.	\
\
Hay Hak!	\
\
(Perde gazelini okur.)	\
Bir beyaz üzre yazılmış dilküşadır perdemiz,\
Atlas u dibadan olsa ger, sezadır perdemiz.	\
Gerçi etfal-i cihana türlü suret gösterir,\
Nezd-i arifte veli ibretnümadır perdemiz.	\
\
Hâsılı her faslı bir faslı bahar evrakıdır,\
Açılır manend-i gülşen pür edadır perdemiz.	\
Oynadıkça Karagözle Hacı Evhad Çelebi, \
Zevk u şevk-i meclise peyk-i safadır perdemiz.	\
Hakle o şah-ı âzamın ömrün firavan eylesün\
RaşIDA, ol hazrete ca-yı duadır perdemiz.	\
\
Efendim! Demem o demek değil! Bu bendenize, bu hakir-i duacınıza, bu yüzü yunmuş, elfazı düzgün, sözü sohbeti tatlı bir fasihüllisan yâr-ı eefaşian olsa, geliveren şu meydan-ı pürsafaya, arabî bilse, farisî bilse, viraz fenu-i şiir ve musikiye aşina olsa, o söylese, bendeniz dinlesem, bendeniz söylesem o dinlese, oturan zevkperveran-ı kiram da safayap olsa! Diyelim: Bu gece işimizi Mevlâm rasgetire!	\
!
( Taganniye başlar.)Yâr, bana bir eğlence!\
Yâr. bana bir eğlence!	\
Yârin bu kadar cevri gelir miydi hayale?	\
Gûş itmedi ahım, beni döndürdü hilâle!	\
\
(Karagöz gelir, Hacivad ile kavga ederler. Hacivad gider.)	\
**Karagöz.**(yerde yatar).Aman aman! Oldum, bimecal oldum! Çıngarın  sonunda kendimi yerde buldum ! Amanın aseldirlerim! Darbe-i tekmeviyenin tesirinden eşek gibi zırların! Amanın omuzbaşlarım ! Cereyan-ı tokattan tüysüz kalan hilâl kaşlarım! Vücudu darbalûdum ahçı kevgiri gibi delikdeşik oldu! Ey sağ cenahım! Adeta temayülen meyl-i inhidam etmiş de haberim yok!	\
**H.**(gelir).Vay efendim! Maşallah!	\
**K.**Selvinin tepesine çık ta kuş avla!	\
**H.**Zevzeklik istemez! Güzelce bu akşam imrar-i vakit eyliyelim!	\
**K.**Emin ağa ile kadayıf mı yiyelim?	\
**H.**Canım, şimdi kadayıfın münasebeti var mı	\
**K.**Babam, sen söyledin!	\
**H.**Bendeniz demek isterim ki güzelce konuşalım! Lâkin sen insan değilsin ki! Ne zaman ruberu gelsen dayakla mukabele ediyorsun!	\
**K.**Ulan! Sana hervakit demiyor muyum: Kapımın önüne gelip te feryad-ı hımarane ile taciz, etme beni? Mademki geliyorsun, kapının tokmağını eline al, bir kere de kapıyı çal!(Hacivada tokadı atar.) Baktın ki içerden kimse ses çıkarmıyor, bir daha çal kapıya! (Yine vurur.)Baktın yine ses çıkaran yok, bir de tekme vur, kerata!(Vurur.)	\
**H.**Yok bilâder! Lâtife lâtif gerek!	\
**K.** Lûtfiyeye Lâtif Ağa mı gerek?	\
**H.**Lâtifeyi bırak!	\
**K.**Lûtfiyeyi bıraktık.	\
**H.**Karagözüm, şimdiye, kadar seninle görüşüyoruz, birbirimizle muhabbet ediyoruz da hâlâ senin adını bilmiyorum!	\
**K.**Hacivad, bu akşam afyonu yine ziyadece yuvarlamışsın!	\
**H.**Neden?	\
**K.**Neden olacak? Ulan, benim adım Karagöz değil mi?	\
**H.**Değil bilâder! Karagöz lâkap.	\
**K.**Ne demek?	\
**H.**Canım, sen ana rahminden düştüğün vakit . . .	\
**K.**Yanlış, Hacivad, ben değil. Geçen gece fenersiz giderken sizin bilâder düşmüş.	\
**H.**Nereye düşmüş?	\
**K.**Analâğımına.	\
**H.**Sus. zevzek! Sen anadan doğmadın mı?	\
**K.**Yo ...!	\
**H.**Pekâlâ, seni kim doğurdu?	\
**K.**Ben doğurdum.	\
**H.**Ananı kim doğurdu?	\
**K.**Anamı da ben doğurdum.	\
**H.**Babanı kim doğurdu?	\
**K.**Babamı da ben doğurdum.	\
**H.**Çoluğu çocuğu kim doğurdu?	\
**K.**Onları da ben doğurdum.	\
**H.**Amcanı kim doğurdu?	\
**K.**Amcamı da ben doğurdum.	\
**H.**Dayını kim doğurdu?	\
**K.** Dayımı da ben doğurdum.	\
**H.**Halanı kim doğurdu?	\
**K.**Halamı da ben doğurdum.	\
**H.**Teyzeni kim doğurdu?	\
**K.**Teyzemi de ben doğurdum.	\
**H.**Soyunu sopunu, sinsileni . ..	\
**K.**Şimdi sinsilenden başlatırsın ha! (Atar tokadı.)	\
**H.**Münasebetsizlik istemez! Siz dünyaya ne ile teşrif ettiniz?	\
**K.**Şimendiferle!	\
**H.**Değil, a canım! Bir insan anasından doğmaz mı?	\
**K.**Anasından doğar,	\
**H.**Sen de doğduğun vakit ebe kadın seni tuzlayıp kundaklamadı mı?	\
**K.**Ulan, beni salamura mı yapacaklar?	\
**H.**Bilâder, bir çocuk doğduğu vakit taaffün etmesin diye ebe kadın çocuğun kısık yerlerini tuzlar.	\
**K.**Ey sonra?	\
**H.**Badehu seni kundağa sarıp sarmalayıp babanın kucağına kundağı verir.	\
**K.**Babama kundağı soktuğu vakit babam çayır çayır yanmaz mı?	\
**H.**öyle kundak değil! Çocuk kundağı! Baban senin kulağına bir şey söylemedi mi?	\
**K.**Söyledi.	\
**H.**Ne dedi?	\
**K.** "Oğlum! Allah utandırmasın! Arsızlıktan, yüzsüzlükten yana bana benze! Benim gibi ol" dedi.	\
**H.**Canım! Pederin, ismini senin kulağına söylemedi mi?	\
**K.**Söylemedi.	\
**H.**Canım, seni çağırdıkları vakit ne diye çağırdılar?	\
**K.**Karagöz diye.	\
**H.** O mahlâsın! Asıl adın yok mu?	\
**K.**Atım da yok, eşeğim de yok.	\
**H.**Canım Karagöz, üzme beni!	\
**K.**Ha. adımı mı soruyorsun?	\
**H.**Evet, adını soruyorum.	\
**K.**Benim adım Lâtiana.	\
**H.**Hay külhani hay! Hiç nebatattan insan ismi olur mu?	\
**K.**Neden inanmıyorsun? Benim babam bahçıvanmış, bahçeye maydanoz dikeceğine lahana dikmiş, ben çıkmışım.	\
**H.**Aman Karagözüm! Ben bu sene lâhana hiç yemedim; bir parça yaprağınızdan verin!	\
**K.**Havalar kurak gittiğinden yaprağını kurudu.	\
**H.**Yaprağınız kurudu ise göbeğinizden verin!	\
**K.**Göbeğim de çürüdü.	\
**H.**Başka bir yeriniz yok mu?	\
**K.**Kucağımdan yerseniz. buyurun!(Hacivada bir tokat atar. Hacivad gider, yine gelir.)	\
**H.**Haydi diyelim ki senin adın Lâhana. Pederin var ya	\
**K.**Var.	\
**H.**Pederin ismi?	\
**K.**Prasa.	\
**H.**Validenin ismi	\
**K.**Şalgam.	\
**H.**Teyzenin ismi?	\
**K.**Kereviz.	\
**H.**Keriz mi?	\
**K.**Hayır, ceviz.!	\
**H.**Hemişrenin ismi?	\
**K.**Enginar.	\
**H.**Biâlder, çocuk var ya?	\
**K.**Var.	\
**H.**Onların ismi?	\
**K.**Salata, soğan, dereotu, maydanoz, nane.	\
**H.**Karagöz, sizi aradıkları vakit nerede bulunursunuz?	\
**K.**Zerzevatçı dükkânında.	\
**H.**Hepiniz beraber mi oturursunuz, yoksa ayrı ayn mı?	\
**K.**Ayrı ayrı otururuz.	\
**H.**Oturduğunuz yer kadife mi döşeli, yoksa kumaş mı?	\
**K.**Hayır, kabaca zift döşeli.	\
**H.**Neden zift döşüyorlar?	\
**K.**Yerimize işeriz de onun için.	\
**H.**Seni gidi tarla bozuntusu herif seni!	\
**K.** Seni gidi akıntı çağanozu herif seni!(Hacivada tokat vurur, Hacivad gider.)Be, neme lâzım? Sen gidersin de beni pamuk ipliği ile mi bağlarlar? Ben de gideyim idgâha, dolaba dilber seyrine. Bakalım ayine-i devran ne suret gösterir!	\
(Karagöz gider, kendi evinin kapısını çalar, karısı kapıyı açar.)	\
\
**Karagözün karısı.** (içeriden).Herif, buraya bak! Yine ellerini sallaya sallaya mı geldin?	\
**K.**(içeriden). Hayır! Ellerimi cebime soktum da geldim.	\
**K.k.**Herif, ne olacaksa olsun, artık senin kahrını çekmeğe tabıtüvanım kalmadı. Bıktım usandım!	\
**K.**Ne oldu sanki? Ne istiyorsun?	\
**K.k.**Ne istiyeceğim, herif? Bir kere şu çocukların haline bak! Ne üstlerinde var, ne başlarında var!	\
**K.**Senin üstüne başına yapmadan onlara vakit kalmıyor ki!	\
**Karagözün oğlu.**Babacığım, doğru söylüyorsun. Nen var, nen yok hepsini anama yediriyorsun, sonra seni enayi yerine koyuyor.	\
**K.**Herif bak! Görüyor musun? Oğlana da yüz verdin de şimdi başımıza çıkıyor!	\
**Karagözün oğlu.** Kim çıkıyor be? Sen çıkıyorsun babamın başına!	\
**K.k.**Sen otur bakayım, seni yumurcak seni!	\
**0.**Neden yumurcak oluyorum?	\
**K.k.**Herif, şu oğlanı sustur!	\
**K.**Haydi oğlum, sen yat !	\
**0.**Yatıyorum, babacığım.	\
**K.k.**Yazıklar olsun senin kılığına kıyafetine! Seni gören de kerli ferli bir adam zanneder.	\
**K.**Beni beğenmiyor musun? Benim gibi koca sana çok bile!	\
**K.k.**Ehem. Senin gibi koca olacağına hiç olmasın!	\
**K.**Ulan, sonra beni mumla ararsın!	\
**K.k.**Güleyim bari! Baksanız, beyefendinin derdinden ölüyorum: Şafii köpeği suratlı herif!	\
**K.**Karı, ağzını topla! Sonra seni kapı dışarı atarım!	\
**K.k.**Ben de rasğeldiğim yerde yatarım. O da bana tasa mı? Nerede akşam, orada sabah.	\
**K.**Saba mı, Dügâh mı o vakit anlarsın!	\
**K.k.**Hah hah hah, güleyim bari! Senin gibi koca saçımın telinden çok! Elinden geleni arkana koyma, şebek maymunu herif!	\
**K.**Şebek maymunu sensin, düzgün kuklası karı!	\
**K.k.**Ömrün, günün kararsın, sümüklü herif!	\
**K.**Ulan, çok kabarma, teneşir horozu kaltak!	\
**K.k.**Haydi şuradan, kırk ev kedisi, leş yiyici çaylak'	\
**K.**Çok dırlama. mundar musibet!	\
**K.k.**Musibet te sensin, mundar da sensin, çöplük kargası herif!	\
**K.**Ulan, hangimiz çöplük kargası? Bir kere aynayı al da suratına bak!	\
**K.k.**Şimdi böyle olduk. Kâthanelerde, Göksularda peşimde dolaştığını unuttun, değil mi? Sana vardığım zaman kaşımın hilâlliğine herkes bayılırdı. Tombul tombul lor peyniri gibi idim!	\
**K.**Haydi oradan, kokmuş sen de!	\
**K.k.**Kokmuş ta sensin, hepisi de serisin ! Ben ananım evinden geldiğim vakit dokuz araba eşya ile geldim. Malimenâlimi sattın savdın, fülûs-u ahmere muhtaç ettin de şimdi fena oldum, öyle mi?	\
**K.**Dokuz araba eşya nerede? Anam diye öğündüğün kadın Yenicamîde takke satıyor.	\
**K.k.**Haydi oradan, yarım pabuçlu herif!	\
**K.**Yarım pabuçlu sensin! Kunduramın altına daha yeni pençe vurdurdum.	\
**K.k.**Herif, çok dırlanma! Bir daha seni yanıma yanaştırmam.	\
**K.**Çıma atar yanaşırım.	\
**K.k.**Öyle saçmalar para etmez.	\
**K.**Kan, hiddetlenirsem fena olacak	\
**K.**„Serçeden korkan darı ekmez." Ateş olsan cürmün kadar yer yakarsın.	\
**K.**Sen öyle sanırsın, hele bir kundak sokayım sana da bak. Allah bilir, ateşi beyninden çıkar,	\
**K.k.**Herif, umduğun dağlara kar yağdı,	\
**K.**Yağarsa yağsın.Ben de fundactlığı bırakır dondurmacılık ederim.	\
**K.k.**Budalâ. hâlâ lâtife mi sanıyorsun? Alıp başımı gidersem Dıral Dedenin düdüğü gibi kalırsın. Sonra başına taş dokunur amma, atı alan Üsküdara geçer!	\
**K.**Geçerse geçsin, ben velosipede biner yetişirim.	\
**K.k.**Herif, sana söylüyorum: Adam olmıyacaksın, benim ayağımın bağını çöz!	\
**K.**Ayağının bağım çözeyim de bahçeyi altüst edesin, değil mi?	\
**K.k.**Çok dırlanma! inan olsun, yuvanı yapacağım!	\
**K.**Yuvaya çok sokulma, sonra leylek gagalar!	\
**K.k.**Kocacığım, barışalım mı?	\
**K.**Barışalım!	\
**K.k.**Ah, benim top sakallı kocacığım!	\
**K.**Ah, benim tüfek suratlı karıcığım!	\

(Şarkı ile Çelebi gelir.)	\
\
Şarkı Nihavend	\
\
Niçin nalendesin böyle?	\
Gönül, derdin nedir söyle!	\
Seni ben istemem böyle.	\
Nakarat:Gönül, derdin nedir söyle!	\
Kimin aşkiyle nalânsın?	\
Kimin hicrile sazansın ?	\
Neden böyle perişansın ?	\
Ey zan.	\
\
 **Hacivad.**.Maşallah, beyim efendim! Sefa geldiniz!	\
**Çelebi.**Sefada daim ol, Hacivad Çelebi!	\
**K. (pencereden)** "Vefada dayım ol!" diyor.	\
**H.**Çoktanberi zatı âlinizi kaybettik. Nerelerdesiniz	\
**Ç.**Meşguliyet, malûm-u âliniz!	\
**H.**Zann-ı âcizaneme kalırsa bu sefer gelişiniz tehi yere değil.	\
**Ç.**Evet, tehi değil. Benim eskidenberi şiire hevesim olduğunu bilirsiniz.	\
**H.**Maşallah! Bilmez miyim efendim? Hattâ peder merhumun gününde devlethaneye az şairler mi gelirdi? Bendeniz bile şiire heves ettimdi.	\
**Ç.**Bendenizin buraya gelmemin sebebi: Buraya bir muamma talikiyle bu mahalde âşıkların imtihan olmasını arzu ediyorum. Sizin ahbablarınızdan şair var mıdır?	\
**H.**Vardır efendim. Zatı âliniz de bilirsiniz o zatı.	\
**Ç.**Kim o. Hacivad?	\
**H.**Refikim meczup Karagöz.	\
**K.**(içeriden).Zevzek kerata! Güya beni methediyor!	\
**Ç.**Pekâlâ. Hacivad! Sız ona haber verin, bendeniz de gideceğim. Selanik tarafından bir âşık gelmiş, onunla görüşeceğim. Bir muamma asmak için nekadar para lâzım ?	\
**H.**Azdan az dört âşık gelse yirmi lira masarif olur.	\
**Ç.**Pekâlâ, Hacivad Çelebi! Siz şu parayı alınız da icabına bakın! Ben yine sizi görürüm. Allaha smarladık.	\
**H.**Sefa geldiniz!	\
(Muamma asılır, Karagöz gelir.)	\
\
**K.**Ulan. Hacivad! Yirmi liraya dört kavanoz murabba olur mu?	\
**H.**Murabba değil, muamma.	\
**K.**Ben sana yalnız paraları yedirmem. Raconca bir mirasyediye iki dalkavuk.	\
**H.**Hay budala hay!	\
**K.**İster bu dala, ister öbür dala! Hacivad, sen de herkesin suratını yala!	\
**H.**Vay horozakıllı Karagöz vay!	\
**K.**Vay hindifikirli Hacivad vay!	\
**H.**Ulan, nasıl murabba?	\
**K.**Şimdi gelen Züppe bey ile murabba lâkırdısı etmiyor muydunuz?	\
**H.**Karagöz, öyle züppe müppe diye ulu orta yürüme! O zatı âli kadir ashab-ı haysiyetten bir zattır.	\
**K.**Astarcı Ahmede senedi mi var?	\
**H.**Değil a canım! Kendisi zengin, ehl-i dil bir mahbup.	\
**K.**Elekçi Deli Malımud mu?	\
**H.**Ona meşhur Zater Bey derler.	\
**K.**Zaten bey olduğu halinden belli.	\
**H.**Karagöz, bunlar beş kardeştir.	\
**K.**Hacivad, ben bunların beşini de bilirim.	\
**H.**Diğer kardeşlerin adı nedir bakayım?	\
**K.**Birinin adı Adaçayı, öbür kardeşinin adı Ihlamur çiçeği, ortancasının adı Ağaç hatmisi, en küçüklerinin Mülver çiçeği. Nasıl, bildim mi?	\
**H.**Haydi, diyelim ki bildin. Bunlar nerede bulunurlar bakayım?	\
**K.**Mısırçarşısında.	\
**H.**Hay utanmaz budalâ! Eğer senin söylediklerini beyefendi duyarsa seni kavur kavur kavurur.	\
**K.**Ben de, Hacivad,eşek öksürüğüne tutulursam, bunların beşini de bir araya getirip mangalın kenarında dumanlarım havaya uçururum!	\
**H.**Bilâtler, sen rezaleti ayyuka çıkarıyorsun!	\
**K.**Zerdaliyi tabaktan kim çıkarıyor?	\
**H.**Muamma dediğimiz şey yok mu?	\
**K.**Yok mu var mı, ben ne bileyim?	\
**H.**Yukarıda asılı olan.	\
**K.**Ulan, ne tuhaf. Bitparzanndaki Hacı Hasan sokağının şubesi buraya mı geldi ?	\
**H.**Canım, sen hiç âşık görmedin mi?	\
**K.**Gördüm.	\
**H.**Nerede gördün bakayım?	\
**K.**Mahmudpaşa başında.	\
**H.**Mahmudpaşa başında âşık var mı?	\
**K.**(kendi kendine),hay sersem keşanî hay!	\
**H.**Koskadaki Simkeş hanı mı?	\
**K.**Hayır! Bayezitteki Bakkal Yani.	\
**H.**Mahmudpaşa başmda olan âşıklar ne cins âşıklar?	\
**K.**Şimşiri var, abanozu var, alelhusus manda boynuzu var. Bu cins âşıklar.	\
**H.**Acayip! Bu âşıklar beste okurlar mı?	\
**K.**Ustaları dükkândan gittiği vakit çırakları beste, mani, şarkı gelsin!	\
**H.**Senin dediğin adeta kaşık!	\
**K.**Kaşık zâhirî	\
**H.**Karagöz, ömründe hiçbir tir-i müjgâna vurulmadın mı?	\
**K.**Ben ömrümde, Hacivad, karadan Tarabyadan Mirgûna giderken yorulmadım.	\
**H.**Bilâder, yaz mevsimi hiç Yenikapıya gitmedin mi?	\
**K.**Evet, gittim.	\
**H.**Orada âşık görmedin mi?	\
**K.**Karpuz çalarken sergiciler beni görmesin diye etrafa baktığım var mı?	\
**H.**Bazı kahvehanelerde âşıkların saz çaldığını işitmedin mi?	\
**K.** İşittim.	\
**H.** Güç hal ile anlattık! Ne diyorlar bakayım?	\
**K.** Âşık taratoru, içer misin çalaboru’?	\
**H.** Ha ha ha!	\
**K.**Kerata eğleniyor!	\
**H.**Eğlenmek değil, ben sana işi anlatayım.	\
**K.**Anlat bakalım!	\
**H.**O  âşıkların hepsinin birer mahlası vardır: Kiminin Mahzuni-, kiminin Hemrahi, kiminin Seyyahî, kiminin Cevheri, benim mahlasım da Mesruri.	\
**K.**Benimki de Maymun! olsa olmaz mi? O zaman da çingenelik size intikal etmiş ulur.	\
**H.**Öyle isim olur mu?	\
**K.**Zerdali olsun!	\
**H.**Meyvadan isim olmaz.	\
**K.**Pek doğru! Manavların elinden yakamı kurtaramam.	\
**H.**Karagöz, kendine birisim bul!	\
**K.**Ne isim bulayım? Benim ismim de Gelberi olsun!	\
**H.** Pekâlâ, senin ismin de Gelberi olsun.	\
**K.** Baksan a Hacivad! Murabbaınn içinde ne var? Ne yazılı?	\
**H.**Bilemezsin, hem bulamazsın.	\
**K.**Hele sen söyle bakayım!	\
**H.**"Bende vardır, sende vardır, âlemde yok, cümlede vardır amma adamda yok."’	\
**K.**Bildim.	\
**H.**Nedir bakayım?	\
**K.**Züğürtlük, ne olacak?	\
**H.**Karagöz, zevzekliği bırak.Sonra gelen âşıklar adamı mat ederler.	\
**K.**Ben de dayakla onları alt ederim, Hacivad.	\
**H.**Pekâlâ. Öyle ise, kendine bir saz bul, kıyafetini de değiştir, tebdil-i came ol!	\
**K.**Camekânda kimi bulayım?	\
**H.**Elbiseni değiştir.	\
(Karagöz gider, Hacivad da gider, şarkı ile Çelebi gelir.)	\
\
Şarkı HicazkâP	\

Gönlümü duçar iden bu hale hep,\
Karagözlüm, kara bahtımdır sebep! \
İttiğim ah ü figandır ruz u şep!	\
Nakarat: Karagözlüm, kara bahtımdır sebep!	\
\
İstemezsin sen perişan olduğum, \
Ateş-i aşkınla nalân olduğum \
Sine çak u dide gıryan olduğum!	\
Ey zan.	\
\
**Çelebi.** Nasıl oldu, Hacivad Çelebi?	\
 **Hacivad.**.Efendimiz, siz hiç merak etmeyin! Muamma asıldı, refikim Karagöz Ağa da bu işe iştirak ediyor, tebdil-i came olup gelecek. Şairlerin gelmesine muntazırız.	\
**Ç.**  Pekâlâ! Şimdi âşıklar gelecekler, ben de köşkten dinliyeceğim. siz de teşrif ederseniz beraber dinleriz.	\
**H.**Siz teşrif ediniz, bendeniz de şimdi gelirim.	\
**Ç.**Allaha ’smarladık!(Gider.)	\
**H.**Safa geldiniz!(Gider.)	\
**Karagöz.**(içeriden).Abla! Şu un torbasını bana versene!	\
**Karısı.**Herif, un torbasını ne yapacaksın? Çoktanberi canım tatarböreği  istiyor, un mu alacaksın?	\
**K.**Ulan! Ne açgözlü karısın be! Sen şu torbayı ver, yumurta tavasını da ver, kaşık sepetindeki kaşıkları da getir!	\
**K.k.**Herif, tekmil ev eşyasını götüreceksin. Al bakalım!	\
**K.**Şu çamaşır ipini de tavanın üstüne birkaç defa dola da uçlarım kaşıklara bağla da bana ver!	\
**K.k.**Ne olacak böyle?	\
**K.**Elinin körü olacak! Sen onları yap. ben de şunları başıma giyeyim!\
**K.k.**Aman herif, ne tuhaf oldun!	\
**K.**Eğlenme, köpoğlu!	\
(Karagöz perdeye gelir. Hacivad da gelir.)Nasıl kıyafetim, Hacivad?	\
**H.**Pekâlâ, bilâller. Şimdi âşıklar burada tecemmü edecekler.	\
**K.**Kaşıklar tecennün mü edecekler?	\
**H.**Benden görürsün külli zararı.	\
Aradım buldum seni firari.	\
**K.**Karşıma geçtin koca hımarî	\
Suratına yersin benden şamari!	\
**H.**Şimdi Selanik tarafından bir âşık geliyormuş, kendini gözet.	\
**K.**Geleceği varsa göreceği de var.	\
**H.**Çok ustaymış.	\
**K.** Ondan yana merak etme, kalbini geniş tut!	\
**H.**Aman Karagözüm, göreyim seni! Beni mahcup etme!	\
**K.**Sen kasavet çekme, hemen gelsinler.	\
**H.**Ben gidiyorum, Karagöz.(Gider.)	\
**K.**Canım, yok mu âşıklardan kaşıklardan?	\
**Aşık Hasan** (gazel ile gelir).	\
Yârin bu kadar çevri gelir miydi hayale ?	\
Gûş itmedi ahım, beni döndürdü hilâle. \
Rüyada bile payını bus itmeği görmem.\
Elden ne gelir ağlamadan başka bu hale?	\
**Hasan.**Merhaba, âşık!	\
**K.**Hoş geldin, bulaşık!	\
**Ha.**Baba, âşık mısın?	\
**K.**Hayır, incik kemiğiyim.	\
**Ha.**Ne dedin?	\
**K.**Mercimek çorbası.	\
**Ha.**Cihangir sakası mı?	\
**K.**Firuzağa bekçisi.	\
**Ha.**Bak, ben senin namım işittim de Serezden kalkıp Selânikten buraya kadar geldim.	\
**K.**Ben de öyle.	\
**Ha.** Sen nereden geldin bakayım?	\
**K.**Selâmsızdan kalktım, Üsküdardan buraya geldim.	\
**Ha.**Öyle ise, biraz seninle kaynaşalım.	\
**K.**Orası biraz güççe.	\
**Ha.**Neden?	\
**K.**Malûm ya! Sen Selânikten, ben Selâmsızdan, kırk yıl kaynasak, etimiz ayrı, kemiğimiz ayn düşer, anlarsın ya?	\
**Ha.**Tuhaf bir zate benziyorsunuz!	\
**K.**Evet, tuhafçılardaki eczacıya benzerim.	\
**Ha.**Söylediğiniz lisan-ı âhar mı?	\
**K.**Evet, bizim saat nisan aymdanberi ayardır, bir dakika bile şaşmaz.	\
**Ha.**Şimdi seninle gazel, koşma yapalım!	\
**K.**Gazinoda araba mı koşturalım?	\
**Ha.**Değil a canım.Bir semaî çıkalım.	\
**K.**Semaya mı çıkalım? Tayyare ile mi?	\
**Ha.**Anlayamadınız, âşık. İstersen Keremden çıkalım!	\
**K.**Kiremide çıkacağız amma, akan yer var mı acaba?	\
**Ha.**Meramımı anlayamadınız! Garip okuyalım!	\
**K.**Garip köpek gibi mi uluyalım?	\
**Ha.**Aşık, ben bir divan okuyorum.	\
**K.**Varıver bakalım!	\
**Ha.** (makam ile söyler.)	\
\
Hasta-i âşık u bol muhabbet derde derman istemez.\
Sıhhat  ümmid itmiyen elbette Lokman istemez.	\
\
**K.** Hasta aşık bol yumurtalı revani istemez\
Sahan dolu yahni olsa ballı lokma istemez \
**Ha.**Suiâdab-i muhabbettir, ne lâzım, kil ü kal? Halet i aşkı bilir erbabı ilân istemez.	\
**K.**Sütlü muhallebi âlâdır, ne lâzım portakal? Aşureyi bizim âşık sever,, ilân istemez.	\
**Ha.** Yapmağa sây it gönül yıkma, Hüdadan kıl hazer!	\
Mülkünü elbette sahiphane viran istemez!	\
**K.**Yarma şeftali sepetten uçtu, al benden haber! Suluca armut yerine kimse şalgam istemez.	\
**Ha.**Gönül birden ırak olmaz hayal-i aşk-ı dilberden.	\
Geçersem ben, gönül geçmez cihan içre güzellerden.	\
**K.** Bilirim ben: vefa gelmez şaşı ile o körlerden,\
Çalarsam ben, manav görmez usuletle o döngelden.	\
**Ha.**  Bugün bir zahidin biri güzel sevmeği men' itmiş.	\
Bulunmamış mı bir âşık? Ataydı anı minderden!	\
**K.**Afyonumun vakti geçti, uyuklayıp durur iken.\
Bana bir tekme vurdular, yuvarlandım o minderden.	\
**Ha.**Felek seyyah-ı âlemdir, sakın, aldanma Gelberi!	\
Nekadar kahraman olsan, geçersin yine çemberden!	\
**K.**Dayak hiç kaydıma gelmez, hicabım yok rezaletten.	\
Benim hergün merakımdır kebap çalması lengerden.	\
**Ha.** Ketmi müşkül ateş-i aşkı ayan itmek de güç, Şulei şem-i firuzanı nihan itmek de güç.	\
**K.** Kirli peşkir suya düştü ise kurtarmak da güç,	\
Kibriti rüzgârda çakıp şamdanı yakmak da güç.	\
**Ha.** İntizar-i rü’yet-i canan, veli, âsân değil,	\
Vasl için amma rakibe imtinan itmek de güç.	\
**K.** Üsküdardan kilimi çalan o Kel Hasan değil,	\
Sarmısaklı yahninin üstüne su içmek de güç.	\
**Ha.**  Şayed eyler hatırın azürde ol mahın deyü, Dud-i ahı ru berah-i asiman itmek de güç.	\
**K.**Martta turşu yemekten sardalya yemek çok âlâ,	\
Kasımın yüz sekseninde portakal yemek de güç.	\
**Ha.** Yâre talim-i vefa eylerdim amma neyleyem?	\
Zor ile namihribanı mihriban itmek de güç.	\
**K.** Benim gibi bir garip çingeneye lâyık mıdır?	\
Küşteri meydanında sazcılık etmek de güç.	\
\
Garip. Makam-ı Hicaz	\
**Ha.**  Gûş eyle, efendim, dinle ahımı	\
Muhabbet bağında gonceye hemrah	\
Aşıklar görürse dayak var sana.	\
Rezalet muamman, Âşık Gelberi?	\
**K.**     Kulakları kısıp zırlama bana!	\
Birdenbire sonra hırlarım sana!	\
On iki köşe haymedir amma,\
Verası ummandır, Âşık Serseri!	\
**Ha.**  Aşkın bağındadır o gül-ü ziba.	\
Goncaya meftundur alidedir vefa,\
Âşık maşukuna bülbül-ü şeyda.	\
Eşek aştan anlamaz, Âşık Gelberi!	\
**K.** " Eşek aştan anlamaz" sen dedin bana,\
Müstamelce bir palan vurayım sana!\
Doğruca gidersin Atpazanna.	\
İşte palan geliyor. Âşık Serseri!	\

(Karagöz vurur, Aşık Haşan gider. Şarkı ile Kayserili gelir.)	\
\
Ben bir Köroğluyam, dağda gezerem,\
Esen rüzgârdan hile sezerem, \
Demir külünk île başın ezerem.	\
Çabuk yap benim sazı sazımı-!	\

Tokat kervanından aldım bakırı.	\
Sevdiğim gelsin göreyim çakırı!\
incitmeyin fıkara-yı fakiri!	\
Eyzan.	\
\
**Kayserili.** Bana bakh, Aşıklı ağa!	\
**K.**Ne var, Armut ağa?	\
**Kay.**Canım, burada bir Karagöz mü ne itin bokhu varmış. Onu bilün mü?	\
**K.**Gelir gelmez gördün mü yediği boku?	\
**Kay.**Çünkü memleketten taze geldim de, o köpoğlu herifle sözleşmek içün haber alıp buraya geldim. Bana diyiver!	\
**K.**Oğlum, öyle ulu orta gitme, belki kulağına gider!\
**Kay.**Brakh şu it bokhu herifi sen de!	\
**K.**Buyurun bakalım! Ölür müsün öldürür müsün? Baksan a bana! Benim gözüm seni ısırıyor. Sen Odun kapısında mı eğleniyorsun?	\
**Kay.**Odungapusunda işim ne? Biz Barnakhgapu ile Tavukhpazarında eyleşiriz.	\
**K.** Galiba ben geçen gün sana benzettim. Zeyrek yokuşundan geçerken kereste yüklü eşeklerin birinin ayağı kayıp yan üstü düştü. Sonra sen mi idin yoksa sana benzer birisi mi idi? Deh çüş diye biçare hayvanı kaldırdı.	\
**Kay.**Ulan, kıyafetime bakhanda beni eşekçi mi zannettin kotu kopoğlu kopek! Barnağımı ağzına sokharsam it buzuğu gibi yırtarım!	\
**K.**Varıver, yarım osuruk!	\
**H.** Ne dedin?	\
**K.**Sana göre değil.(Kendi kendine:)Herif zorlu be!	\
**Kay.**Bana melmekette ..Suyabatmaz" derler, âşıklar beni barnakhla gosteriller.	\
**K.**Ben de adamı buradan yumrukla kaçırırım.	\
**Kay.**Ne dedin?	\
**K.**Sonra anlarsın ne dediğimi.	\
**Kay.**Suya mı atlarsın?	\
**K.**Benden dayak yersin, anlarsın.	\
**Kay.**Sıfatına bir vurursam, kotu kopoğlu kopek, görürsün he!	\
**K.**Maraza mı edeceğiz, yoksa saz mı çalacağız?	\
**Kay.**Sana bir divan geliyorum.	\
**K.**Buyurun bakalım 	\
**Kay.**Laubali meşrebim, gayd u vagar olmaz bana.	\
Âşıg-ı şurideyem. namus u ar olmaz baha.	\
**K.**     Lâlelide şerbetçinin kavuğu gelmez bana.	\
Aşure kâsesi gibi bol külah olmaz bana.	\
**Kay.**  Cam-i lebriz-i muhabbetle ezel mest olmuşam,\ 
Bade-i gülgûn ile def-i humar ohnaz bana.	\
**K.**     Camcı İzzetle bugün meyhanede dost olmuşum, Bademi küfeyle yutsam hiç haram olmaz bana.	\
**Kay.**  Yanmadıkça ateş-i aşk u muhabbetle’ tenim.	\
Rahat ü aram zevki ihtiyar olmaz bana.	\
**K.**Yakmadıkça poğaçayı börekçi aşk olsun derim.	\
Rahatça pösteki varken şilte ram olmaz bana.	\
**Kay.**Bir de Keremden yırlıyalım!2	\
**K.**Hırla bakalım, köpoğlu \
\
Makam-ı Hicaz	\
**Kay.**  Gönül, seni kime, idem şikâyet? Her zaman başıma baltasın, gönül’\
Nerde güzel görsen efkârın artar, çekersin bin türlü belâyı, gönül!	\
**K.** Kel oğlandan hiç olur mu inayet ? Her zaman başıma baltasın, gönül	\
Nerde bir kel görsem safram kabarır, artar midemin fesadı, gönül!	\
**Kay.**  Dil, güzel sevmekte kesb ü kâr ittin.	\
Ol kadar sevdin ki aşikâr ittin,\
Sen beni bu derde giriftar ittin, \
Akibet beni de dilfigâr ettin!	\
**K.**Dil, üzüm yemekle kesb ü kâr ettin,\
O kadar yedin ki işkembeni dar ettin.\
Pisboğazlıkta sen iştigal ettin, \
iskete gibi dalda bıraktın gönül.	\
\
**Kay.**  Bir ateş saçtılar canım evine.	\
Azalarım tutuşmağa başladı.\
Bastırdılar şamadanın eline.\
Pervaneler uçuşmağa başladı.	\
\
**K.**    Bir ateş attılar samanlığın içine. \
Arpa, buğday tutuşmağa başladı. \
Aldı ateş fundaların ormanı.	\
Çingeneler ağlaşmağa başladı.	\
\
**Kay.**  Nazlı yârden beni ayıran adam,\
Dilerem Haktan kör olsun gözü!\
Talihim akrep midir bilmem nedir,\
Benim gönlüm tutuşmağa başladı.	\
	\
**K.**    Ağzımı sulandırdı ekmekkadayıfı,	\
Açlıktan benim karnım gurulmağa başladı.	\
Sütçünün güğümünden çıkardılar akrebi.	\
Akrebi gören savuşmağa başladı.	\
**Kay.**  Sana bir semaî söyleyim!	\
**K.**İster samanlıkta söyle, ister burada söyle!	\
**Kay.**Geliyor!	\
**K.**Hırlamağa başla!	\
**Kay.** Diriğ itme, felek, çevrin dile, hadden ziyad olsun.	\
Cihana bahş-i lûtf it. halk memnun ulfuad olsun.	\
Değil kizb ü kinaye, sözlerime itimad olsun.	\
Der-i ünımid gapansun bana tek gayre küşad olsun!	\
Yıkhanlar hatır-ı viranemi, ya rabbi. şad olsun!	\
Benimçün: Namurad olsun! diyenler bermurad olsun!	\
\
**K.**    Cihangirden Karamana yayan gidene aşk olsun!	\
Uyuz tazı ile yatmak sana her dem reva olsun!	\
Şeker kâğıtlarından gecelik sana külâh olsun!	\
Bizim eşek için yemlikte arpayla yulaf olsun' Tatarböreğini yersen içi hol sarımsak olsun! Tatlılardan âlâ tatlı bana bir balkabak olsun!	\
\
**Kay.**Geçirdi kahrı peyderpeyle gerdun cangüzarimden \
Bilinsün maceramız işte çeşm-i eşkbarimden! \
İdersem şikve namerd olayım ağyare yârimden, Gırılsın şişeveş dil gorkhmasunlar inkisarimden.	\
Yıkhanlar hatır-ı viranemi, ya rabbi, şad olsun!	\
Benimçün: Namurad olsun! diyenler bermurad olsun!	\
\
**K.**    Geçerdim günde on kerre Çeharşembe Pazarından, \
Gidüp hergün çalardım ben manavın ekşi narından.\ Bizim eşek zırlar daim senin gibi merakından, Usandım bizim ayının gece gündüz tımarından.	\
Tatarböreğini yersen içi bol sarımsak olsun!	\
Tatlılardan âlâ tatlı bana bir balkabak olsun!	\
\

**Kay.**  Sitemlerle niçün ol bivefa yâr uydu ağyare?	\
Cefasından safalar kesbedüp zevk itmedi çare.	\
Nasib olan budur çün muttasıl bu âşıkh-ı zare, Dil-i zarım elimde zabt olup incitmesün yâre!	\
Yıkhanlar hatır-ı viranemi, ya rabbi. şad olsun!	\
Benimçün: Namurad olsun! diyenler bermurad olsun!	\
\
**K.** Geçen bayram yapıp sattım beş on maşayla ızgara,\
Ahıra bir kapan kurdum, tutuldu bir iki fare.	\
Bizim eşek uyuz olmuş, acep yok mu buna çare?	\
Geçende bir tavuk aldım, yine olmuş sekiz pare.	\
Tatarboreği yersen içi bol sarımsak olsun!	\
Tatlılardan âlâ tatlı bana bir bal kabak olsun!	\
\
**Kay.**  Alıştım, ülfet-i mihnetten olmam bir nefes mehcur,\
Dil-i mahzunu görmek istemem şimdengerü mesrur. Benim gasr-ı safada yokh yerim, mazur tut mazur!	\
Benim evradım olsun bâdezin bu matla -i meşhur: Yıkhanlar hatır-ı viranemi, ya rabbi. şad olsun!	\
Benimçün: Namurad olsun! diyenler bermurad olsun!	\
\
**K.**Samatyadan geçer iken atardım bazan çarmak çur\
Geçen gün olta attım denize tuttum iki çurçur.	\
Kadın ninem sağ iken dokur idi çevreyle uçkur,	\
Geçen gün oğlan kazmış hanenin önüne bir çukur.	\
Tatarböreğini yersen içi bol sarmısak olsun!	\
Tatlılardan âlâ tatlı bana bir balkabak olsun!	\
\
**Kay.**  Bana bakh, yapma, aşıkh! Sen ağzına ne gelirse söylüyorsun, ben muammayı alacağım.	\
**K.**  Ben de seni buradan dayak ile kovacağım!	\
\
(Vurur Kayserili gider. Şarkı ile Tiryaki gelir.)	\
\
Şarkı Isfahan	\
Fesleğen ektim, gül bitti,\
Dalında bülbüller öttü.	\
Ötme, bülbül! Yârim gitti!	\
Nakarat: Ben dertliyim, kan ağlarım.	\
**Tiryaki.**Merhaba âşık!	\
**K.**Başını sokma, Tiryaki, kaplar bulaşık.	\
**Ti.**Benim şair olduğumu biliyorsun ya?	\
**K.**Elindeki sazı görenler elbette anlar amma, bakalım sözüne!	\
**Ti.**İnsan kocar amma, gönül kocamıyor. meşhur mesel.	\
**K.**Öyledir.	\
**Ti.**Ben şimdi bir divan söyliyeceğim. karşılığını isterim.	\
**K.**Söyle bakalım!	\
**Ti.**Sakiya, kanım ile doldur kadehler boş iken	\
Vâre sun Allah İçün fursat demi mey nuş iken.	\
**K.**Samatyada bir tek attım tezgâh başı boş iken.	\
Birkaç tabak kadeh çaldım meyhaneci yok iken.	\
**Ti.**İdemez elbet sabah el-haşredek def-i humar,\
Cam-ı lebriz-i muhabbetle gönül sarhoş iken.	\
**K.**Ayık olsam meyhaneci beni tezgâhtan kovar, Camcı izzetle muhabbet eyledim sarhoş iken.	\
**Ti.**Çerhi yıkmazsa yıkar ah-i derunum.\ çıkmasın!	\
Elhazer, açtırma ağzım, ey felek, hamuş iken!	\
**K.**Benim ile meyhanede hiç kimse yoldaş olmasın!	\
Babam olsa yoklarım ben ceplerini sarhoş iken.	\
**Ti.**  İşte maksudum o gülfemden nihanın duymasın!	\
Lâl-i nâbın nuşedip amma dehanın duymasın.	\
**K.**     Nane yağını boş şişeye koy ki ablan duymasın!	\
Ağzını da güzel kapa, kokusunu kimse duymasın!	\
**Ti.** Öldürürsen kendin öldür bendeni, kaşı keman	\
Hançer-i üryanını çek vur. meyanın duymasın!	\
**K.**Öldürürsen kehleyi başında öldür, sonra ha!	\
Çingeneden şair olmaz, çeribaşı duymasın!	\

**Ti.**  Birde Garipten söyliyeceğim.	\
**K.** İster garipten söyle, ister zenginden.	\
**Ti.**  Muammadan maksad arz-i muhabbet,	\
Yârana safadır bezm-i letafet.	\
Sen gibi hayvan ile olur mu ülfet?	\
Tavşan nu muamman, Âşık Gelberi?	\

**K.**  Hor bakma bizlere! Biz de sizdeniz,	\
üstadım Hacivad, çırak bendeniz.	\
Zevk u sevka daim biz de hemdemiz.	\
Hor bakına bizim, Aşık Kimyoni!	\
\
**Ti.** Muamman sahtedir, kafiye bitti,	\
Sen gibi âşıklar Tantuna gitti.	\
Yalanın şimdi senin meydana çıktı.	\
Doğruca haber ver. Aşık Gelberi!	\
\
**K.**Bir ustam var idi gayet tiryaki,	\
Afyon diye öte dünyaya gitti.	\
Dayağın meyanesi biraz gecikti,	\
Hazır ol vaktine, Aşık Kimyonî!	\
\
(Karagöz Kimyoniye vurur, Tiryaki gider.)	\
**K.**    Vay kerata vay. seni afyoni seni! Var mı daha dayak yiyecek? Kendine güvenen gelsin!	\
\
(Bebe Ruhi şarkı ile gelir.)	\
\
Ben bir yanaz tazeyim .. .*	\
\
**Bebe Ruhi.**Merhaba baba! Nasıl, eyi misin? Ben eyiyim, sen de eyi misin?	Benim keyfim eyi. seninki de eyi midir?	\
**K.**Ulan, bu nekadar lâkırdı!	\
**B.R.**Baha, sen âşık mısın?	\
**K.**Aşığım.	\
**B.R.**Bana mı?	\
**K.**Defol şuradan, işkembe suratlı! Senin nene âşık olacağım?	\
**B.R.**Baba, başlıyorum!	\
**K.**Başla!	\
**B.R.** Nereden başlıyayun? Sinsilenden mi?	\
**K.**Ben şimdi senin yedi ceddinden başhyacağım!	\
**B.R.** Maşallah, de! Sesime nazar değmesin!	\
**K.**Daha başlamadın, sesini kim işitti?	\
**B.R.**Ben karnımdan söyliyeceğim.	\
**K.**İster karnından söyle, ister ağzınla söyle! Galiba dayak yiyeceksin.	\
\
**B.R.** Makam-i Karacığar.	\
Aman, ey şuh-u levendim, âşık oldum sana işte.. Merhamet it bana zira: sev ki beni, sevdim seni.\
\
**K.**Havaya attım kemendim, boyunu ben pek beğendim.	\
Gördükçe midem bulanır, sevme beni, sevmem seni.	\
\
**B. R.** Vuslatini canım ister gece gündüz hayalimden, \
Firkatinden usandım ben, sev ki beni, sevdim seni.	\
**K.** Dayak ister senin canın, işte geldi meyanesi.\
Hazır ol vaktine yahu, sevme beni, sevmem seni.	\
\
(Tokat vurur. Bebe Ruhi gider.)	\
**K.**Ulan, ne tuhaf âşıklar geliyor!	\
(Şarkı ile Kabakçı Arap gelir.)	\
**Arap.** Ulak, ben nerede geldi?	\
**K.**Al budalanın birini daha! Burası, Hacıbaba, Şeyh Küşteri Meydanı.	\
**A.**Eşekçilerin bayramı mı?	\
**K.** Lâkırdı anlıyan beri gelsin! Buraya niçin geldin?	\
**A.**Burda kaşıklar varmış.	\
**K.**Vardı, Hacıbaba, amma ahçıbaşı götürdü.	\
**A.** Ulan kablak kulaklı! Benimle eğleniyor musun?	\
**K.**Hayır, tek kürekle mehtaba çıkıyorum’.	\
**A.**Burda murabba varmış, nekadar kaşık varsa gelsin! Onlarla imtila olajağım.	\
**K.** Senin sazın onların sazına benzemez, sözünü aslâ kimse dinlemez!	\
**A.**  Benden korktunuz galiba.	\
**K.**Hacıbaba, sen ne çalarsın?	\
**A.**Kabak.	\
**K.** Bağçıvan görürse ananı ağlatır. Hacıbabanın yediği halta bak!	\
**A.**  Başlıyorum.	\
**K.**Başla bakalım!	\
**A.**  Kabak şakırını. dızdızdıdızdız, Kara Fatma, dızdızdıdızdız! 	\ 
Kabak şalarım, dızdızdıdızdız, Kara Fatma, dızdızdıdızdız 	\ Kısmetim ararım, dızdızdıdızdız. Kara Fatma, dızdızdıdızdız!	\
Kısmetim ararım, dızdızdıdızdız, Kara Fatma dızdızdıdızdız'	\
**K.**Bunun içinde beyaz yok mu, hep kara mı?	\
**A.**Yaktı beni gâvurun kızı, dızdızdıdızdız!	\
Şayir şayir yaktı benî, dızdızdıdızdız’	\
Yaktı beni gâvurun kızı, dızdızdıdızdız!	\
Şayir şayir vakti beni, dızdızdıdızdız!	\
**K.**Ulan, bunda ne kafiye var. ne bir şey!	\
**A.**Bizim kâhya kadın haram yemez, dızdızdıdızdız!	\
Şarşuya gider basma şalar, dızdızdıdızdız!	\
Bizim aşçı haram yemez, dızdızdıdızdız!	\
Dolaptan yemek şalar, dızdızdıdızdız'!	\
**K.**Hacıbaba, kafiye bitti!	\
**A.**Ben öyle nafiye fulan anlamam, muammayı alır giderim.	\
**K.**Anlaşıldı, Arap balta, ben de satır!	\
**A.**Ben alajağım.	\
**K.** Bizim evde kırıldı testinin kapağı,	\
Hacıbabanın dinlenmiyor asla kabağı.	\
\
(Taklit vurur, Arap gider, Hacivad gelir.)	\
**H.** Ey Karagözüm, geçmiş ola! Beyefendi sizi bekliyor. Birlikte gidelim paraları alalım!	\
(Karagöz ile Hacivad giderler defa gelirler.)	\
\
**K.** Çok yoruldum, Hacivad, edelim mola!	\
**H.**Çok şükür sağlığa!	\
**K.**Hak bereket versin Kâğıthanelerde biten sazlığa!(Tokat.)	\
**H.**Yıktın perdeyi, eyledin viran,	\
Varayım sahibine haber vireyim heman.	\
**K.**Hernekadar sürci lisan ettik ise affola! Yarın akşam "Kırgınlar" oyununda yakan elime geçerse, bak, ben de sana neler yaparım!	\
