


# kirginlar yahut abdal kardeşler

 **Hacivad.** (semaiyi soyliyerek perdeye gelir).	\
\
Semai Rast	\
\
Gelse o şuh meclise, naz u tegafül eylese,	\
Reng-i hicabı gülşen-i meclisi gül gül eylese,	\
Tâneger-i riyaz-ı huld olur idi vücuh ile, \
Aşık-ı zari gülşen-i vaslına bülbül eylese!	\
Ti ri lel le le le le le le le le le le li.	\
Canım yele le le le le le le le le lel li'	\
Hay Hak.	\
\
(Perde gazelini okur.)	\
\
Benim devletlû sultanım emanet ola Rahmane!	\
Kapısında emekdarım gelüp ol ulu divane.	\
Bihamdillah eriştik meclis-i ashab-ı irfane,\
Sefa bahş idelim bülbül gibi sahn-i gülistane.	\
Nola huzur-u yaranda iderken marifet icra,	\
Virem revnak demadem mecma'-i erbab-ı rindane!	\
Şehinşah-i cihanı hıfz, ide Mevlâm kederlerden! \
Niyazım ruz u şeb budur cenab-ı Rabb-i mennane.	\
Kusurum aff ola özrüm kabul ola huzurunda, \
Hatamı umarım mazur edüp bakmaya noksana!	\
Hayalî Gice gündüz durmayup evkat-i hamsede, \
Açup destin dua eyle o şah-ı zıll-i Yezdane!	\
(Kavgadan sora:)	\
\
 **Karagöz.**Her akşam gelir devlethanemin destgâhına, bülend avaz ile tedenniye başlar, ahali-i mahalle senden taciz naçiz oluyor! Efendim, senin elfaz-ı galîzanı kimse dinlemez. Mademki geliyorsun hımarane gelip de dakk-i bab, fındık kebab edip tasdi'a cür’etle birbirimizle müsavat etsek olmaz mı? Efkâr-i ubeydanemi bir türlü kendisine tekellüm ettiremiyorum, ifade-i hal, kil u kâl edecek yerde bir rezalet, bir gürültü, bir vaveyla kopuyor.Senin gürültünden patırdından mustaklâ oluyorum. Efendim, beni kendi halime brakmiyor ki eçhel herif, rahat evimde oturayım! Kulunuz köşe-i inzivaya çekilüp divan mükâleme ediyordum. Nagehan o eşkal Hacivadın kerih sesi semtime vâsıl olur olmaz  binaenaleyh hiddet ü şiddetim galeyana başlıyor, iradem elimden gidiyor, hane derununda duramayıp pencereden atlıyorum, gırtlak gırtlağa boğuşuyoruz, rezaletimiz ayyuka çıkıyor! Neme lâzım benim? Ben de gider evimde yan gelirim.(Gider.)	\
 **Hacivad.** (gelir)Vay, Karagözü kaçırdık. Ben şimdi onu aşağıya getirtirim.— Galiba hasta olmalı. Gel. francalacı, benim Karagözüm hasta, şundan bana iki okka francala ver, al parasını! Bana baksan a. o limonlar kübbat mı? Yo, iki kuruş çok, altmış para! Ver bakalım beş tane, al parasını! O portakalları kaça veriyorsun? Altı kuruş mu? Çok! Üçer kuruş! Ver ondan da, al parasını!	\
 **K.** (içeriden).Abla!	\
**Karısı.**(içeriden).Ne var, herif?	\
 **K.**Benim üstüme bir yorgan ört!	\
 **K.k**Ne o? Üşüyor musun?	\
**K.**Nene lâzım senin? Ört!	\
 **K.k**Örttüm.	\
**H.**Bana baksan a, gevrekçi! Kaç kuruşa gevrek okkası? On sekiz mi? Ver bana bir okka, al paranı! O pastalar kaçar kuruş? Yüzer para mı? Ver ondan bana beş tane, al parasını!	\
**K.**(içeriden).Abla, benim üstüme bir yorgan daha ört!	\
 **K.k**.üşüyor musun?	\
**K.** Değil a canını! Hacivad beni hasta zannediyor, hatır sormaya gelecek onun için.	\
**H.**Karpuzlar kaç kuruş? Onar kuruş mu? Altı kuruş, haydi yedi olsun!	Ver bakayım bana beş tane!	\
**K.** Abla, bir yorgan daha Ört!	\
 **K.k**Herif, boğuluyorsun!	\
**H.**Gel, küfeci! Benim Karagözüm hasta imiş, bunları oraya götüreceğim. Kaç para vereyim? Beş kuruş, haydi!	\
**K.**Bari ben gideyim de Hacivaddan yemişleri alayım! (Ağır ağır yürüyerek, hasta gibi perdeye gelir.)Aman, ay, aman, ay. hiç dermanım yok!	\
**H.**Karagöz, ne oldun? Hasta mısın?	\
**K.**Aman, Hacivad; hiç sorma! Yan belimden aşağısı tatmıyor.	\
**H.**İlâç yapmadın mı dahilî haricî?	\
**K.**Tahini yaptım pekmezle.	\
**H.**Canım, nasıl tahin? ilaç kaynatıp içmedin mi? Ağrıyan yerlere kâfur ruhu sürmeli!	\
**K.**Yaptım amma, fayda etmedi. Kuzum, Hacivad. o aldığın şeyleri ver de eve getireyim!	\
**H.** Nasıl aldığım şeyler?	\
**K.** Beni hasta diye portakal, francala, kübbat limonu, pasta, karpuz almadın mı? Seni yormayım diye ben geldim, halim de yok.	\
**H.**Hayır, hi—ç!(Der gider.)	\
**K.**Vay, köpoğlu beni aldattı ha!(Eve gelir.)Abla!	\
 **K.k**. (içeriden).Ne var, ne istersin?	\
**K.**Köpoğlu Hacivad beni aldattı!	\
 **K.k**.Ne diye aldattı?	\
**K.** Ne diye olacak? Sokakta beni hasta zanniyle yalandan portakal aldı, francıla aldı ve sair şeyler almış gibi kendi kendine konuşuyor; ben de sahi zannettim gittim, ,,Aldığın şeyleri ver bana!" dedim, ,,Hayır, hi—ç"! dedi kaçtı.	\
 **K.k**.O seninle eğlenmiş, sen de onu aldat	\
**K.**O köpoğlu köpek nasıl aldanır?	\
 **K.k**.O afyon budalasıdır. Sen de git yalandan mahallebi sat; o da inanır gelir, sen de ,,Hayır! hi—ç"! der eve gelirsin.	\
**K.**Eyi hatırına geldi! Ben de gideyim mahallebi satayım,(Perdeye gelir.)Sütü mandradan, şekeri Londradan, kaşıkları katakoftiden, sütlüdür, şekerlidir mahallebi—! Mahallebici bici bici—, alanlar kahpenin piçi — ! Mahallebim sütlüdür kaymaklıdır!(Hacivadm kapısının önüne gelir.)Sütü mandradan, şekeri Londradan, kaşıklan katakoftiden, sütlüdür, şekerlidir mahallebi—! Mahallebici bici bici—, alanlar kahpenin piçi — ! Mahallebim sütlüdür, kaymaklıdır!	\
**H.** (gelir).Karagöz, ne satıyorsun?	\
**K.**Mahallebi.	\
**H.**Sütün eyi mi?	\
**K.** Eyidir.	\
**H.**Karagöz, senin sütün bozuktur.	\
**K.**Senin sütün bozuk, köpoğlu!	\
**H.**Bu nasıl mahallebi satmak? Tabla yok, mahallebi yok. kaşık yok?	\
**K.**Neden yok? Hepsi var.	\
**H.**Hani sehpan? Sıpa da sen misin?	\
**K.**Sıpa sensin'	\
**H.** Meydanda Hiç bir şey yok.	\
**K.**Seni aldatmak için.	\
**H.**Öyle ise, hayır, hiç!(Gider.)	\
**K.**Vay kurnaz Hacivad vay!(Eve gelir.)Abla!	\
 **K.k**Ne var, herif?	\
**K.**O beni aldatın	\
 **K.k**O seni nasıl aldatıyor?	\
**K.**Ben mahallebi satıyordum geldi.	\
 **K.k**Eyi, sora?	\
**K.**„Ne satıyorsun?" dedi bana. Ben de ..mahallebi satıyorum" dedim. ,,Hani tablan, hani muhallebin. hani kaşıkların?" dedi; ben de ,,seni aldatmak için yapıyorum" dedim; ,,Hayır hi-—ç!” dedi gitti.	\
 **K.k**A kaz kafalı kocacığım! Ben sana öyle mi tarif ettim?	\
**K.**Söyle bakalım, ördek başlı kancığım.	\
 **K.k**Evvelâ sen ..Hayır hi~ç!" deyip kaçacaktın.	\
**K.**Onu akıl edemedim.	\
 **K.k**Haydi, bu sefer de revani sat!	\
**K.**Nasıl borani?	\
**H.** Herif, borani değil, revani!	\
**K.**Borani ?	\
 **K.k**Revani revani!	\
**K.** Karı, ağzımı sulandırma benim!	\
 **K.k**.Haydi, sat da gel.	\
**K.**(perdeye gelir).Revani borani!	\
 **K.k** (içeriden).Herif, budala mısın? Revani!	\
**K.** Revani rappani!	\
 **K.k**Haydi şuradan, yabani sen de!	\
**K.** Dilim dönmüyor, ne yapayını?	\
 **K.k**içeri gel!	\

**K.**(gelir).Geldik bakalım!	\
 **K.k**Otur önüme!	\
**K.**Karı, çıldırdın mı! Niye oturuyorum önüne?	\
 **K.k**Otur! diyorum sana!	\
**K.**Oturduk.	\
 **K.k**Sana heceleteceğim.	\
**K.**Ben geceleyemem.	\
 **K.k**Re üstün: Re!	\
**K.** Re üstün: Re!	\
 **K.k**Va sun: va = Reva!	\
**K.** Va sun: va = Reva.	\
 **K.k**Nun asa: ni — Revani.	\
**K.**Nun asa: ni .. .	\
**K.k.** Ne oldu?	\
**K.** Ne oldu?	\
**K.k**Ne oldu, herif?	\
**K.** Okuduğumuz gibi oldu.	\
**K.k**Haydi şuradan, kalın kafalı herif!	\
**K.** (perdeye gelir).Re-va-ni, bo-ra-ni!	\
**H.** (gelir).Karagöz, ne satıyorsun?	\
**K.** Re-va-ni!	\
**K.** Ne olacak bu?	\
**K.**Güneş görürse, olacak.	\
**H.**Aklınla beni mi aldatacaksın?	\
**K.** Bo-ra-ni, re-va-ni'	\
**H.** Öyle ise, hayır, hi~ç!	\
**K.**Vay fitne kerata! Hesapça yine biz aldandık!	\
\
 **Hacivad.**. (gelir). Ah Karagöz, ah! Başıma gelenleri sorma!	\
**K.**Hayrola. Hacivad?	\
**H.**Bizim Arap köle yok mu. Mercan?	\
**K.**Mercan ne olmuş? Çakmakçılar yokuşu ile kavga mı etmiş?	\
**H.**Ah Karagöz! Su istesem ateş getirir, ateş istesem su verir, aksi aksi işler yapar. Bir yere göndersem geç gelir; bunu satmaktan başka bir çare yok.	\
**K.** Sat bari!	\
**H.**Sana göndereyim de şunu satıver, sana da tellâllık veririm.	\
**K.**Kendisi yakışıklı bir şey mi?	\
**H.**Ayın ondördü gibi, ne doğmuş ne doğacak.	\
**K.**Haydi gönder!	\
**H.**Ben şimdi onu sana gönderirim.(Gider. İçeriden:)Bana baksan a, Mercan!\
**Arap (içeriden).**Buyurun efendim!	\
**H.**Karagöz amcan seni istiyor, git de gör!	\
**Arap.**Peki, ben şimdi gider.	\
\
(Şarkı ile Arap gelir perdeye.)	\
Uqliqa uqliqa qala dingala.(Mükerrer.)	\
**K.** (kaçar yukarıya, bakar).Ulan, Hacivad! Bu Silivri marsığı niye gönderdin? Ben senden kömür istemedim! "Ayın ondördü gibi" dedi Hacivad, bu ayın yirmidokuzu! Zifiri karanlıktır! Gözüm alışsın öyle ineyim aşağıya!(Perdeye gelir).	\
**Arap.**Salâme alaykum!	\
**K.**Hacı baba, kim getirdi löküm?	\
**A.**Ulak, lokum değil!	\
**K.**Ya nedir?	\
**K.**Salâme alaykum, salâme alaykum !	\
**K.**Pandispanya lokum!	\
**A.**Ulak kaplak kulaklı herif! Niçun sen lâkirdi anlamaz?	\
**K.**Ne söylüyorsun? Bilmiyorum ki!	\
**K.**Ulak, salam veriyorum!	\
**K.**Aleyküm selâm!	\
**A.**Beni Hajivad gönderdi.	\
**K.**Seni hacamatçı mı gönderdi?	\
**A.** Ulak, kablak kulaklı herif! Beni Hajivad Şelebı gönderdi.	\
**K.**Bak. anhyabilîrsen, anla! Hacivad mi gönderdi?	\
**A.**Euet, o gönderdi.	\
**K.**Seni ben satacağım.	\
**A.** Uay ! Beni sen satajak? Vay, beni sen satajak? (Karagöze vurur.)Ulak, sen beni niye satajak?	\
**K.** Sen istemiyorsan, ben de seni satmam.	\
**A.** Ulak, beni satmiyajak? Ulak, beni satmiyajak?(Karagöze vurur.)Ulak, beni niye satmiyajak?	\
**K.**Ulan,,.satarım” dedim, dayak yedim; ..satmam" dedim.dayak yedim. Ne yapmalı? Mademki istemiyorsun, ben seni ne satarım ne satmam.	\
**A.**Uay, beni niye satarsin niye satmazsın?(Vurur.)	\
**K.**..Satarım" dedim, dayak yedim; ..satmam" dedim, dayak yedim; „ne satarım ne satmam" dedim, yine dayak yedim. Ne yapmalı, bilmem!	\
**A.** Ulak kopek, ol!(Vurur.)	\
**K.**Ulan, zorla ölmek de olur mu?	\
**A.**Ol, kopek, ol!(Vurur )	\
**K.**Ölmem desem dayakla öldürecek! — Öldüm. Mercan.	\
**A.**(vurur).Ulak, kaş okka oldin?	\
**K.**Ölüm okkaya bindi mi be? Yüz okka öldüm.	\
**A.**(vurur).Ulak, şok oldi; az ol!	\
**K.** (başını eğer).Seksen okka öldüm.	\
**A.**(vurur). ok oldi; az ol!	\
**K.** Altmış okka öldüm.	\
**A.**(vurur).Şok oldi; az ol!	\
**K.**Kırk okka Öldüm. Mercan.	\
**A.**(vurur).Az ol. az ol!	\
**K.**Ne demeli? Ne diyeceğimi bilmiyorum. — Yirmi okka öldüm.	\
**A.**(vurur).Şok oldi, az ol!	\
**K.** On okka öldüm, Mercan.	\
**A.**(vurur) öli lâkirdi eder mi?	\
**K.**Onu sana sormalı, ölü ile lâkırdı söyliyorsun!	\
**A.**(vurur).Oldi!	\
**K.** Hm!	\
**A.**(vurur).Oldi!	\
**K.**Hm!	\
**A.**(vurur).Oldi!	\
**K.** Hm!	\
**A.**(vurur).Oldi!	\
**K.** Hm!	\
.**A.**(Karagöze makam ile dayak atar).Oldi oldi olmadi, oldi oldi oimadi. Olilerde şok kaka şok şiş yapar.(Karagözün üstüne çıkar gider.)	\
**K.** Vay, köpoğlu köpek! Benden intikam aldı! Geçme nasibinden, Hacivad!	\
**H.** (gelir).Karagöz, nasıl ettin?	\
**K.** Hacivad, beni satar mısın?	\
**H.**Sen köle misin? Ben seni nasıl satarım?	\
**K.** Demek beni satmazsın, öyle mi?	\
**H.**Ben seni nasıl satarın?	\
**K.** (vurur).Sen beni niçin satmıyorsun?	\
**H.**Sen istersen, ben de satarım.	\
**K.**(vurur).Sen beni niye satıyorsun?	\
**H.**..Satarım" dedim, dayak yedim; ,.satmam" dedim, dayak yedim. Ben de ne satarım ne satmam,	\
**K.** (Vurur). Niye satarsın, niye satmazsın?	\
**H.**Nasıl edeceğiz?	\
**K.** Öl, köpek, Öl1	\
**H.**Zorla mı öleceğiz? "Öldüm "demeden başka çare yok. — Öldüm	\
**K.** (vurur).Kaç okka öldün?	\
**H.** "Okka ile ölüm olur mu?	\
**K.** (vurur).Kaç okka öldün?	\
**H.** Otuz okka öldüm.(Arap gelir, K. başını eğer.)	\
**K.**Arap ardında!	\
**H.**Arabanın ardında mı?	\
**K.** Hayır, önünde.(Makam ile:)Arap arap ardında!(Mükerrer.)	\
**H.**Ben onu gördüm, gördüm de bildim: Tabla önünde, Uzun Çarşı başında,	\
**K.**Ulan, sana fındıkçı arabı söylemiyorum. (Makam ile.:)Arap arap ardında (Mükerrer.)	\
**H.**Ben onu gördüm, gördüm de bildim: Kayış belinde, ustura elinde.	\
**K.**Ben sana berber arabı söylemiyorum.	\
**Arap (Hacivada vurur).** Ulak kopek, ol!	\
**K.** Sen "ölmem" de, o seni dayakla öldürür.	\
**H.**Karagöz, ne diyeyim?	\
**K.** ,,Öldüm" de!	\
**H.** Öldüm, Mercan.	\
**A.**(vurur).Kaç okka oldin?	\
**H.**Karagöz, ,,kaç okka öldün" diyor.	\
**K.**,,Yiiz okka öldüm" de!	\
**H.**Yüz okka öldüm, Mercan.	\
**A.**(vurur)Ulak, kopek, şok oldin, az ol!	\
**H.**Karagöz, ,,çok öldün" diyor.	\
**K.**,,0n okka Öldüm" de!	\
**H.**Ön okka öldüm. Mercan.	\
**A.**(vurur).0li lâkirdi söyler mi?	\
**H.**„ölü lâkırdı söyler mi" diyor.	\
**K.**Sen sesini çıkarma!	\
**K.** (vurur Hacivada).Oldi!	\
**H.*** Öldüm.	\
**A.** (vurur)Oldi	\
**H.** Evet.	\
**A.**(makam ile bir Karagöze, bir Hacivada vurur).Oldi oldi olmadi. oldi oldi olmadi!	\
**K.**Ulan, ben nöbetimi savdumdu!	\
**A.**Olilerde şok kaka şok şiş yapar!(Hem Karagözün üstüne, kem Hacivadın üstüne sıçar gider.)	\
**H.**Karagöz, nedir bu koku?	\
**A.**Arabın boku.	\
**H.** Karagöz, şimdi bunu nasıl temizlemeli?	\
**K.** Doğru hamama gidersin yıkanırsın	\
**H.**Oldu mu böyle?	\
**K.**(vurur, **H.** gider).Kerata, senin bok yemen.Arap köleyi sat diye benim başıma doladı. Fitne kerata, sen bana yaptın, benim ahımı da arap çıkardı!	\
Sen gidersin de ben durur mıyım? Gideyim idgâha, dolaba dilber seyrine! Bakalım ayine-i devran ne suret gösterir!(Gider.)	
(Şarkı ile Zenne Çelebi gelirler.)\
Şarkı  Hüzam\
\
Bu dil düştü sana, yârim, a bu dem,\
Buna çare bulunmaz, mi a  bu dem? \
Harab oldu bu dil nazın elinden.	\
Nakarat:Zevk idelim, gün bugündür, de® bu dem!	\
\
Sevdiğim, gel gidelim rah-i sefaya!	\
Görme lâyık bendeni cevr ü cefaya!	\
Kim tahammül ider bu hoş edaya?	\
\
Eyzan,	\
\
**Zenne.** Vay beyim efendim! Uğurlar olsun!	\
**Çelebi.** Allaha emanet olun efendim!	\
**Z.**Böyle güzel güzel şarkılar okuyarak, besteler söylüyerek ne tarafa teşrifiniz?	\
**Ç.** Brndehanede otura otura canım sıkıldı; bir az kıraathaneye gideyim, bir kaç ahbabla görüşeyim dedim. Bu aralık kapı çalınlı, uşağa hitaben "Kapıyı aç!" dedim. Uşak kapıyı açmaya gitti.	\
**Z.**Evet efendim.	\
**Ç.** Gitti gelmez, gitti gelmez, bana merak oldu.	\
**Z.**Acaba neden geçikti?	\
**Ç.**Bendenize de merak oldu, aşağıya indim: sokak kapısı arkasına kadar açık, uşak meydanda yok,	\
**Z.**Taaccüp olunacak şey!	\
**Ç.**Mecbur oldum ben de uşağı aramaya; uşağın arkasından biz de sokağa çıktık; önüme gelene eşkâlini tarif etmeğe başladık.	\
**K.** (pencereden).Bey ,,eşekliğini tarif etmeğe başladım" diyor,\
**Ç.**..Uzun boylu, orta yaşlı bir adama tesadüf ettiniz mi" diye önüme gelene soruyorum; hiç „böyle bir adama tesadüf ettik" diyen yok.	\
**Z.**Şaşacak şey!	\
**Ç.** Baktım, olacak şey değil. Bizim uşağın hemşerisi var, kahveci, o hatırıma geldi; doğru onun kahvesine gittim. "Aman, Hasan ağa! Bizim uşak kayboldu, şunu bul!" dedim.	\
**Z.** Tuhaf şey! Koskoca adam nasıl kaybolur?	\
**Ç.**Kahveci benim hatırım için işini güçünü bıraktı tabisine. ..Bey efendi, siz merak etmeyiniz, bendeniz onu bulurum'‘ dedi.	\
**Z.**Bey efendi, çocuğunuz kaybolmuş gibi!	\
**Ç.**Ben de mecbur oldum, eve geldim, evdekilerden sual ettim ”gelen giden var mı” diye. ”Ne gelen var,ne giden" dediler. Uzatmıyalım: bugün bir haftadır uşaktan hiç bir haber yok.	\
**Z.**O hemşerisi olan kahveciden de haber alamadınız mı?	\
**Ç.** Defa gittim sordum, ondan da bir haber alamadık. "Sordum sual ettim, kimse bilmiyor" diyor.	\
**Z.**Ey bey efendi, biz gelelim kendi işimize bakalım.Cariyenize vad buyurduğunuz donanma gelini ile atlı karıncaları bendeniz isterim.	\
**Ç.**Başüstüne efendim! Sizin istediğiniz atlı karınca ile donanma gelini olsun. Ben şimdi gider bulurum.	\
**Z.**Sakın, uşağı aramaya gittiğiniz gibi uzunca olmasın!	\
**Ç.**Hayır efendim, ben gider onları bulurum. Şimdiki halde Allaha ’smarladık!	\
**Z.**Sefa geldiniz!(Giderler.)	\
**Ç.**(gelir, H. karşılar).Vay, Hacivad Çelebi.Seni gökte ararken yerde buldum!\
**H.**Hayrola, efendim?	\
**Ç.**Bizim Şekernaz hanıma bir vadimiz vardı,	\
**H.**Ne gibi vad?	\
**Ç.**Ne gibi olacak? Atlı karıncalarla donanma gelini oyunlarını seyretmek için bendenizden istedi. Ben de meşgalemden bir türlü vadimi yerine getiremedim. Bu akşam arzu ediyoruz onları oynatmak için.	\
**H.**Bendeniz, Karagözle beraber yaparız.\
**Ç.**Öyle ise biz de köşkten seyrederiz. Eğer Ortaoyunu da olursa daha âlâ olur.	\
**H.**Bendeniz şimdi gider Karagöz ile konuşur tedarik görürüz, atlı karıncalara haber gönderirim. Şimdilik Allaha 'smarladık!(Gider.)	\
**Ç.**Sefa geldiniz.!(Gider.)	\
**H.** (içeriden).Karagöz!	\
**K.** (içeriden).Ne var, ne haber?	\
**H.**Haydi çabuk git de senin evde elbiselerin var.	\
**K.**Ne elbisesi?	\
**H.** Oyun urubaların.	\
**K.**Evet, var.	\
**H.**Giyin de Şeyh Küşteri Meydanına gel!	\
**K.**Peki!	\
**H.**Atlı karıncalar, hazır mısınız?	\
**Hepsi (içeriden).**Hazırız efendim!	\
**H.**Haydi bakalım raksı!	\
(Oyun havası başlar.)	\
Ten tere lâ. ten tere lâ, tere le le lâ, lele le le lâ, !e le le le lâ,\
Ten tere lâ. ten tere lâ. tere le le lâ, le le le le lâ, le le le le lâ.	\
\
Dağda bir keçi	\
Sivridir kıçı,	\
Haspanın piçi,	\
A canını, bunda bir is var!\
\
Tere le le lel lâ, tere le le lel lâ,	\
Tere le le lel lâ, le le lel lâ, le le lel lâ.	\
\
(Atlı karıncalar oynar giderler. Köçek havası başlar. Karagöz sakil bir kıyafette, Hacivad güzel bir kız kıyafetinde oynarlar giderler. Sora Orta oyunu başlar. Evvelâ Peşekâr çıkar, sora Kavuklu.)	\
\
Peşekârın havası. Saz semaisi.	\
Ten tire le le lâ, tire le le lâ, tire le le lâ. le le le le le le lâ	\
(Mükerrer.)	\
\
**Peşekâr.**Amma, benim pehlivanım.	\
**Çalgıcı.** Buyurun, benim pehlivanım!	\
**P.** O da hesap değil.	\
**Çalg.**Nedir hesabın?	\
**P.**Yazıcı oyununun taklidini aldım. Çal usul ü aheng ile, efendilerimize temaşa ettirelim!	\
(Şarkı ile Kavuklu gelir.)	\
\
Şarkı Hicaz	\
Niçin a sevdiğim niçin ...	\
**Peşe kâr.** Hoş geldin, sefa geldin, deve çanı!	\
**Kavuklu.** Hoş bulduk, sefa bulduk, fındık sıçanı!	\
**P.**Köftehor! Benim fındık sıçanına benzer yerim var mı?	\
**Kav.**Benim de deve çanına benzer yerim var mı?	\
**P.**Ben seni sevdiğimden, lâtife olsun diye, deve çanına benzettim.	\
**Kav.**Ben de seni sevdiğimden fındık sıçanına benzettim.	\
**P.**Canim efendim, nerelerdesiniz? Çoktan beri gördüğüm yok sizi!	\
**Kav.**Nerede olacağız? Her gün evde.	\
**P.**Evde ne ile vakit geçirirsiniz?	\
**Kav.**Kavga ile vakit geçiririz.	\
**P.**Aman efendim, tuhaf söylüyorsunuz! Hiç kavga ile vakit geçer mi?\
**Kav.**Bizim eğlencemiz kavga. -Bir gün bendeniz evde otururken, canım sıkıldı, bir az gezeyim dedim, evden çıktım, ver elini Kumkapi. Kumkapıda gezerken gazinolardan birine girdim, bir köşede oturdum.	\
**P.**Pek eyi etmişsiniz.	\
**Kav.**Orada bulunan gazino müşterilerinden hiç birisi bana benzemiyor.\
**P.**Neden efendim?	\
**Kav.**Onlar zengin takımı, hepsi kalantor. Bir vafir kendi kendime oturdum, beni ipleyen yok. Bir aralık nasılsa müşterilerini savarak kundura boyacılığından yetişmiş bir garson geldi, "Ne istersiniz efendim?" dedi.	\
**P.** Kahve mi içeceksiniz?	\
**Kav.**Hayır, kahveyi her vakit evde içiyorum. ”Bana bir şişe mastika getir” dedim, getirdi. ”Meze olarak balık ızgarası emreder misiniz?" dedi. Ben de ”emretmem, getir!” dedim. Herif soframızı donattı. Acayip şey: bir adam kendi kendine eğlenemiyor, nerede olursa olsun bir arkadaş istiyor. Halbuki işret meclisinde büsbütün. Gözüm daima kapıda.	\
**P.**Hiç ahbabınızdan kimse yok mu?	\
**Kav.** Ne gezer! Ehibbadan birisi gölse de eğlemek diye! Hemen saat da altı raddelerine geldi, gazinonun kapısından birisi girdi, elinde bir koca sopa, arkasında bir delme aba, başında oniki ziradan ziyade kırmızı kuşak: meğer mahalle bekçisi İmiş!	\
**P.**Meyhaneciye kapatılması için bir şey mi söyledi?	\
**Kav.**Hayır! „Daha zıbarmadınız mı ” diyerek yanıma doğrulunca „Hem-şeri. buyurun!" dedim. Hemen herif ,,Pek guzel" ! diyip yanıma çöktü, meğerse canına minnet imiş.	\
**P.**Sen arkadaşı buldun, uzatma artık!\
**Kav.** Evvelâ tütün tabakasını takdim ve badehu bir tane içmesi için kendisine ibram ettim.	\
**P.**Bir tek attıraydın bekçiye!	\
**Kav.**Bir tekte kalsa eyi! Beni kırmasın diye bir tane parlattı; gazinocuya hitaben: „Bir gadeh ırakhı gotur. efandüile mezeteşelim’!" dedi. Halbuki meze önümüzde var.	\
**P.**„Mezeleşelim" dediği görüşüp konuşmak.	\
**Kav.**Himmet dayı meclimizi şereflendirdi. "irakhı gotur!" emrinin asla arkası kesilmedi. Sofra üzerinde bulunan ızgara olunmuş balık ve sair mezeler bir çeyrek saatte bitti. Ve arasını da: "Benim şairliğim	vardır" gibi türkün aşkı domalıp makamat-i hımaraniyeden terennüm ile:	\
„Alâ gözlüm Kezbanum neredesün, nerede?	\
Bilmen dağda musun, bilmen, derede?	\
Geçende aklım aldım oturup pencerede!"	\
\
**P.**Aferin! Himmet dayı makamata aşina!	\
**Kav.**„Koca ayı böyle şeyler de biliyor" diyip kesti. Bendenize ve bekçi şaire bir gaflet gelerek her ikimiz de olduğumuz yerde bihuş olup kaldı-k! Gazinocu sofradan bizim kalkıp gidemeyeceğimizi anladı. Gazinocu dahi gazinonun odasında uyudu. Bir vafir biz uyuduktan sora acı acı ,,aman aman!" sedaları kulağıma gelince aceba rüya mı yoksa hülya mı diye uykudan uyandım.	\
**P.**Acaba ne imiş, anladınız mı?	\
**Kav.**Şiddetli rüzgâr ve yağmurla karışık hava değişmiş, bana dehşetli bir titreme geldi. Meğer gazinonun altı kayıkhane imiş, ben farkında değilim. Kayık çekmesine mani olmasın diye gazinonun altındaki direkleri seyrek vurmuşlar; yağan yağmurun ziyadeliğinden sele göğüs veremez; direkler kırılır kırılmaz gazino denize yürü~r!	\
**P.**O aralık ne yapmak gerekse yapmalıydınız!	\
**Kav.**Biz şaşırdık kaldık. Bozburun sahiline yakın olduğumuzu korku içinde anladım. Gazinocu Mığıra sual ettim „biz hangi sularda ve hangi deryalardayız?" diye. Gazinocu Mığır kendisinden geçmiş şaşırıp kalmış ve adamlarını uykudan uyandırdı, halâsımıza bir çare aradı. Müzakere her halde lâzımdır.	\
**P.**Elbette lâzım.	\
**Kav.**Tedbiri de bırakamadık. Bizim bekçi şairin kalkmasını beklerken hatırıma sobanın borusu geldi. Sobanın borusunu direk yaptık, derakap yatak çarşaflarını yelken gibi açtık ve saatte yüz milden ziyade mesafe yer gittiğimizi mukaddema mütalâa buyurduğum şeyri sefayin kitap-larından aldığım bir parçacık malûmat sayesinde anlaşıldığından şu kadar sây u gayretimizle teselliyi hatır ederek gecenin karanlığından kurtulup şafak yeri ağarmaya başladı.	\
**P.** Canım efendim, nereye geldiğinizi bilir misiniz?	\
**Kav.**Nereden bileceğiz? Bir de ne bakarsın: deniz kenarında ebniyeler. biri birinden güzel ve serapa gaz ve kandillerle donanmış ebniyelerin ekserisi birbirinden farkı yok, mermer taştan sanatli yapılmış, güzel kalemkâr işlenmiş, ebniyelerin araları epeyce bir güzel bahçe-i ferahfeza . . . velhâsıl: bizi gören ahali deniz kenarına toplandı.	\
**P.** Siz halâ nereye geldiğinizi bilemiyorsunuz?	\
**Kav.**Ne gezer! Biz geminin yelkenlerini indirdik, kum üzerine gazinomuzu kedersizce oturtup ahalinin hepsi bizi alkışladı. Bu telâşımız arasında bekçi şair uykudan uyandı, elindeki sopa ile pürhiddet ayağa kalkınca hazır olan ahali bu kibalde adam görmediklerinden bekçi şairi görüp el çırpınca bekçi babanın bu misillû iş, başına gelmediğinden kendisine hayret gelerek lâkırdı söylemeye iktidarı olmadı.	\
**P.**Rüya görür gibi.	\
**Kav.**Sopasına dayanıp melûl u mahzun yüzümüze bakmaya başladı. Herifin akli zayil olur diye bir sille vurdum ki türkün aklı başına geldi. "Ulan, burası neresidir? Ben bugün işkembeciden aylık alacaktım" demesin mi? Bir kahkaha kopardım. Türk kızmaya başladı, elindeki sopayı kaldırıp başıma vururken "amanın can kurtaran yok mu?" diye bağırırken gözümü açar açmaz bizim oğlanın yanında buldum kendimi!	\
**P.** Vay, bu anlattığınız rüya mıydı?	\
**Kav.**Sen sahi diye mi dinliyorsun?	\
**P.**Beni iki saattir göz hapsine aldın. Hayırdır inşallah!	\
**Kav.**İnşallah hayırdır.	\
**P.**Bu tarafa gelişinizden maksat?	\
**Kav.**Sizden bir dükkân isterim.	\
**P.**Başüstüne! İçeri gider bir az teneffüs ederiz, ben de size dükkânı veririm.(Giderler, oyun biler.)	\
\
(Şarkı ile Zenne Çelebi gelirler.)	\
Şarkı Rast\
\
Nar-i aşkın yaktı beni. \
Değişmem cihane seni, \
Unutma gayri bendeni!	\
Nakarat:Değişmem cihane seni.	\
\
Sanma beni sen bivefa, \
itme bana cevr ü cefa. \
Daim eyle zevk u sefa!	\
Eyzan.	\
\
**Çelebi.**Nasıl efendim, beğendiniz mi oyunları?	\
**Zenne.** Eksik olmayın, bey efendi! Pek hoşuma gitti.	\
**K.** (pencereden).Benim hoşafıma gitti.	\
**Ç.**Bendeniz Hacivada para verir gelirim. siz de köşke gidin! Bendeniz de şimdi gelir muhabbet ederiz.	\
**Z.**Peki efendim, cariyeniz gidiyorum.(Gider.)	\
**Ç.**Estağfurullah!	\
 **Hacivad.** (gelir).Vay, beyim efendim! Nasıl? Oyunlarımızı beğendiniz mi?	\
**Ç.**Çok makbule geçti, Hacivad Çelebi.	\
 **Karagöz.** (pencereden) Makbule Menşure geçmedi.	\
**Ç.**Alınız, Hacivad Çelebi, size beşbin kuruş!	\
**H.**(alır).Allah ömürler versin!(Çelebi gider, Karagöz gelir.)	\
 **Karagöz.**.Hacı Cavcav, paralara kavuştuk.	\
**H.**Al. Karagöz, payını!(Verir.)	\
**K.** (alır).Hacivad, bu az; ben bu kadar parayı ne yapayım?	\
**H.**Senin hakkın o kadardır. Daha ortaoyunu takımına vereceğim, atlı karıncalara vereceğim.	\
**K.**Atlı karacalara vereceğine bana ver!	\
**H.**Canım, hakkına razı olsan a!	\
**K.** Ben de zorla alırım! (Vurur.Hacivad yere düşer ölür.)Hacivad, kalk! Şaka yaptım! Kuzum Hacivad, kalk! Ulan, öldü be! Ben şimdi ne yaparım? Gidip evden küpü getireyim!(Gider.)Abla!	\
**Karisi (içeriden).**Ne var? Ne istersin?	\
**K.**Şu bizim küpü versen e!	\
**K.k**.Herif, küpü ne yapacaksın?	\
**K.** Nene lâzım senin?	\
**K.k**.Küp aşağıda duruyor, al!	\
**K.**(küpü alır perdeye gelir, küpü yere kor, Hacivadt alır yerden, küpün içine kor).Ulan, Hacivad. sana çok acıdım.(Küpün üstüne oturur.)	\
**Hacivadın karısı (içeriden).**Bana baksan a, Demeli!	\
**Demeli (içeriden).**Ne var demeli? Ne ister demeli?	\
**H.k.**Hacivad Çelebi şimdiye kadar gelirdi gelmedi. Merak ettim, git de bak!	\
**Dem.**Giderim demeli, şimdi nerede ise bulurum demeli.\
\
(Semaiyi söyliyerek perdeye gelir.)	\
Bir rahat için yâre temennadan usandık.\
Bir lezzet için çerhe müdaradan usandık.	\
Efkâr çekerek yâr-i vefakâri unuttuk,	\
Pürgamm olalı devlet u dünyadan usandık.	\
**Demeli.**Bana baksan a demeli! Hacivad gördün mü demeli? Gördünse söyle bana demeli!	\
**K.** Görmedim demeli, bir gün beş gün değil, çoktan beri görmedim demeli.\
**Dem.**Doğrusunu söyle demeli! Doğrusunu söylemezsen ben adamın avradını sikerim demeli!	\
**K.** Dayağın meyanesi geldi demeli, ben de senin avretini sikerim demeli! (Vurur.Demeli ölür.)Ulan, bu da öldü! Bunların canları burnunda!(Demeliyi küpe kor.)Haydi bakalım, sen dı Hacivadın yanına!	\
**Hacivadın karısı (içeriden).**Bana baksan a, Dediğigibi!	\
**Dediğigibi.** Ne var dediği gibi?	\
**H.k.**Hacivad Çelebi gitti gelmedi, Demeli gitti gelmedi. Sen de bunları ara!	\
**Ded.**Ben şimdi giderim dediği gibi, Hacivadla Demeliyi bulurum dediği gibi.	\

(Semai ile perdeye gelir.)	\
\
Hoş geldi bana meyledenin ab u havası!	\
Billahi lâtif yerde yapılmış yıkılası!	\
Meddah olalı çeşm-i gazâlânene BAKİ\
öğrendi gazel tarzını Rum’un şuarası,	\
\
**Dediğigihi.**Bana baksan a dediği gibi! Hacivadı gördün mü dediği gibi? Gördünse söyle dediği gibi. Doğrusunu söylemezsen avradını sikerim dediği gibi!	\
**K.**Ağzını bozma dediği gibi! Sora sen de onların yanına gidersin dediği gibi!(Vurur, o da ölür.)Gel bakalım. sen de Hacivadin yanına!(Küpe kor.)	\
\
**Hacivadın karısı (içeriden).** Bana baksan a. Tavtatikütüpati!	\
**Tavlatikütüpati (içeriden).**Ne var tavtatikütüpati?	\
**H.k**.Hacivad amcan gitti gelmedi, Demeli gitti gelmedi, Dediğigibi gitti gelmedi. Şunları ara da bul!	\
**Tavt.** Ben şimdi giderim tavtatikütüpati, Hacivadı, Demeliyi. Dediği-gibiyi bulur gelirim tavtatikütüpati!	\
(Semaî ile perdeye gelir.)	\
\
On kere dimedim mi sana: Sevme dokuz yâr.	\
Sekizde vefa yoktur ama yedi de zinhar!	\
Altı ile beş dört ile üç başe çıkılmaz,	\
Üçün ikisin terk idegör ta kala bir yâr!\
\
**Tavtatikütüpati.** Bana baksan a tavtatikütüpati!	\
**K.**Ne istersin tavtatikütüpati?	\
**Tavt.** Hacivad amcamı gördün mü tavtatikütüpati? Demeli amcamı gördün mü tavtatikütüpati?Dediğigibi amcamı gördün mü tavtatikütüpati? Gördünse söyle tavtatikütüpati! Söylemezsem avradını sikerim tavtatikütüpati!	\
**K.**Görmedim tavtatikütüpati. Ağzını bozma, sen de onların yanma gidersin tavtatikütüpati!(Vurur, o da ölür: Karagöz onu da küpe kor.)	\
**Hacivadın karısı (içeriden).**Bana baksan a, Sivrikoz!	\
**Sivrikoz.**Ne var, anne?	\
**H.k.**Hacivad baban gitti gelmedi, Demeli amcan gitti gelmedi, Dediğigibi amcan gitti gelmedi, Tavtatikütöpati amcan gitti gelmedi. Şunlara bak da gel!	\
**Sivrikoz.**Ben şimdi gider hepsini bulurum.(Perdeye gelir.)Karagöz amca, benim babamı gördün mü?	\
**K.**Senin babanın kâhyası mıyım? Ne bileyim ben?	\
**S.** Sen orada küpün üstünde ne oturuyorsun?	\
**K.** Nene lâzım senin? Sen her kesin kâhyası mısın, herkese sual soruyorsun?	\
**S.** Gel, seninle ceviz oymyalım!	\
**K.** Haydi oynıyalım! (Ceviz oynarlar)	\
**S.**Diktin mi cevizi?	\
**K.** Diktim.	\
**S.** At bakalım!	\
**K.** Attım(K. vuramaz.)	\
**S.**Ben de attım.(Karagözün bacağının arasından geçer küpün içine bakar.)Vay, kerata! Babamı öldürmüş, amcalarımı öldürmüş, hepsini küpe koymuş! Ben şimdi gider anneme söylerim.(Gider.)	\
**K.**Ulan, buraya gel! — Vay, meramı ceviz oynamak değilmiş küpe bakmakmış!	\
**S.**(içeriden).Anne!	\
**H.k.**Ne var, Sivrikoz?	\
**S.**Karagöz çingenesi babamı öldürmüş, amcalarımı öldürmüş, hepsini küpün içine kınmış.	\
**H.k.**Haydi git, Tuzsuza söyle de Karagözün hakkından gelir.	\
**S.**(içeriden).Bana baksan a. Tuzsuz amca!	\
**Sarhoş.** Ne var, Sivrikoz?	\
**S.** Karagöz benîm babamı amcalarımı hepsini öldürmüş küpe tıkamış.\
**Sar.**Ben şimdi gider onun hakkından gelirim,	\
\
(Şarkı ile perdeye gelir.)	\
Nice sevmeyeyim dostlar ...	\
\
**Sar.** Ulan, Karagöz!	\
**K.**Buyurun, beyaz göz!	\
**Sar.**Hacivadı gördün mü?	\
**K.**Görmedim, ben bilmem.	\
**Sar.**Orada ne o türüyorsun?	\
**K.** Küp dibi bekliyorum.	\
**Sar.**Ben de kelle bekliyorum. Buraya gel bakalım!	\
**K.**Geldim elendim.	\
**Sar.** (küpün içine bakar).Ulan! Hacivad. Demeli. Dediğigibi. Tavtatikütüpati hepsi burada! Hacivad. gel buraya, çık küpün içinden !	\
 **Hacivad.** (çıkar).Geliyorum efendim.	\
**Sar.**Ne işin vardı küpün içinde?	\
**H.**Karagöz çingenesi bana bir tokat vurdu, kendimden geçtim.	\
**Sar.**Haydi sen işine git!(Küpe sesleniyor.)Demeli, çık küpün içinden!	\
(Demeli çıkar.)Orada ne işin var?	\
**Dem.**Karagöz bir tokat vurdu demeli, kendimden geçtim demeli.	\
**Sar.**Haydi, sen de git rahatına bak!(Küpe seslenir.)Dediği gibi, çık küpten!(Dediğigibi çıkar.) Senin orada ne işin var?	\
**Deri.** Karagöz bir tokat vurdu dediği gibi, ben de kendimden geçtim dediği gibi.	\
**Sar.**Haydi, sen de git!(Küpe sesleniyor.)Tavtatikütüpati. çık bakalım!	\
(Çıkar.)Senin orada işin ne?	\
**Tavt.**Karagöz bir tokat vurdu tavtatikütüpati, ben de kendimden geçtim tavtatikütüpati.	\
**Sar.**Haydi, sen de git!(Gider.)*Ey Karagöz, şimdi seninle ben kaldım. Benim elimden nasıl kurtulacaksın bakalım?	\
**K.** Sen defol şuradan, kerata, ben de gider kurtulurum.	\
**Sar.** Ulan, kerata, ben seni kazıklıyacağım.	\
**K.** O canıma minnet!	\
**Sar.** Senin bildiğin kazık değil! Seni öyle bir kazıkla kazıklıyacağım ki götünden girip ağzından çıkacak!	\
**K.** Efendim, beni affedersiniz.	\
**Sar.**Seni affedersem olmaz. Senin bir değil, iki değil, üç değil, .	\
**K.** Dört değil, beş değil .. .	\
**Sar.** Ulan, benimle eğleniyor musun?	\
**K.**Estağfurullah! "Kulda kusur çok olur, affeder efendisi!"	\
**Sar.** Ben de seni affettim. Velinimet efendilerimiz de affederler! Allaha ’smarladık. ben gidiyorum.	\
**K.** Saadetle!	\
(Hacivad gelir, oyun biter.)	\
