


# hamam
Hacivad (semai söyliyerek perdeye gelir).
\
Hamd ola bugün ruh-i revanımla barıştım !\
O lâli şeker tuti-zebanımla barıştım !\
\
Cevritmek imiş bendesine gerçi muradı,\
Ol fitne-i şuh-i cihanımla barıştım!\
\
Hay Hak!	\
\
(Perde gazelini okur.)\
\
Halkın ne aceb hikmet olur akd ile halli!	\
Her hale münasib görünür cümle mahalli,	\
\
Eyler kimisi fikr-i terakki ü taalli.\
Gelmiş kimine âlem-i süflide teselli.	\
\
Hallâk-ı cihan âleme kıldıkta tecelli\
Her âdemi bir hal ile kılmış müteselli.	\
\
Ey dil, kiminin kısmeti sükkerli aselli, \
Kimisi sefada, kiminin bağrı keselli.	\
\
Gülşen görünür her kişiye kendi mahalli, \
Kassam-i ezel kısmetimiz eyledi belli.	\
\
(Kavgadan sora:)	\
\
**Karagöz.**Seni gidi utanıp arlanmaz, hiç kimseden korkmaz şebek herif seni! Bir akşam da kendi evinde otur da rahatına bak! Nedir bu senin elinden çektiğim? Her akşam gelirsin, benim kapımın önünde bağırmağa başlarsın. Herkes senden bıktı usandı, çomar herif! Geçen akşam da yine sen geldin, aceleyle kunduramı giyeyim derken yanlışlıkla bizim karının tahta papuçlarını giymişim! Yine gelecek olursan, Hacivad. ben de seni istakoz gibi haşlamazsam, bana da Karagöz demesinler!	\
**Hacivad.**(gelir).Vay, Karagözüm! Seni özler özüm.	\
**K.**Eksik olma, iki gözüm!	\
**H.**Hoş geldin, sefa geldin, gönlümün eğlencesi!	\
**K.**Hoş bulduk, sefa bulduk, çarşı işkembesi!	\
**H.**Benim işkembeye benzer yerim var mı?	\
**K.**Seni acelacayip gördüm de işkembeye benzettim.	\
**H.**Ben de seni sevdiğimden eğlenceye benzettim.	\
**K.**Nasılsın bakalım, koca çomar, eyi misin?	\
**H.**Eyiyim, sen de eyi misin?	\
**K.**Çok şükür, ben de eyiyim!	\
**H.**Pederin keyfi eyi midir?	\
**K.**Peder, sizlere ömür, vefat etti!	\
**H.**Peder bize kömür getirirken Vefaya mı gitti?	\
**K.** Hayır! Zeyrek yokuşunda odun beygirlerini ürküttü.	\
**H.**Canım efendim, pedere ne oldu?	\
**K.**Peder sizler baki.	\
**H.**Peder ne zaman sattı çakı?	\
**K.**Peder çakı satmazdı, hilâl satardı.	\
**H.**Esnaflık fena bir şey mi?	\
**K.**Lâkırdıyı anla, Hacîvad, bizim peder vefat etti.	\
**H.**Sizin peder her işinde sebat etti, öyle mi?	\
**K.**Sapan taşını attı gitti. Lâkırdıyı ters anlama, afyun budalâsı!	\
**H.**Pedere ne oldu? Anlatsan a!	\
**K.**Bizim peder yok mu ?	\
**H.**Var mı yok mu ne bileyim?	\
**K.**Orası da doğru ’	\
**H.**Evet, var.	\
**K.**İşte, o bizim peder mürd oldu.	\
**H.**Züğürt mü oldu?	\
**K.**Evet.	\
**H.**Demek ki iflâs etti?	\
**K.**Evet, bu sene tebdili hava için Hisara gitti. Bizim peder mortosunu çekti.	\
**H.**Modada kahve mi içti?	\
**K.**Hayır, Yoğurtçuda bir su içti.	\
**H.**Neden hiddetleniyorsun? Anlat san a!	\
**K.**Sen lâkırdı anlamıyorsun ki! Bizim pederi beş on kişi aldı götürdü.	\
**H.**Teferrüce mi gitti?	\
**K.**Pederi toprağa gömdüler.	\
**H.**Ha, anladım! Tohumunu diktiler.	\
**K.**Evet, son baharda fidanım alacaklar.	\
**H.**Sora ne oldu?	\
**K.**Bizim pederi uzattılar.	\
**H.**Peder lastikli miydi?	\
**K.** Hayır, kundura giyerdi.	\
**H.**Canım efendim, niçin anlatmıyorsun?	\
**K.**Peder öldü	\
**H.**Pederiniz öldü ise baban’ sağ ya!	\
**K.**Aman, babam öldü!	\
**H.**Pek âlâ, babanız öldü, değil mi?	\
**K.**Ne dirayetsiz adamsın be?	\
**H.**Neden dirayetsiz oluyorum?	\
**K.** ,,Pek âlâ" mı derler?	\
**H.**Babanız öldü ise pederiniz sağ değil mi?	\
**K.**Sormak ayıp olmasın arama, baba demek ne demek, peder ne demek? Bunun ikisi bir değil mi?	\
**H.**Şimdi sizin pederiniz hayatta, değil mı?	\
**K.**Ayakta değil, oturuyor.	\
**H.**Babanızın keyfi eyi midir?	\
**K.**Eyidir, size mahsus selâmı var, seni çağırıyor. Pederin yanına sen de git.	\
**H.**Pederin hastalığı ne idi?	\
**K.**İlletin ismi hatırıma gelmiyor; bir tuhaf isim.	\
**H.**Tahattur edemiyor musun?	\
**K.**Hayır, pehriz olduğu için tarator yedirmedik.	\
**H.**Aceba dik-ı sadır mı?	\
**K.**Çifteli katır değil.	\
**H.**Sillürri’e mi?	\
**K.**Sidikli Behiye değil.	\
**H.**Nafha-ı sadır  mı?	\
**K.**Evet, on tane çadır. Ulan, budalâ mısın? Çadır illeti olur mu?	\
**H.**Çadır değil, a canım! Nafha-ı sadır.	\
**K.** O da değil.	\
**H.**Seretan ?	\
**K.**Zaten peder şarlatanın biri idi.	\
**H.**Ha! Eyi hatırıma geldi; Sakın, istiska-yı batın olmasın?	\
**K.**Yeni aldığı potin değil, kundura!	\
**H.**Rih-i tayyar mı?	\
**K.**Revanici Haydar değil.	\
**H.**Aceba da’üs-sa’leb mi?	\
**K.**Sen sahiden kaçıksın. Hiç sütlü salep illeti olur mu?	\
**H.**Sütlü salep değil, da’üs-sa’leb.	\
**K.**Değil.	\
**H.**Nikris mi?	\
**K.**Kırmızı, lâcivert değil, kendisi esmerdi.	\
**H.**Artık hastalık ismi kalmadı saymadığımız! Hâlâ hatırına gelmiyor mu?	\
**K.**Gelmiyor.	\
**H.**Peder hasta iken doktora göstermediniz nü?	\
**K.**Konduktora gösterdik.	\
**H.**Ne dedi?	\
**K.**Ne diyecek? "Peşin para ile bilet almalı yahut abone olmalı" dedi.	\
**H.**Konduktura değil, doktora göstermediniz mi?	\
**K.**Gösterdik.	\
**H.**Ne dedi?	\
**K.**Ne diyecek? Çok baktı amma fayda etmedi.	\
**H.**Kaç ay hasta yattı?	\
**K.**Altı aydan ziyade.	\
**H.**Demek ki altı ay esiri firaş yattı?	\
**K.**Evet, ispir Mar’aşta yattı.	\
**H.**Peder hasta iken nöbet gelir miydi?	\
**K.**Benden hiç kimseye nöbet gelmezdi.	\
**H.**Ne gibi nöbet?	\
**K.**Sofraya oturduk mu, her keşten evvel yemeğe başlarım, kimseye nöbet vermezdim.	\
**H.**Benim söylediğim öyle değil. Hasta iken insanin vücuduna yanına gelir, bazan sıtma tutmuş gibi üşüme gelir, ona nöbet derler.	\
**K.**Bazan gelirdi.	\
**H.**Ateşi çok olduğu vakit ne yapardın?	\
**K.**Üstünü küller, kapağını da kapardım.	\
**H.**Nenin kapağını kapardın?	\
**K.**Mangalın.	\
**H.**Ben mangaldaki ateşi demiyorum, pederin vücuduna ateş geldiği vakit tedavi ederdiniz, değil mi?	\
**K.**Evet, tekâsül ederdik.	\
**H.**Pederden size epeyce akça kalmıştır.	\
**K.**Pederden bize bir büyük bohça kaldı,	\
**H.**Bohça değil! Pederden size kırıntı kalmadı mı?	\
**K.**Bizim peder boğacacı değildi, nereden kırıntı kalacak?	\
**H.**Pederden size akar kalmadı mı?	\
**K.**Hayır.	\
**H.**Sizin pederin çok akan vardı	\
**K.**Vardı amma, sora akıntı kesildi.	\
**H.** Neden kesiliyor?	\
**K.** Tedavi olundu da . ..	\
**H.**Bu nasıl akar böyle?	\
**K.** İhtiyarlıktan burnu akardı, kulağı akardı, götü tutmazdı.	\
**H.**Öyle akar değil, a canım! Müsakkafata dair şeyler.	\
**K.**Evet, musakkaya dair şeyler, patlıcan, kıyma, soğan, domates.	\
**H.**Canım, yiyeceğe dair değil! Sizin pederin çarşu-i kebirde dükkânları vardı.	\
**K.**Tarlada ekinleri vardı anıma kuraklıktan olmadı.	\
**H.**Pederden hiç bir şey kalmadı mı size?	\
**K.** Kaldı.	\
**H.**Ne kaldı?	\
**K.**Bir kırık desti, bir ayı postu.	\
**H.**Sen yalan söylüyorsun. Pederden sana çok şey kaldı, ben sana çatarım. \
**K.**Ulan! Bana ne hakkın var çatmaya? (Vurur. H. gider.)	\
Sen gidersin de beni buraya pamuk ipliğiyle bağlamıyorlar ya! Ben de gideyim idgâha dolaba dilber seyrine! Bakalım aine-i devran ne suret gösterir! (Gider.)	\
\
(Şarkı ile Çelebi gelir. Hacivad tarafına hamam konur.)	\
\
Şarkı Beyati Araban 
Nimet-i vaslın içün, ey goncaleb,\
Terk-i can itmek de bir şey mi aceb? \
İftiraka olmasa, ey meh, sebeb.	\
Nakarat:Terk-i can itmek de bir şey mi aceb?	\
\
Ölmek ol şuh-i peri-endam içün \
Başka devlettir dil-i nakâm içün.\
Rah-i aşkında baka-yı nam içün.	\
\
Eyzan..	\
\
**Hacivad.** (gelir).Vay, beyim efendim! Vakti şerifler hayırlar olsun!\
**Çelebi.** Allaha emanet olun, Hacivad Çelebi!	\
**H.**Efendim, afiyettesiniz?	\
**Ç.** Afiyette berkarar olun!	\
**K.**(içeriden). "Ahırda tımar olun!" diyor.	\
**H.**Böyle ne tarafa teşrif, efendim?	\
**Ç.**Zatı âlinizle görüşmeye geldim.	\
**K.** (içeriden)."Saatçi Ali ile dövüşmeye geldim" diyor.	\
**H.**Hayrola, efendim?	\
**Ç.**Şu bizim Kurubalık hamamı yok mu?	\
**H.**Evet, efendim.	\
**Ç.**Çoktan beri kapalı duruyor; onu size vereyim de işletin, yahut başkasına kira ile verirsiniz.	\
**H.**Pek âlâ olur, efendim.	\
**Ç.**Buyurun, gidelim de size teslim edeyim!	\
**H.**Buyurun efendim, gidelim!(Giderler.)	\
**Ç.** (içeriden). Bak, Hacivad Çelebi, hamamın hiç bir eksiği yoktur. Bu bohçaların içinde hamam takımları, peştamallar, silecekler, hepsi mevcuttur.	\
**H.**Efendim, bunları birer birer saymalı.	\
**Ç.**Olur efendim, sayalım. İki yüz tane silecek büyük havlu, üç yüz tane küçük havlu yüz silmek içün ve baş havlusu, iki yüz de peştamal, bunlar birinci boy.	\
**H.** Evet efendim; tamam saymışsınız.	\
**Ç.** Defa yine üç yüz  tane büyük havlu silecek, dört yüz tane de yüz havlusu ve baş havlusu.	\
**H.** Evet efendim, onlar da tamam.	\
**Ç.**Defa yine peştamal dört yüz tane eski ve yeni, yüz çift nalın.	\
**H.**O da tamam, efendim.	\
**Ç.**Hamam tası yüz tane, büyük tas on tane.	\
**H.**Onlar da tamam.	\
**Ç.**Endam aynası üç tane, el aynası beş tane, baş tarağı on tane, elbise fırçası beş tane, tütün tablası yirmi tane.	\
**H.**Onlar da tamam.	\
**Ç.**Kahve fincanı kırk tane, kahve tepsisi on tane, su bardağı on tane, ateş küreği iki tane, büyük ateş küreği bir tane.	\
**H.**Onlar da tamam.	\
**Ç.**Su testisi beş tane, güğüm on tane, konsol beş tane, mangal beş tane, saat üç tane.	\
**H.**Onlar da tamam.	\
**Ç.**Ve sair şeyler var, süpürge filân gibi, onları saymak istemez.	\
**H.**Defterde mukayyed değil mi efendim?	\
**Ç.** Evet, Hacivad Çelebi, hepsi defterde yazılıdır; döşemelerin mak'adları eskidir, bir aralık değiştirmeli.	\
**K.**(evinden).Bey efendinin mak’adını kullanmalı.	\
**H.**Onlar kolay, efendim. Hele biz işe başlıyalım da . . .	\
**Ç.** Müsaadenizle. Hacivad Çelebi, ben gidiyorum. Sora yine görüşürüz.	\
**H.**Efendim, hamamın yıllığına ne vereceğiz?	\
**Ç.**Hacivad Çelebi, seninle teklifimiz yok, nasıl olsa uyuşuruz. Allaha ısmarladık!(Gider.)	\
**H.**Sefa geldiniz!	\
\
(Şarkı ile Salkım İnci hanım gelir.)	\
\
Şarkı Acem Aşıran\
Yandı dil aşkınla, ey şuh-i şenim,\
Kûh ü deşt olmakta şimdi meskenim,\
Halime rahm itmedin aslâ benim!	\
Nakarat: Hasretinle çâk çâk oldu tenim.	\
\
Vireli gönlüm sana, ey mehlika,\
Görmedim bir kerrecik senden vefa; \
Gayri lûtf it, eyleme cevr u cefa!	\
\
Eyzan.	\
\
**Hacivad.** (gelir).\
“Lûbumuz içre küşad olmuş bir deste gül müsün?	\
Bahçeden kat' olunmuş rayihalı sünbül müsün? \
Meydana teşrif eylediniz naz u eda ile,	\
Henüz kafesten firar itmiş şaklıyan bülbül müsün?	\
\
**Zenne.**\
Neş'e bahşitmede cana bilemem, mül müsünüz?	\
Bezm-i rindane safa virmede gülgül müsünüz? \
Bülbül i dilsude-veş bezm-i şinasane gelüb\
Yoksa İsî-nefes u ruh-i tecemmül müsünüz?	\
\
**H.**Efendim, böyle naz u eda ile teşrifiniz ne tarafa?	\
**Z.**Ne tarafa olacak? Can sıkıntısı!	\
**H.**Eyisiniz inşallah, efendim?	\
**Z.**Eyi diyelim ki eyi olalım.	\
**H.**Şallı Natır hanım da eyidir inşallah?	\
**K.**(içeriden).Nallı katır da eyidır, Hacivad.\
**Z.**Aman, onu sorma, Hacivad Çelebi!	\
**H.**Hayrola, efendim?	\
**Z.**Biz onunla bozuşalı tamam bir seneden ziyadedir.	\
**H.**Canım efendim, nasıl oldu da birbirinizle darıldınız? Aranızdan kara kedi mi geçti ?	\
**K.** (içeriden).Hayır, beyaz köpek geçti.	\
**Z.** Eğer esasını anlatsam siz de bana hak verirsiniz.	\
**H.** Bendeniz meraklıyım, anlatınız!	\
**Z.** Bizim yunucularımızdan birisinin düğünü olur, bizi aşağı yukarı hizmette bulunmaklığımızı rica eder, biz de Şallı ile birlikte düğün günü erkenden gideriz.	\
**H.**Evet, efendim.	\
**Z.**Beni feraceci yaptılar, Şallı da sofralara bakacak.	\
**K.** (içeriden).Gelsin benim soframa da baksın!	\
**H.**Evet, efendim.	\
**Z.**Başladı misafirler gelmeğe. Biz gelenlerin feracelerini toplıyoruz, aşağı yukarı hizmette bulunuyoruz; misafirlerin arkası kesildi.	\
**K.** (içeriden).Ön tarafından işlesinler!	\
**Z.**Yemek vakti geldi, takım takım misafirler yemek yiyorlar; tekmil misafirler hepsi yemek yediler, hiç kimse kalmadı yemek yemedik.	\
**H.**Demek ki. Efendim, düğün mükemmel imiş?	\
**Z.**Evet efendim.	\
**K.** (içeriden).Hacivad, hanımın sofrasına da sen otur.	\
**Z.**Bir aralık baktım ki bizim Şallı kayboldu, meydanda yok.	\
**H.**Olabilir ya, efendim, iş zımnında bir yere gitti ise.	\
**Z.**Yukan kata çıktım, yok; bahçeye baktım, yok; ay çıldıracağım!	\
**H.**Sakın efendim, mutfakta olmasın’?	\
**Z.**Münasebet? Mutfakta ne işi var? Ahçı erkek ahçısı, kadın değil!	\
**H.**Olabilir ya, efendim, bir iş için yollarlar.	\
**Z.**Evin içinde aramadığım yer kalmadı.	\
**H.**Öyle ise, sokağa gitmiş.	\
**Z.**Meğerse yemek odasının yanında bir ufak oda varmış, gizli orada	
oturmuşlar, diğer bir hanımla muhabbet ediyorlar.	\
**H.** Sizin tanıdığınız hanımlardan mı?	\
**Z.**Hayır, tanımadığım bir hanım. Onlar beni görmediler, muhabbete dalmışlar. O hanım koynundan bir portakal çıkardı Şallı Natıra verdi, bizim Şallı da portakalı kokladı, ben orada kendimden geçmişim.	\
**K.** (içeriden).Bu da kabahat mı?	\
**H.**Demek ki, efendim, siz kendinizi kaybettiniz, öyle mi?	\
**K.**Nasılsa bir aralık kendime gelmişim, onlar beni görmediler; doğru ben yukarı kata çıktım, düğün sahibi hanımdan izin istedim hastanlandım diye.	\
**H.**Sora hizmet geri kalır, giderseniz,	\
**Z.**Ben orasını düşünür müyüm, a Hacivad Çelebi? Hanım rica etti: Kuzum hanım, feraceler karmakarışık olur, bırakıp gitme  dedi.	\
**H.**Orası da pek doğru.	\
**Z.**Artık haliyle kalmaya mecbur oldum	\
**K.** (pencereden).Hacivad, sana bir şey soracağım.	\
**H.**Nedir, Karagöz, soracağın?	\
**K.** Bir insan bir ahbabından portakal alırsa ayıp mıdır?	\
**H.**Karagöz, onun mânası vardır, sen bilmezsin.	\
**K.**Nedir mânası?	\
**H.**Portakal: Sevdiğinden arta kal!	\
**Z.**Düğün bitti, ben de Şallıya gözükmeden hazırlandım, eve geldim. O anlamış benim ona darıldığımı, arkadan geldi. Halbuki benim gönlüm bir kere kırıldı, geçmiş ola!	\
**K.** (pencereden).Hanım efendim, edelim mola!	\
**H.**Demek ki o zamandan beri konuşmuyorsunuz?	\
**Z.**Hayır efendim, görüştüğümüz yok.	\
**H.**Bendeniz şimdi burada hamam tutuyorum, siz de kadınlar tarafını tutun, birlikte vaktimizi geçiririz.	\
**Z.**Hacivad Çelebi, güzel söylüyorsunuz, ben çoktan beri hamamcılık ettiğim yok.	\
**H.**Yeniden işe mübaşeret ederiz.	\
**Z.**Olur efendini.	\
**H.**Buyurun, gidelim! (Giderler.)İşte efendim, kurulu düzen, hiç eksiği yoktur.	\
**Z.**Pek âlâ, Hacivad Çelebi; şimdi hamama ana ister.	\
**H.**Ben şimdi gider. Karagözün Bok Anasını alır gelirim.	\
**Z.**Olur. Hacivad Çelebi.	\
\
**H.** (perdeye gelir).Karagöz!	\
**K.** (içeriden)Ne var, Hacivad?	\
**H.**Senin Bok Ananı yolla!	\
**K.**Bok Ana! Seni istiyorlar!	\
**Ana.** Hacivad Çelebi mi çağırıyor?	\
**K.**Evet, o çağırıyor.	\
\
(Şarkı ile Bok Ana geliyor.)	\
Şarkı Nihavend	\
Çeribaşının gelini...	\
\
**Ana.**Hacivad Çelebi beni çağırmış.	\
**H.**Bana bak sana. Naile!	\
**Ana.** Ne var, ne ister?	\
**H.**Şimdi ben hamam tutuyorum.	\
**Ana.**Evet efendim.	\
**H.**Kadınlar tarafını Salkım İnciye verdim.	\
**Ana.**Evet efendim.	\
**H.**O bana: Hamama bir ana bul! dedi, ben de seni münasip gördüm, birlikte çalışırız olmaz mı?	\
**Ana.**Neden olmuyormuş bakayım? Pek âlâ olur.	\
**H.**Haydi gidelim!(Giderler.)	\
**Z.**(İçeriden) O. sefa geldin, Naile!	\
**Ana.** Sefada daim olun, hanımcığım!	\
**K.**(içeriden).Köpoğlu "Vefada dayım olun" diyor.	\
**Z.**Birlikte burada çalışacağız, müşterilere güzel ikram etmeli, yunucular geldiği vakit hizmet riayette kusur etmemeli.	\
**Ana.** Elbette hanımcığım, elimizden geldiği kadar hizmet, dilimizden geldiği kadar güzel söz.	\
**K.**(içeriden) Eksik olma, koca öküz!	\
**Z.**Seni göreyim. Naile!	\
**Ana.**Sen kasavet çekme, hanımcığım!	\
\
(Şarkı ile Karagöz tarafından Şallı Natır gelir.)	\
\
Şarkı Beyati	\
Gördüğüm günden beri, ey şivekâr,\
Eylerem aşkınla daim ah u zar.	\
Korkaram olmazsın amma bana yâr.	\
Nakarat: Aslini bildirmeğe hacet mi var?	\
Sen civansın, sevdiğim, ben ihtiyar.	\
Böyle söyler bir takım ehl-i nifak:	\
Pir ile taze ider mi ittifak?	\
Sen heman sağ ol, efendim, zevka bak!	\
Eyzan.	\
\
**H.** (gelir).\
Bu ne işve, bu ne cilve, bu ne nazik etvar?	\
Nereye böyle edalı yürüyüşle teşrif?	\
Bir demet gonçe-i rengine idilsen teşbih, \
Hüsn ü anın yine hakkiyle olunmaz tarif.	\
\
**ŞallıNatır.**\
İşveme, cilveme, reftarime ah!	\
Yanılıp da yakılıp da bana dil virme sakın!	\
Nice bin sen gibi üftadeleri yaktım ben,\
Ben gibi afet-i dilsuza sakın olma yakın!	\
\
**H.**Efendim, böyle naz edüp reftar ederek, göz süzüp gerdan kırarak, etraf u eknafı temaşa ederek ne tarafa teşrifiniz, ciğerparem?	\
**K.** (içeriden).Vay köpoğlu Hacivad! Nekadar medih bu? Meddah olsa da bir insan bu kadar metheder!	\
**Şa.** Ah Hacivad Çelebi, dünya güzümde yok.	\
**H.**Neden efendim? Siz daha gençsiniz, gaileniz yok, bir şey düşünmezsiniz. Dünya neden gözünüzde yok?	\
**Şa.**Hacivad Çelebi, dünyada hiç dertsiz adam var mıdır? Tuhaf söylüyorsunuz !	\
**H.**Efendim, vakıa dertsiz adam yoktur amma, genç adamın düşüncesi çabuk gelir geçer, ihtiyar adam gibi değildir.	\
**Şa.**Neden, Hacivad?	\
**H.**Neden olacak? ihtiyar adamda ne kadar kalmış? Ne kuvvet ne kudret, hasta olsa çabuk eyi olamaz; genç adam hasta olsa bile kanı cevelân eder çabuk eyi olur.	\
**Şa.**Senin bildiğin gibi değil, Hacivad Çelebi. Her nereye gitsem eğlenemiyorum, canım sıkılıyor.	\
**H.**Ben sizi eğlendiririm, sizin istediğiniz şeyleri alırım getiririm, gönlünüz müteselli olur.	\
**Şa.**Ben de olduğunu arzu ediyorum.	\
**H.**Efendim. Salkım İnci Hanım eyidir inşallah?	\
**Şa.** Ben onun yüzünü gördüğüm yok.	\
**H.**Neden, efendim?	\
**Şa.**Neden olacak? Münasebetsiz bir şey için bana darıldı.	\
**H.**Bendeniz aranızı bulunun.	\
**K.**(içeriden).Vay muhabbet tellâlı kerata vay!	\
**Şa.**O artık geçti, Hacivad.	\
**H.**Benim hatırım için barışınız!	\
**Ana (gelir).**A Hacivad Çelebi, nerede kaldın?(Şallı Natırı görür.) Vay hanım, sen burada mısın? öpeyim!(Eleğini öper.)Ben şimdi gider hanıma söylerim.	\
**Şa.**Salkım İnci burada mı, Hacivad Çelebi?	\
**H.**Burada, hamam tutuyor.	\
**Şa.**Keşki gelmeyeydim bu tarafa!	\
**H.**Yo, efendim, bu sözünüzü kabul etmem! Ben sizi barıştıracağım, yine eskisi gibi bir arada güle oynaya vakit geçirirsiniz, benim hatırımı kırmayın!(Gider.)	\
**H.** (içeriden).Hamamcı hanım! Şallı Natır gelmiş, sizi onunla barıştıracağım.	\
**Salkım İnci.** (içeriden) A Hacivad Çelebi, senin hatırın başımla beraber, amma ben arzu etmiyorum.	\
**H.**Yo, olamaz efendim! Dışarı teşrif ediniz!	\
**Ana.** A hanımcığım, ayakların altım öpeyim, barışınız!	\
(Önde Salkım İnci, arkadan Ana, daha arkada Hacivad perdeye gelir.)	\
**H.**Benim hatırım için birbirinizle barışın!	\
**K.** (gelir).Bana bak san a. Şallı Natır hanım. Salkım İnci ile barışın!	\
**Şa.** A Karagöz, eyi söylüyorsun amma, kabahat bende değil, niye barışayım?	\
**K.**Benim hatırım için.(Salkım İnciye gelir.)Bana bak, hamamcı hanim. Şallı Natır hanımla barışın!	\
**Salkım İnci.**A Karagöz, doğru söylüyorsun amma, ben ona varımı yoğumu yedirdim külkömür oldum.	\
**K.**Ne yedirdin?	\
**S.İ.**Ona bir altın saat aldım.	\
**K.** Telâş etme! (Şallı Natıra gelir.)Bana baksan a, Şallı Natır hanım! Hamamcı hanımın sizde bir altın saati varmış, istiyor.	\
**Şa.**A sahi mi söylüyorsun, Karagöz?	\
**K.** Sahi ya! Yalan mı ?	\
**Şa.**Al da götür! Benim de onda bir tek taşlı yüzüğüm var.	\
**K.** (hamamcı kanıma gelir). Şallı Natır hanımın sizde tek taşlı yüzüğü var, istiyor.	\
**S.İ.**Al. Karagöz! Benim de onda dut küpem var.	\
**K.** (alır).Şallı Natır hanım! Hamamcı hanımın sizde dul küpesi varmış.	\
**Şa.** Al. Karagöz! Benim de onda bir akar suyum var, gerdanlık.	\
**K.** (alır).Hamamcı hanım! Şallı Natır hanımın sizde bir akar suyu varmış, istiyor, küpleri dolduracak.	\
**S.İ.**Al. Karagöz! Benim de onda iki tane yıldız iğnesi var.	\
**K.** (alır).Natır hanım! Hamamcı hanımın sizde iki tane yıldız iğnesi varmış.	\
**Şa.**Al. Karagöz! Benim de omla bir boroşum var.	\
**H.**Karagöz, ne yapıyorsun ? Çulha mekiği gibi iki tarafa varıp geliyorsun ?	\
**K.**Ne yaparsın? Muhabbet tellâllığı ediyoruz.	\
**H.** Haydi, hamamcı hanım, barışın .Haydi, Natır hanım,edna hatırımı kırmayın!	\
**Şa.**Estağfurullah efendim. Karagöz, bir mani söyle.\
**K.**(teganni eder).\
Adam aman! Yası var yası var!	\
Benim gönlümün bugün yası  var.	\
Koynumdaki dut küpenin, adam aman! foyası var.	\
**S.İ.**Kuzum Karagöz, bir mani daha söyle!	\
**K.**Söyliyeyim! Adam aman! Demeyin demeyin!	\
Bedestende işim var bana da dur demeyin. (Gider.)	\
**Hepsi birden .**Ah!	\
**H.**Haydi efendim, öpüşün barışın!(Öpüşürler.)	\
**Ana.**Adam gördün mü? Ölümlü dünyada dargınlık nedir?	\
**H.** Haydi birlikte hamama gidelim.(Hepsi giderler.)	\
\
**S.İ.**(içeriden).Hacivad Çelebi, bize bir külhancı lâzım.	\
**H.**Lâzım değil, elzem efendim. Bendeniz haber gönderdim. Sergiz namında bir külhancı vardır, şimdi nerede ise, gelir.	\
\
(.Şarkı ile külhancı gelir.)	\
Aya bakh, yıldıza bakh!	\
Damda duran kıza bakh!	\
Sen bizim baldıza bakh!	\
Ne gündür içmemiştim, halim harabdır benim.	\
Yüküm şarabdır benim.	\
\
**Hacivad.** (gelir) A. koca Sergiz, sefa geldin’	\
**Külhancı.**Sefa buldukh, Hacivad Çelebi.	\
**H.** Canım, nerede kaldın?	\
**Külh.**Siz bana kefat göndermişsiniz.	\
**H.**Evet, Sergiz, gönderdim. Boştaydın, değil mi?	\
**Külli.** Avat, aski Çukhurçâşma hamamında çalıştım, Topkhana hamamında çalıştım, Kasavat’ta çalıştım.	\
**Karagöz.**Kasavetle değil, ferahlıkla çalış!	\
**H.**Haydi gel, bakalım!	\
**Külli.**Galirin afandim.(Giderler.)	\
\
**Karagöz.** (perdeye gelir).Hamamcı, hamamcı!	\
**H.** (gelir).Ne var. Karagöz?	\
**K.**Başım kirlendi, hamama geleceğim.	\
**H.**Daha hamam kızmadı.	\
**K.**Ben küfredeyim de kızdırayım bari!	\
**H.**Külhana odun atılacak.	\
**K.**Seni atalım bari!	\
**H.**Sular ısındığı vakit haber veririm, Karagöz.	\
**K.**Haber ver, Hacivad !(Gider.)	\
(Şarkı ile Çelebi gelir.)	\
\
Şarkı Suzinak	\
\
Aşık oklum sana, ey gonca-dehen.	\
Sönmez ateşlere yaktın beni sen,	\
Görmeyeydim, ne olaydı, seni ben?	\
Nakarat:Sönmez ateşlere vaktin beni sen.	\
\
Değilem gerçi sana ben layık,\ 
İhtiyarsız sevüp oldum âşık. \
Merhamet kıl, bana oldu yazık!	\
Eyzan..	\
\
**Çelebi.**Çoktan beri hamama gittiğim yok, başım kir içinde.	\
**K.**(pencereden )Vay, bey efendi hamama gidiyor!	\
**Ç.**Çoktan beri kapalıydı bu hamam, yeni küşadolmuş.	\
**K.**Evet, uşağını bulmuş hamamcı.	\
**Ç.**Gideyim de yıkanayım!(Gider,)	\
**K.** (perdeye gelir).Ulan, ben de giderim, başım kel değil ya! (Kamama girer.)	\
**Karılar.** (içeriden) Dışarı, haydi dışarı!	\
**K.** (elinde ayna) Vay,köpoğulları kovdular! Ben de bir ayna çaldım ya!	\
Emeğim boşa gitmedi.(Gider.)	\
\
(Şarkı ile Ak Arap gelir.)	\
Yâ weled, yâ weled...	\
\
**Ak.Arap.** Ulak, hamam aşilmiş, şukdan beri kapalı idi; gideyim hamama yıkanayım!	\
**K.** (pencereden), Bir müşteri daha.	\
**A.**Yâ sahih el-hamam!	\
**H.** (gelir).Vay, Hacı Kandil, safa geldin!	\
**K.** (pencereden).İçeri buyur, sana şamandıra uyduracaklar!	\
**A.**Safa bulduk, ganim!	\
**H.**Buyurun, efendim, buyurun! (Gider.)	\
**A.** Gideyim bir güzel yikanayim! (Gider.)	\
\
**K.**(gelir) Ben de giderim ya! (Girer içeri).	\
**Karılar.** A dışarı herif  dışarı!	\
**K.** (süpürge elinde dışarı çıkar) Ulan, hiç olmazsa bir süpürge çaldım! (Gider.)	\
\
(Şarkı ile kilci gelir.)	\
Şarkı Saba \
Vardım hamam kapısına,\
Mail oldum yapısına, \
Hamamcı hanımın kil kutusuna.	\
Nakarat: A canım, kilci geldi, kil alan var mı?	\
\
Yemenimi serdim taşa,\
Yazılanlar gelir başa.	\
Sen, efendim, binler yaşa!	\
Eyzan..	\
\
Hamam kapısı keçeli.	\
Aşkın şarabın içeli.	\
Yârim çok oldu mu geçeli?	\
Eyzan..	\
\
**Kilci. Kefe** kili, âlâ kil, kilci!	\
**K.** (pencereden).Ulan, bu kim? "Kilimci" diyor, galiba kilimci olacak.	\
**Ki.**Kefe kili, âlâ kil, kilci!	\
**Ana.** (perdeye gelir). Bana baksan a, kilci!	\
**Ki.**Ne var. gozum?	\
**Ana.** Kilin eyi mi?	\
**Ki.**Eyidur, gozum.	\
**Ana.** Gel bakalım. Hamamcı hanım alacak.	\
**Ki.**Geliyon. gozum!(Hamama giderler.)	\
\
**Karagöz.** (perdeye gelir).Ulan, ben de girerim!(içeri girer.)	\
**Karılar.**Haydi dışarı! Dışarı diyorum sana!	\
**K.**(elinde beşik. perdeye gelir). Vay köpoğulları, ne yaygara basıyorlar!(Gider.)	\
\
**Karagözün karısı.** (içeriden).Ya hu!	\
**K.**Ne var?	\
**K.k.**Benim başım kirlendi; çocukla beraber hamama gideceğiz.	\
**K.**Uğurlar olsun!	\
**K.k.**Hamamın parasım ver bize!	\
**K.** Hamamın anası ahbabımdır, para istemez. Benden selâm söyle!	\
**K.k.**Canım, öyle şey mi olur? Bize para ver!	\
**K.** Al bakalım!	\
**K.k.**A herif, bu on kuruş!	\
**K.** Çok vermişim, yarısını ver!	\
**K.k.**Sen bana yirmi kuruş vereceksin.	\
**K.** Neden? Hesap gür bakalım!	\
**K.k.**İki kuruş kuma, iki kuruş benim baş hakkı, kırk para oğlanın baş hakkı, iki kuruş natır hanıma, kırk para ana kadına, iki kuruş turşu, küçük oğlanı da götürürsem ona da para vereceğiz, tamam yirmi kuruş.	\
**K.**Al bakalım sana on kuruş daha!	\
**K.k.**Haydi oğlan, hazırlan, hamama gidiyoruz!	\
**Karagözün oğlu.**Baba, hamama gidiyoruz, seni götürelim mi?	\
**K.k.**Bohçayı yüklen.	\
**Oğlu.**Ben götüremem bohçaya, hamal mıyım?	\
**K.k.**Ben alırım.	\
\
(Şarkı ile perdeye gelirler.)	\
Çeri başının gelini	\
Çergeye dayamış belini,\
Arap çıkarmış dilini.\
Korkarım ısıracak elini.	\
Nakarat:. .	\
Baltaya vurdurdum çelik,	\
Çergenin tepesi delik, \
Haydi, yapalım şenlik!\
Kimseye itmeyelim kemlik.	\
Eyzan.	\
\
**Karagözün karısı.**Ulan, arkamdan ayrılma!	\
**Oğlu.**Geliyorum, anne.(Hamama girerler.)	\
**Karılar.**A oğlum, babanı da gelir!	\
**Oğlu.**Ben şimdi gider çağırırım.(Eve gelir.)Baba!	\
**K.** Ne var. oğlan?	\
**Oğlu.** Bana dediler ki babanı da getir dediler.	\
**K.** Haydi gidelim!(Hamama gelirler.)	\
**Karılar.**A Karagöz, kadınlar hamamında ne işin var?	\
**K.** Siz çağırmışsınız.	\
**Ana.** Biz kinaye söyledik. Koskoca oğlan kadınlar hamamına gelir mi? Haydi dışarı!	\
**K.**Yine kovulduk!( Evine gelir, merdiveni alır, hamama merdiveni dayar, kubbenin üstüne çıkar.)Ulan! Göbek taşında bey oturmuş, sigara içiyor; Arap da kese sürüyor; ben kubbenin camını kırarım. (Kubbenin camını kırar, içeri girer. Karagözün oğlu hamamdan çıkar, merdiveni alır gider, hamam tutuşur, kanla; bağırırlar.)	\
**Hepsi birden.**Yanıyoruz a dostlar. Yetişin imdadımıza! (Erkekler tarafından müşteriler çıplak kaçarlar. Karagöz de kaçar. — Karagözle Hacivad gelirler, oyun biter.)	\
