


# tahmis

**Hacivad.** (semaiyi söyliverek perdeye gelir).	\
\
Semaî Rast	\
\
Gelse o şuh meclise, naz u tegaful eylese,	\
Reng-i hicabı gülşen-i meclisi gül gül eylese, \
Tâneger-i riyaz-ı huld olur idi vücuh ile, \
Aşık-i zarı gülşen-i vaslına bülbül eylese.	\
Tiri lel le le le le le lele le le le lel li,	\
Canim yele le le le lel le le le lel li	\
\
Hay Hak!	\
\
( Perde gazelini okur.)	\
\
Şem’a-i şadı yanınca cilvezadır perdemiz, \
Pertev-i feyz u sefa-la ruşenadır perdemiz.	\
Her dakika calib-i hayret manazır arz ider. \
Bir temaşahane-i ibretnümadır perdemiz.	\
Şem'amızdan pertev-i feyz-i hakikat aşikâr,\
Hiresaz-ı dide-i ehl-i dehadır perdemiz.	\
Çeşm-i dikkat perdemizden zıll-i mâna seyr ider,\
Böyle bir mir’at-i ulviyetfezadır perdemiz.	\
Dideler ruşen, gönüller zevkyab olsun bu şeb. \
İnbisat-efza-yı bezme aşmadır perdemiz.	\
Gelse ol Çeşm-i siyahım handeler peyda olur, \
Cilvegâh-ı şahid-i zevk u sefadır perdemiz.	\
(Kavgadan sora:)	\
\
**Hacivad.** (gelir).Vay, benim Karagözüm! Ömrüm hâsılı, hoş geldin!	
**K.** Vay. benîm burnumun mayasılı Hacivadım, boş geldin!	\
**H.**Hilebazım Karagöz!	\
**K.** Hilebazım Hacivad!	\
**H.**Karagöz, nerelerdesin?	\
**K.** Nerede olacağız? Her gün evde.	\
**H.**Evde ne yaparsın?	\
**K.** Ne yapacağım? Tahta silerim, çamaşır yıkarım, ortalığı süpürürüm, yemek pişiririm.	\
**H.**Senin karın bu işleri görmez mi?	\
**K.** Hayır, hazır yeyici.	\
**H.**Hiç böyle şey görmedim. Sen mi evin hanlım yoksa o mu?	\
**K.** Biz hem evin erkeği hem kadını.	\
**H.**Öyle ise, Karagöz, bana bir akşam bir tatlı yap ta yiyeyim.	\
**K.** Ne tatlısı istersin sana pişireyim?	\
**H.**Helva yap ta yiyelim!	\
**K.** Olur. Harcı senden, pişirmesi benden, olmaz mı?	\
**H.**Olur, Karagözüm, niye olmaz? Hem onun beyitleri de vardır, söyleriz.	\
**K.** Nasıl beyit, Hacivad?	\
**H.**Eskiden helva sohbetleri yaparlardı. Bu akşam senin evinde, yarın akşam benim evimde, öbür akşam başkasının evinde.	\
**K.** Şarkısı nasıl helvanın ?	\
**H.** Evvelâ helvayı pişirirler, badehu bir tabağın yahud bir tepsinin içine korlar, üstünü de tellerler pullarlar.	\
**K.** Ne o? Helva gelin mi oluyor?	\
**H.**Değil, a canım! Adet öyle. Yarın akşam kimin nöbeti ise, götürürler onun önüne korlar helvayı.	\
**K.** Beyitleri nasıldır. Hacivad?	\
**H.** Sana öğreteyim ’	\
**K.**Öğret bana!	\
**H.** (makam ile).	\
Helvanın üstünde fıstık.	\
Hanenize kadem bastık.	\
Al, topun mübarek olsun!	\
Almazsan da benim olsun!	\
Bir ahoy, canım, ya lel li!	\
**K.**Aferin tereleili!	\
**H.**Nöbet senin, Karagöz!	\
**K.**Ben de mi söyliyeceğim?	\
**H.**Söyliyeceksin zahir! ..Bana öğret!" demedin mi?	\
**K.**Nasıldı, Hacivad?	\
**H.**,,Helvanın üstünde fıstık".	\
**K.**(makam ile)...Ah ama~n!“	\
**H.** Karagöz, bir yerin mi ağrıyor?	\
**K.**Evet. Yem vakti geldi de anırıyorum.(Makam ile:) "Helvanın üstünde yastık".	\
**H.**Münasebet?	\
**K.**Uykumuz geldi, helva sıcak, oraya sıkıştık.	\
**H.** "Helvanın üstünde fıstık”.	\
**K.** (makam ile)."Ah, helvanın üstüne bastık!"	\
**H.**A canım! Helvanın üstüne neden basıyorsun? Ne münasebet?	\
**K.** Mum söndü, karanlıkta kaldık, kazara üstüne bastık.	\
**H.** "Helvanın üstüne fıstık."	\
**K.** (makam ile). "Aman, helvayı yedik te kustuk".	\
**H.**Canım, münasebet?	\
**K.** Yağ acı imiş, midemiz de hazmetmedi.	\
**H.** Değil, Karagöz. ..Helvanın üstünde fıstık".	\
**K.**(tokadı atar; H. gider). Ulan, ister fıstık olsun ister badem, neme lâzım benim?	\
Sen gidersin de ben durur mıyım? Ben de gideyim evime!(Gider).	\
**K.** (içeriden kendi evinin kapısını çalar).Aç kapıyı!	\
**Karısı.** (içeriden).Kim o kapıyı çalan ?	\
**K.**Hırsız.	\
**K. k.**Arsız mı?	\
**K.** Arsız şensin, köpoğlu!	\
**K.k.**Ben şimdi sana kapıyı açamam.	\
**K.** Niye açmıyorsun kapıyı, ulan?	\
**K.k.**Gergef işliyorum.	\
**K.** Aç kapıyı, şimdi kapıyı kırarım ha!	\
**K.k.**Kır da bak ne görürsün.	\
**K.** Ne göreceğim, ulan? Senden mi korkacağım?	\
**K.k**.Elbette korkarsın, zahir!	\
**K.** Aç kapıyı diyorum sana!	\
**K.k**Açtık; gel bakalım! Yine, herif, elini kolunu sallıya sallıya mı geldin ?	\
**K.** Hayır! İki elimi cebime soktum da öyle geldim.	\
**K.** Herif, evde ağıza koyacak bir şey yok. Git şuradan, yarım okka pirinç al da bir pilâv pişirelim de çocukların önüne koruz da yerler.	\
**K.** Ver parasını alayım!	\
**K.k**Herif, sen nenin kocasısın?	\
**K.** Paraya sen bana ver de sen benim kocam ol!	\
**K.k**Yazık si nin kılığa kıyafetine!	\
**K.**Daha başka bir şey istiyor musun?	\
**K.k.** Sade pilâv pişmez ya! Elli dirhem de yağ al, tuzla biberi de unutma!	\
**K.**Peki, unutmam.	\
**K.k** Herif, gidiyor musun?	\
**K.** Gidiyorum.	\
**K.k**.Hazır gitmişken, bir okka kuru fasulya, üç okka soğan, iki okka da bulgur al!	\
**K.**Peki, alayım!	\
**K.k** Herif, yüz dirhem sucuk, yarım okka pastırma, bir okka da peynir al!	\
**K.** Peki, alayım!	\
**K.k**.Herif, gidiyor musun?	\
**K.**Gidiyorum.	\
**K.k**.Bir binlik zeytin yağı, üç okka nohut, iki okka da börülce, bir okka da sabun, üçyüz dirhem de mercimek al!	\
**K.** Peki, alayım.	\
**K.k**.Herif, gidiyor musun?	\
**K.** Gidiyorum.	\
**K.k**.İki okka zeytin, beş okka tarhana, bir okka da yufka, on okka da kömür, yarım çeki de odun unutma?	\
**K.** Unutmam.	\
**K.k**.Herif, gidiyor musun?	\
**K.** Gidiyorum.	\
**K.k**.Kuzum kocacığım! Çocuğun ayağında hiç ayakkabı yok. Bir takunya al, mektebe yalın ayak gidiyor,	\
**K.**Peki, alayım.	\
**K.k**.Herif, gidiyor musun?	\
**H.** Gidiyorum.	\
**K.k**.Hazır gitmişken. kocacığım, benim de ayağıma giyecek hiç bir şey yok. Bana da terlikçi sokağından terlik al; entarim da yok, sekiz arşın kadar da basma al; büyük oğlana da mintan yapacağım, dört arşın da ona basma al!	\
**K.**Peki, alayım.	\
**K.k.** Herif, gidiyor musun?	\
**K.**Gidiyorum.	\
**K.k**.Kuyunun ipi yoktur; kuyuya bir ip al, kova de eskimiş, bir de kova al, sacayağı ile maşayı da unutma!	\
**K.**Olur.	\
**K.k**.Herif, gidiyor musun?	\
**K.** Gidiyorum.	\
**K.k**.Kuzum kocacığım, bana düzgünle rastık al, podra ile sürmeyi unutma!	\
**K.** Olur.	\
**K.k**.Herif, gidiyor musun?	\
**K.** Şimdiki halde hiç bir yere gittiğim yok, burada oturuyorum. Sen bana baksan a!	\
**K.k**.Ne var, kocacığım?	\
**K.** Bu alacağımız şeyler hepsi pilâvın içine mı konacak? Vay köpoğlu! Yarım okka pirinçten kapıyı açtı, tamam alacağımız şey beşyüz kuruşu geçti!	\
\
(Semaî ile Acem gelir.)	\
\
Şarkı Uşşak.	\
Hayli dem zincir-i zülf-ü aşkının meftuniyem ...	\
\
**Hacivad.**. Vay,efendim, hoş âmedi, sefa âmedî!	\
**Acem.** Hoş bulmuşum, safa bulmuşam, canım baba ha ha hay!	\
**Karagözün karısı.** (içeriden) Herif, dışarıda birisi bir şey söylüyor.	\
**Karagöz.**.Ne diyecek? "Hoşaf boş bulmuşum he he hey" diyor.	\
**H.**Efendim, böyle ne taraftan âyende, ne tarafa revendesiniz?	\
**Acem.** Man, efendim, İrandan galiram.	\
**H.**Efendim, sebeb-i teşrifiniz ziyaret kasdiyle mi, yoksa ticaret maksadiyle mi?	\
**Acem.** Ela mana bakh, canım baba! Ticaret gasdiyle gâlânin gıllığı ela olurdi ha?	\
**H.**Demek ki, efendim, ziyaret kasdiyle geldiniz?	\
**Acem.**Bâli! Pâdarim vâfat edândâ. Tahran manim başıma dar gâlübdi. Tiflisa gedândâ Tiflis mânâ ğâmmâvâr gözükürdü. Vallah efendim, sora ela bâlki yâsîmâ ğalaba elârâm fikriynân Oropanın, Amerikanın, Afrika, Asyanın çokh yârlârin gâştügüzar eliyârakh tâkhfifi-i gamma çalışmış isem de  nâ çara, müvâffâğ olammamişam.	\
**H.**Evet efendim.	\
**Acem.** Sora mandaniz bir mârağa oğradım.	\
**H.**Ne gibi merak?	\
**Acem.** Sayd u şikâra mârağ ettim.	\
**H.**Onun ziyanı yok, bendeniz de başka şeye zâhip oldum.	\
**Acem.** Çokh sâyyahlarınan bulundum; bir gün genâ seyd u şikâra gedarken âsnai rahda bir ahuya tâsaduf olundu. Mân bu ahuyu ouladım süknâma gatirdim, görân heyran galıbdı; görsaz insan gibi hüsnü var, göyçâkh gibi oynar.	\
**H.** İranda ne isimle yad olunursunuz?	\
**Acem.** Ela mânâ Yümni oğli Mârğub diyâllâ,	\
**K.** (gelir) "Bana yemeni oğlu merkûp derler" diyor. Oğlum, tabanların sağlamsa bir ikilik vereyim’".	\
**Acem.** Yıkhıl! diyirâm, galtapan kişi, yıkhıl! diyirâm.	\
**K.** Balkabağı sessin, ulan !(Gider.)	\
**Acem.** Ela sizdâ mânâ ismivüzü bağışlasiz?	\
**K.** (pencereden).Bağışlama, Hacivad!	\
**H.** Efendim, Meydan-i Küşterinin yekahengi, meşhur insan mehengi . . .	\
**K.**(pencereden).Galatada oğlan pezevengi!	\
**H.**Brusalı Hacivad namiyle marufum.	\
**Ac.**Hacivad sansan? Hacivad sansan?	\
**K.**(pencereden).Hacivad da sersem, sen de sersem.	\
**H.**Yıkıl oradan, Karagöz! O senin tanıdığın adamlardan değil; o İran gülüdür, İran gülü!	\
**K.**Dikeni burnuna batsın, kerata!	\
**Ac.** Sân mâninmân ela mâzakhlânisân ?	\
**H.** Seninle alay edersem ne olur?	\
**Ac.** Fârisî midânâm.	\
**K.** Kayısı bir tane iki tane, sana ne?	\
**Ac.** Zuhd-i rindâm. khûn-i mân dar gârdân-i peymâna ast,\
Hûş-i mastânâm ki gabrâm gûşâ-i meykhânâ ast.	\
Har şâb iiz andîşâ-yi zulf-i siyah mujgân-i mân \
Tâ sâhâr bâr turrâ-i khâb-i pârîşân şânâ ast.	\
**K.**Zembil-i men ıspanak başed zehey meydâne est.\
Ez himâr-i taşçı gûyed hâl-i men dîvâne est.	\
Pantalon dârem ki ez ceybi hemişe tamtakır, \
Haneden attı karı men, kaynanam vîrâne est.	\
**Ac.**Karagöz, bunlar ne?	\
**K.** Bunlara acizane eş’ar-i uydurmasyon-i namütenahi tâbir olunur.	\
**H.**Canım efendim, deminden söylediğiniz ahuyu görebilir miyiz?	\
**Ac.** Baş üstünü. Hacivad Çalabil mân şimdi onu aparıram.	\
**H.**Bendeniz de dairemi alır gelirim.(Giderler, sora gelirler.)	\
(Ahu gelir.)3	\

Şarkı Uşşak	\
\
Ey belâ hanım, \
Çeşm-i mestamm \
Çıktı, gel, canım,	\
Ey dilber, niçün?	\
\
Aklımı aldın.	\
Gör ne şor saldın, \
Ben yazık kaldım,	\
Ey dilber, niçün ?	\

Ey belâ. Fatma.	\
Kaşların çatma!	\
Yad ile yatma!	\
Ey dilber, niçün?	\

Ey, aklımı aldın,	\
Gör ne şor saldın, \
Ben yazık kaldım.	\
Ey dilber, nicün ?	\
\
**H.**Elendim, söylediğiniz ahu bu değil mi?	\
**Ac.**Bâli.	\
**H.** Aman efendim, şunu oynatın da görelim!	\
**Ac.**(ahuyu oynatır. Makam ile:).Bibâdâl ahu-yi mân! Bibâdâl ahu-yi mân, vay!	\
**Hepsi beraber söyler.** Bibâdâl ahu-yi mân! Bibâdâl ahu-yi mân. vay!	\
**Ac.** Gözleri yakhşi tüman! Gözleri yakhşi tü mân, vay!	\
Hepsi birden.Gözleri yakhşi tümün! Gözleri yakhşi tuman, vay!	\
**Ac.** Heyranm olanı, gurbamn olam, sârgardanınâm, vay!	\
**Hepsi birden.** Heyranın olam. gurbanın olam, sârgârdanınam, vay!	\
(Baştan nihayete kadar üç defa söylenecek.)	\
**H.**Methettiğinizden ziyade görülecek bir şey!	\
**Ac.**Sizi yahu, Hacivad Çâlâbi!(Gider.)	\
**H.**Ya men hu!	\
**Karagöz.**.Ulan, methettiğiniz ahu bu mu?	\
**H.**Evet, bu.	\
**K.**Ulan, bende bundan daha âlâsı var.	\
**H.**Haydi getir de görelim!	\
**K.**Ben şimdi alır getiririm.(Gider. İçeriden:)Abla!	\
**Karısı.** (içeriden).Ne var, herif?	\
**K.**Bizim bahçede leyleklerin yuvası vardı, duruyor, değil nü?	\
**K.k**.Elbette, duruyor.	\
**K.**Ben çıkayım da şunun bir tanesini tutayım!	\
**K.k**.Herif, çarpılırsın, sakın dokunma!	\
**K.** Nene lâzım senin? Çarpıhrsam, ben çarpılırım.	\
**Leylek.** (içeriden öter) Lak kik lak lak!	\
**K.** (bağırır).Ulan, dur!(Zorla perdeye getirir.)	\
**Leylek.** Lak hık laklak!(Karagözün yüzünü, Hacivadınyüzünü gagalar.) \
**H.**Canim, bunu nerede buldun? Bu nasıl ahu?	\
**K.** Bu ahu değil midir?	\
**H.**Bu leylek, budala herif! Ahu ile leyleğin farkında değil! (Leylek gider.)	\
**K.**Ben şimdi bulur gelirim.(Gider, H. da gider.)Abla!	\
**Karısı.** (içeriden) Ne var, herif?	\
**K.** Bizim merkep nerede?	\
**Karısı.** Koynumda değil ya! Ahırda, nerede olacak?	\
**K.** Gel bakalım, benim kardeşim gibi merkebim! (Şarkı ile merkebin üstünde perdeye gelir.)	\
\
Şarkı Hüseyni Zemzeme	\
\
Ben bu teferrüçte başkalfa oldum.	\
Yolunu öğrendim, erkânın buldum,	\
Fundanın kıymetin ben şimdi buldum.	\
Nakarat:Süpürgeler, süpürgeler, eyi meydan süpürgeler!	\
\
Funda dedikleri bir yanar dağdır \
Firavun’dan kalma bir eski kârdır.\
Bu garib çingene çok ustakârdır!	\
Eyzan.	\
\
**Hacivad.** (gelir).Karagöz, böyle nereye gidiyorsun?	\
**K.** Ahu aramaya.	\
**H.**Beni de beraber götür sen e!	\
**K.** Ulan, iki kişiyi merkep götürür mü? Meşhur meseldir: „Ağır bir şey kaldırırsan, belin açılır yatağına işersin" derler. Sen de binersen merkebin canı götünden cicoz!	\
**H.**Öyle şey mi olur? Merkep senin benim gibi daha ne kadar ağır adamlar binse kaldırır.	\
**K.** Gel, bin bakalım!(H. biner.) Deh deh!(Gazel söylerler; ağır ağır gider gibi, Hacivad baş tarafında. Karagöz arka tarafında, merkep ayrılır. iki parça olur.)	\
\
Gazel Ayırılık	\
\
Yürütmez serv-i bağı sim-sima bir nihalin var,	\
Getirmez goncayı güftare canperver makalin var!	\
Nakarat: Ah ayrılık, vah ayrılık, belim büken bu ayrılık!	\
\
Yaraşır, gün gibi tenha, sallınsan, ey sehi-kad, kim\
Benim gibi reh-i aşkında yüz bin payimâlin var!	\
Eyzan.	\
\
**Karagöz.** (bakar, Hacivad merkebin yarısının üstünde gidiyor).Ulan, Hacivad! Merkep uzadı!(Eğilir bakar.) Ulan! Hain kerata! Ben sana söyledim, bu merkep ikimizi çekmez diye! Şimdi ne yapacağız?	\
**H.** (merkepten iner).Canım Karagöz, şurada kenetçi var, götür, merkebi kenetlesin!	\
**K.** Ulan kerata’ Bu tabak mı yoksa kâse mî? Merkep kenetlenir mi?	\
**H.**Sen bir kere götür göster!(Gider.)	\
\
**K.**Fitne kerata! En sonunda benim merkebin kanına girdi! Bari götüreyim de bir kere göstereyim!(Merkebin iki parçasını da götürür; içeriden:)Baksan a, kenetçi baba!	\
**Kenetçi.** (içeriden).Ne va, gözüm ?	\
**K.**Şu bizim merkebi kenetle!	\
**Kenetçi.**Sen küreği çek, ben kenetleyim!(Kenetler merkebi, iki ayağı yukarı iki ayağı aşağı.)Al bakalım!	\
**K.**Ver bakalım'	\
**Kenetçi.** Hani parası?	\
**K.** Para, da mı vereceğiz? Küreği ben çektim, (iki kuruş verir.)	\
**Kenetçi.** Az amma, haydi bereket visün!	\
**K.** (perdeye gelir, merkebi yere kor). Hani ön ayakları, hani ard ayakları? Şimdi çıldırırım.(Çevirir.) Ulan, bu nasıl iş? Şimdi anladım: Yanlış kenetlemiş, bundan hayır yok. Ben götüreyim de pastırma yaparım, kışın yeriz! (Gider,)	\
(Şarkı ile Çelebi gelir; Hacivad tarafına tahmis konur.)	\
\
Şarkı Hicaz\
Aşkınla sine dağlaram, \
Gülgûne yare bağlaram, \
Bunca zemandır ağlaram.	\

Nakarat:Eşk-i terim silmez misin?	\
Mecburinem. bilmez misin?	\
\
Geldikçe sen, ey gülnihâl, \
Ben ağlaram bülbül misâl, \
Alıp eline destimâl	\
Eşk-i terim silmez misin? \
Mecburinem, bilmez misin?	\
\
**Hacivad.** Vay, maşallah, beyim efendim, uğurlar olsun!	\
**Çelebi.** Allaha emanet ol, Hacivad Çelebi!	\
**H.** Böyle, efendim, güzel güzel şarkı okuyarak ne tarafa teşrif?\
**Ç.**Zatı âlinizi arzuladım, görüşmek için geldim.	\
**K.** (pencereden).Vay Hacivad. seninle dövüşmeye gelmiş bey! Senin ona gücün yeter mi? O gene, sen ihtiyar!	\
**H.**Görüşmeğe gelmiş, Karagöz.	\
**K.**(pencereden).Vay beyim, akşamı şerifler hayır olsun!	\
**H.**Karagöz, sen beyi tanır mısın?	\
**K.** Hayır, tanımıyorum amma, gözüm ısırıyor.	\
**H.** Beye Razakızade derler.	\
**K.**Şimdi tanıdım. Bunlar üç kardeştir.	\
**H.**Evet, üç kardeştir; neden bildin?	\
**H.**Bunun büyüğüne Kara Üzüm derler, küçüğüne de Çavuşüzümü.	\
**Ç.**Hacivad Çelebi, bu zat kimdir?	\
**H.** Efendim, bu zate Çeşmi siyahi, basında külahi, mahalle ihtiyari, lâkırdı kavvafı Karagöz derler.	\
**H.** Ulan, ne kadar adım var benim!	\
(Perdeye gelir.)Efendim, akşamı şerifler hayırlar olsun!	\
**Ç.**Allaha emanet ol!	\
**H.** Efendim, kulunuz geçende sizin küçük hemşireyi gördüm.	\
**Ç.** Aman, Karagöz, nerede gördün? Bir fena yerde mi?	\
**K.** Mahallebici dükkânında.	\
**Ç.** Orada ne yapıyordu?	\
**K.** Ne yapacak? Fıstık çapkınına uymuş aşure kâsesinin üstünde muhabbet ediyorlardı.	\
**Ç.**Benim hemşirem kim?	\
**H.** Sizin hemşireniz Kuşüzümü değil mi?	\
**Ç.** Haydi oradan defol! Yüreğime iniyordu!	\
**H.**Karagöz, haydi evine git; artık elverir ettiğin rezalet!	\
**K.** Bey efendiden beş on kuruş almadıktan sora gitmem.	\
**H.**Bey efendinin sana borcu mu var?	\
**K.**Senin nene lâzım? Bey efendi belki bana verecek yahut benim ona borcum var; sen kâhya mısın? Her şeye karışıyorsun!	\
**Ç.**Defol, Karagöz, çok oluyorsun!	\
**K.** Ne tef olurum ne de dümbelek!(Gider.)	\
**H.**Siz ona bakmayın, bey efendi, o arsız yüzsüz utanmaz bir adamdır.	\
**K.**(pencereden).Beni mi çağırdınız?	\
**H.**Ulan, seni kim çağırdı?	\
**K.**Arsız yüzsiz dedin de . . .	\
\
**Ç.** Şimdi. Hacivad Çelebi, buraya gelmemin veçhi: Bizim tahmis var, size teslim edeyim; bir isteyen olursa kiraya verirsiniz, olmaz mı?	\
**H.**Pek âlâ olur.	\
**Ç.**Buyurun gidelim de size teslim edeyim!	\
**H.**Buyurun efendim!(Giderler.)	\
**Ç.**(içeriden).Hacivad Çelebi, içinde hiç eksiği gediği yoktur, hepsi tamam. Bir isteyen olursa erbabına verin!	\
**H.**Başüstüne efendim!	\
**Ç.**Allaha ’smarladık (Gider.)	\
**H.**Sefa geldiniz!	\

(Şarkı ile Ak arap gelir)	\
Yâ weled, yâ weled . ... 	\
\
**Hacivad.**.Vay efendim, sefa geldin, Hacı Fitil!	\
**Arap.** Safa bulduk, ya ganim!	\
**H.** Nasılsın, evi misin?	\
**A.**Şok eyi, Hajivad Şelebi, siz de eyi misiniz?	\
**H.**Duada kusurumuz yok.	\
**K.**(pencereden) O. hoş geldin. Hacı Fitil!	\
**A.**Hoş bulduk, ganim!	\
**K.**Ne var ne yok bakalım?	\
**A.**Siz beni tanir?	\
**K.**Tahtakalede Avurzavur kahvesinde görüşmedik mi idi?	\
**A.** Aywa.	\
**K.**Evet, ayva da aldık ıdı.	\
**A.**Şimdi biz yene Tahtagal'ada oturur.	\
**H.**Ben size haber gönderdimdi.	\
**A.**Aywa, geldi khaber, bizim hurda eskiden tutar idik takhmis var.	\
**H.**Evet, şimdi o tahmis boşta, sîz tutar işletirsiniz.	\
**A.** Pek âlâ olur efendim.	\
**H.**Haydi gidelim de sizi gezdireyim!	\
**K.** (pencereden).Terli ise gezdir, Hacivad!	\
**A.**Şok güzel, buyurun gidelim!(Giderler.)	\
**H.** (içeriden).Bakınız efendim, hiç eksiği gediği yoktur.	\
**A.**Şok gazel efendi, şimdi ayda gaş guruş werejek?	\
**H.**Canım, siz bilmez değilsiniz, beşyüz kuruş.	\
**A.** Şok, Hajivad Şelcbi: biz werejek dortyuz guruş.	\
**H.**Pek âlâ efendim.	\
**A.**Şimdi size peşin verejek bir kuruş.	\
**H.**Olur efendim.	\
**A.** Şimdi ben gider bizim Tahtagal'ada duwucular var. onlari şağrajak, sora gelejek.	\
**H.**Olur efendim, pek âlâ.	\
(Gazel söyliyerek diğer dovücü Arap gelir, karşısına ustası çıkar.)	\
\
**Usta.** O. khoş geldin, Hajı Kandil!	\
**Dövücü.** Khos bulduk, ganim!	\
**U.**Ben khaber gönderdi, geldi?	\
**D.**Geldi.	\
**U.**Şimdi hurda ben takhmis tuttu, beraber burda iş yapar, olmaz?	\
**D.**Pek güzel, pek âlâ olur.	\
**U.**Başka arkadaş ta gelejek, burda siz beraber gahvva duwejek,	\
(Usta gider, orta yere dibek konur.)	\
**D.**Ya Haji Şamandura!	\
**Şamandıra.** (içeriden) Na'am. yâ sîdî!	\
**D.** Aşaği gel!	\
**Ş.** (içeriden). Geliyorum, ganim!(Gazel söyliyerek gelir.)Marhaba, Haji Kandil!	\
**D.** Marhaba, Haji Şamandura! Biz burada şalişajak.	\
**Ş.**AyWa.	\
**D.**Haydi duvvelim gahwa!	\
**Ş.**Duwelim!	\
**D.** (makam ile).Udrub gahwa!(İkisi beraber:)Hey ya hey ya!(ikisi beraber döverler.)	\
**Ş.**Duvvelim gahwa!(İkisi beraber:)Hey ya hey ya!	\
**D.**Udrub gahwa!(İkisi beraber:)Hey ya hey ya!	\
**Ş.**Duvvelim gahwa! (İkisi beraber:)Hey ya hey ya!(içeriden gazel söylerler.)	\
**D.**Udrub gahwa!(İkisi beraber:)Hey ya hey ya!	\
**Ş.**Duvvelim gahwa!(İkisi beraber:)Hey ya hey ya!	\
**D.**Udrub gahwa!(İkisi beraber:)Hey ya hey ya!	\
**Ş.**(bazan ağır, bazan yürük). Duvvelim gahwa!(İkisi beraber:)Hey ya hey ya!	\
**D.**Udrub gahwa! — Hey ya hey ya!	\
**Ş.** Duvvelim gahvva! — Hay ya hey ya!	\
**D.**Udrub gahwa! — Hey ya hey ya!	\
**Ş.**Duvvelim gahwa! — Hey ya hey ya!	\
**K.**Bana baksan a, Hacı Kandil!	\
**D.**Ne, ganim?	\
**K.**Tahtakalede kahveciye brakmışlar, sana İskenderiyeden mektup gelmiş.	\
**D.**Ben şimdi gider, uyle ise, alir mektubu.(Gider.)	\
**K.**Sen böyle yalınız nasıl dövecek kahve? Ben şimdi gider dokmak alır gelir, seninle kahve döver.	\
**Ş.** Şabuk gel!	\
**K.** (evinde).Abla!	\
**Karısı.**Ne var, herif?	\
**K.**Hani benim bir eski kolsuz kısa bir entarim vardı?	\
**K.k**.Ne yapacaksın?	\
**K.**Nene lâzım senin?	\
**K.k** Al, kocacığım!	\
**H.** Bir eski bir külah vardı?	\
**K.k**Çocuklar oynıyordu.	\
**K.**Bul da ver!	\
**K.k** Al, kocacığım!	\
**K.** Şu kol demirini de sökeyim !	\
**K.k** A herif, kapının kol demirini niye söküyorsun?	\
**K.** Sen karışma!	\
**K.k** Bu kıyafetle nereye gidiyorsun?	\
**K.** Kahve dövmeğe. (Perdeye gelir.) Haydi bakalım, dövelim'	\
**Şamandıra.**Udrub gahwa!	\
**K.** (dibeğe vurur. tokmağı çıkaramaz).Ulan, ne cenabet şey? Tokmak çıkmıyor!	\
**Ş.**Sizin tokmak nasıl şey buyle?	\
**K.** Bizim tokmak sizinkine benzemez, bizimki kol demiri.	\
**Ş.** Hiş buyle tokmak olur mu? Şimdi ben sokajak. sora sen sok, ben şıkarajak, sora sen sokajak, ben şikarajak!	\
**H.** Haydi bakalım, Hacı baba!	\
**Ş.**  Udrub gahwa! — Hey ya hey ya!	\
**K.**Ben sekiyorum sora çıkaramıyorum.	\
**Ş.** Şimdi awwala ben sokdu şikardi, sora sen sok! Udrub gahvva! — Hey ya hey ya!	\
**K.** Dövelim kahve! — Hey ya hey ya!	\
**Ş.**Udrub gahvva! — Hey ya hey ya!	\
**K.** Dövelim kahve! — Hey ya hey ya!	\
**Ş.** Udrub gahvva! Hey ya hey yal	\
**K.** Dövelim kahve! — Hey ya hey ya!	\
**Ş.** Udrub gahwa!(Karagözün kafasına vurur.)	\
**K.**Hacı baba, kafama tokmağı niye vurdun?	\
**Ş.** Tokmak bizikdi.	\
**K.**Bizim tokmak bızıkırsa sora fena! Hacı baba, o kafanın hayrını gör!	\
**Ş.**Udrub kahwa! — Hey ya hey ya!	\
**K.** Dövelim kahva! — Hey ya hey ya!	\
**Ş.**Udrub . ..(Karagözün kafasına vurur.)	\
**K.**Hacı baba, tokmak yine kafamıza geldi!	\
**Ş.** Tokmak bizikdi.	\
**K.** Bizimki bızıkırsa sora fena olacak!	\
**Ş.**Udrub gahwa!(Karagöze vurur.)	\
**K.**(bir kaç defa vurur. Arap kaçar).Köpoğlu, dokmak bızıktı diye muttasıl kafama vuruyor!	\
\
**Bebe Ruhi.** (gelir) Haydi, dövelim kahve!	\
**K.** Ulan,seninle kahve nasıl dövülür? Döverken sen dibeğin içine düşersin!	\
**B.r.**Boy ile bos ile mı kahve dövülecek? Kuvvetle!	\
**K.**Udrub kahve!	\
**B.r.** "Udrub kahve" değil! Dövelim kardaş, ya kardaş!	\
**K.**Peki, haydi, öyle olsun! — Dövelim kardaş ya kardaş!	\
**B.r.**Kardaş kardaş ya kardaş!	\
**K.** Dövelim kahve, ya kardaş	\
**B.r.**Kardaş kardaş ya kardaş!	\
**K.** Dövelim kardaş, ya kardaş!	\
**B.r.**Kardaş kardaş ya karılaş!(Karagöze vurur,)	\
**K.**Bana baksan a, Altıkulaç! Sora seni yarımkulaç yaparım ha! Ulan, tokmağı kafama vuruyorsun, köpoğlu köpek!	\
**B.r.**Gitti de dibek, ya kardaş!	\
**H.** Kardaş kardaş ya kardaş!	\
**B.r.** Gitti de dibek, ya kardaş!	\
**K.** Kardaş kardaş ya kardaş!	\
**B.r.** Gitti de dibek . . .(Karagöze vurur.)	\
**K.**Ulan, köpoğlu! (Tokmak ile vurur. B.R. gider.) Vay, kayboldu kerata!	\
**B.r.**(gelir).Haydi dövelim!	\
**K.** Cin misin, köpoğlu? Nereden çıktın?	\
**B.r.** Anamın karnından. Haydi dövelim! Gitti de dibek, ya kardaş!	\
**K.** Kardaş kardaş ya kardaş!	\
**B.r.** Gitti de dibek . . .(Karagöze vurur.)	\
**K.** (vurur).Ulan, bu sefer gebermedin se . . .	\
**B.r.**(havadan). Haydi dövelim'	\
**K.** Cin bu be! Haydi'	\
**B.r.** Gitti de dibek, ya kardaş!	\
**K.** Kardaş kardaş ya kardaş!	\
**B.r.** Gitti de dibek, ya kardaş!	\
**K.** Kardaş kardaş ya kardaş!	\
**B.r.** Gitti de dibek, ya kardaş! (Dibeği alır havaya kalkar. Atayım mı kafana?	\
**K.**Ulan, atma!(Bebe Ruhi gider. Vay köpoğlu! Dibeği kaptı!	\
Ben de gideyim esbablarımı değiştireyim!	\
(Gider. Hacivadla beraber karşı karşıya gelirler.)	\
\
**H.** Karagöz, geçmiş ola! .. .	\
(Ali tarafı malûm.)	\
