

# tahir ile zuhre	

**Hacivad.** (semaiyi söyliyerek perdeye gelir).	\
Yürük Semaî Nihavend.	\
\
Yârin bu kadar çevri gelir miydi hayale?\
Gûş itmedi âhIm, beni döndürdü hilâle.\
Rüyada bile pâyını pus itmeği görmem.	\
Elden ne gelir ağlamadan başka bu hale?	\
\
Bir nevcivandir, kaşı kemandır, derd-i aşkiyle halim yamandır. \
Rahm it bana sen, ey şuh-i gÜlten! Can u gönülden sevdim seni ben.	\
\
Hay Hak!	\
\
(Perde gazelini okur.)	\
Perde kurdum bezm-i irfana safa göstermeğe.\
Şem'a yaktım suret-i ibretnüma göstermeğe.	\
Ta ezel Feyyaz-i kudret şem'i icad eylemiş, \
Çeşm-i ibretbine reng-i ma-maza göstermeğe, \
İtibar itsün şuunat-i zemanı seyreden,\
Yoktur istidad-i fitrat bir daha göstermeğe.	\
Benliği terk it! Eğer "İnsan olanı!" dersen, çalış \
Gûşe-i mahviyet içre itilâ göstermeğe.	\
Huzur-u erbab-i safada ..	\
\
( Taganniye başlar.) Yâr, bana bir eğlence! Yâr, bana bir eğlence!	\
Subha dek baht-i siyahla hasbihal ittim bu şeb,\
Düşmana, ey mâhrû, arz-i melal ittim bu şeb.	\
Yâr, bana bir eğlence!	\
(Karagöz gelir, Hacivadla kavga ederler, H. gider.)	\
\
**Karagöz.**.Yürü gidi anacağızını sallayıp sıyırıp attığım herif! Ciğeri bir para etmez, mum bacaklı kerata seni! Her gün gelirsin kapının önüne dır dır dır(Hacivad gelir) dır(H. kaçar),zır zır zır(H. gelir)zır!(H. gider.) Seni, inan olsun, dolma gibi yutarim. Ben yiğidim, hangi kavgaya gitsem evvelâ dayağı ben, yerim! Hacivadı korkuttum amma, ben de şalvara uydurdum. Seni, imanım hakkı için, Hacivad, kuyruğundan tutarsam Tekirdağına kadar fırlatırım!	\
**Hacivad.** (gelir)Vay! Efendim! Safa geldiniz!	\
**K.**Unuttum getirmeğe.	\
**H.**Neyi?	\
**K.**Sopayı.	\
**H.**Sopa? Münasebet?	\
**K.**Getireydim kafam gözünü yarardım !	\
**H.**Bilâder, yukarıdan aşağı bir patırdı, bir küfürdü, bir vaveyladır koptu.	\
**K.**Hangi bahçeden koptu?	\
**H.**Ne?	\
**K.**O mavi leylâk,	\
**H.**Canım, mavi leylâk değil.	\
**K.**Kırmızı zambak.	\
**H.**Bir patırdı, bir gürültü, bir hengâmedir koptu,	\
**K.**Yengen yorganı mı yaktı?	\
**H.**Değil a canım! Ben gelir gelmez sen yukarıdan aşağı paçacı damından kelb uçar gibi kendini attın.	\
**K.**Keratadaki teşbihe bak. bizi köpek yapıyor!	\
**H.**Aklım başımdan gitti.	\
**K.**Nereye gitti?	\
**H.**Ne?	\
**K.**O nakıl.	\
**H.**Nakil değil, akıl akıl!	\
**K.**Ne yapayım, gitti ise takır takır?	\
**H.**İnsanın aklı başında olmaz mı?	\
**K.**Hiç öyle sivri yerde akıl durur mu? Yuzgâr aldığı gibi götürür.	\
**H.**Senin aklın nerede?	\
**K.**Benim .ıklım götümde.	\
**H.**Hiç göte akıl konur mu ?	\
**K.**Benim aklım çingene aklı olduğundan sovuğa dayanmaz da götüme sokarım.	\
**H.**Bir def'i hacet iktiza ederse ne yaparsın?	\
**K.**Defi hacet nedir?	\
**H.**Abdes bozmaz misin ?	\
**K.**Benim abdestim bozulmaz, tuzlu su ile aldım.	\
**H.**Tuzlu su ile abdes bozulmaz mı?	\
**K.**Yaz günü kırk sekiz saat dayanır.	\
**H.**Canım efendim, sen taşraya gitmez misin?	\
**K.**Ben tezkereyi kaybettim, taşraya nasıl gideyim?	\
**H.**Öyle değil, ayak yoluna gitmez misin?	\
**K.**Ayak yoluna gidersem izi bulurum.	\
**H.**Kademhaneye gitmez misin?	\
**K.**Kadırgadaki haneye giderim.	\
**H.**Kenefe girmez misin?	\
**K.**Sıçmaya mı?	\
**H.**Tü! Utanıp arlanmaz herif!	\
**K.**Sen zorla söylettin!\
**H.**Kenefte abdes bozmaz mısın?	\
**K.**Bozarım.	\
**H.**Abdes bozarken aklını ne yaparsın?	\
**K.**Abdes bozarken aklımı götümden çıkarırım, abdes bozduktan sora yine götüme sokarım.	\
**H.**O öyle ne olur?	\
**K.** Gire çıka boktan bir akıl olur. Hacivad, geçen gün abdes bozarken aklımı şöyle direğin üstüne kodum; bir de baktım ki bizim aklı köpek kapmış.	\
**H.**Hiç aklı köpek kapar mı?	\
**K.**Benim aklım yağlı olduğundan kapar.	\
**H.**Sen şimdi akılsız mısın ?	\
**K.**Hayır. Bitpazannda tellâlın elinde bir akıl buldum aldım.	\
**H.**Hiç akıl tellâla verilir mi?	\
**K.**Birisi çıldırmış da aklını müzayedeye vermişler.	\
**H.**Sora aldın mı?	\
**K.**âldım.	\
**H.**Evi akıl mı idi?	\
**K.**Karanlıkta görmedim, aydınlıkta baktım kİ üç yerinde güve deliği var.	\
**H.**Bilâder. hiç aklı güve yer mi?	\
**K.**Fıkara aklı olduğundan sandıkta çok durmuş, güve yemiş.	\
**H.**Rengi ne renk?	\
**K.**Vişne çürüğü. Sora terziye verdim, içini dışına çevirdik, bombok bir şey oldu.	\
**H.**insanın aklı başında olmaz mı? insan ana rahminden dünyaya geldiği vakit akılla fikirle doğar.	\
**K.**Vay! İnsan anadan mı doğar?	\
**H.**Anadan doğmaz da seni kim doğurdu?	\
**K.**Beni ben doğurdum.	\
**H.**Bilâder, bir adam kendi kendini doğurabilir mi?	\
**K.**Anamın ebeye verecek parası yoktu, dokuz aylık yolu dört buçuk ayda çıktım dünyaya.	\
**H.**Bilâder, dokuz aylık yol hiç dört buçuk ayda çıkılır mı?	\
**K.**Ben kestirme geldim.	\
**H.**Kestirme nasıl?	\
**K.**Götten doğdum.	\
**H.**Vay edepsiz külhani vay! Senin adam olacağın yok, a maymun!	\
**K.**Senin de ayı olacağın yok, eşek!(Vurur, H. gider.) Be, neme lâzım? Sen gidersin de beni pamuk ipliğiyle mi bağlıyorlar? Ben de gideyim idgâha dolaba dilber seyrine. Bakalım, ayine-i devran ne suret gösterir!(Gider.)	\
\
(Şarkı ile Zührenin babası gelir.)	\
\
Esirin oldum, ey zülfü kemendim.	\
\
**Hacivad.** Vay efendim! Vakti şerifler hayırlar olsun!	\
**Zührenin babası.**  Allaha emanet ol. Hacivad Çelebi!	\
**H.**Keyf-i âliniz eyi mi efendim?	\
**B.**Elhamdülillah, sizler ne yapıyorsunuz bakalım? Ne âlemdesiniz?	\
**H.**Duada kusurumuz yok efendim.	\
**Karagöz.** (pencereden bakar).Efendim, duvarda kusurumuz yok, yalınız temel bozuk.	\
**B.**Hacivad Çelebi, bu zat kimdir?	\
**H.**Efendim, bizim mahallenin sâlhurdelerinden,	\
**K.**(pencereden).Evet efendim, sahurda köfteyi yiyenlerdenim, bumbar olursa yemem.	\
**H.**Hanım efendi eyi midir?	\
**B.**Eyidirler.	\
**H.**Zülıre hanım ne yapıyor?	\
**B.**Elinizi öperler.	\
**K.**(pencereden).Elini öperse zararı yok, ayağını kaparsa fena!	\
**H.**Estağfurullah efendim! El öpenleri çok olsun, kullar, halayıklar Öpsün elini! Tahir bey nasıl? Eyi midir?	\
**B.**O da eyidir,	\
**H.**Aman efendim, hayli zamandır zati âlinizle görüşemedik.	\
**B.**Çok zamandan beri görüşülemedi.	\
**H.**Tahir beyin pederi vardı, Rüstem ağa, zati âlinizin kâhyası. Hayatta mıdır?	\
**B.**Sizler baki. Hacivad Çelebi.	\
**H.**Zatı âlinizden eyi olmasın — pek eyi bir zattı, illeti ne idi?	\
**B.**Zîk-ı sadır.	\
**K.**(pencereden).Hiç böyle illet ismi işitmedim. "Çifteli katır" diyor!	\
**B.**Gençlik zamanından beri çekerdi.	\
**H.**Çok yattı mı?	\
**B.**Bir kaç seneyi mütecaviz esiri firaş yattı.	\
**K.**(pencereden).İspir faraş mı attı?	\
**H.**Hayır, Maraşta yattı! Defol oradan! — Demek ki hekimler derdine deva bulamadılar?	\
**B.**Çok hekimlere baktırdık amma, Hacivad Çelebi, bir türlü etibbalar derdine deva bulamadılar.	\
**H.**O yattıkça efendim, sizler afiyette ber karar olun!	\
**K.**(pencereden) Ahırda bir tımar olun!	\
**B.**Benim niyetim; Zühreyi Tahire vermek arzusundayım. Bana Rüstem ağanın da vasiyeti vardır "Tahir ile Zühreyi birbirinden ayırma!" diye tenbih etti. O vasiyeti yerine getirmeli.	\
**H.**Pek âlâ efendim, siz de balı yağa, yağı bala katarsınız.	\
**K.**(pencereden ).Balı yağa, yağı bala katarsın, içine un katarsın, bir güzel helva olur.	\
**H.** Hin-i sahavetten bu ane gelinceye kadar bir arada kardeş gibi büyüdüler; bunları birbirinden ayırmak olmaz efendim.	\
**B.**Şimdi bana bir adam lâzım umur n hususu tesviye etmek için ve sair hizmet için.	\
**H.**Efendim, bendenizin refikim vardır. Karagöz. Pek güzel bir zattır, ehl-i hizmet. Eğer kabul ederseniz, zatı âlinize göndereyim.	\
**B.**Pek âlâ olur. Hacivad Çelebi. Bendenize müsaade buyurun!(Gider.)	\
**H.**Estağfurullah efendim, müsaade sizin!	\
\
(Hacivad gider, Karagözü çağırır.)	\
**H.**Karagöz, sana bir güzel havadisim var.	\
**K.**Avadis mi var? Kirkor yok mu?	\
**H.**Böyle boş gezmek olmaz; seni bir yerde kapılandıracağım.	\
**K.**Yorgan tiresi var mı yarımda?	\
**H.**Ne yapacaksın?	\
**K.**Kaplatmak için.	\
**H.**Bu mahallede hanedan-i mütemeyyizandan bir zat-ı muhterem var. Onun yanına seni koyacağım.	\
**K.**Dandini ile beni uyutacak mısın? Ben çocuk mıyım, ulan?	\
**H.**Birinin yanına koyacağım.	\
**K.**Pek eyi olur.	\
**H.**Onlann da bu yakında cemiyetleri olacak. Sıdk u sadakatle hizmet edersen düğünde çok bahşiş alırsın.	\
**K.**Efendinin ne düğünü var?	\
**H.**Kendisinin bir kızı var, diğer bir zata akd-i izdivaç ile verecek.	\
**K.**Şimdi anladım. Aktar dükkânında safrası kabarmış, aç karnına kaymaklı güllâç yiyecek. Vay pis boğaz kerata vay!	\
**H.**Zevzekliğin lüzumu yok. Kendi kızı Zöhre hanımı müteveffa kâhyasının oğlu Tahire verecek.	\
**K.**Kendi mühresini Vefadaki kâhyasının oğlu Şahika mı verecek?	\
**H.**Kendisinin kâhyası vardı, ölmüş; onun oğluna kızını verecek.	\
**K.**Vay, kâhyası ölmüş mü? Şimdi efendiye biz mi kâhya olacağız?	\
„Bana ne karışıyorsun?" diye darılırsa?	\
**H.**O ölmüş.	\
**K.**Aceba derdi ne imiş?	\
**H.**Kendisinin illet-i kadimesi varmış.	\
**K.**Kendisinin kadın ninesi mi varmış?	\
**H.**Hin-i sahavetinden beri duçar olduğu illetten esiri firaş olmuş.	\
**K.**Kahveci Ahıned ağanın pekmez testisini alıp çeşmeden hamamı doldurmuş?	\
**H.**Çocukluk zamanından beri bir illete duçar olarak yatak esiri olmuş.	\
**K.**Çarşamba pazarında atı kaybeden ispiri bulmuş mu?	\
**H.**Benimle eğleniyor musun?	\
**K.**Hayır! Tek kürekle mehtaba çıkıyorum.	\
**H.**Bu kadar etıbbalar mualece tertibinden âciz kahp , . .	\
**K.**Ne kadar aç gözlü varsa fırından ekmek çalıp . . .	\
**H.**Nihayetül-emir hastalıktan rehâyab Olamayıp dar-ı fenadan dar-ı bakaya irtihal etmiş.	\
**K.**Ondan bana ne? Eyi etmiş.	\
**H.**Neden, Karagöz?	\
**K.**Nihayet derecede borcunu veremeyip . . .	\
**H.**Ey sora?	\
**K.**Fener yolunda bakkalı yakalayıp sık boğaz etmiş.	\
**H.**Niçin o, Karagöz?	\
**K.**Bakkal benden para istemesin diye.	\
**H.**Değil, a canım! ölen kâhyasının illeti nefes darlığı imiş, bir seneden ziyade hasta yatmış. Çok hekimlere göstermişler, hiç bir fayda hâsıl olmamış.	\
**K.**Benîm neme lâzım,olan olmuş, torba dolmuş. Biz kendi işimize bakalım!	\
**H.**Şimdi senin anlıyacağın: efendinin yanına gireceksin. Gidelim, tebdil-i came olur geliriz.	\
**K.**Niyet edip çanakçı izzete geliriz.	\
**H.**Haydi gidelim! Sana bazı talimatını var, onları tutmalısın	\
**K.**Başüstüne, tutarım. Eskiden avculugum vardı,.(Giderler.)	\
**H.**(içeriden).Al şu elbiseleri, giy bakalım!	\
**K.**(içeriden).Kendi elbisem daha eyi; bunlar alacalı bulacak bir şey.	\
**K.** Bunlar seni eyi açtı, Karagöz!	\
**H.** Ne demek! Güzele ne olsa yakışmaz ?( Perdeye gelirler.) Aman Hacivad, beni yalınız bırakma, sora puslayı şaşırırız, (Efendi gelir, sandalyeye oturur, Hacivad gider.). İş fenalaştı.	\
**Baba.**Benim bahçemin derununda geştügüzar etmeye ne hakkın var?	\
**K.**Hacivad,yetiş imdadıma. "Benim bahçemde keşkekle zırvayemeye ne hakkın var" diyor!	\
**H.** (arkadan) "Buraya gelmemin veçhi" zatı âlinizle görüşeceğim."	\
**B.**Kiminle güreşeceksin?	\
**K.**(kendi kendine).Gördün mü, Hacivad. ettiğin haltı? Bir çuval inciri berbat ettin!	\
**H.** (arkadan)..."Haddim değil efendim, bendeniz kimse ile görüşmem"	\
**B.** Görüşmeye gelmedin, öyle mi? Demek ki efkârın başka. Doğru söyle, buraya niçin geldin? Yoksa sarik güruhundan mısın?	\
**K.** Hacivad, „Sanğı burma ile et var, yer misin" diyor. — Yemem, efendim.	\
**H.** (arkadan)."Hırsız mısın" diyor. "Bendeniz fiil-i sirkati asla kabul etmem" de sen e!	\
**K.** Bendeniz aslâ kimse ile kavga etmem.	\
**H.** „Hırsız değilim" de!	\
**K.** Hırsız değilim; çalıp bana getirirlerse saklarım.	\
**B.** Demek ki düzd-efşarsın?	\
**K.**Hızlı koşamam. efendim, ihtiyarim.	\
**B.**Böyle vakitsiz leylen etraf u eknafı taharri etmede bir mâna yok.	\
**K.**Evet efendim. Leylâyı tahrik etmede mâna yok. mefhum var.	\
**B.**Senin sözlerinden bir me’al anlaşılmıyor, bütün saçma.	\
**K.**Kaçmam efendim; kovsanız bile buradan bir yere gitmem.	\
**B.**Senin kelâmında hiç vezn-i mevzun yok.	\
**K.**Kısa uzun yok efendim, hep bir boydayız.	\
**B.**Yoksa mecnun musun?	\
**K.**Mecnunum efendim, yalnız Leylâm yok.	\
**B.**Sen söz anlamadan bibehre misini'	\
**K.**Evet efendim, kehleyim, tatarcık değilim.	\
**B.**Yoksa düvelbaz mısın?	\
**K.**Davlumbazım efendim, yalnız pervanelerim yok. Pervanelerim olsa her tarafa işlerim. İsterseniz sizin tarafa da işleyim.	\
**B.**Bu tarafa serseri güruhundan bir takım adamlar geliyor, sen de onlardan misin?	\
**K.**Evet efendim, bendeniz de sersem güruhundanım.	\
**B.**Hattâ geçen şeb ittisalimizdeki kasra duhul etmişler.	\
**K.**Evet efendim, hasra fuhul etmişler.	\
**B.**Ne dedin?	\
**K.**Dediğiniz gibi efendim.	\
**B.**Kasrın derununda olan camedanı şikest ile ne kadar melbusat varsa sirkat etmişler.	\
**K.**Hasekideki Cafer ağa ile ne kadar armut sattılarsa ziyan etmişler.	\
**B.**Doğru söyle! Sen kimsin ve kimi islersin? Burada işin ne ve niçin geldin? Kimin nesisin, ismin nedir?	\
**K.** Durun, kaydımı çıkarayım da geleyim!	\
**H.**(içeriden). "Bendeniz bigâne değilim, efendim."	\
**K.** Bendeniz çingene değilim, efendim, kıptiyim.	\
**B.**Malâyani sözlerden hoşlanmam. Bana istifade olacak söz söylemeli.	\
**K.** Hacivad! Efendi "Manav Yaniden hoşlanmam, istefan ağa ile hesap görmeli" diyor.	\
**H.**(içeriden)."Efkar-ı fıkaradanım efendim."	\
**K.**Fikarayım efendim, karnım açtır efendim.	\
**B.**Meşrubata ve mekûlata dair bir şey mi istiyorsun?	\
**K.** Hacivad! " Pulat maşrabayı mı istiyorsun" diyor,	\
**H.** "Yiyeceğe içeceğe dair bir şey istemem. İltifatınıza mazhar olmak için geldim."	\
**K.** Mazhar beyle beraber su doldurmak için geldim.	\
**B.**Ne dedin?	\
**H.**„Eltaf u mürüvvet sahibisiniz efendim."	\
**K.** Mutafla beraber yün didiniz, efendim.	\
**B.**Söylediğin sözler harikulâde.	\
**H.** Hacivad! Efendi "Harik var bizim mahallede" diyor. Tulumbacılara haber verelim mi ?	\
**B.** Vaktini böyle betaletle mi geçiriyorsun?	\
**K.** Hacivad! "Vaktini bizim Şetaretle mi geçiriyorsun" diyor.	\
**H.** (içenden) "Vaktini boş mu geçiriyorsun" demek ister. Sakın efendiye bet bir şey söyleme!	\
**K.**Nekbetlere bir şey söylemem.	\
**B.**Herif, nekbet kim?	\
**K.**Siz.	\
**B.**Bana mı söylüyor?	\
**H.**Karagöz, itale-i lisanda bulunmayın!	\
**K.**Efendim, nisanda gelincik çiçeği toplayın'	\
**B.**Gelincik çiçeğini kim toplıyacak?	\
**K.**Bendeniz,	\
**B.**Doğru söyle, niçin geldin buraya?	\
**K.**Hacivad, ne cevap vereyim?	\
**H.**Hakipayımzla görüşmeğe geldim.	\
**K.**Akif ağa ile dövüşmeğe geldim.	\
**B.**Burada Akif ağa isminde kimse yok.	\
**H.**"Efendim, sizinle görüşeceğim."	\
**K.**Efendim, sizinle görüşeceğim.	\
**B.**Ben çok lâkırdıdan hoşlanmam.	\
**K.**Bendeniz de mektebe başlanmam.	\
**B.**Söyliyecek söz mufassal olmasın, muhtasar, müfid olsun!	\
**K.**"Karşımda durmasın, gidip Hafidi bulsun" diyor.	\
**B.**Hangi Hafidi bulacağız?	\
**K.**Sizin.	\
**H.**Hafid, sizlere ömür! vefat etti.	\
**K.**Hafid sîzlere kömür getirirken Vefaya gitmiş.	\
**B.**Hafide ne olmuş?	\
**K.**Hafide ne olmuş. Hacivad?	\
**H.** "Murg-i hayatı kafes-i tenden pervaz eyledi."	\
**K.** Mor patlıcanı yiyen Kafesli Meyhanede kavga eyledi.	\
**B.**Kavga eden kim?	\
**K.** Bendeniz.	\
**B.**Pek tuhaf zat ve acube sıfat!	\
**K.**Topal Behzat, Necibe sıfır at!	\
**H.**Topal Behzat kim?	\
**K.**Çolak Mcmişin kardeşi sıfır atarsa, sora imtihandan geri kalır.	\
**H.** "Efendim, bendenizi Hacivad Çelebi gönderdi".	\
**K.** Efendim, bendenizi Hacivad Çelebi gönderdi.	\
**B.**Seni Hacivad mı gönderdi?	\
**K.** Evet efendim.	\
**B.**Zaten ben ona sipariş etmiştim.	\
**K.** Kulunuzum.	\
**H.** "Efendim, şâtır kulunuzum".	\
**K.** Efendim, katır kulunuzum.	\
**B.**Ben katır istemedim. Bizim dolabı çeviren katır var, fazla katırın lüzumu yok bana.	\
**K.** Hacivad. katır istemiyorlar, eşek İstiyorlar; sen git bari!	\
**H.** "Hakipayınız Hacivad Çelebiden hizmetkâr istemişsiniz, bendeniz efendime hizmet etmeğe geldim."	\
**K.** Hacivaddan himzekâr istemişsiniz; himzekârim efendim.	\
**B.**Pek âlâ, memnun oldum.	\
**K.**Ben de memnun oldum.	\
**B.**Şehriyü-l-asil misin?	\
**K.**Şemsiyeci Vasil değilim, Karagözüm.	\
**B.**Yoksa diyar-ı aherden misin?	\
**K.**Evet, değirmenin yanındaki ahırdanım.	\
**B.**Ne dedin?	\
**K.** ... darım, efendim.	\
**B.**Kanaat sahibi misin yoksa şikemperver mi?	\
**K.**Kandillideki acemi berberim.	\
**B.**Kanaat sahibi misin yoksa çok yemek mi yersin?	\
**K.**Kanaat sahibiyim.	\
**B.**Eğer gözüme girersen makbul olursun.	\
**K.**Dide-î âlinize kulunuzu istilâb ederse dahilen medhul olurum.	\
**H.**"Reviş-i halinize bakılırsa, mürüvvet madenisiniz efendim."	\
**K.**Geviş getirmenize bakılırsa koca öküzsünüz,	\
**B.**Ne dedin?	\
**K.**Eyi ki anlamadı. Bir şey değil efendim. Lâkırdı olsun diye söyledim amma, bereket versin duymadınız.	\
**B.**Söyliyeceğim sözleri dikkatle dinle!	\
**K.**Dinlerim efendim.	\
**B.**Bir hususî iş için bir yere gönderirsem hemen o anda damen-der-miyan olmalı.	\
**K.**Merdiven başında durmalı. Dururum efendim.	\
**B.**Bir şey ihtar edersem sem'ine vâsıl olmalı.	\
**K.**Bulurum efendim.	\
**B.**Kimi bulacaksın?	\
**K.**Akşam iftardan sora semerci Vasili bulmalı.	\
**H.**Efendi bir şey söylerse, kulağına girsin.	\
**B.**Hane derununda kuud etmeli.	\
**K.** Elbette kovulduğum vakit giderim, zorla oturulmaz ya.	\
**H.**"Evde otur" diyor.	\
**K.** Otururum efendim.	\
**B.**Her gün şükûfezarda geşt ü güzar etme!	\
**K.** Küfe omuzumda pazara gitmem, efendim küfesiz giderim.	\
**H.**„Hergün bahçede gezme!"	\
**K.**Gezmem, efendim, evde otururum.	\
**B.**Canın sıkılırsa pencereleri küşad cdüp mürur u ubura bakarsın.	\
**K.**Hacivad, efendinin canı sıkılırsa pencereleri mezada verip yıkılmış kuburu yaparsın.	\
**H.**„Canın sıkılırsa pencereyi açıp gelene geçene bakarsın."	\
**B.**Masarif-i beytiyeye sen bakacaksın,	\
**K.** Hacivad, yalınız evde sen yatacaksın.	\
**H.** ”Evin masarifine her bir hususuna sen bakacaksın.”	\
**K.** Bakarım efendim.	\
**B.**Mahiye mi istersin siliye mİ?	\
**K.** Mahya kurmak içün zeytin yağı isterim.	\
**H.**Aylık mı istersin yıllık mı?	\
**K.** Hem gündelik isterim, hem haftalık isterim, hem aylık isterim, hem yıllık isterim; arada sırada da bahşiş isterim.	\
**B.**Hem aylık hem yıllık olmaz.	\
**H.**İkisinden birisini kabul et!	\
**K.**Aylık isterim.	\
**B.**İşine devam etmezsen kıstelyöûm keserim.	\
**K.**Fıstık badem yeme, küserim.	\
**H.**”İşine devam etmezsen gündeliğinden keserim.”	\
**B.**Haydi gidelim! Muayyen bir maaş olmak üzere ayda üçyüz kuruş veririm.(Giderler.)	\
\
(Zühre hanım ile Arap halayık arkasında. Karagöze karşı gelirler.)	\
**Zühre.**Karagöz, Tahir bey nerede?	\
**K.** Bilmem efendim, nerede olduğundan malûmatım yok.	\
**Arap.**Nişim bilmiyorsun?	\
**K.**Benim de buna canım sıkılıyor, her şeye karışıyor.	\
**Ar.** Mundar, muskin, musubat şingana!	\
**Zü.**Karagöz, ne dedi?	\
**K.** ”Kitapları sıkıştırmak içün içeride mengene” diyor.	\
**Zü.**Tahir bey aceba nereye gitti?	\
**Ar.** Galiba gezmeye gitti.	\
**Zü.**Ne dedi, Karagöz?	\
**K.** ”Galiba ağabeyine gitti” diyor.	\
**Ar.**Her lâkırdıya bir şey uyduruyorsun.	\
**K.** ”Akşam sabah yiyip yiyip kuduruyorsun” diyor. Sen kuduruyorsun, köpoğlu!	\
**Ar.**Ağzını topla! Ben adamın ağzım yırtarım.	\
**K.** ”Mayısta ot otla, ben lâbada toplarım" diyor.	\
**Ar.**(gülerek).Ne tuhaf adam! Ben gidiyorum,(Gider.)	\
**K.** ”Yabani adam” dedi gitti.	\
**Zü.**Kuzum Karagöz, doğru söyle! Tahir bey nerede?	\
**K.** Galiba, efendim, av vurmak için seyre gitmiş.	\
**Zü.** Sayd ü şikâre mi gitti?	\
**K.** Said ağa ile aşkâre gitti.	\
**Zü.** Kuzum Karagöz, Tahir beyi al da gel!	\
**K.**Gideyim arayım. Bulursam alır gelirim.(Gider.)Vay Tahir bey! Neredesin? İki saattir seni Zühre hanım arıyor!	\
**Tahir bey.** (içeriden) Zühre hanım nerede?	\
**K.**(içeriden) Bahçede teşrifinize muntazır.	\
**Tahir.** (gelerek) Vay, Zühreciğim, sizler burada misiniz?	\
**Zü.** İki saattir zatı âlinizi arıyordum. Merak ettim, nerede kaldınız ?	\
**T.**Keklik vurmak için şikâre gittim, bir türlü vuramadım; eğer vursaydım sizlere getirecektim.	\
**Zü.**Keklik bana zatı âlinizdir. Tahirim, sizden eyi keklik mi olur, efendiciğim?	\
**Beyt-i Tahir.**Habe varmaz dideler her şeb hayal-i yâr ile,\
Akl u fikrim zail olur gördükçe ağyar ile.\
Bir dakika görmesem ruyun senin, ey mâhru.\
Başıma zindan olur dünya benim efkâr ile.	\
\
**Beyt-i Zühre.** Aff it bilmeyerek belki bir günah ittim ise,\
Yanılup yüzüne karşı nâle v'ah ittim ise.	\
Azıcık halime bak merhamet eyle efendim !\
Didelerim kör olsun gayriye nigâh ittim ise.	\
\
**Beyt-i Tahir.**Bir sitemkâre esir itti beni hükm-i kader,	\
Bir taraftarı felek sitem eyler ; ne iştir bu böyle?\
Başımı derde salıp virdi küduretle haber, \
Hiç ne mümkin bu benim tali'im olmak yaver.	\
\
**Beyt-i Zühre.**Bir sebeble sen gücendin mi bana?	\
Söyle sultanım, ne ittim ben sana?	\
İnfialin saklama, ey bivefa!	\
Söyle sultanım, ne ittim ben sana?	\
Rahmidüb feryadıma dâd itmedin,\
Bunca demlerdir beni yâd itmedin,\
Bir Selâm ile dahi şâd itmedin,	\
Söyle sultanım, ne ittim ben sana?	\
\
(Babası gelir, Zühre ile Tahir görüşürken dinler.)	\
**Baba.** (gizliden) Bunların bu halini görmek için çoktan beri arzu ederdim. Şimdi aynen müşahede ettim. Bunlar birbirine muhabbet ve iştiyakla müştaktırlar. Bu günden itibaren her ikisini birbirine akd-i izdivaç etmeli.(Gider.)	\
**Zü.**Tahirciğim, haydi gidelim! Belki bizim bu halimizi görürler de iki gönül birbirine rabtolmuş iken belki birbirimizden ayırırlar.(Gider).	\
\
**B.** (gelerek sandalyeye oturur).Karagöz!	\
**K.**(içeriden).Buyurun efendim!	\
**B.**Buraya gel!	\
**K.**Geliyorum!(Gelir.)Bir emriniz mı var?	\
**B.**Kızım Zührem nerede?	\
**K.**Su doldurur derede, İncili köstek boynunda. Tabir Beyin koynunda.	\
**B.**Tahir Bey kumar oyununda mı?	\
**K.**Değil efendim, içeride.	\
**B.**Zührem nerede?	\
**K.**Mühreniz içeriki odada yazıhanenin yanında duruyor; isterseniz getireyim.	\
**B.**Mühre beyninde paralansın ! Burada ben sana mühreyi sormıyorum; duhter-i pakizemi soruyorum!	\
**K.** O, sizlere ömür, vefat etti.	\
**B.**Vefat eden kim ?	\
**K.**Kurşuncu Nefise.	\
**B.**Herif, benimle eğleniyor musun? Kızım hücresinde mi? Bak da gel!	\
**K.**(gider gelir).Evet efendim, hücrede yan gelmiş oturuyor.	\
**B.**Hücrede oturan kim?	\
**K.**Bardak su destisiyle muhabbet ediyor.	\
**B.**Defol karşımdan, herif! Gözüm görmesin seni!	\
**K.**Efendim, benim ne kabahatim var beni kovuyorsunuz?	\
**B.**Senin bu mecnunane hareketlerini gördükçe şuuruma halel geliyor,	\
**K.**Akşamla mahalle kahvesine mi geliyor?	\
**B.**Mahalle kahvesine gelen kim?	\
**K.**Aşureci Hali!.	\
**B.**Ben sana aşureci Halili sormıyorum, eçhel herif ! Kızım kasırda mı, bak da gel!	\
**K.**(gider gelir).Hasırda yan gelmiş oturuyor.	\
**B.**Hasırda oturan kim?	\
**K.** Kızınız mindere darılmış, onun için hasırda oturuyor,	\
**B.**Kızım, bak, habıgâhta mı?	\
**K.**(gider gelir).Agâhta.	\
**B.**Seri bâlîne dayanıp hab-ı rahate mi dalmış?	\
**K.**Kahveci Agâhtan boşanıp sirkeci Rifata varmış.	\
**B.**Benim kızını seyyibe mi yoksa bakire mi?	\
**K.**Ne Seyyîde ne Bekire, ben alacağım efendim.	\
**B.**Herif, ne söylüyorsun? Budala mısın?	\
**K.**Hayır efendim, kaçığım. Kızın çoktan kocaya vardı Tahire.	\
**B.**Kızım nezaman ârus oldu?	\
**K.**Efendim, geçen akşam bizim horozu sansar boğmuş; onun yerine horoz oldu. Tavuklar yalınız kalmasın diye kümeste oynaşıp yatıyorlar.	\
**B.**Zevzekliğin lüzumu yok. Kızım gunuden pister-i rahatte mi bak!	\
**K.**Kayanam pis yatakta yatıyor.	\
**B.**Sen nasıl söz anlarsın, ahmak?	\
**K.**Söyleyiniz efendim, siz ne söylediniz de ben anlamadım?	\
**B.**Kızım firaşında mı?	\
**K.**Faraşında.	\
**B.**Nasıl faraşında?	\
**K.**Kızınız sokak süpürgesi olduğundan faraşının içinde oturuyor.	\
**B.**Çabuk git de bak, kızım hab-ı rahatte mi yoksa bidar mı?	\
**K.**Dar.	\
**B.**Ne dar?	\
**K.** Kunduranın bir teki dar, bir teki bol. Yağmur yağarsa bollaşır, hava sıcak olursa darlaşır.	\
**B.**Ben sana kundurayı sormıyonım. Kızım uyuyor mu bak da gell	\
**K.**(gider gelir).Uyuyor efendim.	\
**B.**Nevm galebe edüp habe mi dalmış?	\
**K.**Naime ile beraber obada kalmış.	\
**B.**Defol şuradan, budalâ sen de!	\
**K.**Efendim, benim ne kabahatim var?	\
**B.**Çabuk kızımı bana çağır.	\
**K.**Baş üst üne!	\
**B.**Horozu kaldır!	\
**K.**Tavuklar yatsınlar mı?	\
**B.**Öyle değil! Kapının horozunu kaldır yavaşça, kızım korkmasın!	\
**K.**Başüstüne efendim!(Gider.) Zühre Hanım, pederiniz sizi çağırıyor.\
**Zü.** (içeriden) Peki, gidiyorum.(Gelir.)Pederim, bendenizi istemişsiniz.	\
**B.**Evet kızım. Seni çağırmamın veçhi bu ki artık geldin yetiştin. Bana olacak hürmet ve riayette asla fütur etmeyip evlâtlık vazifesini hakkiyle ifa eyledin. Şimdi ise ben de pederlik vazifesini icra etmeliyim.	\
**Zü.**Ey benim hakikatli pederim! Keşki kapınızda cariyeniz olsaydım! Belki bu teklifi etmezdiniz.	\
**B.**Niçin istemiyorsun kızım? Ben sana fena bir şey teklif etmedim. (Bir mikdar sükût eder.) Niçin cevap vermiyorsun?	\
**Zü.**Daha vaktim değil. Tahsil-i ulûm etmek için çok vakte muhtacım.	\
**B.**Ben seni Tahire vermek arzusundayım.	\
**K.**Hava değişti!	\
**B.**Zühre, kızım! Sen kadınsın, yani zayıfsın, lâkin hanenin ziynetisin. Zevcin daima sende letafet bulmalıdır. Birbirinize teselli etmelisiniz. Elden geldiği kadar mesrur olmağa gayret etmeli ; çünkü sürur bir dereceye kadar kederi izale edebilir. Evlâdın terbiyesi, hane işi senden sual olunduğundan bu vezaifi hüsnü ifada kusur etmemelisin. Zevcine itaat et, elinde mağlûb olma! Haydi bakayam, her zaman için birbirinizin olunuz! (Zühre gider.) — Karagöz!	\
**K.**(içeriden).Buyurun efendim!(Gelir.)	\
**B.**Tahiri bana çağır!	\
**K.**Peki!(Gider.)Tahir Bey! Efendi seni çağırıyor.	\
**Tahir.** (içeriden).Karagöz, efendi beni ne yapacak?	\
**K.**(içeriden).Ne bileyim?	\
**T.** (gelir) Efendim, bendenizi istemişsiniz.	\
**B.**Tahir oğlum! Artık geldin yetiştin. Bu ane kadar gördüğüm hüsnü nezaket, ve senin bana olan hürmet ve riayette asla kusur etmedin. Şimdi ise seni evlendirmek arzusundayım.(Tahir sükût eder.)Niçin sükût ediyorsun ?	\
**T.**Daha vaktim değil, efendim. Bir çok zamanlar ulûm tahsil etmeliyim.	\
**B.**Hüsn ü haline halel getirmeksizin ikmal-i terbiye eylersen kızımı sana tezvic eyliyeceğimi vadedenim.	\
**T.**(elini öper) Eksik olmayınız efendim!	\
**K.**Hava değişti! Şimdi Zühre yıldızı esmeğe başladı.	\
**B.**İşret ve sefahat gibi rezailden ictinab evle!	\
**K.**Tahir kelepiri yakaladı!	\
**B.**Tahir oğlum! Sen erkeksin, yani büyük familyadansın. Eyice dikkat et ki haiz olduğun iktidar senden zail olmasın. Saadeti tahsil için pek çok meşakkatler çekilir. Felâketin ağır yükleri arasında ezilip yeis gelir, insanı her şeyden nefret ettirir. Bunların hepsine katlanmalı, feleğin her çevrine kahramanane davranup göğüs germeli. Hanenize girerken yine gülerek şen girmeli. Validenin, zevcenin ve bunlar gibi zayıfların daima gönüllerini almağa gayret etmeli. Çünkü kadınların kalbleri zayıf olduğu için erkeklerde cüz'î bir alâmet-i hüzün görseler kanlı yaş dökmekten kendilerini alamazlar. Erkeğin en ufak bir tesellisi kadınların en büyük hüzünlerini izaleye kâfidir. Sen evinin sahibi ol! Emret, fakat zulmetme! ( Tahir gider.) — Karagöz!	\
**K.**(içeriden).Buyurun efendim (Gelir, efendinin muttasıl elini öper.)Efendim, şey!	\
**B.**Ne şey?	\
**K.**Kulunuz geceleri yatarken korkuyorum.	\
**B.**Koskoca herif neden korkar?	\
**K.**Korkuyorum, elimde değil.	\
**B.**Ayvaz ile beraber yat!	\
**K.**Efendim, öylesi değil.	\
**B.**Öylesi değil ne?	\
**K.**Ayvazı istemem.	\
**B.**Bahçıvanla yat!	\
**K.**Efendim, kulunuzun vakti geldi; pilâv zerde de pişiyor.	\
**B.** Ne demek istiyorsun, anlamıyorum.	\
**K.** İki başlı, dört ayaklı, dört gözlü olmak.	\
**B.**Dört gözlü sefer tası istiyorsun?	\
**K.**Efendim, önümüz, kış, odun pahalı, kömür pahalı, sovukta donacağım.	\
**B.**Ben seni külhancıya söyler külhanda yatırtırım.	\
**K.**Bir türlü anlatamadık vesselâm.	\
**B.**Hanıma söyle; "Efendi şükûfezarda teşrifine muntazır".	\
**K.**Söylerim efendim.	\
**B.**Ne diyeceksin?	\
**K.** "Efendi küfe omuzunda pazarda hazırdır" derim.	\
**B.** "Efendi bahçede seni bekliyor" de!	\
**K.**Başüstüne!	\
**B.**(yüksek sesle). Ge~l	\
**K.**(yüksek sesle).Geldim efendim.	\
**B.**Hanıma söyle: Serine kellepoşunu Örtsün de gelsin!	\
**K.**Serinlikte tahtapoşa çamaşır sersin de gelsin'	\
**B.**Ge~l! — Amber geysularını tarasın da gelsin!	\
**K.** Amber Geysu kalfayı arasın da gelsin.	\
**B.** Ge~l— Ebrularına rastık çeksin de gelsin!	\
**K.** Sana yarım okka fıstık alsın da gelsin!	\
**B.**Ge~l! — Müjgânına sürme çeksin de gelsin!	\
**K.**Mirgûndan Sarıyere karadan gelsin!	\
**B.**Ge~l! — Ruhsarına zülüflerini döksün de gelsin!	\
**K.** Hisardaki Zülfüsiyahı dövsün de gelsin!	\
**B.**Ge~l! — Sim-i zenahdanını örtsün de gelsin!	\
**K.** Zemberek anahtarını alsın da gelsin!	\
**B.**Ge~l! — Veçh-i zibasını örtsün de gelsin!	\
**K.** Çeribaşmın Zıbayı görsün de gelsin!	\
**B.** Ge~l! — Elbise-i fahiresini giysin de gelsin!	\
**K.**Kurşuncu Tahireyi alsın da gelsin!	\
**B.** Ge~l! — Yeşil camelerini giysin de gelsin!	\
**K.** Terlikçi Ahmedi alsın da gelsin!	\
**B.** Ge~l! — Gûşuna mengûşunu taksın da gelsin !	\
**K.** Köşe başındaki sarhoşunu alsın da gelsin!	\
**B.** Ge~l! — Altın bileziğini koluna, tek taşlı yüzüğünü parmağına taksın da gelsin!	\
**K.** Kuyu bileziğini soluna, denk taşını sağına alsın da gelsin!	\
**B.** Ge~l! — Sarı kemerini beline, yelpazeyi eline alsın da gelsin!	\
**K.** Bozdoğan kemerini beline, su terazisini eline alsın da gelsin!	\
**B.** Ge~l! — Yaşmaklarını giysin de gelsin!	\
**K.** Başmaklarını alsın da gelsin!	\
**B.** Ge~l! — Çeşm-i mahmurlarını süzerek etraf u eknafı gezerek gelsin!	\
**K.**Çeşme başında Mahmud beyi üzerek etrafındaki esnafları süzerek gelsin!	\
**B.** Ge~l! — Reftar ile naz ederek gelsin.	\
**K.** Muhtar ile kaz güderek gelsin!	\
**B.** Ge~l! — Bin naz ile işvebazlıkla gelsin!	\
**K.** Çengi Binnaz ile hokkabazlıkla gelsin!	\
**B.** Ge~l! — Servi gibi hıram eyliyerek gelsin!	\
**K.** Semerci Vasili alsın da gelsin!	\
**B.** Ge~l! — Vücud-u nazikânelerini incitmiyerek gelsin!	\
**K.** Çocuklarla beraber incir yiyerek gelsin!	\
**B.** Ge~l! — Kalp ferahnâk olup sefalarla meserretle gelsin.	\
**K.** Ferah kalfaya bulup Vefadaki Meserret de gelsin! (Gider.) Baksan a, hanim efendi!	\
**Hanım.** Zührenin annesi (içeriden). Ne istersin, Karagöz?	\
**K.** Efendi seni istiyor.	\
**Ha.**Kendisi nerede?	\
**K.** Bahçede sizi bekliyorlar.	\
**Ha.**Hani benim nazar boncuğum? Nazar takımım nerede? Karagöz, eğer kaybolduysa sokağa böyle nasıl gideyim? Sora bana nazar değer!	\
**K.** Senin alnına bir eşek nah ile bir baş sarımsak, bir eski kundura asalım. o vakit kimsenin nazarı sana değmez.	\
**Ha.**Hani benim tuvalet takımım, nerede? Podra kutusu yok, allığım, nerede?	\
**K.** Senin alıklığın her yerde. Hiç gözünü açmazsın, yalınız ağzını açarsın !(Perdeye gelirler.)	\
**Ha.**Aman Karagöz, fenalaşıyorum!	\
**K.** Neden efendim?	\
**Ha.**Neden olacak? Çok yoruldum terledim!	\
**K.**isterseniz sizi gezdireyim, teriniz kurur.	\
**Ha.**Benimle eğleniyor musun? Musibete bak! Seninle sokağa çıktığıma pişman oluyorum. Her kes yüzüme bakıyor, hiç adam görmemişler mi bilmem!	\
**K.** Herkesin sana baktığı ne için, biliyor musun?	\
**Ha.**Ne için olacak? Güzelliğim için.	\
**K.** Yanlışın var. Vakitsiz maskaralar çıkmış diye bakıyorlar. Sizin burnunuzu görüyorlar da suratınıza maske takmış zannediyorlar.	\
**Ha.**Musibete bak! Benim burnuma çekme burun tâbir olunur.	\
**K.** Sizin burnunuza çekmece burun tâbir olunur? Küçükçekmece mi yoksa Büyükçekmece mi?	\
**Ha.**Benim gibi bir güzel de hiç sokağa çıkmasın, beni gören bayılıyor.	\
**K.** Herkes korkusundan bayılıyor; seni gören gulyabani zannediyor.	\
**Ha.**Seni beşaret seni! Benimle eğleniyor musun? Sen artık haddini tecavüz ettin! Bak, ben seni efendiye söyliyeyim de gör!	\
**K.** Senden eyi beşaret mi olur? Beşaret sensin!	\
**Ha.**Ne mırıldanıyorsun kendi kendine? "Şetarete ne olmuş" dedin?	\
**K.** Eyi ki anlamadı! — Bizim Şetaret kalfa eyi yemek pişiriyor da onu söylüyorum.	\
**Ha.**Evet, güzel yemek pişirir.	\
**K.** Nasılsa yutturduk.	\
**Ha.**Cuma günü efendiye Kâthaneye gitmek için araba mı tut turdun?	\
**K.**Evet.	\
**Ha.**Bu günlerde galiba isabet-i ayna uğrıyacağım.	\
**K.** Postan ise uğrarsın, postan değilse uğrıyamazsın.	\
**Ha.**Nereye?	\
**K.** "Bu gün Galip ağa ile Kuzguncuğa uğrıyacağım" demedin mi?	\
**Ha.**Benimle mehtaba mı çıkıyorsun?	\
**K.** Hayır, ay karanlığında oturuyorum. Senin yanında bir insan bulundu mu şeb-i deycurda kalmış gibidir.	\
**Ha.**Anahtar Dilcuda m! kalmış?	\
**K.** Evet, Galata borsası kapanmış.	\
**Ha.**Galetadaki kârgirler mi yanmış?	\
**K.**Hayır, basılmış. İkimiz de birbirimizden uğursuz. İçimizde lâkırdı anlıyan varsa beri gelsin!	\
**Ha.**Karagöz, yüzüme o kadar dikkatli bakma! Bana nazarın değecek. Ay! Fena oluyorum!	\
**K.**Sana benimki değmez. Ben nazargâh değilim. Ben senin gibi güzelleri kibrit kutularında çok gördüm umma, böyle değil. Nazarım değse onlara değer; sen hiç merak etme, sana bir şey olmaz.	\
**Ha.**Tuvalet takımını aceba kızlar kaldırdı mı?	\
**K.**Evet efendim. Efendi geçen gün seni mürd oldu diye beni öteye beriye saldırdı.	\
**Ha.**Efendi benim üzerime Gülbeyazı mı kandırdı?	\
**K.** Vay gidi lâkırdı anlıyan hanım vay.	\
**Ha.**Sahi mi söyliyorsım, Karagöz? Şimdi yüreğime inecek! Benim üzerime efendi hainlik etsin?	\
**K.** Haniya o günler? Sen ölürsen biz kurtuluruz.	\
**Ha.**Ne dedin. Karagöz?	\
**K.** "Minderdeki yünler" dedim. Sen olmasan bizim halimiz nice olur!	\
**Ha.** Eksik olma. Karagöz! Sen beni seversin bilirim. Efendin nerede kaldı aceba?	\
**Baba.** (gelir).Vay, hanım efendi, nerede kaldınız?	\
**Ha.**Kasırdan çıktım, Karagöz ile birlikte ağır ağır geliyorduk. Arkamıza bir takım adamlar düştü.	\
**B.**Demek ki etraf u eknafı temaşa ederek geldiniz, öyle mi?	\
**Ha.**Evet efendim. Esnai rahta gelirken, bir çeşme-i râna ve yanında bir şecer-i balâ vardı; o ağacın sayesinde oturduk	\
**B.**Bir az dinlendiniz ini?	\
**Ha.**Evet efendim. Arkamızda bir takım delikanlılar geldiler, karşımıza oturdular.	\
**B.**Demek sizi takip ettiler?	\
**K.**Evet efendim. Arkamızdan taktuka ile süprüntü döktüler, hanımı tanzifat arabası zannettiler.	\
**Ha.**İçlerinden birisi bana harf atmağa başladı.	\
**B.**Karagöz, söz attılar mı?	\
**K.**Söz atmadılar amma, ikimize bir temiz dayak atacaklardı. Bereket versin çabuk kaçtık!	\
**Ha.** " Behey hayatım, behey gözüm! Benim bu çektiğim zahmet ve meşakkat ve giriftar olduğum aşk u muhabbet hep senin güzelliğinden neş’et etmiştir. Zevcinin başı için olsun bana ruyunu göster" diye tazarru ve niyaz eyledi.	\
**B.**Tinet-i asliyesinde merkûz olan habaseti izhar eylediler, öyle mi?	\
**K.**İstinye körfezinde kumar oynadığından Hisarda iflas eyledi.	\
**Ha.**Bendeniz de hiddetimden bunları kovdum, "Ey benim nur-u aynım! Benim senden başka mahbubem yoktur. Sen beni tard u teb’id etme! Edince kime gideyim ve halimi ifşa edeyim?" demesin mi?	\
**B.**Karagöz, sen o esnada kazık gibi duruyor muydun?	\
**K.**Hayır, rıhtım gibi oturuyordum.	\
**Ha.**Defatan bir ah çekip bendenize bir beyit söyledi.	\
**B.**Karagöz, ne söyledi?	\
**K.**Evvelâ hanım söylesin de sonra ben.	\
**Ha.**Çesm-i mestim, hasta sanma âşık-ı biçareni	\
Hab-i rahatten figan u ahı dür eyler seni.	\
**B.**Karagöz, öyle mi söylediler?	\
**K.**Hayır efendim, öyle söylemediler.	\
**B.** Ya ne dediler?	\
**A** Çeşme başını boş sanma, ört çevreyi burnuna	\
Fıstık ağacının dibinde leylek zannettik seni.	\
dediler. Hanımın burnunu gördüler leylek zannettiler.	\
**K.** Haydi musibet! Benim burnuma çekme burun tâbir olunur. Efendim, içlerinden birisi de bir beyit daha söyledi.	\
**B.** Karagöz, ne söyledi?	\
**K.** Nöbet evvelâ hanımın, sora bizim.	\
**Ha.**Bir görüşte mail oldum nergis-i mest anına,	\
Kâmyab eyle efendim, gelmişem divanma.	\
Böyle cevr itmek mi kâri daima lütfün senin	\
Ben kulun olsam sezavar lutfuna ihsanına?	\
**B.**Karagöz, öyle mı söylediler?	\
**K.**Yalanı yok, yanlışı var.	\
**B.**Ne dediler?	\
**K.**İri salatalık yersen gel Sergizin bostanına!	\
Burnuna zinciri takıp götürün deve hanına!	\
Böyle eşeklik etmek midir daima kârin senin?	\
Pek ziyade kırılmayın yestehlerim  fistanına! dediler.	\
**B.**Karagöz, bu günlerde hanımın pek güzelliği var. İsabet-i ayna uğrıyacak. Bir kaç tane kum karanfil çatlatalım!	\
**K.** Bir kaç tane kuru karanfil çatlatacağımıza hanımın burnunda bir nüsha fişeği patlatsak daha eyi olur.	\
**Ha.**Haydi beşaret sen de!	\
**K.**Hanımı bu sene tebdili hava için Modaya götürelim!	\
**B.**Eyi dedin. Karagöz!	\
**K.**Moda karşısına hanımı yüzü üstüne yattırırız, üste de toprak örteriz, orası liman olur. Bazı fırtınaya tutulan kayıklar liman gibi orada gizlenirler; iki burun karşı karşıya olur.	\
**Ha.**Efendim, bendenizi niçin çağırttınız?	\
**B.**Biz gelelim ma-nahnü-fthimize! Seni çağırtmamın veçhi: kizım Zühreyi Tahire vereceğim. Her ne kadar ben pederi isem de sen de validesisin. senin de rızam tahsil etmeli.	\
**H.**A efendi, deli mi oldun? Onların da ikisi de çocuktur, daha vakitleri değil!	\
**B.**Çocuk olup ta yedişer yaşında değil ya! Her ikisinin on yedişer yaşla nnda vardır.	\
**Ha.**Baksan a! Bir şey söliyeyim! Onlan birbirlerine vermek olmaz. İkisi de birbirlerini kardeş gibi seviyorlar, bu nasıl olur?	\
**B.**Ben söz verdim; bunları mutlaka birbirlerine vereceğim; sözümden nükûl etmek olmaz.	\
**Ha.**Benim neme lâzım? A! üstüme eyilik sağlık! Var. ne yaparsan yap!(Giderler; defa Karagöz ile hanım gelirler.)	\
Ah. Karagöz, sana bir şey söyliyeceğim.	\
**K.** Buyurun efendim!	\
**Ha.**Etrafı dinlet Kimse olmasın!	\
**K.**Kimse yok.	\
**Ha.**Şu kapıları da kapa!	\
**K.**(gider gelir).Kapadım efendim.	\
**Ha.**Hiç kimse yok ya?	\
**K.** Acaba hanım çıldırdı mı?	\
**Ha.**Karagöz, için sırlı mı?	\
**K.**Sırlı değilim. Göksu destisi gibi bir şey saklıyamam , sızarım.	\
**Ha.**Ah Karagöz ah! Yanıyorum!	\
**K.**Tulumbacılara haber verelim mi?	\
**Ha.**Değil a canım! Öyle yanma değil; derunumda ateşler var.	\
**K.** Ne demek istediğinizi anlıyamıyorum.	\
**Ha.** "Zalİm! Beni söyletme derunumda neler var" fehvasınca se...se...	\
**K.** . . . viyorum.	\
**Ha.**Seviyorum. Karagöz.	\
**K.** Hanım acaba abayı bana mı yaktı?	\
**Ha.**Karagöz, Tahir Beyi seviyorum. Zühre olacak aşüfte benim üzerime Tahire gönül vermiş; ikisi de birbirlerini pek çok seviyorlar. Ben dururken Zühre Tahiri sevmek olur mu?	\
**K.**Doğrusu: olamaz. İkiniz de birbirinize lâyıksınız: Yarım elmanın yarısı Tahir, kabukları da siz. Terazinin bir gözüne seni, bir gözüne Tahir Beyi koymalı, ikiniz de bir deliksiniz, yalınız daranız alınmamış.	\
**Ha.**Karagöz. doğru söyle, tenasüb-ü azada noksan mıyım yoksa güzellikte güzellik, boyda boyum mu yok, gözde gözüm mü yok?	\
**K.** Gözünüz yok değil, var. Tabirde!	\
**Ha.**Kaşta kaşım mı yok acaba?	\
**K.** Bir yeri unuttunuz; oraya gelince çabuk geçiyorsunuz: burunda bur	\
nunuz mu yok? Haritada mevcut olan Ümidburnu gibi.	\
**Ha.**Karagöz, nasıl yaparsan yap, bu işin çaresine bak! Yoksa civanlığıma yazık olacak, kaldırıp kendimi kuyuya atacağım.	\
**K.** Kuyuyu da murdar edeceksin.	\
**Ha.**Kuzum Karagöz, gençliğime merhameten bu işin çaresine bak!	\
**K.**Ne efendim? Benim elimde ne var?	\
**Ha.**Ben sana para veririm , bizim mahalli de bir koca karı vardır, ona büyü yaptırırsın ; o vakit efendi Tahirden soğur. Zührevi Tahire vermez,ben de meramıma nail olurum, olmaz mı, Karagöz?	\
**K.**Burasını bir az düşünmeliyim. Senin gibi bir mel'unenin hevesat-i mülevvesesine hizmet etmek kabil mı?	\
**Ha.**Karagöz, al bu beşibiryerdeyi, bu işin icabına bak; ben sana daha çok para veririm,	\
**K.**(alarak).Peki, bu işin icabına bakarım.(Gider.)	\
\
(Efendi gelir, Karagözü çağırır, Karagöz gelir.)	\
**B.**Karagöz, bir az uyuyacağım, beni bekle!	\
**K.**Başüstüne efendim.(Baba uyur.)Nusha başına sokulacak, verdiği toz da bardağın içine konup su ile içirilecek. Elim ayağım da tiril tiril titriyor.Keşki yapmayıdım şu işi! (Bir an gelir, vızlıyarak gezer, efendinin üstüne doğru gider, Karagöz kovar, yine gelir vızlıyarak gezer, K. kovar, vine gelir. Eline bir sürpürge alır arıyı kovarken efendinin başına süpürge ile vurur. Efendi uyanır.)Ulan zembur-u himar! Vay köpoğlu!	\
**B.**Herif, ne yapıyorsun?	\
**K.**Efendim, kaza oldu, kusura bakmayın! Arıyı kovayım derken başınıza rasgeldi.(Efendi yine uyur.)	\
**Ha.** (efendinin arkasından).Karagöz, nushayı soksan a efendinin başına!	\
**K.** (sokarken yanlış sokar). Ulan, bir türlü cesaret edemiyorum.	\
**Ha.** Karagöz, burnuna sokuyorsun!	\
**K.** (sokar.hanım gider).Nasılsa soktuk! Korkumdan titriyorum.	\
**B.** (sayıklar).Evet, vermiyeceğim. Zühreyi Tahire vermiyeceğim.(Dik sesle:) Evet, sözümden nükûl ettim, vermiyeceğim!	\
**K.**(korkar).Vay, iş fenalaştı!	\
**B.**(uyanır, Karagözün boynuna sarılır).Evet. Öldüreceğim.	\
**K.** Aman efendim! Kendinize geliniz! Yanınızdaki benim!	\
**B.**Karagöz, sen misin? Aman, pek fena oldum ! Bir rüya gördüm gayetle korkulu! Sen bana bir su getir!	\
**K.** Başüstüne! — Şimdi sırası amma, amması var!(Gider, bardakla su getirir, efendi içer, bardağı Karagöze verir, K. götürür gelir.)	\
**B.**Rüyamda sayd u şikâra gitmişim. Esna-i rahta giderken yolum bir şükûfezara uğradı. Bir de baktım ki orta yerde bir köşk; içine girdim, köşkün içi döşenmiş; ortasında binazir bir şadırvan yapılmış, dört tarafında altından arslan ağızlarından ma-ı leziz cereyan eder ve bahçesinde enva-ı reyahin ve ezhar olduğunu seyr u temaşa eylerken nagehan bir kapı açıldı: içeriden bir ifrit zuhur ederek üzerime hücum eyledi. Beni telef edecekti. Her ne kadar kendisine tazarru ve niyaz ettimse de ricamı aslâ kabul etmeyip beni reddetti. Bana hitaben "Sen Zührenin pederisin değil mi?" diye sual eyledi. Benden "Evet" cevabını alır almaz def'aten üzerime hücum ederek "Eğer sen kızını Tahire verecek olursan şimdi şu anda seni telef ederim!" diye kasd eyledi. Nasılsa gözümü açtım seni gördüm.	\
**K.**Hayırdır inşallah efendim !	\
**B.**Karagöz, hanımı bana çağır!	\
**K.**Başüstüne. Vay acuze vay! Senin yüzünden neler olacak!(Gider. İçeriden.)Hanim efendi, sizi efendi çağırıyor!	\
**Ha.** (gelerek).Buyurun efendim! Beni istemişsiniz!	\
**B.**Baksan a bana, hanım!	\
**Ha.**Buyuran, arslanım!	\
**B.**Zühreyi Tahire vermek için söz vermiştim.	\
**Ha.**Evet efendim.	\
**B.**Bu olmıyacak. Bu işten rücu ettim.	\
**Ha.**Aman efendim! Hiç böyle şey mi olur? Her kes duydular; sizin cemiyet yapacağınızı kendilerine bile söylediniz: şimdi bize ne derler?	\
**B.**Ne derlerse desinler, söz benim olacak.	\
**Ha**Ne yaparsanız yapın, ben işinize karışmanı. Evvelâ razı oldunuz, sora caydınız. Ben gidiyorum.(Gider.)	\
\
**B.**Karagöz!	\
**K.**(gelerek).Buyurun efendim! — Vay düztaban köpoğlu vay!	\
**B.**Tahir nerede?	\
**K.**Nerede olacak efendim? Zühre hanımın yanında.	\
**B.**Haremde ne işi var?	\
**K.**isterseniz Salacağa çıksın,	\
**B.**Çabuk bana çağır!	\
**K.**Başüstüne!(Gider. İçeriden.)Tahir bey. sizi efendi istiyor.	\
**Tahir.**Kendisi nerede?	\
**K.** Bahçede.	\
**T.** (gelir).Bendenizi istemişsiniz. Ne var efendim? Çehrenizde sufret gelip veçhinize bir fenalık âriz olmuş, hasta mısınız?	\
**B.**Hasta değilim. Size bir sözüm var.	\
**T.**Buyurun efendim!	\
**B.**Oğlum Tahir! Seni çağırmamın veçhi: Kızım Zühreyı sana vermek için her ne kadar söz vermiş isem de hal bu ki bu aralık bu olamıyacak. Sana bir mikdar harcırah ve bir at vereyim de bir kaç mahı mütecaviz dolaşır sora yine gelirsin olmaz mı oğlum?	\
**T.**Aman efendim, bu neden icab ediyor? Bendeniz zatı âlinizin yanında bir kabahat mı işledim? Tard u teb’ide neden müstahak oluyorum?	\
**B.**Bu suallerin lüzumu yok, çünkü böyle istiyorum.	\
**T.**Benim, efendim, velimemiz için söz verdiğiniz günden beri dilşad u ferahnak idim. Şimdi ise bu haberi alır almaz mağmum u mükedder olarak vücuduma bir illet âriz olmuş gibi bir fenalık hissediyorum. Aman, efendim, aziz başınız için olsun bendenizi reddetmeyiniz!	\
**B.**Oğlum Tahir! Sözümü reddetme, sura fena olursun!	\
**T.**Bu iki biçarenin nahak yere kanına gireceksiniz. Aman efendim, mürüvvet buyurun! Kızınıza olan şiddet-i muhabbetim ve size olan sıdk-ı ubudiyetimi, aman efendim, hatırınızdan çıkarmayınız! Diğer bir mahalde benim yaşılmaklığım mümkün olamaz, cansız ceset hareket edebilir mi?	\
**B.**Ahlâk-ı hamidem ahlâk-ı zemimeye münkalıp oldu. Sana emrediyorum: Bu günden itibaren buradan gideceksin’	\
**T.**Mademki bendenizi icbar ediyorsunuz. bendeniz de buradan bir yere gidicilerden değilim!	\
**B.**Vay, bana bet muamele ediyorsunuz! Bu ana kadar benim nan u nimetimle perverde ol da şimdi ise benim sözüme inkiyat etmeyip sözlerimi reddediyorsunuz öyle mi? Ey sefih-i nan ve münkir-i nimet olan menhus! Şimdi seni cebirle buradan Mardin şehrine göndereyim de ilelebed orada mahpus dur! işte, sana lâyık ve seza böyle cezadır ki sana hilmiyet etmek büyük hatadır. — Gel. kim var orada?	\
**K.**(gelerek).Buyurun (fendim!	\
**B.**Çabuk seymanbaşmı bana çağır!	\
**K.** Peki efendim!(Gider.)Seymanbaşı! Efendi seni istiyor.	\
**Arnavut.** Efendim, bizi istemişsiniz.	\
\
**Tahir.**Gelmeyin yanıma! (Zorla tutarlar.)Eyvah!	\
\
Bülbülün feryadı damı güllere,\
Sefasın sürmeden geçti gidiyor!\
Üftadeler yalın ayak yollara \
Ağlıya ağlıya düştü gidiyor!	\
\
Gül taciz olmuştur bülbülün sesinden,\
Doyulmaz Zühremin şirin sözünden.	\
Eyvah, can kuşu ten kafesinden \
Küşad-ı bab edüp uçtu gidiyor!	\
\
Ecel gelse demez: bay, gedasın.	\
Ben öleyim. Zührem binler yaşasın!	\
Yetiş bahtı kara, helallaşasın, \
Tabir ecel camın nuş itti gidiyor!	\
\
( Tahiri götürürler.)	\
\
**Zühre.**\
Felek ayırdı beni cevr ile cananımdan.	\
Hazer itmez mi acep nale vü efganımdan?	\
Oda yandırsam bir şule ile nüh feleği\
Ne yeter ateş-i ah-ı dilsuz itmeden.	\
\
Gitti Tahir, hemtürab oldu teni.	\
Bu gün için mi saklamış hazret-i Mevlâ beni?	\
\
(Zühre bayılır. alırlar götürürler.)	\
\
**K.** (gelir)Gördün mü olan işleri? Hep kabahat bizde oldu! O cadının sözüne uyup ta musibet tellâlı olduk. Ben de odama çekileyim de bir parça rahat edeyim.(Gider.)	\
\
**Tahir.** (mahpus haliyle gelerek).Ah, nihayet kurtuldum! Bir takım canilerin ellerinden halâs bularak sürüne sürüne buraya kadar geldim. Ah! Tab ü tüvanım kalmadı! Dünya göziyle ölmeden bir daha sevgilimi göreydim, o zaman ölsem de hiç gam yemem. Ben kabahatın başı kim olduğunu biliyorum. O Karagöz olacak alçak hain nankör karı ile şeriktirler. Ben de onların her ikisinden de öcümü almazsam bana da adam demesinler! (Gider.)	\
**K.**(içeriden).Yine zıkr-ı menhusum sebkat etti!	\
**Baba.** (gelerek).Karagöz!	\
**K.**(gelerek).Buyurun efendim!	\
**B.**İçeriden bir ses geliyor, baksan a!	\
**K.**(gider) Vay, Tahir bey gelmiş! Şimdi ayı kazana yestehledi!(Gelerek:)Efendim, Ta ... Ta ... Ta . ..	\
**B.** (hiddetle).Ne olmuş?	\
**K.**Tahın yemişler.	\
**B.**Kim yemiş?	\
**K.**Yiyen yemiş. Zühre hanım yemiş, çanağı da odaya bırakmış.	\
**B.**Ben sana tahin yiyen mi soruyorum?	\
**K.** Ben sana pekmez içen mi soruyorum'	\
**B.** Git, bak da gel! İçeriden bir ses geliyor.	\
**K.**(gider gelir).Ta .. . Ta .. . Ta ...	\
**B.**Ne olmuş, herif? Senin damağının altında bir şey var.	\
**K.**Damağımın altındaki dilim.	\
**B.** Hay, dilin tutulsun.	\
**K.**Senin çenen çekilsin! — Efendim. Ta . . . Ta.,. Ta . . .	\
**B.**Ne olmuş, ne?	\
**K.**İçeriki odada tatarcıklar var. Eskiden orada adam yattığı zaman lâkırdı ederlermiş. O lâkırdıları tatarcıklar açlıktan yemişler, sora başlamışlar konuşmağa. Şimdi onların sesleri buraya geliyor.	\
**B.** Karagöz, ben bunları yutayım mı?	\
**K.**Çiğneye çiğney. tükürün efendim! Niyet tutun da size üç tane mani söyleyim.	\
**B.**Herif, maninin türkünün sırası mı şimdi?	\
**K.**İçimden geldi. Kuzum efendim, kırk yılda bir benim sözümü dinleyin, kırmayın beni! "Her kim benim kalbimi kıra kendisi de ola kara!"	\
**B.**Söyle bakalım!	\

**K.**Mani	\
Hanim buradan gidecek.	\
Rümuz ile bilecek.	\
Tahir buraya gelirse	\
Elbet bir kan edecek.	\
\
Mani	\
Fahişelikte bahir.	\
İşlerim oldu zahir.	\
İçeriden ses geliyor,	\
Mardinden geldi Tahir.	\
\
Mani	\
Büyük hamın fahirdir,	\
Sahharlıkta mahirdir.	\
işler meydana çıktı,	\
içerideki Tabirdir.	\
\
**B.**Vay! Tahir geldi mi ?	\
**K.** Benim haberim yok efendim; siz kendiniz söylüyorsunuz.	\
**B.**Çabuk buraya gelsin, çağır!	\
**K.**Nasılsa biz yakayı kurtardık.(Gider.)Tahir bey. seni efendi istiyor.	\
**Zühre **(içeriden). Pederim ne yapacak Tabir beyi?	\
**K.**(içeriden).Bilmem efendim.	\
**Tahir.**Zühreciğim, ben şimdi gelirim. (Gelerek:)Buyurun efendim, bendenizi istemişsiniz.	\
**B.**Tahir, buraya ne cesaretle geldin? Seni yolda kaçırdılar mı? Yoksa yalvardın da haline merhameten salıverdiler mi? Yoksa kendi hüsn-ü rızaleriyle koyuverdiler mi?	\
**T.**Tuhaf söylüyorsunuz efendim! Kendi cesaretimle geldim. Adamlarınız beni ne kaçırdılar ne de halime merhameten salıverdiler. Onların merhametini celbetmek pek güç. Emriniz üzere beni götürüp Mardin şehrine teslim ettiler.	\
**B.** Ne çabuk buraya geldin. Gittiğin mesafe-i baide!Doğru söyle! Yalan söylüyorsun!	\
**T.**Hilafı asla kabul etmem. Adamlarınızdan anlıyâbilirsiniz.	\
**B.**Çabuk. Karagöz, seymanbaşını çağır bana!	\
**K.**(gider).Buraya gelin! Efendi çağırıyor.	\
**Arnavut.**(gelerek).Buyurun efendim!	\
**B.**Siz Tahiri Mardin şehrine götürmediniz mi?	\
**Arnavut.**Götürdük efendim. Götürdüğümüze dair bir kefat bile aldık. Alınız efendim!	\
**B.** (kağıdı okuyor).Siz Tahiri görseniz tanır mısınız?	\
**Arnavüt.** (Tahiri görürler şaşarlar. Efendinin başından nushayı koca karı alır.)Vay, Tahir burada!	\
**K.**Vay, nüshayı aldı köpoğlu.	\
**B.** (uykudan uyanır gibi).Amanın, bana bir şey oldu! Uykudan uyanır gibi şimdi aklını başımageldi! Ettiğim işlere nadim ve pişman oldum!	\
**T.**Dur efendim! Şimdi işin esasını anlarsınız!(Kama ile Karagöze vurur.)\
**K.**Amanın, sıcak sıcak içime bir şeyler girdi!	\
**T.**İşin hakikatini kama ile anlat!	\
**K.** Efendim, sözün doğrusu: Sizin büyük hanını Tahire muhabbeti olduğundan bana para verdi büyü yaptırdı. Bir nusha ile bir toz verdiler. Nushayı başınıza soktuk, tozu da su ile içirdik. Ondan sora sizin efkârınız değişti, sözünüzden döndünüz.	\
**B.**Demek ki bu kadar felâkete ben sebep oldum. Tahir oğlum! Benim kusurumu affet! Size tarziye veriyor, kusurumu itiraf ediyorum.	\
**T.**Estağfurullah efendim. Kusur daima küçüklerdedir.	\
**B.**Haydi, içeriye gidelim de bu günden itibaren düğünümüze mübaşeret edelim!(Hepsi gider.)	\
\
**Ha.** (gelerek) Acaba Tahirin gönlünü kendime celbedemiyecek miyim?	\
**T.** Behey fahişe! Benim bu çektiğim zahmet ve meşakkat ve giriftar olduğum belâ-yi mihnet hep senin iktisab eylediğin fazahat ve kabahattan neşet etmiştir ki zevcin biçarenin duçar olduğu azaptandır. Gerçi zahirde ona ise de batında banadır. Mademki o biçare muazzep olur, beheme hal benim halâs olacağım yoktu. Nasılsa kurtuldum.	\
**Ha.**Efendim, sizin güzel hatırınız için zevcimi ol beliyeden halâs edip olveçhile siz efendimi dilşad eyledim. Artık şimden sora birbirimizin oluruz.	\
**T.** Vay! Bu kadar fazahatı ve kabahati yaptıktan sora bir de utanmadan "Birbirimizin olacağız" diyor! Seni alçak! Ben de senden intikamımı alayım da gör! (Vurur.)	\
**Ha.** Amanın,can kurtaran yok mu? Gençliğime doyamadan gidiyorum!(Ölür.)	\
**T.**intikamımı aldım.	\
**K.** Can kurtaran  var amma, gemide; orası da bir az uzakça!	\
( Hitam.)	\




