


# balık muhaveresi

(Von Küçük Ali)	\
\
(İlk muhavere bitlikten sonra yardaklar bir şarkı okurlar. Şarkı bitince aşağıdaki türküyü söyliyerek Çelebi kayıkla Hacivad tarafından gelir. Kürekte Arap Mercan Ağa oturur.)	\
\
Türkü	\
Mercan balığına attım oltayı.	\
Kefali görünce geriye kaçtı.	\
Palamut ağzından ateşler saçtı,	\
Bu sene balıkçılık pek yaman kaçtı!	\
Laka lak lak, cumlak cumlak, mastora bak	\
\
**Çelebi.**Ey Mercan Ağa! Eğer bolca balık tutarsak, sana bir çift kırmızı pabuç, bir kırmızı fes, bir kırmızı şalvar alırım.	\
**Mercan.**Eksik olma, koçuk beyim!	\
**Ç.**Sen yavaş yavaş küreği çek, ben oltayı atıyorum!	\
**Mer.**At bakalum! Balık tutarsan bana kırmızılı mırmızılı babuç alajak, öyle mi?	\
**Ç.**Alacağım. Aman Mercan Ağa, kürekleri suya yavaş batır! Balık geliyor.	\
**Mer.**(sevimle). Aman, geliyor!	\
**Ç.**Aman, sus! Geliyor.	\
**Mer.** Geldi mi balık?	\
**Ç.** (yavaş sesle).Sus! Geldi.	\
**Mer.** (yavaş sesle).Tutuldu mu?	\
**Ç.** (yavaş sesle). Sus! Tutulacak.	\
**Mer.** (sevinçle bağırarak).Bana kırmızılı mırmızılı babuç alajak mı?	\
(Balık kaçar.)	\
**Ç.**Sus, canım! Ne bağırıyorsun? Balığı kaçırdın!	\
**Mer.** Niçun kaçlı o kerata? \
**Ç.** Bağırdın kaçtı.	\
**Mer.** Söyle ona kaçmasın!	\
**Ç.** Hiç balık lâf anlar mı?	\
**Mer.** Anlamaz olur mu? Ben bağırınca nasıl kaçıyor?	\
**Ç.**Aman Mercan Ağa, sus! Balık geliyor.(İkinci balık gelir.)	\
**Mer.**Tutuldu mu?	\
**Ç.**Sus, canım'	\
**Mer.**Bana kırmızılı mırmızılı babuç alajak mı?	\
**Ç.**Sus canım! Alacağım.	\
**Mer.**er.(bağırarak). Aman, koçuk bey kırmızılı mırmızılı babuç alajak.	\
( Balık kaçar.)	\
**Ç.**Gördün mü? Balık yine kaçtı.	\
**Mer.**Niçin kaçtı o kerata?	\
**Ç.**Tabii, bağırdın, korktu kaçtı.	\
**Mer.** Korkmasın gelsin!	\
**Ç.**(hiddetli).Bak, Mercan Ağa! Bir daha bağırırsan sana ne pabuç alırım ne de fes. İşte bu kadar.	\
**Mer.**Bağırmam, koçuk Bey!	\
**Ç.**Sus! Balık geliyor,(üçüncü balık gelir.)	\
**Mer.** (yavaş sesle). Balık geldi mi?	\
**Ç.** (yavaş sesle), Geldi, sus!	\
**Mer.** (yavaş sesle), Tutuldu mu?	\
**Ç.**(yavaş sesle). Sus! Tutulacak. (Balık tutulur. Çelebi oltayı yukarı kaldırırken ) \
**Mer.** (yavaş sesle).Tutuldu. tutuldu. (Bağırır: ) Kırmızılı mırmızılı babuç alajak mı? Tutuldu (Balık oltadan kaçar.)	\
**Ç.** (hiddetli), Allah müstahakkım versin! Haydi, çek kayığı, gidelim!	\
**Mer.**(hem söylenir hem çeker; giderler).Kırmızılı babuç alamadı; balık tutamadı. (Giderler.)	\
\
**Karagözün karısı** (içeriden).Yahu!	\
**Karagöz.**(içeriden) Ne var?	\
**K.k.** Böyle miskin miskin oturacağına bari git te şurada deniz kenarında bir iki tane balık tut da yiyelim!	\
**K.** Eyi aklıma getirdin! Nerede senin çamaşır teknesi?	\
**K.k.**Çamaşır teknesini ne yapacaksın?	\
**K.** Kayık yapacağım.	\
**K.k.**Hay bunak herif hay! Hiç çamaşır teknesinden kayık olur mu?	\
**K.**Ne vazifen senin? Sen teknenin yerini söyle!	\
**K.k.**İşte orada mutbakta duruyor.	\
**K.** Sen oradan bir parça yorgan ipliği ver, bir de toplu iğne!	\
**K.k.**Ayol! Hiç yorgan ipliğiyle, toplu iğne ile balık tutulur mu?	\
**K.** Hüner öyle tutmaktır.	\
**K.k.**öyle tutacağına soyun denize dal da tut!	\
**K.**Daha senin kadar ustası olamadım. Sen tavayı hazırla da ocağı yak! Ben şimdi senin istediğin balıklan tutar gelirim.	\
**K.k.**Haydi bakalım, görelim.	\
**K.**Sen şimdi görürsün. (Kayıkla meydana gelir.) Haydi bakalım! Ya kısmet! Şu benim karıma karşı yüzümü kara çıkarma! Şöyle irice okkalıca bir tane gel de...Gel! gel! gel! ( Balık gelir tutulur, K. kayığa alır.) Hey anam babam! Karı  kulakların çınlasın! Bir tane yakaladım ki! (Tekrar ollayı atar.) Gel, gel gel. babam, gel! (Kir daha tutar, kayığa alır.) Oh! Anam babam! Derya kuzusu mübarek! Karı, kulakların çınlasın! Şu önümdekini bir hafta yesen bitiremezsin. Balık değil, balıkların ağa babası! (Oltayı atar.) Gel, gel, gel! Bili bili bili gel! (Kir kılıç balığı gelir.) Ulan! Bunun ağzında bıçak var he! Haydi, sen git, senin ağzında kaka mira var, bir yerime batırırsın! Haydi, kışt! (Kalık tutulur, kayığa alır.) Ulan, bıçağını bir tarafıma batırma, tepelerim ha! (Oltayı atar.) Bir tane daha tutayım yeter. Gel gel, gel, bili bili bili! (Bir balık daha tular, kayığa alır.) Hey babam hey. Benim karımın talii yavermiş be! Öyle iri balıklar tutuluyor ki her biri beş oka gelir. Bir de benim taliime gel bakalım! Gel gel! (Ağzını açarak canavar balığı gelir. K. korkarak:) Ben seni istemedim, kış kış kış! (Balık ağzını açarak gelir. Karagöz korkar.) Haydi, kış! Al, sana bir balık vereyim , ye de cehennem ol! (Balığın birini atar, canavar balığı yutar.) Vay köpoğlu vay Çiğnemeden yuttu be! Ulan, boğazında kılçığı kalır be! (Kalık yine ağzını açarak gelir.) Bir balıkla doymadı. Al bir tane daha! Haydi defol, git!( Bir balık daha atar, canavar yutar.) Amma gırtlak var ha! Leblebi yutar gibi yutuyor! Haydi, defol artık! (Balık ağzım açarak gelir.) Haydi, git be! Bana bir şey kalmadı! (Canavar	ağzını açar durur.) Ulan! Ne doymaz şeymişsin be! Bir tane kaldı şuracıkta amma, yutamazsın, ağzında bıçağı var gırtlağına batar. (Balık ağzını açarak gelir, K. korkar.) Ulan gelme, dur! Al al! (Kılıç balığını da atar, canavar onu da yutar.) Ulan amma pisboğaz şeymiş be!  Ne bıçak dinliyor ne kılıç ! (Balık ağzını açarak kayığa dayanır. K. korkarak:) Ulan, dur dur! Bu sefer beni de yutacak! (Canavar kayığı ağzına alır, Karagöz korkarak bağırır.) Ulan, dur dur! (Kayık ve Karagöz canavarla altüst olurlar. Canavar kaçar, K. kayığı çekerek:) Eyvahlar olsun! Zor kurtuldum be! (Evine gelir.) Yahu, aç kapıyı!	\
\
**Karagözün karısı.** (içeriden) Balık getirdin ini?	\
**K.** (içeriden) Sen önce şu poturları bir yıka!	\
**K.k.**Ne oldun böyle?	\
**K.** Ne olacağım? Özünün körü oldum! Denizden koca bir canavar çıktı, az kaldı beni yutacaktı.	\
**K.k.**Vah vah kocacığım! Geçmiş olsun! Nasıl kurtuldun?	\
**K.**Zorla kurtuldum amma, ben de poturlara kaçırdım.	\
( Son.)	\
