


# meyhane
\
**Hacivad.** (semai söyliyerek perdeye gelir).	\
\
Hamd ola, bugün ruh-i revaninıla barıştım,\
Ol lâli şeker tuti-zebanımla barıştım!	\
\
Cevr itmek imiş bendesine gerçi muradı,	\
Ol fitneger-i şuh-i cihanımla barıştım!	\
\
Hay Hak!	\
\
( Perde gazelini okur.)	\
Bezm-i hestide kurulmuş zıll-ı hikmet perdesi,\
Gösterir nakş-i ezelden sun’-i kudret perdesi.	\
\
Kıssadan ârif olanlar hisse almaktır garaz,	\
Karagözdür oynayan amma, bu ibret perdesi.	\
\
Bu hayâl-i enfüs u âfakı seyran ittiren\
Sani'in te'siridir göz göre rüyet perdesi.	\
\
Alem-i eşbaha amed şüd eden her bir nüfus \
Kendi fi’lin zahir eyler mazhariyet perdesi.	\

Yek nazar kıl âlem-i mânada zat u surette, \
Keşf ola ta kim sana bu sırr-ı vahdet perdesi.	\
\
Nur-u Haktir gösteren her zıl vera-yı perdeden,\
Kurmuş üstad-i ezel zahirde suret perdesi.	\
\
Bende ol âl-i abaya sıdk ile, HîLMÎ, müdam \
Açılır bab-i Ali'den Hakka vuslat perdesi.	\

(Kavgadan sora.)	\
\
**Karagöz.**Seni gidi utanıp arlanmaz sivri sakallı herif seni! Ulan, ne aldın ne veremiyorsun? Gelirsin kapının önüne, bir değil, iki değil, üç değil, her akşam! Bu nedir senin elinden çektiğim? Dad bir, feryad iki! Yarın akşam da gelecek olursan, Hacivad, elini ayağını bağlıyacağım, götürüp seni bir battal kuyuya atacağım. O vakit elinden tahlis-i geriban olurum: başka çarem kalmadı!	\
**Hacivad (gelir).**Vay efendim, uğurunuz küşad olsun !	\
**K.**İçtiğin tömbeki Keşan olsun!	\
**H.**Ah Karagöz, seni bîr gün görmesem divane olurum!	\
**K.**Ben de seni görmesem çingâne olurum!	\
**H.**Ah benim nur-u aynım!(Vurur.)	\
**K.**Eksik olma, osurukta kaynım!(Vurur.)	\
**H.**Benim bîr tanecik civanım !(Vurur.)	\
**K.**Ah benim mor patlıcanım! (Vurur.)	\
**H.**Benim işvebazım! (Vurur.)	\
**K.**Benim hilebazım.( Vurur.)	\
**H.**Benim küçücük püserim!( Vurur.)	\
**K.**Yanıma gelme, yakana kusarım !(Vurur.)	\
**H.**ömrümün sermayesi. Karagöz! (Vurur.)	\
**K.**Çocuk hayesi, Hacivad!( Vurur.)	\
**H.**Benim mini mini beyim !( Vurur.)	\
**K.**Koca şebeğim!(Vurur.)	\
**H.**Benim servi boylu Karagözüm! (Vurur.)	\
**K.**Benim kötü huylu Hacivadım!( Vurur.)	\
**H.**Canım, Karagöz, bana merak oldu. Çoktan beri soracağım, şimdi hatırıma geldi: Bundan bir hafta evvel size rasgeldim, acele gidiyordunuz.	\
**K.**Nerede rasgeldin?	\
**H.**Çakmakçılar yokuşunda: günlerden perşembe günü idi.	\
**K.** O günü işim vardı.	\
**H.**Elinizde kazan yağlısı.	\
**K.**Kazan yağlı değil amma, tencere yağlı.	\
**H.**Nasıl tencere?	\
**K.**Bizim karı geçen gün evde yemek pişirdi, nasılsa tencere yıkamamış; sabaha kadar kediler tencereyi yalıya yalıya kalayını gidermişler.	\
**H.** Hiç tencerenin kalayı kedi yalamasiyle gider mi?	\
**K.** Gitmiş. Bir kaç. gün sora o tencerede yemek pişirdik, bakır çalmaz mı?	\
**H.** Sora ne yaptınız ?	\
**K.** Nasılsa kurtulduk; az kaldı ölüyorduk.	\
**H.**Geçmiş olsun, Karagöz!	\
**K.**Eksik olma, Hacivat!’	\
**H.**Kazan yağlısına bayılırım.	\
**K.**Ben de tencerenin ballısına bayılırım.	\
**H.**Tencerenin ballısı olur mu?	\
**K.**Kazan yağlısı olur da tencerenin ballısı olmaz mı?	\
**H.**Benim söylediğim bir nevi simit.	\
**K.**Nasıl simit?	\
**H.**Nasıl simit olacak? Adeta simit, adına kazan yağlısı derler, Çakmakçılarınki meşhurdur.	\
**K.**Benim size söylediğim helva tenceresi: Helvayı pişirirler, sora da tabaklara korlar, tencere boş kalır, dibi ballı olmaz mı? Onun adına tencerenin ballısı derler.	\
**H.**Senin söylediğin kirli bulaşık tencere.	\
**K.**Yıkılmış kırık tencere değil.	\
**H.**Bendeniz de külbastıya bayılırım; sen de sever misin. Karagöz ? Ekseri evde bizimkine pişirtirim.	\
**K.**Biz de evde geçende yaptık.	\
**H.**Afiyetle yedin mi?	\
**K.**Biz evde afiyetsiz birbirimizi yedik.	\
**H.**Nasıl birbirinizi yediniz?	\
**K.**Malûm ya! Fıkaralık maskaralık ! Evde bizim bir toprak tencereden başka bir şeyimiz yoktur: tatlısı da tuzlusu da onun içinde pişer. Meşhur meseldir: "Tencerede pişir, kapağında ye!" derler. Biz de tencerede pişiririz kapağında yeriz.	\
**H.**Aman efendim - Müteaddit tencereniz yok mudur?	\
**K.** Kırık tenceremiz çok, hepsi yapılacak. Tencerenin içine bir az su koyduk, çorba pişireceğiz; mangalın üstüne sacayağını koyduk, tencereyi de üstüne koyduk, mangalın başında oturuyoruz. Bizim oğlan geldi, kapıdan içeri girer girmez başladı sıçramaya.  "Ulan, otur!" derim, oturmaz  „Dur!" derim, durmaz.	\
**K.**Senin oğlan zaten veledizinanın biri!	\
**K.**Ağzını topla! Minderin üstüne çıkar, aşağıya iner, nasılsa bir aralık oturdu. Ben de mangalın başında otııra otura uyudum: bu aralıkta bir gürültü koptu.	\
**H.**Karagöz, o gürültü ne imiş?	\
**K.**Meğerse bizim oğlan bent uyudu diye minder üstüne çıkmış, ayağı kayar kaymaz haydi mangalın üstüne düşer düşmez mangal bir tarafa, tencere bir tarafa, tencerenin içindeki su dökülür dökülmez tekmil odayı kül bastı hattâ kirpiklerime kadar çıktı.	\
**H.**Hay afacan! Hep kabahat sende. Niçin terbiye etmiyorsun oğlunu?	\
**K.**Terbiye  ediyorum amma, faydası yok; ne bakkalda yumurta kaldı ne de Limon iskelesinde limon kaldı.	\
**H.**Hiç insan yumurta ile terbiye olur mu?	\
**K.**Ya ne ile olur ?	\
**H.**İnsan insan terbiye eder. Senin terbiyen yak ki çocuğunu terbiye edeceksin!	\
**K.**Senin terbiyen var mı bakalım?	\
**H.**Var zahir! Oldukça dirayetim nezaketim vardır.	\
**K.**Yüzüne karşı söylemek olmasın, adeta eşeğin büyüğüsün. Bir adam kendi kendini metheder mi?	\
**H.**Senin gibi adama dersem, sen lâkırdı anlamazsın ki!	\
**K.**Sen benim kim olduğumu biliyor musun ? Adam terbiye etmekten yana birinciyim, tokadı atar atmaz gözünü patlatırım! (Vurur, H. gider.) Kerata kendini dehri zannediyor!	\
Sen gidersin de ben durur mıyım? Ben de gideyim karımla görüşeyim!(Gider.)	\
\
(Şarkı ile Laz gelir)
\
Pür ateşem, açtırma, sakın, ağzımı, zinhar!	\
Zalim, beni söyletme derunumda neler var!	\
Bilmez miyim ittiklerini? Eyleme inkâr!	\
Nakarat: Zâlim, beni söyletme derunumda neler var!	\
\
Derdinle yürek yareleri işler, onulmaz,\
Meydan-i muhabbette bu hicran unudulmaz, \
Aşık sana çoksa, bana dilber mi bulunmaz?	\
Eyzan.	\
\
**H.**Vay efendim, sefa geldin, hoş geldin. Trabzon gülü!\
**Lâz.** Hoş pulduk, sefa pulduk, meydan pülpülü içi cüzüm I\
**H.**Nasılsın, eyi misin, Hayreddinim?	\
**L.**Eyiyum, Hacivat! Çelebi, sen de eyi musun?	\
**H.**Çok şükür!	\
**L.**Hiç paşuma çelenleri sormayın!	\
**H.**Ne gibi, hayrola?	\
**L.**Ne cibi olacak? Puradan kakhtum Tarabuzana citmeye.	\
**H.**Evet efendim.	\
**L.**Pir cemi pakhur aldum, pir cemi fundukh aldum. Tarabuzandân açuldukh, aldu pizi pir furtana, aldu pizi pir furtuna!	\
**K.**(pencereden).Al kerata, pırtıyı sırtına!	\
**H.**Demek ki. efendim, deniz coştu?	\
**L.**Ne teorsun. Hacivad Çelebi? Teniz kabardukça kabardu, kabardukça kabardu, paşladı midem karışmağa.	\
**K.**(pencereden).Ne hakkı var karışmağa?	\
**L.**Paşladum isyan etmeğe.	\
**k.**(pencereden).Vay kerata, gaseyan diyeceğine isyan diyor!	\
**H.**Demek ki sizleri deniz tutuyor.	\
**K.**Al budalanın birisi daha! İnsanı deniz nasıl tutar? Eli ayağı var mı?	\
**H.**öyle değil, Karagöz. Bazı adamı deniz tutmaz, bazı adamı tutar: yani safrası kabarır bulantı gelir, bazı adam da bir şey olmaz.	\
**L.**Çimisü ağlar, çimisü pağırur, çimisünün sesi çıkhmaz, öyle oturur şaşurdum kaldum. Kapudan haber cöndermiş pazu eşyaları  denize atacağım tiye pizüm pakhurları tinize attular, fundukhları da attular. Pakhurlar cilttü tenizün tibüne, fındukhlar çıkhdu tenizün yüzüne. Pana pir aksakallu fundukh tilünu çıkharmuş cüler, tilünu çıkharmuş cüler.	\
**K.**(pencereden).Budala bu herif! Fındık insana dilini çıkarır mı?	\
**L.**Nasulsa, Hacivad Çelebi, Istanbula celdukh.	\
**H.**Geçmiş olsun efendim !	\
**L.**Cecürdük amma, mallarum da cittü!	\
**H.**Canin sağolsun efendim’	\
**L.**Purada pazu yerlerde alacağım vardu, onları da alamadum.	\
**H.**Baksan a. ciğerparem, sizden bir küle aldımdı, hatırınıza gelmiyor mu?	\
**L.**Hatırıma çelmiyor. Nasul? Cenç miydi, yoksa kart mu ?	\
**H.**Kartça, bendenize itaat etmiyor; su istesem ateş verir, ateş istesem su verir; aksi aksi işler yapar, hiç tahammülüm kalmadı; bana karşı gelir.	\
**L.**Pana cönderun de onun terbiyesunu vireyum.	\
**H.**Bizim fakirhaneye buyurun da bir kahve içersiniz, ben onu bulur size gönderirim. Hiç evde oturmaz her gün kahvehanelerde vakit geçiriyor.	\
**L.**Puyurun cidelüm! (Giderler.)	\
**H.** (içeriden).Bana baksan a, hanım kızım! Misafire bir şekerli kahve pişir, bendeniz şimdi gelirim.	\
**L.**Hacivad Çelebi, ceç kalma!	\
\
**H.** (Karagözün kapısını çalar).Bana baksan a. Karagöz!	\
**K.** (tavan arasından seslenir).Ne var, Hacivad, ne istiyorsun?	\
**H.**Neredesin. Karagöz? Sesin derinden geliyor.	\
**K.**Tavan arasındayım.	\
**H.**Tavan arasında ne yapıyorsun?	\
**K.**Farelerle değişik oynıyorum.’	\
**H.**Aşağı gel!	\
**K.**(pencereden).Öte tarafa çekil, atlıyacağını!	\
**H.**Patlıyacak mısın?	\
**K.**Sen patla, köpoğlu! ( Perdeye gelir.) Ne var?	\
**H.**Aman, Karagöz, müjde!	\
**K.** Hayrola. Hacivad?	\
**H.**Yine eyiliğimi bilmezsin! Ben seni bu akşam yağa bala batıracağım.	\
**K.**Ulan, hamamlar da pahalı; sora nasıl temizlenmeli?	\
**H.**Öyle değil, köftehor!	\
**K.**Söyle bakalım, çorbahor!	\
**H.**Tüccarın birisi fırtınaya tutulmuş.	\
**K.**Evet.	\
**H.**Eğer sahil-i selâmete çıkarsam fıkaraya tasadduk edeyim diye niyet etmiş.	\
**K.**Taktuka ile süprüntü mü dökmüş?	\
**H.**Türkçesi: Sağ sâlim karaya ayak basarsam fıkaraya para vereyim, yağ, pirinç, bulgur, fasulya, bu gibi şeyler dağıtayım diye şimdi bana geldi, bildiğin yerde fıkara var mı diye. Benim de sen hatırıma geldin; ben şimdi onu sana gönderirim.(Gider.)	\
**K.**Eksik olma. Hacivad. ne kadar olsa baba dostu!	\
\
(Eve gelir.) Abla!	\
**Karısı (içeriden).**Ne var herif?	\
**K.** Kilerde ne varsa komşuya ver!	\
**K.k.**Kiler nerede, mutfak nerede? Bizim kilere fare düşse başı yarılır. Bir şeyler yok.	\
**K.** A karı, insanı böyle mahcup etmezler. 'Var'de bari!	\
**K.k.**Bir ufak kavanoz var. onun içinde bir parça yağ var.	\
**K.**Sen onu komşuya ver! Şimdi kazevi ile pirinç, fıçı ile şeker, çuvalla fasulya, bulgur, hepsi gelecek.	\
**K.k.**Davetliler mi var?	\
**K.**Eğleniyor musun?	\
**K.k.**Ne bileyim, ayakta rüya mı görüyorsun?	\
**K.**Sen de dediklerimi yap, ben şimdi gelirim.(Perdeye gelir.) Nerede kaldı tüccar?	\
**H.** (içeriden)Efendim. Şeyh Küşteri meydanında teşrifinize muntazır.\
**Lâz.**Pen şimdi cidenım, Hacivad Çelebi!(Perdeye gelir.)	\
\
**Karagöz.**Vay efendim, sefa geldiniz! Evde ne kadar kavanoz varsa hepsi boş; akşamdan sabaha yiyeceğimiz yok efendim.	\
**L.**Seni çopek seni! Sen ağana niçun itaat etmaisün ?( Tokat atar.)	\
**K.**Ulan, bu lâhana turşusu ne? Bu pehriz ne?	\
**L.**(vurur). Seni terbiyesuzseni! Sen ağanım sozunu tinlemaysün!	\
**K.**Tokat iki oldu.	\
**L.**Seni pen poyle mi terbiye ittum?(Vurur.)	\
**K.**Rüya mı görüyoruz?	\
**L.**Cözünü patlaturum! Adam ol, çöpek!(Vurur.)	\
**K.**Hacivad, kulağın çınlasın!	\
**L.**Seni mum iderum! (Vurur.)	\
**K.**Hacivad, geçme nasibinden! Kuzum efendim! Benim ağam kim?	\
**L.**Sen Hacivadın çölesi teğül müsün?(Vurur).	\
**K.**Anlaşıldı, fitne kerata!	\
**L.**(vurur).Puni çami?	\
**K.**Burnum çamur, efendim.	\
**L.**(vurur).Şedevraha?	\
**K.**Satar patar, efendim.	\
**L.**(vurur).iskele mutani?	\
**K.**İskelede boğday taşırım, efendim.	\
**L.**İmereli. (Vurur.)	\
**K.**İmrenmeli efendim, dayağa.	\
**L.**(vurur).Punt çami?	\
**K.**Burnum çamur efendim.	\
**L.**(vurur).Şedevraha!	\
**K.**Satar patar, efendim.	\
**L.**(vurur),iskele mutanı.	\
**K.**İskeleden boğday taşırım, efendim.	\
**L.**(vurur) İmereli.!	\
**K.** İmrenmeli efendim!(Laz gider.)	\
**Hacivad.** (gelir) Karagöz, nasıl ettin?	\
**K.** (Hacivada vurur).Burnum çamur, efendim	\
**H.**Nasıl burnun çamur?	\
**K.** Satar patar! (Vurur)	\
**H.**Canım, nasıl satar patar?	\
**K.**İskelede boğday taşır!	\
**H.**Nasıl iskelede buğday taşır?	\
**K.**İmrenmeli!(Vurur.)	\
**H.**Neye imrenmeli?	\
**K.**(vurur).Dayağa imrenmeli.	\
**H.**Ben bundan bir şey anlamadım.	\
**K.**Şimdi anlarsın, kerata! (Vurur.H gider). Bahane ile bana bir temiz dayak attırdı, ona yanmıyorum; evde bir parça yağ vardı, karı benim sözümü dinleyip te komşuya verdi ise o zaman işim fena. Ben de gideyim evime! (Gider.)	\
\
(Şarkı ile Çelebi gelir: Hacivad tarafına meyhane konur.)	\
\
Şarkı Mahur	\
Ey şah-i melik sen gibi devlet bulunur mu?	\
Mislinde senin şah-i adalet bulunur mu?	\
Kullarına adlin gibi nimet bulunur mu?	\
Nakarat:  Mislinde senin şah-i adalet bulunur mu?	\
Rahında senin itse cihan canını kurban,\
Billâhi bulunmaz senin ihsanına payan, \
Veçhinde keramet meh-i taban gibi rahşan.	\
Ey zan.	\
\
**Hacivad.** (gelir) Vay efendim, uğurlar olsun!\
**Çelebi.**Allaha emanet olun, Hacivad Çelebi!	\
**H.**Efendim, böyle ne tarafa teşrif?	\
**Ç.** Zatı âlinizle görüşmeye geldim.	\
**H.**Teşekkür ederim efendim, bendenizi arzulayıp geldiğinize!	\
**Ç.**Sizleri de kaybettik!	\
**H.**Bizimkisi ihtiyarlık, bir yere gidemem. Akşamdan afyonu yutar, kış ise mangal başında, yaz ise pencere önünde uyuklar dururum.	\
**Ç.** Yine, Hacivad Çelebi, bu mahallede mi oturuyorsunuz?	\
**H.**Evet efendim. Karagöz mahallesinde.	\
**K.**(içeriden).Yine zikr-i menhusum sirkat olunuyor!	\
**Ç.** Benim bir çok işlerim var, Hacivad Çelebi.	\
**H.**Evet efendim.	\
**Ç.**Buraya gelmemin veçhi: Bizim şu meyhane var. onu sizi teslim edeyim. talibi çıkarsa kiraya verirsiniz.	\
**H.**Olur efendim.	\
**Ç.**Buyurun, gidelim de size teslim edeyim!(Giderler, içeriden:)İçinde hiç bir eksiği yok, Hacivad Çelebi; kim tutacak olursa kuntratsız verme!	\
**H.**Başüştüne efendimi	\
**Ç.**Bendeniz müsaadenizde gidiyorum.	\
**H.**Müsaade sizin!	\
**Ç.**Allaha 'smarladık!(Gider.)	\
**H.**Sefa geldiniz efendim!	\
(Şarkı ile Frenk gelir, meyhaneci.)	\
\
Geçme kapım önünden ...	\
\
**Hacivad.** Vay, musyö Oturaki, sefa geldin!	\
**Frenk.**Hoşaf bulduk, hoşaf bulduk!	\
**K.** (içeriden). Hoşaf bulsam ben de içerim ama yok.	\
**H.**Nereye gidiyorsunuz böyle?	\
**Fr.**Dzanim Hadzivad Tselebi. tsokdan beri gozikdiğiniz yok.	\
**H.**Ben bir yere gitmem, mahalle kahvesinde, evde vakit geçiririm.	\
**Fr.**sok eyi, tsok eyi!	\
**H.**Buraya gelmenizin elbet bir sebebi var,	\
**Fr.**Tsokdan beri bir is yapdiyim yok; simdi isterim bir dükkân tutayım isleteyim.	\
**H.**Efendim, burada size göre bir dükkân var; isterseniz bir kere bakın!	\
**Fr.**Olur, Hadzivad Tselebi.	\
**H.**Buyurun, sizi gezdireyim!	\
**K.**(pencereden). Terli ise, gezdir, Hacivad!	\
**Fr.**Haydi gidelim!(Giderler.)	\
**H.** (içeriden).İçinin mobilyası takımı hepsi tamam, hiç eksiği yoktur.	\
**Fr.** (içeriden).Tsok eyi, tsok eyi! Simdi aydan aya ne veredzeyiz?	\
**H.**Ben sizden çok istemem, beşyüz kuruş.	\
**Fr.**Pahalı, bizi yabandzi gibi tutma!	\
**H.**Siz de verin bakalım!	\
**Fr.**Dortyuz kuruş verelim!	\
**H.**Haydi, sefayı hatırla oturun!	\
**Fr.**Simdi isterseniz, size bir aylik vereyim peşin!	\
**H.**Olur efendim.	\
**Fr.**Aliniz size dortyuz kuruş!	\
**H.**Eksik olmayın!	\
**Fr.**Ben bu dükkânda eskiden oturdum, tsok müşterim vardi.	\
**H.**Yine eskisi gibi müşteri toplarsınız.	\
**Fr.**Müşteri hos tutarsan gelir.	\
**H.**Allaha ’smarladık!	\
**Fr.**Sefa geldin!	\
\
( Şarkı ile meyhaneci çırağı gelir.)	\
**Çırak.** Beni tsagirmis usta, burada dukkân tutmuş, su karsuki dükkân olmali!	\
**Fr.**O, sefa geldin!	\
**Ç.** Sefa bulduk!	\
**Fr.**Simdi bu dükkânda tsalisatsayiz, göreyim seni! Müşterilere riayette kusur etme!	\
**Çı.** Usta, ben elimden geldiyi kadar tsalisirim, sen kasavet tsekme!	\
**Fr.**Göreyim seni; kim olursa olsun hepsini müşterilerin bir tutmalı!	\
**Çı.**Elbette, usta, hepsini bir tutmalı.	\
**Fr.**Sana aydan aya utsyuz kuruş, gelenlerden bahşiş alirsin.	\
**Çı.**Pek âlâ, ben raziyim. (İçeri girerler.)	\
\
(Şarkı ile Bekri Mustafa gelir.)	\
Nice sevmeyeyim dostlar ...	\
\
**Bekri Mustafa.** "içtim aşkın dolusunu yar bugün mecliste dir." işittim, bizim eski meyhaneci burada dükkân tutmuş. Çok eyi heriftir, müşterilerine eyi bakar, güzel ikram eder. — Bana baksan a, Apistol!	\
**Çırak (içeriden).**Oriste!	\
**M.** Buraya gel!\
**Çı.**Geliyor, gozum! (Gelir.) Vay, Mustafa Aga, sefa geldin!	\
**M.** Sefa bulduk, oğlum. Şuraya bana bir sandalye getir bir masa getir!	\
**Çı.** Basustune, Mustafa Aga! (Gider bir sandalye getirir. Bekri Mustafa oturur.)	\
**M.**Haydi oğlum, bir masa da getir!	\
**Çı.**(getirir).Simdi başka ne istersin?	\
**M.**Ne istiyeceğim? Benim İstediğim belli: bir oka rakı getir!	\
**Çı.**Basustune, Mustafa Aga, simdi getiririm. (Gider, bir şişe rakı getirir.) Daha başka bir emriniz var mi?	\
**M.**Şimdiki halde bir şey istemem.	\
**Çı.** Nezeman bir sey isterseniz beni tsagirin.(Gider.)	\
**M.**Bir tek atalım! (İçer.) Bir tek daha atayım! (İçer.)	\
**K.** (pencereden).Herif kofti mi atıyor, yoksa başka bir şey mi? Ha anladım: rakı atıyor. \
**M.**Gel keyfim gel! Bir tek daha atayım!	\
**K.**(pencereden).Yut, baban görmesin! Herif rakı fabrikası!	\
**M.**Apistol!	\
**Çı.**Geliyor, gozum! Ne istersin. Mustafa Aga?	\
**M.**Meze getir!	\
**Çı.** Basustune! (Gider getirir.) Daha başka bir sey ister misiniz?	\
**M.**İstemem.	\
**Çı.** Peki!(Gider.)	\
\
(Şarkı ile Çelebi gelir, Karagöz tarafından.)	\
\
Şarkı Hüseyni Aşiran	\
\
Serv-i sehi bimenendim: Gel, gülüm!	\
Çeşmim nurusun, efendim: Gel gülüm!	\
Kesb ittim aşkını kendim: Gel gülüm!	\
Nakarat: Çeşmim nurusun, efendim! — Gel gülüm!	\
\
Canım mevcud iken tende.	\
Karar itti bu aşk bende,	\
Bakmam gayre, gözüm sende.	\
Eyzan.	\
\
Didim sana, candan yârim,	\
Ne dirsen emrine ramım,	\
Budur ancak benim kârim.	\
Eyzan.	\
\
**Çelebi.** Vay, efendim, Mustafa efendi, iki gözüm!	\
**Mustafa.**Vay. benim nuru aynım, böyle ne tarafa teşrif?	\
**Ç.**Efendim, bendenizin evde otururken canım sıkıldı. Varayım şöyle bir parça gezeyim dedim.	\
**M.**Eyi tesadüf oldu! Oturun bakalım! Gel, Apistol!	\
**Çı.**(içeriden). Oriste! (Gelir.) Ne ister efendim?	\
**M.**Şuraya bir sandalye getir!	\
**Çı.** (getirir).Buyurun, oturun! (Çelebi oturur.)Ne emrededseksiniz?	\
**Ç.** Bir az oturayım da sora!	\
**Çı.**Peki efendim.	\
**M.** Yo, olmaz ama.	\
**Ç.**Bir az dinleneyim, sora içerim.	\
**M.**Apistol!	\
**Çı.**(içeriden).Oristel(Gelir.)	\
**M.**Doldur bakalım, evvelâ beye ver, sora bana!	\
**K.**(pencereden).Sora da bana versin üçüncü olarak!	\
**Çı.**(doldurur).Buyurun efendim!(Çelebiye verir.)	\
**Ç.**(içer).Muhabbete!	\
**M.** Şifa olsun!	\
**K.**(pencereden) Ölmüş kargalar gözünü oysun!	\
**Ç.**(doldurur, Mustafaya verir).Buyurun efendim!	\
**M.** Muhabbete! (İçer.)	\
**Ç.**Şifa olsun!	\
**K.**(pencereden). Ne kadar kulampara varsa meftun olsun!	\
**M.** (şarkı söyler).	\
\
Şarkı Karcığar	\
\
İki de turnam gelir, allı karalı,	\
Birisini şahin vurmuş, biri de yaralı.	\
O yavruya sorun: aslı nereli?	\
Nakarat: Eğrim eğrim olmuş olmuş gelir de turnalar,\
Katar katar olmuş olmuş gelir de turnalar.	\
\
İnme, turnam, inme  sen bu pınara!	\
Avcu tuzak kurmuş; var, yolun ara!	\
Cümlemizin işin Mevlâm onara!	\
Eyzan.	\
\
**Ç,**Teşekkür ederiz efendim!	\
**M.** Kuzum, oğlum, sen de bir mani söyle!	\
**Ç.**Başüstiine efendim!	\
**M.** Apistol!	\
**Çı,**(içeriden). Oriste! (Gelir.) Ne istersin, Mustafa Aga?	\
**M.**Oğlum, bize bir tek ver bakalım!	\
**Çı.** (doldurur).Buyurun, beyefendi!	\
**Ç.** Efendiye ver!	\
**M.**Yok oğlum! Sen iç de ben sora,	\
**Çı**(Çelebiye verir).Buyurun!	\
**Ç.**(içer) Muhabbete!	\
**M.**Şifa olsun!	\
**Çı.** (doldurur).Buyurun, Mustafa Aga!	\
**M.**(içer). Muhabbete!	\
**Ç.**Adam aman! Dile, yâr, dile, yâr!	\
Bugün eşref saattir. Ne dilersen, dile, yâr!	\
Çünki beni sevmezsin, ne düşürdün dile, yâr?	\
\
**M.** Yaşa, evlâdım, yaşa! Apistol!	\
**Çı.** Oriste!	\
**M.**Birer tek daha ver, oğlum!	\
**K.** (pencereden).Herif rakı küpü!	\
**Çı.** (doldurur).Buyurun!(Çelebiye verir.)	\
**Ç.** (içer).Muhabbete!	\
**M.**Şifa olsun!	\
**Çı.**(doldurur).Buyurun, Mustafa Aga!	\
**M.** (içer).Muhabbete!	\
**Çı.** Şifa olsun!	\
**M.**Oğlum, haydi, köçeklere haber ver, gelsinler!	\
**Çı.** Basustune! (Gider.)	\
(Köçekler gelirler, köçek havası çalınır ; aynarlarken kol geçer.)	\
**Çı.**Aman, Mustafa Aga, kol geçiyor!(Köçekler durur.)	\
**M.**Kol geçiyorsa bize ne?	\
**Çı.** Vakit geç, sora biz ceza yeriz.	\
**Ç.** Kol geçti!	\
**Çı.**Oynasınlar!(Köçekler oynar.)	\
**M.**Yaşa, yosma civan!	\
**K.**(pencereden).Meyhane aklı yürüdü!	\
(içeriden çıngırak çalınır, köçekler durur.)	\
**Çı.**Aman, Mustafa Aga, kol geçiyor!	\
**Af.** Artık gitsinler! (Köçekler giderler.)	\
**Çı.** Müsaadenizle bendeniz gideyim! (Gider.)	\
**M.**Sefa geldin! Hoş geldin, oğlum!	\
\
**Karagöz.** (içeriden) Abla!\
**Karısı.**Ne var, herif?	\
**K.** Şu benim zurna nerede?	\
**K.k.**Ben onu çocuğa sübek yaptım.	\
**K.** Karı, ne bulursan çocuğun götüne mi sokarsın?	\
**K.k.**Al bakalım!	\
**K.** Ulan, bu tuzlu be!	\
**K.k.**Sabunla yıka!	\
**K.** Sıçmış da bana akıl öğretiyor!	\
**K.k.**Bir kere üfle!	\
**K.** (üfler).Ulan, sesi çıkıyor! (Perdeye gelir.) Akşam-i şerifler hayır olsun!	\
**M.**  Senin tavuklarını sansar boğsun! Elindeki nedir?	\
**K.**Zuma efendim.	\
**M.**  Efendin zurna mı?	\
**K.**Evet, bendeniz çifte nara.	\
**M.** At bakalım!	\
**K.**Ne atacağız? Nara mı atacağız, rakı mı?	\
**M.**Nara atarsan, dayak; rakı atarsan, halin harap.	\
**K.**Bendeniz de gece gündüz içerim şarap.	\
**M.**Vay, senin şairliğin de var!	\
**K.**Min gayri haddin . . .	\
**M.**At bakalım!	\
**K.** (doldurur içer). Muhabbete!	\
**M.**Şifa olsun!	\
**K.**Şifa hamamını kim bulsun?	\
**M.**Bir tek daha at!	\
**K.**(bir daha içer).Muhabbete!	\
**M.**Aşk olsun!	\
**K.**Burnuna koskocaman leş konsun!	\
**M.**Zurna çal!	\
**K.**Başüstine !(Evvelâ taksim eder.)	\
**M.**  Aferin, Karagöz! Başka havadan çal!	\
**K.** Kulunuz her havadan çalarını.( "Çiğerde nar-ı hasret" şarkısını çalar.)	\
Şarkı Hicaz	\
\
Ciğerde nar-ı hasret ...\
\
**M.** Çal!	\
**K.** Çalayım! (Diğer bir şarkı çalar )	\
\
Şarkı Rast	\
\
Yine bir gülnihal ...	\
\
**M.** Çal, arnavutça çal!	\
**K.** Çalayım!(Çalar.)	\
Tunada çırpar bezini ...	\
**M.** Çal, Vanlıca çal!	\
**K.** Çalayım!(Çalar.)	\
Aya bakh, yıldıza baklı...	\
**M.** Çal, çingenece çal!	\
**K.** Çalayım! (Çalar.)	\
Çeri başının gelini.	\
**M.** Çal, rumca çal!	\
**K.** Çalayım!(Bir sirto çalar.)	\
**M.**Yahudice çal!	\
**K.** Çalayım! (Çalar.)	\
Ande vamoz el de aki.	\
**M.**Köçekçe çal! (Uyur,)	\
**K.**Çalayım!(Çalarken kaçar.)	\
\
(Şarkı ile iki çocuklu Zenne gelir, biri kucağında, birisinin elinden tutmuş.)	\
Şarkı Uşşak	\
Ateş-i suzan’ı fırkat yaktı cism u canımı,\
Bir harababade döndürdü dil-i viranımı.	\
Neyle teskin eyleyem bu dide-i giryanimı?	\
Çünki aldırdım elimden sevgili cananımı.	\
Nakarat:Ağla, çeşmim, ağla durma, gitti elden nazlı yar!	\
Çağla, ey eşk-i terim çağla misal-i cuyibar !	\
\
Bağrımı deldi seraser tir-i hasret ez kaza,	\
Neşter-i gam işledi itti ciğergâhım dü ta.	\
Perde çekti subh-i kâm-i vuslata şam-i belâ.	\
Yâr u yaversiz haram olsun cihan artık bana!
\
Eyzan.	\
\
**Zenne.** Seni Tanrının zalimi herif seni! Nedir senin bu halin? Her akşam evde bekleriz; çoluk çocuk aç biilâç sen meyhane köşelerinde sabahlara kadar oturursun; Allahtan korkmaz, hiç kimseden utanmaz!	\
**M.** Ne var, ne olmuş? Gel, sen de otur, çocuklarda otursun!	\
**Z.** Seni utanıp arlanmaz seni!	\
**M.** Gel, Apistol! Şunlara birer tek ver!	\
**Z.** Herif, senin Allahtan korkun yok mu? Nedir bu hal? Haydi kalk, eve gidelim!	\
**M.** Ha ev, ha burası. Buranın evden ne farkı var?	\
**K.** (pencereden).Orası doğru! Buna han da bir külhan da!	\
**Z.** Budalâ, budala! Söylenme, herif! Haydi kalk gidelim!	\
**M.**Canım, otursan a! Günahı boynuma, ne içersen iç!	\
**K.** (pencereden).Eksik olma, kâfir piç!	\
**Z.** Anlaşıldı, senin kulağına lâkırdı girmiyor. Ben de gideyim kardeşini yollayım!(Gider.)	\
**Karagöz.** (perdeye gelir. Bekri uyur).Nasıl gelirse gelsin, şunun rakı kadehine işerim! (İşer.)	\
**M.** (uyanır).Vay, sen burada mısın?	\
**K.** Evet, buradayım.	\
**M.**Ben sana ikram etmek isterim, ne emredersen emret!	\
**K.** Benim haddim mi emretmek?	\
**M.** Ben sana emrediyorum öyle ise, bir kadeh rakı iç!	\
**K.**Kulunuz tövbeliyim.	\
**M.**Ulan, deminden eşekler gibi içiyordun!	\
**K.**Eşeklerden sora töybe ettim.	\
**M.**İç! diyorum sana!	\
**K.** Boku yedik! Kendi siydiğimizi nasıl içmeli!	\
**M.**Ulan, ne içmiyorsun?	\
**K.**İçemiyeceğim.	\
**M.** Ben sana zorla içireceğim. İç! diyorum sana!	\
**K.**(içer). Vay ağzına kesdiğimin! Kendi siydiğimizi içtik! (Gider.)	\
(Şarkı ile Matiz gelir.)	\
\
Bir gemim var ...	\
\
**Tuzsuz.**Vay bilâder. sen burada mısın?	\
**M.**Gel bakalım, otur, muhabbet edelim!	\
**T.** Muhabbetin sırası değil. Evde çoluk çocuk seni bekliyor. Haydi gidelim! (Gelir Bekri Mûstafayı kucaklar.) Haydi gidelim!	\
\
(Bekri Mustafa ayağa kalkar. Tuzsuzun üstüne düşer. Karagöz ile Hacivad gelir. Karagöz Tuzsuzu kaldırır, Bekri Musta fanın üstüne düşer. Hacivad Bekri Mustafayı kaldırır yıkıla yıkıla giderler. Hacivad ile Karagöz gelirler. Mabadı malûm.)	\
