


# salincak

**Hacivad.** (semai söyleyerek perdeye gelir).	\

Semai Müstear	\
O nevreside nihalim ne serv-kamet olur!	\
Benim hayal-i dilim meşrebimce afet olur.	\
Rüsum-u nazı temam ezber eylemiş ARİF\
O fitnecuyu görürsen katı kıyamet olur.	\
\
Beli beli yele lel le lel le lel lel li aman \
Ne serv-kamet olur!	\
\
Hay Hak	\
\
(Perde gazelini okur.)	\

Bak, ne suret görünür hüsn-ü eda-yı perdede\
Buldular üftadeler derde devayı perdede.	\
Kande kurulsa bütün ahbabı eyler şadkâm.	\
Aşinalar kesb ider zevk u safayı perdede.	\
Ser te ser erbab-ı bezmin hatırın tenvir ider.	\
Meşale olsa firuzan mavera-yı perdede.	\
Beste-hanlıkla Hacı Evhad gelince ortaya.	\
Gam bırakmaz Karagöz hiç mübtelâya perdede.	\
Nağmesaz oldukça yardaklar dahi bülbül gibi.	\
Guş iden dembestedir nüzhetfeza-yı perdede.	\

Huzur-u erbab-ı salada ...	\
\
Yâr. bana bir eğlence! Yâr, bana bir eğlence!	\
Dide en sevdafeza bir suretin hayranıdır.	\
Şişe en şiddetli bir sevdanın ateşdanıdır.	\
\
(Karagöz aşağıya gelir. Harİvadla kavga ederler. H. gider. Karagöz yalnız kalır, arka üstü yatar.)	\
\
**Karagöz.**Aman aman, enf-i sagirim! Esna-yi mudarebede yam yassı oldu batn-ı kebirim! Bana yarım okka ekmek verin, pek fakirim !(Kalkar.)Kulunuz bu gibi şeyleri afak buyurduğum ecilden müncemiden ictima etmekliğiniz icab eder. Mademki redd-i batıldan tagayyur buyuruyorsunuz bendeniz de hiç bir vakitte tekâsülden ictinab etmem; bilâ te’hir tecdid-i temayül olmanızı iltimas ederim. Maama-fih, binaenaleyh, bu abd-i âcizi ve zat-i âlikadrim daimul-evkat sizi darbettigimden dolayı mahcup oluyorum. Sizler de bilâ fasila madrubü aleyh olduğunuz için sârikul-etfâl ve kesirül-emsal olmaklığım icabeder.	\
**Hacivat.** (gelir). Vay efendim! Akşamı şerifler hayırlar olsun!	\
**K.**Rayiha-i kerihe burnuna dolsun! (Vurur.)	\
**H.**Bendenize vurmanın veçhi?	\
**K.**Pek büyüktür Eleni hanınım ferci! (Vurur)	\
**H.**Bana vurmanızın sebebi?	\
**K.**Manavındır, bırak yerine sepeti! (Vurur.)	\
**K.**Bendenize vurmanızdan bâis?	\
**K.**Bıyığına osursun ahırdaki kör seyis!(Vurur).	\
**H.**Vurmanızdan aksa-yı murad?	\
**K.**Aksaraylı murtad babandır!(Vurur.)	\
**H.**Ne hakkın var beni dövmeye?	\
**K.**Yalnız dövmek değil, şimdi başlıyacağım sövmeye!(Vurur.)	\
**H.**Seni idbar köpek seni!(H. da Karagöze vurur.)	\
**K.**Seni müflis pezevenk seni!(Vurur.)	\
**H.**Seni arsız herif seni! (Vurur.)	\
**K.**Seni yüzsüz herif seni!(Vurur.)	\
**H.**Böyle sabaha kadar dayakla vakit mi geçireceğiz?	\
**K.**Artık dayağın hızı geçti.	\
**H.**Ah, benim ömrümün hâsılı Karagözüm!	\
**H.**Karagöz, bir daha söyliyeceğim!	\
**K.**Söyle bakalım!	\
**H.** Ah, benim götümün mayasılı Hacivad!	\
**H.**Karagöz, terbiyesizliği bırak, güzel güzel muhabbet edelim!	\
**K.**Muhabbet edelim, kavga ne lâzım!	\
**H.**Aferin Karagöz, oldukça şairliğin de var.	\
**K.** Varlık olmasın, şairlikten yana birinciyim.	\
**H.**Öyle ise, sana bir beyit söyliyeyim tanzir et!	\
**K.**Başüstüne, Hacı Cavcav!	\
**H.**Sezadır fahr idersern meclis-i irfana geldim ben, \
Ezelden lûbebazım ta ebed efsane geldim ben. \
Burusa, semtidir aslım,Hacı Evhad denir namım,\
Safa meddahıdır tab’ım, zehi bir dane geldim ben!		\
**K.**Dinle, Hacivad!	\
**H.**Söyle bakalım!	\
**K.**Sulukulede mevlûdum düşüp meydane geldim ben,	\
Yonulmamış, odun gibi tuhaf bir dane geldim ben. !	
Sorarsan hal ü şanımdan sual it, var. Selâmsızdan.	\
Temürcü Karegöz namında bir çingâne geddim ben.	\
\
**H.** Alup sabr u karanım bir periru nimsiyah-çerde, \
Hayali didede, bad-i muhabbet cuş ider serde, \
Ne yapsam neylesem âya o şuh-i fitne-engize?	\
Nigâh-ı şefkat itmez, RAŞİD-âsâ düşmüşenm derde.	\
\
**K.**Geçüp Ayvansaraydan azm iderken Altımermerde\
Görüp bakkal yakamdan tuttu, borcum vardı defterde.	\
Çıkardım boş kesemden bir sıfır teslim-i deyn ittim,\
Abamı aldı sırtımdan, salıvirmedi, bak derde!	\
\
**H.**Karagöz, bir daha söyliyeceğim.	\
**K.**Buyurun, söyleyin!	\
**H.**Çeküp cam-i meyi nuş eyleyüp ta mest olup yattım,	\
Tesellibahş olup dilden gam u efkâri hep attım.	\
Düşümde haneme teşrife rağbet eyledi canan,	\
Şaşırdım fikrimi ruyun görünce aklım oynattım.	\
\
**K.**Çeküp bir hayli zahmet kendimi bir yana dar attım.	\
Sıracı görmesün deyü kaçarken lağıma yattım.	\
Ne hal ise eve geldikte yattım yok yatak yorgan.	\
Genişçe bir nefes aldım, düşümde maymun oynattım,	\
\
(Hacivada atar tokadı, H gider.)Ben şair miyim? Yoksa Aşik Garip miyim? Yoksa Gevherinin süt bilâderi miyim?	\
Ulan, sen gidersin de beni pamuk ipliğiyle mı bağlıyorlar? Ben de gideyim idgaha,dolaba, dilber seyrine. Bakalım aine-i devran ne suret gösterir! (Gider.)	\
\
(Şarkı ile salıncak ferdeye konur.)	\
Şarkı Hicaz.	\
\
Esirin oldum ey zülfü kemendim ...	\
\
(Hacivad salıncağın İçine biner, salınacak sallanmaya başlar: sallanırken uyur, başlar hırlamaya.)	\
**K.** (içeriden bakar).Ulan! Hacivadı asmışlar, daha can verememiş hırlıyor! Gideyim de şunun ipini keseyim! (Perdeye gelir, Hacivada seslenir:) Hacivad, ulan, Hacivad!	\
**H.**Vay hınzır çingene vay! Ulan, rahatımı selbettin!\
**K.**Hacivad. ben seni asmışlar zannettim!	\
**H.**Bak yediği naneye!	\
**K.** Bu ne, Hacivad?	\
**H.** Ömrün içinde hiç görmedin mi?	\
**K.**Hayır, görmedim.	\
**H.**Buna bayram beşiği derler.	\
**K.**Hangi Bayramın eşeği?	\
**H.**Bayramın eşeği değil, idgâhta kurdukları salıncak.	\
**K.**Bitpazanndan aldığın oyuncak mı?	\
**H.**Canını efendim, sen nasıl lâkırdı anlarsın?	\
**K.**Sen anlatırsan ben de anlarım.	\
**H.**Bayram günleri Fatihte, Karagümrükte ve sair yerlerde salıncak kurmazlar mı?	\
**K.**Evet, kurarlar.	\
**H.**İşte bu da o salıncaklardan.	\
**K.**Ne olacak şimdi bu?	\
**H.**Ne olacak? Ben burada salıncakçılık edeceğim, elbette bir kaç kuruş kazanırım.	\
**K.**Kuzum Hacivad, beni de yanına al!	\
**H.**Yo, Karagöz! Bana balta olma! Salıncak benim malım.	\
**K.** Salıncak senin malın olsun; senin elinden salıncağını almıyoruz ya!	\
Bu perdenin yarısı seninse yansı da benim.	\
**H.**Eyi ya; ne demek istiyorsun?	\
**K.**Bir şey demek istemiyorum. Seninle ortak olur, burada bu akşam para kazanırız.	\
**H.**Haydi diyelim ki seni kendime ortak ettim. Evvelâ senin elin uzundur.	\
**K.**Ben şimdi elimi kastırdım.	\
**H.**Yok yok, olamaz! Ben kendi kendime yaparım.	\
**K.**Ben de sana rahat vermem,	\
**H.**Peki; diyelim ki ortak olduk. Salıncağı kaç pay yapacağız?	\
**K.** "Salıncağı kaç pay yapacağız" ne demek?	\
**H.**Yani kazandığımız paraları kaç pay yapacağız?	\
**K.**İki pay.	\
**H.**Neden iki pay?	\
**K.**Bir pay benim, bir pay yine benim.	\
**H.**Şimdi efendim, senin anlıyacağın: Bir pay benim, bir pay senin, bir pay da salıncağın.	\
**K.**Ulan, salıncağın ağzı var mı?	\
**H.**Efendim, salıncağın tamiri var eskirse,	\
**K.**Eskirse ben yaparım.	\
**H.**Güleyim bari! Sen bir ufak kümes bile yapamazsın, nerede kaldı ki böyle büyük ince iş yapacaksın!	\
**K.** Neden yapamam?	\
**H.**Değme tavşan yapamaz, nerde kaldı ki sen!	\
**K.** Vay, tavşanlar da yapıyor mu? Tavşanlar yaptıktan sora ben niye yapamam?	\
**H.**Karagöz, benim işime ket veriyorsun,	\
**K.**Keti kütü yok; mutlaka ortak olacağım.	\
**H.**Peki, haydi ortak olalım! Müşteri geldiği vakit ne yolda muamele edeceksin bakayım?	\
**K.**Ne yolda olacak? Adamına göre muamele.	\
**H.**Bazı müşteriler salıncağa binemez, sen bindireceksin.	\
**K.**Elbette bindiririm.	\
**H.**Haydi bakalım, sen kendin bin bakalım! Çık üstüne!	\
**K.** Peki, çıkayım! (K. salıncağın üstüne? ftkar.) Haydi, salla beni!	\
**H.**Karagöz, sesin derinden geliyor, ne taraftasın?	\
**K.**Salıncağın üstünde.	\
**H.**Ulan, in aşağıya! Bütün salıncağın oymalarını kıracaksın.	\
**K.**(iner aşağt). Ulan, sen söylemedin mi "üstüne çık" diye?	\
**H.**Altına gir!	\
**K.** Peki, gireyim. (K. salıncağın altına yüzü koyun yatar.)Salla!	\
**H.**Neredesin? Yine sesin derinden geliyor!	\
**K.**Altındayım, altında!	\
**H.**(bakar görür).Hay Allah müstahakkınıversin! Oradan kalk!	\
**K.**(kalkar) Nasıl edeceğiz?	\
**H.**Sen lâkırdı anlamaz mısın, yoksa türkçe mi bilmiyorsun? Salıncağın içine otur!	\
**K.** (salıncağa binerken düşer). Hacivad, salıncağa bineceğim diye başım	\
yarılacak.	\
**H.**Dursan a, tarif edeyim!(H. biner, başlar sallanmaya.)	\
**K.**Vay köpoğlu! Tesbih böceği gibi!	\
**H.**(salıncaktan iner) Öğrendin mi?	\
**K.**(biner).Dur bakalım, yapabilecek miyiz? Hacivad, beni salla !	\
**H.**Peki, sallayım! (Sallar.)	\
**K.**Hacivad, salıncağı tut, ineceğim.	\
**H.**(tutar) İn bakalım!	\
**K.**(Hacivadın omuzunda durur) Aman Hacivad, burası ne rahat!	\
**H.** İn aşağıya! (Karagözü yere atar.) Omuzum çöktü.	\
**K.** Ulan Hacivad. ne kadar merhametsizsin î Beni yere attın!	\
**H.**Karagöz, ben gidiyorum, göreyim seni! Gelen müşterilere rıfk ile muamele et, bet muamele etme, anladın ya? Sora gücendirirsen. kimse gelmez sallanmaya.	\
**K.** Başüstüne , sen esef etme! Aman. Hacivad, bana müşteriyi sallamasını öğret!\
**H.** Salıncağı it, geri çekil!	\
**K.** (salıncağı iter, üstüne doğru gelir). Hacivad, salıncak üstüme geliyor!	\
**H.**Canım, it de geriye çekil!	\
**K.**(iterken salıncağı bırakır, Karagözün kafasına çarpar).Hacivad, kafam yarıldı!	\
**H.** Karagöz, hiç senin elinden bir şey gelmiyor! İt de dur, bak, ben yapayım! (Başlar sallamaya salıncağı.) Gördün mü?	\
**K.** Ulan, ben yapamıyorum.	\
**H.**Ben gidiyorum.(Gider.)	\
**K.**Ben kendi kendime meşkedeyim! (Salıncağı iter geri çekilir, iter geri çekilir.) Ulan, yapıyorum be!	\
\
(Şarkı ile Çelebi gelir.)	\
\
Şarkı Acem Aşiran.	\
\
Yandı dil aşkınla, ey şuh-i şenim, \
Kûh u deşt olmakta şimdi meskenim.\
Halime rahm itmedin aslâ benim.	\
Nakarat: Hasretinle çâk çâk oldu tenim.	\
\
Vireli gönlüm sana, ey mehlika, \
Görmedim bir berecik senden vefa, \
Gayri lûtf it, eyleme cevr ü cefa!	\
Eyzan.	\
\
**Çelebi.** İdgâh mahalli gibi ne güzel salıncak kurmuşlar!	\
**K.**Gel sallangıca!	\
**Ç.** Salıncakçı baba hu!	\
**K.**Ne var, oyuncakçı oğlum?	\
**Ç.**Ne tuhaf adam! Ben ona salıncakçı dedim, o da bana oyuncakçı diyor! Baba, burada Hacivadin salıncağı varmış, bu salıncak mı?	\
**K.**Ben Hacivadın salıncağını bilmiyorum.	\
**Ç.** Neme lâzım benim? İster Hacivadın olsun ister başkasının. Ben sallanayım da kimin olursa olsun!\
**K.**Gel sallangıca!	\
**Ç.**Baba, kaç paraya sallayorsun?	\
**K.**Efendim, bin beşyüz kuruşa,	\
**Ç.**Salıncağı mı satıyorsun ?	\
**K.**Değil efendim, sallama parası.	\
**Ç.**aba, sana yirmi kuruş vereyim, beni güzel salla!	\
**K.** Ben yirmi kuruşa sallayamam, sermayeden ziyan ederim. Bir kuruş verirsen sallarım.	\
**Ç.**Anlaşıldı. Sen bir saf adama benziyorsun. Sen beni salla da ben senin gönlünü hoş ederim.	\
**K.**Sen beni sarhoş edersin amma, ben de sana bir tek zorla attırırım. Gel oğlum, bakalım!	\
**Ç.**Baba, beni bindir!	\
**K.**(Çelebiyi kucaklar kaldırır, salıncağa bindiremez).Ne kadar ağırsın!	\
**Ç.** Baba, beni bindirsen e!	\
**K.** Oğlum, bindireceğim anıma, bir türlü bindiremiyorum.	\
**Ç.**Haydi bindir!	\
**A.** Bindirmesem de seni kucağımda sallasam olmaz mı?	\
**ç.** Baba, eğlenme, bindir!	\
**K.**(Çelebiyi salıncağa bindirir) Nasıl oğlum, rahat mı?	\
**Ç.**Salla, baba!	\
**K.**Sallayım oğulcuğum.(Çelebiyi sallar.)Gel sallangıca!	\
**Ç.**Baba, sana bir mani söyliyeyinı mi?	\
**K.**Bir de söyle, iki de!	\
**Ç.**(mani söyler:)Ben-diken bend iken!	\
Anası gül, kızı gonçe, ara yerde ben diken.	\
Nasıl sana meyl itmeyem başım sana bend iken?	\
**K.**(Yandık diye salıncağı durdurur).Yandı, yandı, yandı!	\
**Ç.**Baba, bir yer mi yandı?	\
**K.** Yani salıncak yandı, sallaman da bitti.	\
**Ç.** Beni indir!	\
**K.**(Çelebiyi salıncaktan indirir).Gel oğlum, bakayım!	\
**Ç.**Al baba, sana otuz, kuruş, beş kuruş da bahşiş!	\
**K.**Bana baksan a, oğlum! Hacivadı görürsen sakın bir şey söyleme!	\
**Ç.**Ne gibi efendim?	\
**K.**Salıncağa bindiğine dair "Salıncağa bindim otuz beş kuruş verdim" deme!	\
**Ç.**Neme lâzım benim? Ben zevkimi ettim ya!(Gider.)	\
\
**K.**Gel sallangıca! (Salıncağı sallar.) Gel!	\
**Hacivad.** (gelir) Karagöz, müşteri geldi mi ?	\
**K.** Gelen giden yok.	\
**H.** Nasıl gelen giden yok? Bir bey gelmedi mi ?	\
**K.** Ne bey geldi ne de ikili geldi.	\
**H.** Canım, gelmiş, inkâr etme! Hattâ sana otuz kuruş vermiş, beş kuruş da bahşiş vermiş.	\
**K.**(kendi kendine:)Vay boşboğaz puşt vay! (Hacivada:) Gelen giden yok.	\
**H.** Karagöz, sen işin elifbasından başladın yalana.	\
**K.**Sabahtan ben sinek avlıyorum.	\
**H.**Sora yakalarım, Karagöz!	\
**K.**Tut bacımı, al haracımı!	\
**H.**Ben gidiyorum müşteri yollamaya.(Gider.)	\
**K.**Yolla gelsin! (Salıncağı sallar.) Gel sallanmaya!	\
\
(Şarkı ile Zenne gelir.)	\
\
Şarkı Acem Kürdi.	\
\
Sen şeh-i nazik-edasin, ey peri,	\
Ben senin mecburinem çoktan beri, 
Hayli demdir gezerem ben serseri.	\
Nakarat:Ağlamaktan kalmadı çeşmim teri.	\
\
iştiyakın canıma kâr eyledi.	\
Başıma dünyaları dar eyledi,	\
Can u dil nakdini hep gar eyledi.	\
Eyzan.	\
\
Daima ağyar ile hemdem-neşin,	\
Cevre mail bir güzelsin, yok eşin,	\
Ben kulun gördükte sen çatma kaşın!	\
Eyzan.	\
\
**Zenne.**Evde otura otura canım sıkıldı; bir az gezeyim!	\
**K.**Gel sallangıca! (Salıncağı sallar.)	\
**Z.**Ey, inan olsun! Burada salıncak var. Baksan a, salıncakçı baba!	\
**K.**Buyurun efendim!	\
**Z.**Beni sallar mısın ?	\
**K.**Niye sallamam? Hem sallarım hem sana sallanırım.	\
**Z.**Bu Hacivadın salıncağı mı?	\
**K.**Hacivadın neden oluyor? Benim salıncağım.	\
**Z.**Neme lâzım benim ? Kimin olursa olsun, ben sallanayım da ...	\
**K.**Gelin bakalım!	\
**Z.**Kaç para vereceğiz?	\
**K.**İkiyüz kuruş.	\
**Z.**Salıncağın kirası mı ikiyüz kuruş?	\
**K.**Hayır ( Efendim, sallanmaya ikiyüz kuruş.	\
**Z.**Baba, çok para, ikiyüz.	\
**K.**Efendim, mürvete endaze olmaz. Siz de bir kuruş verin!	\
**Z.**Anlaşıldı, siz hesap bilmiyorsunuz. Siz beni bindirin, ben sizin gönlünüzü hoş ederim.	\
**K.**Gel bakalım! (K Zenneyi kucağına alır, elinde tutar.)	\
**Z.**Baba, salıncağa bindirsin e!	\
**K.**Böyle dursan daha eyi değil mi?	\
**Z.**Baba, haydi bindir!	\
**K.**(Zenneyi bindirir, başlar sallamaya).Kızım, bir şey söyle!	\
**Z.**Söyliyeyim. babacığım!	\
\
Şarkı Nihavend.	\
\
Bir güzel kız salıncakta sallanır.	\
Kolan vurdukça göklere yollanır,\
Şiddetinden yanakları allanır.	\
Nakarat: Salıncaktır genç kızların oyunu,	\
Kolan vurdukça seyr edin boyunu!	\
\
Gelin, kızlar, anamıza soralım,	\
Bahçemize salıncağı kuralım, \
Karşılıklı binip kolan vuralım !	\
Eyzan.	\
\
**Z.**Bana baksan a, salıncakçı!	\
**K.**Buyurun efendim!	\
**Z.**Gel salınçağa, ben de seninle kolan vuralım!	\
**K.**Eyi amma, ben safralıyım, sora başım döner, kusarım.	\
**Z.**Kuzum baba, gel!	\
**K.**Nasıl gelirse gelsin!	\
(Zenne ayağa kalkar, Karagöz de. karşısında ayakla kolan vururlar.)\
**Z.** Haydi bakalım, babacığım, kolan vur!	\
**K.**Nasıl yapacağız?	\
**Z.**Sen şöyle üstüme doğru gel!(Kız kolan vurur.)	\
**K.**(kolan vurur).Hop, amma ne tuhaf şeyi	\
**Z.**Sen benim üstüme doğru gel, hop!	\
**K.**(de yapar). Hop ama. sorası fena! Benim safram kabarmaya başlıyor.(Sallanırlar.)	\
**Z.**Aman babacığım, üstüme gel, eyi kolan vuralım!	\
**K.**Beni başladı ıskarmoz tutmaya, titriyorum!	\
**Z.**Köpeğin olayım, azıcık daha şöyle üstüme doğra kolan vur!	\
**K.**Ne kolam kaldı ne de palam! Titriyorum! Boku yedim; şimdi salıncaktan aşağıya düşeceğim!	\
**Z.**Kuzum babam, azıcık daha kolan vur da salıncak eyi uçsun!	\
**K.**Salıncaktan evvel ben uçacağım!	\
**Z.**Sakın elini bırakma, düşersin!	\
**K.**İhtikan oldum gitti!	\
**Z.**Haydi uçur!	\
**K.**Ne uçurması kaldı ne de muçurması? (Salıncaktan aşağıya inerler.) Yandı, yo, koptu!	\
**Z.**Al baba, sana otuz kuruş, beş kuruş da bahşiş!	\
**K.** Bereket versin! Sakın Hacivada bir şey söyleme!	\
**Z.**Neme lâzım benim? (Gider.)	\
**K.** Gel sallangıca!	\
\
**Hacivad.** (gelir) Karagöz!	\
**K.** Ne var?	\
**H.**Şimdi müşteri gönderdimdi, gelmedi mi?	\
**K.**Nasıl müşteri o?	\
**H.**Bir kızcağız gelmedi mi?	\
**K.**Gelen giden yok.	\
**H.**Benim de bu lâkırdıya karnım tok.	\
**K.**İsterse aç olsun, neme lâzım benim?	\
**H.**Karagöz, seni yakalayacağım; sora pişman olacaksın. Evvelâ bey geldi, sora hemşiresi geldi. ikisi de otuzar kuruş sana verdiler, beşer kuruş da bahşiş, sen inkâr ediyorsun.	\
**K.** Almadım bilmem, görmedim bilmem,	\
**H.**Ben seni yakaların. (Gider).	\
**K.**Siktir kerata! Ben burada eşek gibi çalışayım da sora sana para vereyim? Yağma yok!	\
**H.** (gelir).Ne o. Karagöz? "Yağma yok" diye söyleniyorsun?	\
**K.**Sana göre değil. Akşam bakkaldan fasulya aldım, parasını vermedim, bakkal da  "Verdiğim fasulya pişeyendir, ben tecrübe etmedim amma, piştikten sora bîr sahan bana ver!" dedi, ben de ",."yağına yok” diye söyledimdi.	\
**H.**Bir insan kendi kendine konuşur mu ?	\
**K.**Sen bana bakma ’ Ben kendi kendime de hem konuşurum hem görüşürüm.(H. gider.) Sana para mı. sana para mı? Odun atarım odun!	\
**H.** (gelir).Ne o. Karagöz? "Odun atarım" diyorsun?	\
**K.** "Salmcakçılıktan para kazansam vaktiyle eve odun atarım" dedim. (H. gider.) Sana para vereceğim? O kadar budala değilim. Senin gözüne koruk koruk!	\
**H.** (gelir).Ne o, Karagöz? Koruk moruk diye bir şey söyliyorsun ?	\
**K.**Efendim, bizimki yeni bir isim taktı, ben de kızıyorum.	\
**H.**Ne gibi isim?	\
**K.**Ne gibi olacak? Moruk  aşağı, moruk yukarı, moruk diye eğleniyor.(H. gider.)	\
(Şarkı ile Tiryaki gelir.)	\
\
Şarkı Saba.	\
Bir esmere gönül verdim3. . .	\
\
**Tiryaki.** Her ne dem mecliste, saki, cam kendin gösterir, \
Bus-i lâle suret-i ibram kendin gösterir.	\
Suret-i hüsnü idince aks-i mir’at-i zamir	\
Daima ol şuh-i simendam kendin gösterir.	\
\
Karşı tarafta da bir salıncakçı oturmuş, o da endam gösteriyor.	\
Bana baksan a, salıncakçı!	\
**K.**Ne istersin, oyuncakçı?	\
**T.**Beni sallar mısın?	\
**K.**Sen mezarcı Mahmuda git de o sallasın seni!	\
**T.**Bu nasıl lâkırdı ? Sen esnaf değil misin?	\
**K.**Esnafım, ne olacak?	\
**T.**"Esnaf esnafı tanır" derler. Ben seni tanırım.	\
**K.** Ben kimim bakayım?	\
**T.**Sen kim olacaksın? Üzüm hevengi, Galatanın mezevengi değil misin?	\
**K.**Pek doğru söyledin. Esnaf esnafı tanır diye ben de seni tanının.	\
**T.**Ben kimim bakayım?	\
**K.**insan mehengi, Galatanın pezevengi değil misin?	\
**T.**Ağzını topla! Ben adamın ağzım yırtarım!	\
**K.**Benim ağzım mutfak paçavrası mı ?	\
**T.**Haydi, beni salla!	\
**K.**Kaç para vereceksin?	\
**T.**Beş on para veririm.	\
**K.**Öyle senin dediğin gibi beş paraya on paraya salıncak yok.	\
**T.**Benim de bu lâkırdıya karnını tok.	\
**K.**Ayağını öpeyim, bir lokma daha al!	\
**T.**Haydi bindir!	\
**K.**Gel bakalım, başımın belâsı!(Bindirir.)	\
**T.**Sana bir şey okuyayım mı?	\
**K.**Aman oku!	\
**T.**Sesim pek yanıktır.	\
**K.**Demek is kokulu.	\
**T.**\
Şarkı Saba.	\
Fasl-ı güldür, nevbahar eyyamıdır,	\
Goncasın, ey nevcivanım, gül açıl!	\
Bağa çık, seyr ü kenar eyyamıdır.	\
Nakarat:Goncasın, ey nevcivanım, gül açıl!	\
\
**K.** Yandı (Salıncağı durdurur.)	\
**T.** Ne oldu? Bir yer mi yandı?	\
**K.** Hayır, salıncak yandı,	\
**T.**Gözükürde bir şey yok, duman filân çıkmıyor.	\
**K.**Baba, Beyoğlu yangını değil, salıncak yandı demek salıncak yok.	\
**T.**Ha şimdi anladım: Sallanntı yok.	\
**K.**Evet. Yedikardeşleri geçtik, köprüye geliyoruz. Ulan ne bunak herifi	\
**T.**Al paranı!	\
**K.**Bereket versin! (T. gider.)	\
\
**Hacivad.** (gelir) Ey Karagöz, haydi bakalım hesap görelim!	\
**K.**ister kasabı gör. ister zerzevatçıyı!	\
**H.**Ben onu bunu bilmem, senden hesap istiyorum,	\
**K.**Ben bir para almadım ki sana para vereyim!	\
**H.**Ben seni yakalarım.(Gider.)	\
**K.**Ben şu aldığım paraları hesap edeyim.	\
\
**H.** (içeriden). Baksan a bana, yahu !	\
**Hacivadın karısı.**Ne istersin, Hacivad Çelebi?	\
**H.**Benim bir eski takke vardı, onu bana ver!		\
**H.k.** Al. Hacivad Çelebi!	\
**H.**Senin eski feraceni de ve bir baş örtüsünü de!	\
**H.k.**Alınız!	\
**H.**Sarı çedik pabuçlar var, nerede onlar?	\
**H.k.**Alınız efendim!	\
**H.**Bir ufak baston vardı, nerede o?	\
**H.k.**Kapının arkasında duruyordu,	\
**H.**Buldum.	\
**H.k.**Siz böyle ne tarafa teşrif?	\
**H.**Efendim, Karagözle ortak olduk. Şimdi bana madik ediyor, desise ile onun hırsızlığını meydana çıkaracağım.	\
\
(Şarkı ile Hacivad gelir.)	\
Şarkı Dügâh.	\

Dil mest olur huşyar iken . . .	\
\
**Hacivad.** (kocakarı taklidi yapar).Baksan a oğlum, sen salıncakçı mısın?	\
**K.**Neden sordun ?	\
**H.**Burada Hacivadın salıncağı varmış.	\
**K.**Kim halletmiş onu?	\
**H.**Hacivadın salıncağı yok mu?	\
**K.**Yok.	\
**H.**Bu salıncak kimin?	\
**K.**Benim.	\
**H.**Beni sallar mısın?	\
**K.**Salıncağa gençler biner, sen salıncağa binip de ne yapacaksın?	\
**H.**A oğlum! İnsan kocar ama, gönül kocamaz.	\
**K.**Sen mezara git de orada sallan!	\
**H.**Kuzum salıncakçı, beni salla!	\
**K.**Peki, sallarsam kaç para vereceksin?	\
**H.**Ey, para ile mi sallıyorsun?	\
**K.**Bedava mı sallanacaksın?	\
**H.**Ne bileyim? Herkes bedava sollanıyormuş.	\
**K.**Bedava yağma yok. para ile, para!	\
**H.**Benim oğlumla kızım vardır, onlar bedava sallanmışlar.	\
**K.**Yanlış.	\
**H.**Ey para verdiler mi?	\
**K.**Verdiler ya!	\
**H.**Kaç para verdiler?	\
**K.**Evvelâ oğlan geldi sallandı, otuz kuruş verdi, beş kuruş da bahşiş.	\
**H.**Ya! öyle mi? Kız kaç kuruş verdi?	\
**K.**O da aynı oğlan gibi otuz kuruş verdi, beş kuruş da bahşiş.	\
**H.**Demek ki otuz beş, otuz beş: yetmiş kuruş.	\
**K.**Yetmiş kuruş.	\
**H.**Daha başka müşteri geldi mi?	\
**K.**Bir tiryaki geldi o da sallandı.	\
**H.**O kaç kuruş verdi?	\
**K.**O da yirmi kuruş verdi.	\
**H.**Yetmiş kuruş, yirmi daha, etti doksan kuruş.(Başını yukarı kaldırır: ) Karagöz, hani benim hakkım?	\
**K.**(başlar yalandan gülmeye). Ulan, Hacivad, Hacivad, ha ha ha!	\
**H.**Karagöz, ne gülüyorsun?	\
**K.**Ulan, uzaktan gelirken seni tanıdım, bakalım şu Hacivad ile bir az eğleneyim dedim.	\
**H.**Karagöz, ben böyle dolma yutmam.	\
**K.**Yutmazsan çiğne çiğne tükür!	\
**H.**Ben gidiyorum, elbette seni yakalarım!(Gider.)	\
**K.**Vay köpoğlu! Kimin hatırına gelir? Karı kılıfına girmiş, hiç tanıyamadım ! Ben şu paraları hesap edeyim ! (Oturur, paraları hesap etler.) Beş, beş daha: on, beş daha on beş. (H. gelir. Karagöz Hacivadı görmez.) Beş daha: yirmi.	\
**H.**Karagöz!	\
**K.**(şaşırır, paraları alır koynuna kor). Ulan Hacivad, ne tuhafsın!	\
**H.** Ey Karagöz, bu ne? Ne diyeceksin?	\
**K.** Ulan , onlar benim param.	\
**H.**Ben şimden sora hiç bir şeye karışmam. Ne halin varsa gör!(Gider.)\
**K.**Vay köpoğlu! Gafil aldandım.	\
(Şarkı ile Sarhoş gelir.)	\
\
Şarkı	\

Nice sevmeyeyim dostlar ..	\
\
**Sarhoş.**Hey gidi yiğitlik hey!	\
**K.**Hey gidi eşeklik hey!	\
**S.** Ulan, burada bir şey var,	\
**K.**Sarhoşluktan herifin gözü de görmüyor,	\
**S.** Baba, necisin ?	\
**K.** Efendim, salıncakçı kulunuz.	\
**S.** Oyuncakçıymış!	\
**K.**Evet efendim. Eğer isterseniz bir tane kaynana zırıltısı vereyim.	\
**S.**Yo, ben istemem. Her akşam evde bizim kocakarının zırıltısını dırıltısını dinlemeden bıktım.	\
**K.**İsterşeniz bir tane aferin saka vereyim.	\
**S.**Parasız su getirirse ver!	\
**K.**Tenekesini üç kuruşa getiriyor.	\
**S.**Baba, doğru söyle, necisin ?	\
**K.**Efendim, salıncakçı dedik ya!	\
**S.**Öyle ise, beni salla!	\
**K.**Sallamaya hacet yok; durduğunuz yerde kendiniz sallanıyorsunuz!	\
**S.** Kuzum baba, salla!	\
**K.**Sallayım efendim.	\
**S.** Seninle mukavelem var.	\
**K.**Ne gibi?	\
**S.**Ne gibi olacak? Beni hem sallamak, hem uyutmalı, hem uyandırmak, ağlatmak, güldürmek.	\
**K.**Söylediğiniz şeylerin bazısı kolay, bazısı güç.	\
**S.** Neden güç?	\
**K.**Neden olacak? Haydi sizi sallayım, o kolay, o vazifem, sallarım. Uyutmak, o da kolay, zaten sarhoşsunuz, sızacak yer arıyorsun, o da kolay. Uyandırmak, o da güç. bir kere sızdınız mı top atsalar duymazsın. Seni ağlatmak güldürmek ne kadar zor! Gel bakalım!(Sarhoşu salıncağa bindirir.)	\
**S.**Salla, Karagöz!	\
**K.**(sallar).Sallayım efendim. „Uyusun da büyüsün ninni, tıpış tıpış yürüsün, ninni!"	\
**S.**(uyur).Khr khr khr ...	\
**K.**Ulan, bu köpek cinsi, hırlıyor! (Bağırarak:) Yandı yandı!	\
**S.**(uyanır).Sabah mı oldu?	\
**K.** Evet efendim. ..Sabah oldu, uyansan a!	\
Gül yastığa davansan a!"	\
Haberiniz var mı?	\
**S.** Hayrola ?	\
**K.**Rakının okkası.. .	\
**S.** Ey?	\
**K.** Beşyüz kuruşa çıkmış.	\
**S.**Aman Karagöz, deme! (Ağlar.)Ööö . . .	\
**K.**Eşek nağmesi yahu! Efendim, rakının okkası beş kuruşa inmiş.	\
**S.**(gülerek).Ha ha ha ha! Aman Karagöz, göönüm bulanıyor.	\
**K.**Gördün mü ettiğin haltı? Hiç sarhoş adam salıncakta sallanır mı? Olacağı bu!	\
**S.**(salıncaktan iner, başlar salıncağın içine kusmaya:)Balo bolo bol !	\
**K.**Ulan, boku yedi salıncak!(Sarhoş gider. Karagöz salıncağın içine bakar.) Ulan, takimiyle çiğnemeden yutmuş sardalya balıkları, salatalık, hıyar! Ulan, kırmızı turplara hak! Gideyim Hacivada haber vereyim, ben kimsenin hakkını yemem! (Gider Hacivadın kapısını çalar.)Hacivad, Hacivad!	\
**H.** (içeriden). Ne var, ne istiyorsun?	\
**K.**Aşağıya gel de seninle hesap görelimi	\
**H.**Karagöz, akça tahtasını getireyim mi?	\
**K.**Akça tahtasını getireceğine iki kova su ile bir çalı süpürgesi getir!	\
\
(Hacivadla Karagöz perdeye, gelirler.)	\
**Hacivad.** Ne o, Karagöz?	\
**K.** Salıncağın içine bak, Hacivad!	\
**H.** (bakar). Pööff!(Der çekilir.)	\
**K.** (bakar). Pööff!(Der çekilir.)	\
**H.** Ben gidiyorum, sen ne yaparsan yap, mundar musibet!	\
**K.** (salıncağı eğer, kusmuklar akar). Kalpağımla temizlerim. (Başı ile de siler.)	\
(Şarkı ile Yahudi gelir.)	\
\
Balat kapisinda yirdim içeri,\
Yuzeller oturnuş iki keçeli.	\
Buyuyune selâm verdim : Al beni içeri!	\
Nakarat:Yuzeller oturmuş iki keçeli.	\
\
**Yahudi.**Maşalâ maşalâ! Çoktan beri ayi yorduğum yokdu, karşima çikti!	\
**K.**Bezirgan, tepelerim!	\
**Y.** Kimi tepelersin?	\
**K.** Seni.	\
**Y.** Bu suratlan mı?	\
**K.** Hayır, maraza için evde ayrı suratım var.	\
**Y.** Surata bak, boya bak, biçime bak!	\
**K.**Ulan, suratımı beğenmiyor musun?	\
**Y.** Niçun beğenmem? Maşalgam, maşalgam!	\
**K.**Gırla turp salatası!	\
**Y.** Osurmak ayb olmasın: necissin ?	\
**K.**Necis senin baban!	\
**Y.**Ne iş yapıyorsun?	\
**K.**Salıncakçıyım.	\
**Y.** Aman, baba, beni salla!	\
**K.**Gel de sallayım!	\
**Y.**Kaç para vereceğiz sallanmak içim?	\
**K.**Yüz kuruş,	\
**Y.**Vay kademsiz oğlu kademsizi! Sen de karin da beraber mi?	\
**K.**Yahudi, tepelerim! Doğru konuş. Sen ne verirsin?	\
**Y.**Haydi bir kuruş vereyim!	\
**K.**Olmaz, bezirgân!	\
**Y.**Haydİ, iki yirmilik vereyim!	\
**K.**Olmaz.	\
**Y.**Haydi dört tane onluk vereyim!	\
**K.**Gel bin!	\
**Y.**Bindir bakalum!	\
**K.**(Yahudiyi bindirir).Nasıl, rahat mısın?	\
**Y.** Haçenki „Salla“ derim, sallama! „Sallama!" derim, salla!	\
**K.** Böyle ters iş ölür mu?	\
**Y.** Sallama!	\
**K.** Sallamıyorum.	\
**Y.** Sallasan a!	\
**K.**(sallar) Sallıyorum.	\
**Y.**Sallama salla! (K. sallar, Y. düşer ölür.)	\
**K.**Yahudinin canı götünden çıkıp gitti. Neme lâzım, ben evcağızıma gideyim.(Gider.)	\
**Hacivad.** (gelir) Bakar mısın bir kere? Yahudi galiba salıncaktan düşmüş ölmüş, Karagöz de firara kadem basmış. Ben Balata gideyim de haber vereyim arkadaşlarına, gelsinler bunu kaldırsınlar. (Gider.) Baksanız a, bezirganlar!	\
**Yahudiler.** (içeriden) Buyurun, ne istersiniz?	\
**H.** (içeriden). Sizin arkadaşlardan biri Şeyh Küşteri meydanında yatıyor. Bir kere baksanız a!	\
**Yahudiler.** (içeriden) Yideriz. (Bir kaç Yahudi gelirler meydandaki Yahudiyi alırlar götürürler.)	\
**Hepsi bir ağızdan.**Anda la vizo! (Makam ile:) Anda la vizo anda la vizo imero nane kavizo!(Mükerrer.)	\

(Önde Hahambaşı, arkada diğer Yahudiler, ortada tabut, Yahudiler perdeye gelirler: en arkada bir kocakarı, bir Yahudi çocuğu. Hepsi susarlar.)	\
**Haham.** (dua eder) A kerez ma kerez, havyar salatasi!	\
**Yahudiler.** Hamme !	\
**Haham.**A kerez ma kerez, turp salatasi!	\
**Hepsi birden.**Hamme!	\
**Haham.**A kerez ma kerez, zeytun salatasi!	\
**Hepsi.**Hamme!	\
**Haham.**A kerez ma kerez, tomatiz salatasi!	\
**Hepsi.**Hamme!	\
**Haham.**A kerez ma kerez, soğan salatasi!	\
**Hepsi.**Hamme!	\
**K.** (yukarıdan bakar).Ulan, bunlar gidiyorlar. Yahudi ölmedi. Ben şimdi atlarım, bunlar kaçar.	\
(Karagöz atlar, cümlesi kaçarlar, yalnız tabut kalır. K. tabutu açar,	
Yahudiyi tabuttan çıkarır arka üstü yatırır. K. de arka üstü yatar.)\
**K.**Dur bakalım! "Çingene ile Yahudi taban tabana zıt" derler.	\
(Yahudi usul usul başını kaldırır. K. de kaldırır.)	\
**K.**Vay köpoğlu!	\
(Birbirlerini gördüğü vakit ikisi de başını yere korlar.)	\
**K.**Nasıl edeceğiz bu Yahudi ile?	\
(Bir kaç defa yaparlar, Karagöz kalkar. Yahudiyi yüzü koyun yatırır, kendisi de yüzü koyun yatar. Yahudi usul usul kalkar, Karagözün ensesine bir tokat atar, yine yatar. Bir kaç defa yaparlar, Yahudi kaçar, Karagöz kalkar. Hacivad gelir, Karagöz Yahudi zanniyle Hacivadı yere vurur.)	\
**Hacivad.**Aman. Karagöz! Ne yapıyorsun ?	\
**K.**Ulan, ben seni Yahudi zann ettim.	\
**H.**Çok şükür sağlığa!	\
**K.**Hak bereket versin Kâthanedeki sazlığa!(Hacivada vurur.)	\
\
(Alt tarafı malûm.)	
