


# bursalileyla
\
**Hacivad** (semaîyi söyliyerek perdeye gelir).	\
Semai Beyati	\
\
Her güzel böyle nazlı mı olur?	\
Sürmeli elâ gözlü mü olur?	\
Dilberi sevmek gizli mi olur?	\
Nakarat:Ömrümün varı, gel sarıl bari!	\
\
Dilberin dudağı ab-i kevser mi ?	\
Dişleri inci, lâli gevher mi?	\
Rahmı yok, zalim, kalbi mermer mi?	\
\
Eyzan.	\
\
Kandesin, güzel? Kande varayım	\
Hal ü hatırın kime sorayım?	\
Ayda bir kerre yüzün göreyim!	\
\
Eyzan.	\
\
(H. perde gazelini okur.)	\
Hayme-i zıllım kurup fennimde geçtim çok hayal, \
Ehl-i dil anlar hayalim, gayriler bilmek muhal.	\
\
Hazret-i Şeyh Küşteri hu zıllı tarif eyleyüp \
İbret alsınlar deyü fâni cihandan ehl-i hal.	\
\
Sureta irşad idüp dirilttin, ey can, çün bizi. \
Her kımıldı vahidindir, kesret ansız bimecal.	\
\
Gök direksiz hayme oldu, perde suret gösterüp \
Hayme ıssı gizleyüp gösterdi surette kemal.	\
\
İBN-İ İSA AKHİSARİ der: Bu suretler kamu	\
Kahr u lütfun mazharıdır geh celâl u geh cemal.	\
\
(Kavgadan sora:)	\
**Karagöz.**Seni gidi utanıp arlanmaz, hiç kimseden korkmaz, çarpık bacaklı kerata! Her akşam gelirsin kapımın önüne, feryad u figana başlarsın, ben de senin sinsilenden başlıyacağım! Bir akşam gelmesen ne olur kerata? Tramvaya abone olmuş gibi her akşam gelir, gelmese olmaz! Bir daha gelecek olursan, Hacivad, bizim çocuğun oturağını senin başına dökeceğim!	\
**Hacivad.** (gelir) Vay Karagözüm! Akşamı şerifler hayır olsun!	\
**K.**Ölmüş kargalar gözünü oysun!	\
**H.** Karagöz, bazı mühim işlerin tesviyesi hususunu sana ihâle etmiştim. Tesviye oldu mu?	\
**K.** Evet, bulundu.	\
**H.**Ne bulundu?	\
**K.**Fıskiye.	\
**H.**Nasıl fıskiye bulunan ?	\
**K.**Senin küçük oğlan geçen gün aktardan almış. Bütün üstümü başımı ıslattı. Nasılsa oynarken kaybetmiş, sora aradık bulduk.	\
**H.**Ben sana aktardan alman fıskiyeyi sormiyorum.	\
**K.** Senin sorduğun ne?	\
**H.**Çarşuyi kebirdeki dekâkinlere bakmıyor musun?	\
**K.**Tarladaki ekinlere baktım; bu sene mahsûl pek ziyade.	\
**H.**Tarladan ekinden bahsetmiyorum; benim sana söylediğim müsakkafata dair şeyler.	\
**K.**Evet, musakkaya dair şeyler: patlıcan, domates, soğan, yağ; kıyma da bol olursa musakka güzel olur.	\
**H.**Senin söylediklerin hep saçma.	\
**K.**Kaçmam, Hacivad, senin yanından ayrılmam.	\
**H.**Sen söz anlamadan bibehre misin?	\
**K.**Evet, kehleyim, tatarcık değilim.	\
**H.**Benim akarlarım nasıl oldu?	\
**K.**Onu sana sormalı, Hacivad. Kendin bilmiyor musun akarın nasıl olduğunu?	\
**H.**Karagöz, benim müteaddit iratlarım vat	\
**K.** İri atların vardı, Hacivad, amma, onların hepsini kokozluktan sen sattın. Geçen gün sana geldiğim vakit gördüm, ahırda yalnız senin topal merkepten başka bir şey kalmamış. 0 da akşama sabaha açlıktan kuyruğu titretecek.	\
**H.**Sen nasıl lâkırdı anlarsın, Karagöz?	\
**K.** Sen anlatırsan ben de anlarım.	\
**H.**Akarlara bakmıyor musun?	\
**K.** Bakıyorum, hiç bakmaz mıyım?	\
**H.**Epeyce akça teraküm oldu mu?	\
**K.** Suyolcu lökün buldu.	\
**H.**Nasıl lökün?	\
**K.** Akarlar için sormıyor musun?	\
**H.**Evet!	\
**K.** Suyolunun bir kaç yerinde sızıntı vardı, suyolcuya lökünlettim, ne akar kaldı ne bir şey.	\
**H.**Ahmak herif! Benimle eğleniyor musun?	\
**K.** Eğlenmiyorum, tek kürekle mehtaba çıkıyorum.	\
**h.**Benim emlaklerim yok mu: hane, han. bağ, tarla, bostan?	\
**K.**Bostanda var.	\
**H.**Bostanda ne var?	\
**K.**Fasulya, kabak, ıspanak, Hacivad bunak.	\
**H.**Zerzevat küfesi başına geçsin! Ben sana zerzevatı sormıyonım; benim o dükkân ve sair iratlarım var.	\
**K.** Var, biliyorum.	\
**H.**Mahiyelerini müstecirlerden mah bemah alıyor musun?	\
**K.**Alıyorum.	\
**H.**Aldığını verdiğini bir yere kaydediyor musun?	\
**H.** Aklığını verdiğini bir yere yazıyor musun?	\
**K.** Yazıyorum.	\
**H.**Aldığın paralar defterinde mukayyet değil mi?	\
**K.**Bir kıye et değil, iki kıye.	\
**H.**Onun lüzumu yok bana.	\
**K.**İstersen zerzevat alalım,	\
**H.**Ne budala herifsin, zerzevatı kim istiyor?	\
**K.** Kimse istemiyor mu?	\
**H.**Ne kadar şehriye aldın?	\
**K.**Yirmi okka.	\
**H.**İratlardan aylık ne kadar aldın? Hepsini hesap et!	\
**K.**Başüstüne, hesap edeyim.	\
Bir, bir daha, bir: Hacivad, yerin dibine gir!	\
Sekiz, sekiz daha, sekiz: Hacivadın ağzından sakız.	\
Sekizden sekiz çıktı: Ayvaz Sergiz konaktan çıktı.	\
Altıya altı: Her sabah yerim kahvaltı.	\
Beş, beş daha, beş: Ekle var dübeş.	\
Beşten beş çıktı: Evden kiracı çıktı.	\
Sıfıra sıfır: Elde var sıfır.	\
Sıfırdan sıfır çıktı: Balıkçı Yanko sana çıktı.	\
Geride kalan: Topal Kirkor ile Çolak Ohanes, usta Takvor.	\
**H.**Bu nasıl hesap? Budala mısın, kaçık mısın?	\
**K.**Açık değilim, kapalıyım. Açığım çıktı, açıkta boğulurdum.	\
**H.**Sen rakam bilmez misin?	\
**K.**Bilirim, niye bilmem?	\
**H.**Kerrat bilir misin?	\
**K.** Kır atı da bilirim beyaz atı da.	\
**H.**Kır at beyaz at değil. Şimdi sana sual soracağım, bakalım cevap verebilecek misin.	\
**K.**Sor bakalım!	\
**H.**Kara cümleyi bilir misin?	\
**K.**Kara Cemile değil mi? Bizim mahallede kurşun döker.	\
**H.**Cem bilir misin?	\
**K.**Acemi de bilirim Evcarayı'da.	\
**H.**Ulan, onlar makam.	\
**K.**Evet efendim, rakam.	\
**H.**İlm-i riyazi?	\
**K.**Her gün mahalle kahvesinde görürüm.	\
**H.**Kimi görürsün?	\
**K.**Hamal Niyazîyi.	\
**H.**Ben ne söylüyorum, sen ne anlıyorsun! Darb bilir misin?	\
**K.**Bilirim.	\
**H.**Darbet bakayım!	\
**K.**Sora kabahati bulma! Sen söylüyorsun. Sıfıra sıfır: Elde var bir!(Harivada vurur.)	\
**H.**Ulan, üşekâ herif! Ne vuruyorsun bana?	\
**K.**Sen „darbet“! demedin mi? Ben de darbettim.	\
**H.**Bu ne cür'et, bu ne habaset, beni darbe cesaret!	\
**K.** Cesareti mesareti yok, tokadı attım gitti.	\
**H.**Taksim bilir misin?	\
**K.**Taksimi de bilirim Beyoğlunu da.	\
**H.**Öyle değil, taksim!	\
**K.** Bilirim.	\
**H.**Taksim et bakayım.	\
**K.**Başüstüne! (Elini kulağına kor. makam ile söyler:) Yâr ey meded ey aman aman!	\
**H.** Bu nasıl taksim?	\
**K.**Adeta taksim, süratlı değil.	\
**H.**Kesr-i âdi bilir misin?	\
**K.** Keserci Badiyi bilirim.	\
**H.**Kesr-i aşari?	\
**K.** Pek severim, Hacivad, kaşari; peynir değil mi?	\
**H.**Âdad-i mürekkebe?	\
**K.**Her,gün binerim bizim merkebe.	\
**H.**Cebir?	\
**K.** Yo Hacivad! Ben cebre gelemem!	\
**H.** Müsellesat?	\
**K.** O benim ahbabımdır.	\
**H.**Kim ahbabın?	\
**K.**Deli Esad.	\
**H.**Anlaşıldı, Karagöz; sen hiç bir şey bilmiyorsun. Ne hesaptan anlıyorsun ne de kitaptan. Ben yine kendi işime kendim bakarım, cahil köpek!	\
**K.**(vurur).Siktir şuradan, sersem pezevenk! (H. gider).	\
Sen gidersin de ben durur mıyım? Ben de gideyim!  (Gider.)	\
\
(Şark ile. Ermeni gelir.)	\
Şarkt Rast	\
\
Bugün hiç bakmadın, ey meh. yüzüme.	\
Haram oldu bu şeb uyku gözüme. \
Gelirsin, bir gün olur da, sözüme.	\
Nakara: Haram oldu bu şeb uyku gözüme.	\
\
**Ermeni.**Vay efendim! Aşkamı şerifleriniz hayır olsun!	\
**Karagöz.**Öyle olsun!	\
**Er.**He efendim, bendenizi çağırdınız, bir emriniz vardır?	\
**K.** Bir şey soracağım.	\
**Er.**Efendim, soracağınız şey muhakkak ulûm u fünuna dair olmalı.	\
**K.** Hoppala! Alsan a bir budala daha!	\
**Er.**Yo, efendim. Kulunuzu böyle ufak tefek görüp de Karamürsel sepeti sandınız. Bendeniz oldukça ulûm u fünun çekmecesiyim. Ana rahminden düşdüğüm günün eksesinden bugüne kadar tahsil-i ulûm ile urgaşmışım.	\
**K.**  Hay köpoğlu!	\
**Er.**  Zira, efendim; bizim torpağı bol olsun irahmetlik peder zamanın kıyak şayirlerindendi. Dorgusunu istersen, öyle kıyak beyitler düzerdi, o zaman ona Samatyanın  Lamartini derlerdi.	\
**K.** Ya?!	\
**Er.**Evet efendim. Her zaman beni karşusuna çağırır; ”Hey Vartan, sana nasihatim şudur ki bir adam ana dilini bihakkın Örgenmeli” derdi. Maylûm ya, benim de ana dilim, yani lisau-i maderzadım türkçe olduğundan ben de türkçeyi bihakkın örgenmiş etdim ; velâkin nasıl örgendim, biloorsun? Ta kökünden örgenmişim.	\
**K.**Kökünden ha!	\
**Er.**Evet. Zira bilirsiniz ki türkçe üç lisandan kompoze etmişdir: türkçe, aryabça, farizice. İşte bende bu üç lisanı öyle örgendim ki en kaba yerinden tut da en elenikasına kadar örgendim. Daha durgusu: o lisanların şayilerinin yazdıkları beyitleri sanki yutmuş etdim.	\
**K.** Ne gibi beyitler yuttun bakalım?	\
**Er.**He efendim, bakınız: aryabça bir beyit var okuyayım da dinleyiniz!	\
**K.**Oku da dinleyim!	\
**Er.**Ah minel-aşk ve hayalâtuhu ! Ahraka kalbihi bihararâtuhu.	\
İşte efendim, bu aryabça, pek kıyak şiyirlerindendir ya! Efendim, tarizi onda da o kadar ilerlemişim ki tut ki Gülistanları Bostanları yutmuş etmişim.	\
**K.** Vay köpoğlu! Bostanları yuttuysan o hesapça epeyce hıyarlar da yutmuşsundur.	\
**Er.**He efen
dim, zatı âliniz muhakkak istihza edoorsunuz. Brak ki ben bostanları yutdum doorsam bostanı değil, mefhumlarını yutmuşum.	\
**K.** Marullarını yutmuşsun? Aman oğlum, eyi ki koçanları midede oturmadı.	\
**Er.**He efendim, rica ederim! Alayı şöyle brakalım, irahmetli Şeyh Sadi Gülistanında door ki:	\
Ey murg-i seher çi âğâz kerdi işkrâ zi-pevrane biyâmû ! Yani ne door, bilirsin?	\
**K.** Ne diyor?	\
**Er.**Yani door ki: „Ey sabah bülbülü, ne carcar edersin, aşkı pevraneden örgen!'' door.	\
**K.** Hay Allah mustahakkmı versin be!	\
**Er.** He efendim.  "bülbül" dedim de merakım kalktı. Söylemişdim ki mehrum peder şayirdi, hiç unutmam: Bir şiyirinde bülbüle der ki: "Sen kemanesiyle tamburasiyle hanendesiyle bir takım çalgıyı içine yutmuş gibi bir kuşsun. O ufacık karnına bu kadar takım notayı nasıl sığdırdın? Hangi hocadan meşkettin? Meşrebine haryan olayım, bu kadar ustasın, dallarda bağırırsın nağme edersin! A bülbül, artık bundan tınma ! Git, cananemin cumbasına kon, sesin çıkdığı kadar bağır Suzinâktan Suzidilden, daha yanık makamlardan, her ne bilirsen oku!" Göroorsun lâkırdıda ne güzellik vardır!	\
**K.** Pek âlâ amma, o ufacık bülbülün karnına Öyle muzikalar sığar mı?	\
**Er.**Al cahili de otur aşağı! Khendsin nesin? Bunca şayir şuera gelmiş beyitler düzerek kitablar doldurmuşlarsa hep onlar tıpatıp dorgu lâf etmişlerdir. Sanırsın âşıklık bir nevi yalancılıkdır; bunlar kırmızı bir yanağı güle, kıvır kıvır saçları sünbüle teşbih ederler. Her ne görürlerse ona cünbüşlü lügat uydururlar, sanki lâfın dorgusunu söylemezler, onları güzel şeylere benzedirler. Senin ağnıyacağın ; Lâfla adeta piyaz ederler.	\
**K.** Senin hiç şirin filân yok mudur?	\
**Er.**He efendim, nasıl yok? Bak. okuyayımda dinleyiniz!	\
**K.** Oku oku, köpek boku!	\
**Er.**Bir ermeni şuhu etti kendine haryan beni,\
Etmedi "Payringun, aszuzu payrin!"le şadan beni. \
Yanılıp nas içere dedim: "İnzi mek şeftali dur!"
"As ons meçi çıllar" dedi mi terk şayan beni.	\
O köpoğlunun herifi dedise horyatla, \
Zo, ne dersin, hele kandırmış itdi Vartan beni.	\
Nasıl? Güzeldir?	\
**K.** Ona hiç diyecek yok. Ben de oldukça şairlerdenim. Bak, sen onu okur okumaz karşılığını şıp diye hazırladım,	\
**Er.**Aman, ayağının dibini öpeyim! Oku da dinleyim!	\
**K.** Dinle!	\
Ferah verir, durgusu, içtikçe aryan beni, \
Zeytin ile soğan ekmek eylemez viryan beni.	\
\
Yağda pişmiş karnı yarık, börek olsa yerim.\
Dibimi tutmaz eder kıymalı şalgam beni.	\
\
Bakkal dükkânından peynir aşırmağı fikr ittimse,\
Hıp diye enseledi ensemden Dikran beni.	\
\
Nasıl buldun şiirimi ? Doğru söyle!	\
**Er.**Hakikat kıyak şeydir.	\
**K.**  Benim sana borcum vardır, ben borcunum kölesiyim amma, bu aralık pek dardayım. Bir kaç gün sabret, sana para veririm, hattâ sana haber gönderirdim İdi.	\
**Er.** Doğru söyloorsun efendim amma, kulunuza da paranın iktizası vardır.	\
**K.** Bir kaç gün daha sabret!	\
**Er.** Peki efendim! Allaha ’smarladık!(Gider.)	\
**K.** Sefa geldin, hoş geldin!(Gider.)	\
\
(Şarkı ile Kayserili gelir )	\
\
Şarkı Hüseyni	\
Şu Gayseriyenin dağı daşı bostandır.	\
Gız. senin ettikhlerin bana destandır,\
Ayağına geydığın yığın fistandır.	\
Nakarat: Çımnağını çımnağını çımnağını çım.	\
Çımdığım çımdığım, şimdi de bildim kimdığım.\
Ağ gerdanından şöylece bir emdiğim	\
Gız. senin aşğın değel mi boz eşagha gömdüğüm?	\
Eyzan.	\
\
Şeftali goparmağa çıkhtım bağlara.	\
Giz, senin aşgından düştüm dağlara.	\
Şu halımı gören benim ağlar a!	\
Eyzan.	\
\
Yığın olur şu Gayseriyenin meşesi.	\
Nerede de galdı cığarımın köşesi?	\
Anasının yedeğde bağlı Aişesi.	\
Eyzan.	\
\
**Kayserili.** Aşkamı şerifler hayır olsun!	\
**Karagöz.**Dilini eşek arıları soksun. Öyle ola!	\
**Kay.**Nasılsın bakhalım, pazar iti?	\
**K.**Babandır pazar iti! Söyle bakalım, bekâr biti!	\
**Kay.**Canım, ne diye hiddetleniyorsun? Sana irkâm ettim, irkâm! Anliyon mu?	\
**K.**Adam herif irkâm ediyormuş,vay, ayı dayı! Hemşerim,onun doğrusu ikram, irkâm değil.	\
**Kay.** Hele şu gıl guyrukh herife bakh! Hele bana lûvat örgetmeğe gagdı. Ulan, avşar oğlu avşarsın, hiç nektep görmedin mi?	\
**K.** Al bir galât daha! Mektebe nekteb diyor da bir de ben lügat bilirim diyor!	\
**Kay.** Adam nece bakh! Zırtaboz’ herifsin! Senin garşundaki uşakh değel!Ben mîn gayri haddin aşkam sabah guravathanede oturdukhlayın bütün gazaveteleri bir başdan bir başa dek okhurum.	\
**K.** İşte şimdi gülmeden çatlarım! Hemşerim, o birinci söylediğine kıraathane. İkincisine de gazete derler, gazete!	\
**Kay.**Adam, bi kere etrafına bakh! Efendiler sana gulirler. Ülen, ona gazavete derler, gazavete, gıl guyrukh herif!	\
**K.**Anlaşıldı, ya ben bunu döverim ya o beni döver.	\
**Kay.**Kimi döveceksin, biçimsiz oğlu biçimsiz! Bir keret garşundakine bakhsana! Duva et ki dakgımlarım yanımda değel! Melmekette olaydın ben seni güzelce boyardım, a siniri bozukh!	\
**K.**Ulan, herif bizi eşek yaptı, katlanmalı!	\
**Kay.**Zırtaboz! Şu bizim pareler nasıl olacakh?	\
**K.**Yakında veririm, şimdi param yok.	\
**Kay.**Eğer paramı vermezsen abubokh tutar, seni porodistan yaparım!	\
**K.**Vay ayı vay! Yine çam devirdi. "Avukat tutar protesto ederim" diyecek yerde "abubok tutar sem porodistan yaparım" diyor!	\
**Kay.** Ne zaman geleyim paramı verirsin?	\
**K.** Bir hafta sora gel!	\
**Kay.** Allaha ’smarladıkh!(Gider.)	\
**Kay.**Hoş geldin, sefa geldin!(Gider.)	\
\
(Şarkı ile Zenneler gelirler.)	\
\
Şarkı Müste'ar	\
Ey tuti-i mir'at-i tekellüm,	\
Kıl bülbül-ü gülzara tebessüm!	\
Lûtf it, a canım, ilme teellüm!	\
Nakarat: Kurban olayım, kurban olayım!	\
Sen gül, heman ben nalân olayım!	\
Aşkın, efendim, gelmez beyane, \
Ta sineden tesir itti cane!\
Olmaz behane bu hüsn ü ane.	\
Eyzan.	\
\
**Hacivad(gelir).**Vay efendim, kızım, vakti şerifler hayırlar olsun!	\
**Zenne.**Allaha emanet olun, efendim!	\
**H.**Eyisiniz inşallah?	\
**Z.**Elhamdülillah! Siz de eyisiniz, Hacivad Çelebi?	\
**H.**Duada kusurumuz yoktur.	\
**K.** (pencereden). Duvarda kusurumuz yok, temel bozuk.	\
**H.**(ikinci zenneye hitaben:) Hanım kızım, sen de eyisin inşallah?	\
**İkinci Zenne.**Elhamdülillah efendim, eviyim.	\
**H.**Çoktanberi sizleri gördüğüm yok; nerelerdesiniz?	\
**1. Zenne.**Ayol, biz burada değildik.	\
**H.** Neredeydiniz, hanım kızım?	\
**2. Zenne.**Bursadaydık.	\
**H.**Misafir mi gittiniz?	\
**1. Zenne.**Temelli gittiydik.	\
**H.**Buradaki evinizi sattınız mıydı?	\
**1. Zenne.**Evet, sattık. Hacivad Çelebi.	\
**H.**Oraya gitmenizin esbabı ne idi?	\
**1. Zenne.**A Hacivad Çelebi, ben bir derde giriftar oldum ki bir türlü eyi olamadım. Bu kadar hekimlere baktırdım, şifasını bulamadılar. Nihayet doktorun birisi „Siz Bursaya gitmelisiniz, başka türlü olmaz" dedi.	\
**H.**Evet efendim.	\
**1. Zenne.**Baktım ki olacak iş değil; insana birinci vücud sıhhati lazım.	\
**H.**Pek doğru söylüyorsunuz.	\
**1. Zenne.**Paran da olsa vücudun sıhhatte olmadıktan sora ne para eder?	\
**H.**Efendim, vücud sıhhati üzerine bir beyit bile vardır:	\
Halk içinde muteber bir nesne yok devlet gibi,	\
Olmaya devlet cihanda bir nefes sıhhat gibi.	\
**1. Zenne.**Pek doğru, Hacivad Çelebi!	\
**H.**Bu da başka:	\
Bilmedik zevk-i visâlin çekmeyince fırkatin.	\
Olmayınca hasta âdem kadrin bilmez sıhhatin.	\
\
**1. Zenne.**Biz evvelâ yalnız başımıza Bursaya gitmeğe karar verdik. Bir takım yatak, bazı öteberi şeyler aldım, hemşire ve sair komşular bizi rıhtıma kadar teşyi eylediler. Biz Bursa vapuruna bindik, hemşire ve sair komşularla vedalaştık. Vapur rıhtımdan ezani saat on buçukta hareket eyledi; başladı vapur Sarayburnuna doğru gelmeye. Sarayburnunu dolaşır dolaşmaz içime bir gariplik geldi, başladım ağlamaya.	\
**H.**Demek efendim, taşraya hiç gitmediniz?	\
**1. Zenne.**Hayır, Hacivad Çelebi.	\
**H.**İnsan ilk defasında bir acayip olur.	\
**1. Zenne.**Nasılsa bir vafır gittik. Mudanyaya geldik, vapurdan çıktık, bir araba kiraladık, doğru Bursaya vâsıl olduk.	\
**H.** Hemşire hanımı soradan mı aldırdınız?	\
**1. Zenne.**Evet. Hacivad Çelebi. Cariye bir ay kadar oturdum, sora Istanbula geldim, Bursanın havası bana eyi geldi. Evi de sattık temelli Bursalı olduk.	\
**H.**Demek ki efendim, şimdi Bursadan geliyorsunuz?	\
**1. Zenne.**Evet, Hacivad Çelebi, buraya gelişimizin veçhi: burada bazı işlerimiz var, çabuk da bitecek. Sizden bir ev isteriz. Hacivad Çelebi.	\
**H.**Başüstüne efendim! Elimin altında bir güzel ev var, sizlere göstereyim. Buyurun gidelim !	\
**1. Zenne.**Buyurun efendim! (Giderler.)	\
**H.**(içeriden).Bu efendim ev. Ne güzeldir! içinin mobilyası da var, bahçesi de var, mutfak da bahçede, hıfz-i sıhhaya mugayir değil.	\
**1. Zenne.**Pek âlâ. Sen ne dersin, hemşire?	\
**2. Zenne.**Güzel, efendim.	\
**1. Zenne.**Malı bemah ne vereceğiz?	\
**H.**Efendim, siz yabancı değilsiniz. Aydan aya dörtyüz kuruş verin!	\
**1. Zenne.**Dörtyüz kuruş çok. Aydan aya üçyüz kuruş verelim!	\
**H.**Haydi efendim, sefa yı hatırla oturun! (H. gider.)	\
(Şarkı ile Zeybek gelir.)	\
Şarkı Nihavend. Edhem Efendi	\
Efeyim, severim ben zevk u sefayı. \
Gam bilmen ne imiş, attım ben cefayı.\
Hangi efe sevmez, hangi yiğit sevmez \
Su başında sefayı, su başında sefayı?	\
\
Efeyim, takarım kulaklı bıçağı,	\
Merd olurlar Aydının uşağı.\
Hangi efe sarmaz, hangi yiğit sarmaz \
Tarabulus kuşağı. Tarabulus kuşağı?	\
\
**Zeybek.** (nara atar).Üle~n!	\
**K.**(içeriden). Gök görülüyor galiba.	\
**Zey.** (lâkırdıyı uzatarak söyler). Ülen kahbe nalları! Şinci Bursadan geldin de kurtuldun mu zannediyorsu~n?	\
**K.** (içeriden).Bu kim be?	\
**Zey.**Ülen, kapıyı açı~n!	\
**K.** (perdeye gelir).Sefa geldin, hemşerim!	\
**Zey.** Sefada daim o~l!\
**K.**Sen de Zeyrekte amcam ol! Nereden geliyorsun, yiğidim?	\
**Zey.** Bursadan geliyonru~m,	\
**K.** Senin adın nedir?	\
**Zey.**Benim adım: Bursalı Sarı Efe derler bana~.	\
**K.**Buraya niçin geldin?	\
**Zey.** Benim Bursada çamurlum vardı, Leylâ~,	\
**K.**Sen de o Leylâmn Mecnunusun, öyle mi?	\
**Zey.**Ben mecnun filân bilmem. O benim yavuklum. Leylâ~,	\
**K.** Onları mı arıyorsun?	\
**Zey.**Evet, onları arıyoru~m.	\
**K.** Onlar Bursada değil ini?	\
**Zey.**Onlar buraya gelmiş, hattâ bu mahallede bir ev tutmuşla~r.	\
**K.**Ulan kokudan mı aldı? Galiba deminden gelenler olacak. Hacivad, ayı kazana sıçtı.	\
**Zey.**Sen onları tanır mısı~n?	\
**K.**Hayır, tanımam(Zenneler içeriden türkü söyler.) Ulan, sesinizi çıkarmayın. köpoğlan!	\
**Zey.**Bu sesler onların sesi~.	\
**K.**Tanıdınız demek?	\
**Zey.**Nasıl tanıma~m? Onlarla cümbüş yaptığım vakit böyle şarkı söyler göbek atarlardı. Haydi sen git de onlara söyle: "Bursadan Sarı Efe geldi" de~!	\
**K.**Ben pişiricilikten çıktım, şimdi hamurkârım. (Gider.)	\
**Zey.**Ülen, kaçtı be~! (Bağırır.) Ülen, Leylâ ~! Aç kapıyı ~!	\
**Zenneler.** (perdeye gelirler).A buyurun efendim !	\
**Zey.**Ülen kahbe nallan~!	Siz buraya geliyorsunuz da bize haber yok, öyle nıi~?	\
**Birinci Z.**Acele ile geldik, size haber veremedik, buyurun!	\
**Zey.** Şinci gideli~m! (Hepsi eve giderler.) Haydi bana rakı bulu~n!	\
**Birinci Z.**Burada var, sizin için aldık.	\
**Zey.**Ülen, şarkı, türkü söyleyi~n!	\
**Zenneler.** (ikisi de beraber söylerler).	\
\
Yaşmağı başında, rastık kaşında.	\
Onüç ondört yaşında, cilveli hanım.	\
\
Göz kırptım ona, o geldi bana,\
Aldım şu yana, cilveli hanım.	\
\
**K.**(perdeye gelir).Artık rezalet ayyuka çıkıyor. Bu böyle olmaz. Ben şimdi bunun ötesini beri ederim! (İçeri seslenir:) Bana bak, arkadaşlar, Recep, Şaban, Ramazan, Bayram!	\
**Hepsi birden.**Ne var, ne istiyorsun?	\
**K.** Aşağıya gelin! (Gelirler.)Haberiniz var mı?	\
**Recep.**Hayır, arkadaş, ne olmuş?	\
**K.**(makam ile). Buraya bir zeybek gelmiş.	\
**Hepsi.**Ya ya ya ...	\
**K.**(makam ile). Karşıki eve girmiş.	\
**Hepsi.**Niçin girmiş ya . . .	\
**K.**(makam ile). Benim de haberim yok.	\
**Hepsi.**Ya ya ya ya . . .	\
**K.**(makam ile).Şunu tutalım, arkadaşlar!	\
**Hepsi.**Ya ya ya ya . . .	\
**K.**(makam ile).Sora iş fena olacak.	\
**Hepsi.**Ya ya ya ya . ..	\
**K.**(makam ile). Siz lâkırdı anlamaz misiniz?	\
**Hepsi.** Ya ya ya ya . . .	\
**K.**Hepimiz birlikte tutalım!	\
**Şaban.**Tutalım mori, tutalım mori!	\
**Hepsi.** (Karagözü tutarlar).Tuttuk mori.	\
**K.** Aşk olsun size! Beni tutacak değilsiniz!	\
**Ramazan.**Çimi tutacağız?	\
**K.**Ramazanı tutacaksınız.	\
**Bayram.**Biz arkadaşımızı tutmayız.	\
**K.**Arkadaşınızı değil, Zeybeği tutacaksınız.	\
**Hepsi.**Tutarız mori!	\
**K.**(gelir kapının önüne). Çık bakalım, Sarı Efe. dışarı! Yoksa iş fena, evi yakacağım.	\
**Zenneler.**Aman, evi yakıyorlar, aman! A dostlar, şimdi ne yapalım?	\
**Zeybek.**Ülen, siz korkmayı~n! Ben şinci gider onların kolunu keserim.	\
(Gelir.) Ülen, kimdi o kapının önünde zıbıkdıra~n?	\
**K.**Bendim zıbıktıran, ne olacak? (Arnavudlara:) Buradasınız ya?	\
**Hepsi.**Korkma, a canım, hepimiz buradayız.	\
**K.** Ne hakkın var eve girmeğe?	\
**Zey.**Ülen, bana mı söylüyo~n ?	\
**K.** Sana söylüyorum. (Arkasına bakar, Arnavutlar yok.)Haydi, içeriye! Rahat et!	\
**Zey.**İçeriye gideyim mi~?	\
**K.**(arkasına bakar, Arnavutlar duruyorlar).Hayır, gitmeyeceksin!	\
**Zey.**ülen, bana mı söylüyo~n?	\
**K.**Evet, sana söylüyorum.	\
**Zey.**Ülen, şinci kafanı keseri~m!	\
**K.**(arkaya bakar, kimse yok).Haydi, içeri gir, rahat et! Ben de sana küserim.	\
**Zey.**Ülen, benimle eğleniyon mu~?	\
**K.**(arkasına bakar. Arnavutlar duruyorlar).Yazık size be! Erkek değil misiniz ?	\
**Hepsi.**Mori. buradayız.	\
**K.** Haydi tut a mori!	\
**Hepsi.**Haydi, tut a mori! (Hepsi Zeybeğin üstüne hücum ederler, kavga eder Zeybeği kaçırırlar. ArnavUtlar gider, Karagöz yalnız kalır. Hacivad de gelir, oyun biter.)	\
